"""Build the reviewed raw services slice from explicit source-grounded assertions.

No network, inference-by-name or aggregate loss calculation occurs here.
Run from repository root; outputs services.json.
"""
import json, pathlib, re

ROOT=pathlib.Path(__file__).resolve().parents[4]
OUT=ROOT/'research/raw/deep-investigation/services.json'
ROUTE='/follow-the-money'
D={'asOf':'2026-10-06','sources':[],'entities':[],'relationships':[],'records':[],'localities':[]}

def source(id,title,url,publisher,date,locator,summary,tier='documented',limits=[]):
    D['sources'].append(dict(id=id,title=title,url=url,publisher=publisher,publishedAt=date,retrievedAt='2026-10-07',locator=locator,summary=summary,tier=tier,limitations=limits))

def geo(src,states=[],scope=None,basis=None,note=None,localities=[]):
    return [dict(scope=scope or ('state' if len(states)==1 else 'multi-state' if states else 'national'),stateCodes=states,localityIds=localities,basis=basis or ('programme-coverage' if states else 'national-context'),note=note or 'Only the stated programme or institution geography is established; no whole-state spend allocation is inferred.',sourceIds=src)]

def dims(src,domains,layers,g=None,limits=[]):
    return dict(sourceIds=src,domains=domains,layers=layers,geography=g or geo(src),route=ROUTE,limitations=limits)

def entity(id,label,type,summary,src,domains,g=None,canonical=None,identity=None):
    row=dict(id=id,label=label,type=type,resolved=True,identityBasis=identity or 'Named in the cited document in this specific institutional role; no surname, address or group-brand merge.',summary=summary,**dims(src,domains,['people' if type=='person' else 'legal' if type in ['court','case'] else 'organisations'],g))
    if canonical:row['canonicalId']=canonical
    D['entities'].append(row)

def amt(value,unit,stage,period,currency='INR'):
    return dict(value=value,currency=currency,unit=unit,stage=stage,period=period)

def rel(id,fr,to,kind,label,summary,src,domains,layers,record,amounts=[],tier='documented',status='Source-retained relationship within the stated source period; read evidence tier',asof=None,start=None,end=None,g=None,limits=[],alternatives=[],falsifier=None,response=True):
    D['relationships'].append(dict(id=id,**{'from':fr,'to':to},kind=kind,label=label,summary=summary,tier=tier,status=status,statusAsOf=asof,fromDate=start,toDate=end,dateBasis='Exact event/observation dates only; amounts retain separate periods. Null dates mean the source provides no exact day.',recordIds=[record],responseIds=[record] if response else [],amounts=amounts,alternativeExplanations=alternatives,falsifier=falsifier,**dims(src,domains,layers,g,limits)))

def record(id,title,summary,src,entities,relationships,domains,layers,period,response,alternatives,falsifier,amounts,tier,status,asof,start,end,g=None,limits=[]):
    D['records'].append(dict(id=id,title=title,summary=summary,kind='investigation-case',tier=tier,status=status,statusAsOf=asof,fromDate=start,toDate=end,dateBasis='Dates bound the explicitly described events or reviewed procedural observations; fiscal and transaction periods remain attached to each amount.',entityIds=entities,relationshipIds=relationships,period=period,response=response,alternativeExplanations=alternatives,falsifier=falsifier,amounts=amounts,**dims(src,domains,layers,g,limits)))

source('khyati-hc-2025','Gujarat High Court: Prashant Vazirani v State of Gujarat, regular bail','https://indiankanoon.org/doc/91530568/','Gujarat High Court, primary order reproduced by Indian Kanoon','2025-05-08','R/CR.MA/6649/2025; §§3–3.4 defence, §§4–5 prosecution, §§6–13 prima facie analysis and bail refusal','Records the clinical defence, State allegations and expert-review material considered at bail. Later bail developments are separately retained.',limits=['Direct mirror retrieval returned HTTP 403; indexed court text is archived in svcFetch1.json and svcFetch4.json.','A bail order uses a prima facie standard; it is not a conviction. Patient names are not entities in the structured slice.'])
source('khyati-ie-june2025','Khyati chairman bail hearing: reported PM-JAY earnings and bank-loan use','https://indianexpress.com/article/cities/ahmedabad/khyati-hospital-chairmans-bail-plea-rejected-rs-8-crore-from-pmjay-earnings-used-to-clear-bank-loan-plan-new-hospital-court-told-10086503/','The Indian Express','2025-06-25','Report of Ahmedabad Rural Sessions Court order; paragraphs on 3,578 claims, ₹16.64 crore and ₹8 crore bank loan','Reports prosecution submissions and the sessions bail order, including the chairman’s denial of personal withdrawal and day-to-day involvement.','reported',['The underlying bank ledger and sessions order were not independently retrieved. Earnings in a reported order are not verified bank receipts or adjudicated illicit proceeds.'])
source('khyati-operator-2025','Khyati supplementary charge sheet names hospital holding company','https://indianexpress.com/article/cities/ahmedabad/chargesheet-ahmedabad-khyati-hospital-pmjay-9946166/','The Indian Express','2025-04-15','Opening paragraphs: Ahmedabad Bariatrics and Cosmetics Pvt Ltd; supplementary charge sheet','Identifies the company behind Khyati Multispeciality Hospital and reports the Ahmedabad Detection of Crime Branch charge sheet.','reported',['Charge sheet filing is a prosecution step. The article is not a company-register extract or final criminal judgment.'])
source('khyati-sc-bail-2025','Supreme Court grants Kartik Jasubhai Patel bail','https://indiankanoon.org/doc/5649905/','Supreme Court of India, primary order reproduced by Indian Kanoon','2025-12-11','SLP(Crl) Diary 70302/2025; §§3–7, especially co-accused bail and regular trial attendance','Supreme Court allowed the petition and directed release on bail after noting bail granted to the co-accused. This supersedes the earlier custody snapshot.',limits=['Direct mirror retrieval returned HTTP 403; indexed primary order archived in svcFetch2.json.','Bail is neither acquittal nor a finding that the allegation was false.'])
source('khyati-discharge-2026','Khyati directors’ discharge applications refused after rehearing','https://timesofindia.indiatimes.com/city/ahmedabad/ahmedabad-court-rejects-discharge-pleas-of-khyati-hospital-directors-ceo/articleshow/130973635.cms','The Times of India','2026-05-09','Report of Additional Sessions Judge A S Vyas; March High Court rehearing direction and renewed discharge refusal','Reports that the trial court heard the discharge pleas following a High Court direction and again refused discharge.','reported',['Original discharge and remand orders not retrieved. Latest retained trial-stage observation is May 2026; no final conviction or acquittal is established by this corpus.'])
source('pmjay-parliament-2025','Rajya Sabha reply: measures to prevent misuse of AB-PMJAY','https://www.pib.gov.in/PressReleasePage.aspx?PRID=2099542','Ministry of Health and Family Welfare / PIB','2025-02-04','Release 2099542; NHA/SHA medical-audit, recovery, suspension and de-empanelment paragraphs','Documents the ministry’s national anti-fraud and audit mechanism; not a Khyati-specific recovery order.',limits=['National disciplinary totals cannot be attributed to a named hospital without a hospital-specific order.'])
source('byju-sc-2024','GLAS Trust Company LLC v BYJU Raveendran: 2024 INSC 811','https://api.sci.gov.in/supremecourt/2024/35406/35406_2024_1_1502_56620_Judgement_23-Oct-2024.pdf','Supreme Court of India','2024-10-23','§§6–10 credit/guarantee and BCCI debt; §§16–21 settlement and responses; §§81,86–88 outcome','Primary judgment separates the US credit facility, Indian guarantee, settlement objections and the statutory insolvency-withdrawal procedure. ₹158 crore was ordered held by the committee of creditors in escrow.',limits=['Paragraphs 86–87 expressly decline merits adjudication and any finding on stakeholder conduct. Recited allegations about US transfers are not treated as findings of this Indian judgment.'])
source('byju-nclat-2026','Byju Raveendran v GLAS Trust: procedural appeal dismissed','https://indiankanoon.org/doc/152758496/','National Company Law Appellate Tribunal, primary order reproduced by Indian Kanoon','2026-08-17','CA(AT)(CH)(Ins)383/2026; §§1–5','Appeal against an order merely listing the application was held non-maintainable. The parties’ underlying creditor-claim disputes were left open.',limits=['Direct mirror retrieval returned HTTP 403; indexed primary text archived in svcFetch2.json, with irrelevant residential-address lines omitted.','No later merits order is established. This is not a ruling that every GLAS claim or alleged transfer was valid.'])
source('akshaya-annual-2025','The Akshaya Patra Foundation Annual Report 2024–25','https://www.akshayapatra.org/includefiles/financialreports/Annual_Report_24-25_Tapestry_web.pdf','The Akshaya Patra Foundation; audit by Walker Chandiok & Co LLP',None,'Printed pp75–76,81,102,129–134,147–150,154–156; PDF pp70,72,79,80,82,83 visually checked','Contains audited trust financial statements signed 7 October 2025, programme narrative, a Chikkajala kitchen table and note 2.25 related-party disclosures.',limits=['Financial-statement audit does not independently verify all meal counts, nutrition or learning outcomes in the narrative.','The auditor gives an unmodified opinion with emphasis on the trust’s adopted accounting basis.','Support from state governments combines programme types and accounting components; organisation-wide support is not a Chikkajala-only grant.','The scanned tables require visual verification; OCR is retained as a finding aid and is not authoritative.'])
source('akshaya-kitchen-2024','Akshaya Patra’s Chikkajala kitchen inauguration','https://www.akshayapatra.org/news/akshaya-patra-75th-centralised-kitchen-in-chikkajala','The Akshaya Patra Foundation','2024-10-04','30 September 2024 event; donor and planned school-coverage paragraphs','Names the Thakkar Family Foundation as patron donor and states the kitchen’s planned reach in Yelahanka, Jakkur and Hebbal.','self-reported',['Inauguration capacity and planned reach are not meals actually served. Dignitary attendance is not evidence of a grant, corporate donor or improper influence.'])
source('nsap-cag-2023','CAG Report 10 of 2023: NSAP publicity expenditure','https://cag.gov.in/uploads/download_audit_report/2023/Report-No.-10-of-2023_NSAP_English_PDF-A-064d229f832dad7.55068084.pdf','Comptroller and Auditor General of India','2023-08-08','§5.5.1, printed p41; report audit FY2017-18–FY2020-21; Ministry reply December 2022','Traces approved publicity heads, work orders to DAVP, actual NSAP IEC charge and lack of work-execution confirmation.',limits=['Direct original PDF again returned HTTP 503 on 7 October 2026. Existing indexed original text, retrieved 6 October 2026, is archived with its provenance.','The Ministry’s statement that it referred the issue internally is a response, not evidence of completed recovery.'])
source('nsap-followup-2026','Lok Sabha Standing Committee 31st report: NSAP action taken','https://elibrary.sansad.in/server/api/core/bitstreams/f2af3284-ac25-4d40-9671-d10b728827d0/content','Lok Sabha Standing Committee on Rural Development and Panchayati Raj','2026-04-02','31st report, 18th Lok Sabha, action taken on 9th report; complete 31-page retained PDF','Checked later parliamentary scrutiny of NSAP. The report concerns scheme recommendations and does not establish settlement of CAG §5.5.1’s 2017 DAVP transactions.',limits=['A later action-taken report on another committee report is not automatically an action-taken note closing this CAG paragraph. Non-observation in this document does not prove no remediation happened elsewhere.'])

# Hospital: direct scheme reimbursement allegation, identified operator, service harm and later procedural outcome.
ks=['khyati-hc-2025','khyati-ie-june2025','khyati-operator-2025','khyati-sc-bail-2025','khyati-discharge-2026','pmjay-parliament-2025']; kd=['welfare','health','capital','justice']; kg=geo(ks,['GJ'],scope='city',basis='institution-location',note='Khyati Hospital in Ahmedabad; camp at Borisana village, Kadi, Mehsana district. Neither is a national fraud estimate.',localities=['ahmedabad','borisana-kadi'])
D['localities'] += [dict(id='ahmedabad',name='Ahmedabad',stateCode='GJ',kind='city',aliases=[]),dict(id='borisana-kadi',name='Borisana',stateCode='GJ',kind='village',aliases=[],districtName='Mehsana'),dict(id='chikkajala-bengaluru',name='Chikkajala',stateCode='KA',kind='locality',aliases=[],districtName='Bengaluru')]
entity('mohfw','Ministry of Health and Family Welfare','ministry','Union ministry responsible for the parliamentary PM-JAY account; no specific Khyati payment amount attributed to the ministry.', ['pmjay-parliament-2025'],kd)
entity('pmjay-gujarat','PM-JAY in Gujarat','programme','Scheme reimbursement channel at issue in the Khyati proceeding; not a company or a finding against all empanelled hospitals.',ks,kd,kg)
entity('khyati-hospital','Khyati Multispeciality Hospital','hospital','Ahmedabad hospital named in the PM-JAY medical-procedure criminal case.',ks,kd,kg)
entity('ahmedabad-bariatrics','Ahmedabad Bariatrics and Cosmetics Pvt Ltd','company','Named holding company of Khyati Hospital in the April 2025 charge-sheet report. Separate from other businesses carrying the Khyati brand.',['khyati-operator-2025'],kd,kg)
entity('kartik-patel','Kartik Jasubhai Patel','person','Hospital chairman named in the same FIR and Supreme Court bail proceeding. Later bail on 11 December 2025 retained.',['khyati-operator-2025','khyati-sc-bail-2025'],kd,kg,identity='SC Diary70302/2025 identifies FIR11191020240478/2024; the same hospital proceeding identifies the chairman. No unrelated Kartik Patel or Khyati company is merged.')
entity('khyati-case','Khyati PM-JAY criminal proceeding','case','FIR11191020240478/2024; charge-sheet and bail/discharge stages. No final merits judgment retained.',ks,kd,kg)
entity('supreme-court','Supreme Court of India','court','Primary court for the retained December2025 bail and October2024 insolvency judgments.',['khyati-sc-bail-2025','byju-sc-2024'],['justice'])
kamount=[amt(16.64,'crore','Hospital earnings reported in a sessions-court bail order for 3,578 PM-JAY angiography/angioplasty claims; not independently reconciled bank receipts or proven loss','31 March 2022–11 November 2024'),amt(8,'crore','Prosecution account of bank-loan repayment from hospital earnings, recorded at bail; no lender named and no separate/additional loss inferred','Historical hospital funds use reported 25 June 2025')]
rel('mohfw-pmjay','mohfw','pmjay-gujarat','administers','National PM-JAY audit framework','Parliamentary reply describes national and state audits and possible recovery or criminal proceedings, without assigning a Khyati-specific penalty.',['pmjay-parliament-2025'],kd,['policy','welfare'],'khyati-pmjay-claims',asof='2025-02-04',g=geo(['pmjay-parliament-2025']))
rel('pmjay-khyati','pmjay-gujarat','khyati-hospital','reimbursement','Reported PM-JAY claim earnings','The reported bail order puts the hospital’s PM-JAY claim earnings at ₹16.64 crore for the stated period. This is not a bank-certified receipt trail.',['khyati-ie-june2025'],kd,['funding','welfare'],'khyati-pmjay-claims',[kamount[0]],'reported',asof='2025-06-25',start='2022-03-31',end='2024-11-11',g=kg,limits=['Claim count is not a count of distinct patients or a count of all claims proven fraudulent.'])
rel('operator-khyati','ahmedabad-bariatrics','khyati-hospital','operates','Named hospital holding company','The April2025 report identifies the company behind the hospital; no chain to other same-name Khyati entities is inferred.',['khyati-operator-2025'],kd,['organisations'],'khyati-pmjay-claims',tier='reported',asof='2025-04-15',g=kg)
rel('kartik-operator','kartik-patel','ahmedabad-bariatrics','role','Chairman in the charge-sheet report','Named management role is distinct from personal enrichment and from proof of the charged offences.',['khyati-operator-2025','khyati-ie-june2025'],kd,['people','organisations'],'khyati-pmjay-claims',tier='reported',asof='2025-04-15',g=kg)
rel('khyati-proceeding','khyati-hospital','khyati-case','subject-of','Alleged unnecessary procedures and manipulated records','State prosecutors allege monetary exploitation through unnecessary angioplasty. The HC considered contrary clinical arguments and prima facie expert material; two deaths followed procedures in November2024.',['khyati-hc-2025'],kd,['services','legal'],'khyati-pmjay-claims',tier='alleged',status='Criminal allegations; bail-stage prima facie analysis, not conviction',asof='2026-05-09',start='2024-11-11',g=kg)
rel('sc-kartik-bail','supreme-court','kartik-patel','adjudicates','Supreme Court granted bail on 11 December 2025','The Supreme Court ordered release on bail, citing bail granted to co-accused, and required attendance at trial.',['khyati-sc-bail-2025'],kd,['legal'],'khyati-pmjay-claims',asof='2025-12-11',start='2025-12-11',end='2025-12-11',g=kg,limits=['Later discharge refusal was reported in May2026; neither step determines guilt.'])
record('khyati-pmjay-claims','PM-JAY → Khyati: claim earnings, clinical allegations and later bail','Public health cover reaches a named private hospital. A sessions-court account records ₹16.64 crore in PM-JAY claim earnings and alleges ₹8 crore bank-loan use; patient-level records and bank reconciliation remain absent. The clinical charges are contested. The Supreme Court granted the chairman bail in December2025; discharge refusals were reported in May2026.',ks,['mohfw','pmjay-gujarat','khyati-hospital','ahmedabad-bariatrics','kartik-patel','khyati-case','supreme-court'],['mohfw-pmjay','pmjay-khyati','operator-khyati','kartik-operator','khyati-proceeding','sc-kartik-bail'],kd,['funding','services','welfare','legal','review'],'Claims31Mar2022–11Nov2024; clinical incident11Nov2024; last retained procedural report9May2026','Dr Prashant Vazirani’s counsel argued clinical indications and pre-authorisation justified the procedures, complications could explain the deaths, and some patients declined treatment. Kartik Patel’s counsel disputed personal withdrawal and day-to-day management. The Gujarat HC rejected the doctor’s May2025 bail plea on a prima facie view; the Supreme Court’s 11Dec2025 order records later bail for him and all other co-accused and grants Patel bail. A May2026 report records discharge refusal. No final conviction or acquittal is established.',['Legitimate PM-JAY treatment also earns package revenue; the total cannot be classified as fraud without claim-level findings.','A corporate loan repayment can serve hospital operations. It does not establish personal withdrawal or illegality without the source-of-funds and clinical evidence.','Adverse medical outcome alone does not prove unnecessary treatment or criminal intent.'],'Obtain authenticated claims adjudication and disbursement ledgers, clinical videos/independent reviews, bank-use tracing and the final reasoned trial or appellate judgment; reconcile each disputed claim and preserve any acquittal or recovery.',kamount,'alleged','Charges contested; chairman granted bail 11Dec2025; discharge refusals reported May2026; no merits verdict retained','2026-05-09','2022-03-31','2026-05-09',kg,['The ₹8 crore account and ₹16.64 crore earnings may overlap; do not add them or infer a residual.','No hospital-specific government recovery, final loss, bank identity or amount paid to individual patients is established.','A general national anti-fraud response is included as policy context, not as an answer clearing this hospital.'])

# Edtech: loan, guarantee, sponsorship debt and settlement protection remain distinct.
bs=['byju-sc-2024','byju-nclat-2026'];bd=['education','capital','finance','justice'];bg=geo(bs,['KA'],basis='headquarters',note='Think & Learn’s Bengaluru corporate/insolvency association; not a map of loan deployment or school delivery. US borrower and litigation are separately described.')
for args in [('glas','GLAS Trust Company LLC','company','Administrative/collateral agent for the credit-facility lenders, not the beneficial lender population.'),('byju-alpha','BYJU’S Alpha, Inc.','company','US borrower under the November2021 credit agreement; distinct from Indian guarantor Think & Learn.'),('think-learn','Think & Learn Private Limited','company','Indian edtech corporate debtor and guarantor; the Byju’s brand is not a separate loan recipient.'),('bcci','Board of Control for Cricket in India','organisation','Operational creditor under the 25July2019 Team Sponsor Agreement.'),('riju-ravindran','Riju Ravindran','person','Settlement funder whose personal-funds undertaking was contested.'),('byju-coc','Think & Learn committee of creditors','organisation','Collective insolvency body directed by the Supreme Court to retain settlement money in escrow.'),('nclat','National Company Law Appellate Tribunal','court','Appellate tribunal whose August2026 ruling concerns maintainability of a procedural appeal.')]:
    entity(*args,bs,bd,bg)
bamount=[amt(1200,'million','Contracted term-loan facility to US borrower; guarantor exposure is the same facility, not a second disbursement','Credit and guarantee agreement24November2021','USD'),amt(158,'crore','Settlement sum held in escrow and ordered transferred to committee-of-creditors escrow; not lender recovery or adjudicated proceeds of fraud','Supreme Court order23October2024')]
rel('glas-alpha-credit','glas','byju-alpha','credit-facility-agent','Agent for a $1.2 billion lender facility','Supreme Court §6 identifies the facility extended by lenders and GLAS’s agent role. No Union ministry grant or Indian taxpayer funding is established.',['byju-sc-2024'],bd,['funding'],'byju-credit-bcci',[bamount[0]],asof='2024-10-23',start='2021-11-24',g=bg,limits=['GLAS is the administrative/collateral agent, not the funding source. No lender-by-lender economic funding allocation is established.'])
rel('think-alpha-parent','think-learn','byju-alpha','subsidiary','Ultimate parent / step-down subsidiary','The Supreme Court identifies BYJU’S Alpha as a step-down subsidiary of Think & Learn.',['byju-sc-2024'],bd,['organisations'],'byju-credit-bcci',asof='2024-10-23',g=bg)
rel('think-glas-guarantee','think-learn','glas','guarantee','Indian guarantee for the US loan','Think & Learn gave a guarantee under the same24November2021 transaction; the later demand and claim were disputed.',['byju-sc-2024','byju-nclat-2026'],bd,['funding','legal'],'byju-credit-bcci',asof='2026-08-17',start='2021-11-24',g=bg,limits=['No duplicate $1.2b amount added for the guarantee.'])
rel('think-bcci-sponsorship','think-learn','bcci','operational-debt','Team sponsorship debt triggered Indian CIRP','BCCI petitioned under IBC§9 over approximately₹158crore operational debt. This was sponsorship debt, not an education subsidy.',['byju-sc-2024'],bd,['funding','legal'],'byju-credit-bcci',asof='2024-10-23',start='2019-07-25',g=bg)
rel('riju-bcci-settlement','riju-ravindran','bcci','settlement','Contested personal-funds settlement','Riju said settlement money came from his own resources; GLAS disputed its provenance. The Supreme Court did not decide the merits.',['byju-sc-2024'],bd,['funding','legal'],'byju-credit-bcci',asof='2024-10-23',start='2024-07-30',g=bg,limits=['Source objections are not established round-tripping.'])
rel('bcci-coc-escrow','bcci','byju-coc','escrow-direction','₹158 crore ordered into CoC escrow','Supreme Court §88 directed settlement money plus any accrued interest to CoC escrow pending further NCLT directions; compliance bank proof is not retained.',['byju-sc-2024'],bd,['funding','legal'],'byju-credit-bcci',[bamount[1]],asof='2024-10-23',start='2024-10-23',g=bg)
rel('nclat-glas-procedure','nclat','glas','adjudicates','August2026 ruling leaves creditor merits open','The appeal challenged a listing order. NCLAT dismissed it as not maintainable, leaving substantive controversy open.',['byju-nclat-2026'],bd,['legal'],'byju-credit-bcci',asof='2026-08-17',start='2026-08-17',end='2026-08-17',g=bg)
record('byju-credit-bcci','Byju’s: a dollar loan, an Indian guarantee and a ₹158 crore escrow','The source trail links US lender funding through GLAS to BYJU’S Alpha, Think & Learn’s guarantee and a separate BCCI sponsorship debt. The Supreme Court set aside approval of the ₹158 crore settlement because insolvency-withdrawal procedures were bypassed, while expressly declining a merits finding on stakeholder conduct. The August2026 NCLAT dismissal also left the underlying creditor dispute open.',bs,['glas','byju-alpha','think-learn','bcci','riju-ravindran','byju-coc','nclat','supreme-court'],['glas-alpha-credit','think-alpha-parent','think-glas-guarantee','think-bcci-sponsorship','riju-bcci-settlement','bcci-coc-escrow','nclat-glas-procedure'],bd,['funding','organisations','legal','review'],'Facility24Nov2021; CIRP admitted16Jul2024; SC23Oct2024; NCLAT17Aug2026','Riju Ravindran’s undertaking said settlement funds were personal, derived from his share-sale resources, and did not come from the disputed US loan proceeds. GLAS challenged that provenance and priority. The Supreme Court §§86–87 made no finding on stakeholder conduct and left remedies under the proper withdrawal procedure available. In2026 Byju’s side challenged lender authorisations and claim quantum; NCLAT declined to adjudicate those merits in an appeal from a listing order.',['A documented guarantee and operational debt explain a multi-creditor insolvency without themselves proving diversion.','Payment by a third party can be lawful; lawful source and compliance still need proof where challenged.','The US transfer disputes and Indian withdrawal litigation are distinct proceedings; one cannot stand in for a final outcome in the other.'],'Produce the relevant authenticated lender authorisations, disbursement/transfer bank records, guarantee enforcement and final merits orders; determine the exact funds used for settlement and any later escrow distribution.',bamount,'documented','Indian settlement approval set aside; funds protected in escrow by order; August2026 procedural appeal dismissed, underlying issues left open','2026-08-17','2021-11-24','2026-08-17',bg,['Dollar loan principal and rupee operational-debt settlement are different currencies and obligations; never sum them.','No final US recovery or damages number is presented, and no inference about public subsidy or school-delivery outcome is supported.','No current company valuation is supplied merely because the brand was previously described as a unicorn.'])

# School-meal NGO: verified accounting stages, named physical kitchen, and disclosed related party.
asrc=['akshaya-annual-2025','akshaya-kitchen-2024'];ad=['education','welfare','ngo'];ag=geo(asrc,['KA'],scope='project',basis='project-location',note='Chikkajala kitchen in Bengaluru is a documented site. Foundation-wide financial figures cover the whole trust and are not allocated to Karnataka or this kitchen.',localities=['chikkajala-bengaluru'])
entity('tapf-state-support','State governments — TAPF aggregate funding counterparties','public-body','Collective accounting label for support in the foundation’s financial statements; not one government or a state-by-state release ledger.',['akshaya-annual-2025'],ad)
entity('akshaya-patra','The Akshaya Patra Foundation','trust','Public charitable trust implementing school meals and other nutrition programmes; audited financial statements and self-reported delivery claims are separated.',asrc,ad,ag,canonical='ngo:akshaya-patra-foundation',identity='Audited FY2025 note1.1 names the registered public charitable trust formed1July2000, registered16October2001; same legal foundation as the existing canonical record, not its foreign affiliates.')
entity('thakkar-foundation','Thakkar Family Foundation','foundation','Patron donor named for Chikkajala kitchen, founded by Janardan and Linda Thakkar; no amount or corporate CSR status assumed.',asrc,ad,ag)
entity('chikkajala-kitchen','Akshaya Patra Chikkajala kitchen','facility','Kitchen inaugurated30September2024. FY2025 trust table reports30,000 children/192 schools, while launch publicity describes capacity/planned reach of35,000/over200.',asrc,ad,ag)
entity('iskcon-bangalore','International Society for Krishna Consciousness, Bangalore','trust','Counterparty specifically named ISKCON in TAPF note2.25; no merge with unrelated ISKCON entities or other jurisdictions.',['akshaya-annual-2025'],ad,ag,identity='Audited note2.25(a) expands ISKCON to International Society for Krishna Consciousness, Bangalore and lists common-trustee relationships. Exact counterparty scope retained.')
aamount=[amt(42093.64,'lakh','Audited support-from-state-governments income; includes accounting and in-kind components, not cash release alone','FY2024-25'),amt(36788.98,'lakh','Audited receipts-and-payments ScheduleB: state-government support cash receipts after reconciliation; overlaps income figure','FY2024-25'),amt(1351.66,'lakh','Trustees’ report: Chikkajala capital expenditure; not the donor’s contribution or a government grant','FY2024-25'),amt(275.76,'lakh','Audited related-party note: rent and other expenses paid to ISKCON Bangalore; not an allegation of diversion','FY2024-25')]
rel('states-tapf-income','tapf-state-support','akshaya-patra','grant-income','State support: income and receipts differ','Audited income records₹42,093.64lakh; cash-support receipts reconcile to₹36,788.98lakh. Difference includes accounting/in-kind and working-capital effects, not an unexplained missing-money balance.',['akshaya-annual-2025'],ad,['funding','welfare'],'akshaya-meals-related-parties',aamount[:2],asof='2025-10-07',start='2024-04-01',end='2025-03-31',g=geo(['akshaya-annual-2025']),limits=['Aggregate for all trust operations, including Anganwadis. No state or scheme-specific split asserted.'])
rel('thakkar-kitchen','thakkar-foundation','chikkajala-kitchen','donation','Named kitchen patron donor','Foundation narrative says Thakkar Family Foundation funded the new kitchen. No donation amount is disclosed in the retained passage.',asrc,ad,['funding'],'akshaya-meals-related-parties',tier='self-reported',asof='2024-10-04',start='2024-09-30',g=ag)
rel('tapf-kitchen','akshaya-patra','chikkajala-kitchen','operates','₹13.5166 crore reported Chikkajala capital expenditure','Trustees’ report records location-specific capital expenditure. The kitchen’s school-meal programme metrics are organisation-reported service coverage, not independently audited outcomes.',['akshaya-annual-2025'],ad,['funding','services'],'akshaya-meals-related-parties',[aamount[2]],tier='self-reported',asof='2025-03-31',start='2024-04-01',end='2025-03-31',g=ag,limits=['The 30,000-child/192-school table and 35,000/200+ launch plan have different measurement bases.'])
rel('tapf-iskcon-related','akshaya-patra','iskcon-bangalore','related-party','Common-trustee relationship disclosed','Audited note2.25(a) identifies the specific Bangalore counterparty among entities with one or more common trustees/directors.',['akshaya-annual-2025'],ad,['organisations'],'akshaya-meals-related-parties',asof='2025-10-07',g=ag,limits=['Common trustees alone do not establish undue benefit or unlawful conduct.'])
rel('tapf-iskcon-rent','akshaya-patra','iskcon-bangalore','payment','₹275.76 lakh rent and other expenses paid','Note2.25 lists the related-party payment category. The record does not trace earmarked government grants into this payment or allocate it to Chikkajala.',['akshaya-annual-2025'],ad,['funding'],'akshaya-meals-related-parties',[aamount[3]],asof='2025-10-07',start='2024-04-01',end='2025-03-31',g=geo(['akshaya-annual-2025']),limits=['Other cross-charges, payables and donations in the note have different stages and are not added here.'])
record('akshaya-meals-related-parties','Akshaya Patra: state support, school meals and related-party payments','A documented NGO service chain separates state-support income from cash receipts, identifies the Thakkar-funded Chikkajala kitchen and exposes the audited₹275.76lakh rent/other-expense payment to related party ISKCON Bangalore. The trust reports kitchen coverage; neither charity status nor related-party disclosure establishes misuse. No restricted government grant is traced to a particular rent payment.',asrc,['tapf-state-support','akshaya-patra','thakkar-foundation','chikkajala-kitchen','iskcon-bangalore'],['states-tapf-income','thakkar-kitchen','tapf-kitchen','tapf-iskcon-related','tapf-iskcon-rent'],ad,['funding','services','organisations','review'],'FY2024-25; kitchen inaugurated30Sep2024; audited statements signed7Oct2025','This is a funding-transparency case, with no fraud allegation asserted. The Foundation’s audited statements disclose the related parties and transaction categories. Walker Chandiok & Co LLP gave an unmodified financial-statement opinion with emphasis on the adopted trust accounting basis. Programme narrative describes school nutrition work; it is not the same assurance as an independent service-outcome audit.',['Income and cash receipts differ because of the accounting basis, in-kind support, receivables, provisions and advances. Their difference is not automatically loss.','Related organisations may legitimately share premises and services. Assessing value requires the lease, allocation basis and comparable charges.','A kitchen’s capacity or inauguration promise may exceed period-end children actually served.'],'Reconcile government sanctions and bank credits to ScheduleB and grain support; match kitchen registers to school acknowledgments; inspect leases, common-trustee approvals, cost allocation and market comparisons before asserting excess or grant misuse.',aamount,'documented','Audited financial disclosures retained; programme delivery is self-reported; no misconduct finding asserted','2025-10-07','2024-04-01','2025-10-07',ag,['Foundation totals, kitchen capital expenditure and related-party payments overlap in scope and must not be totalled.','Cash/income records include non-school nutrition operations. No national outcome or per-child subsidy is calculated.','A public figure’s presence at an inauguration creates no funding or influence edge.'])

# Pension-programme publicity: authorisation, payment and delivered-work verification.
ns=['nsap-cag-2023','nsap-followup-2026'];nd=['welfare','governance'];ng=geo(ns,note='National Ministry administrative-expenditure finding. It cannot be allocated to a state merely from the publisher’s address.')
entity('mord','Ministry of Rural Development','ministry','NSAP administrator and source of the DAVP work orders audited by CAG.',ns,nd,ng,canonical='min:ministry-of-rural-development',identity='The CAG names the same Union Ministry of Rural Development as the canonical ministry; not a state rural-development department.')
entity('nsap-iec','NSAP information, education and communication funds','programme','Earmarked programme-administration expenditure head; distinct from a beneficiary’s pension bank account.',ns,nd,ng)
entity('davp','Directorate of Advertising and Visual Publicity (DAVP)','agency','Government publicity agency named in the 2017 work orders and payment finding; no private media vendor identified.',ns,nd,ng)
entity('pmay-ddu-publicity','PMAY-G and DDU-GKY publicity work orders','programme','Only these schemes were named in the audited work orders; no NSAP scheme included.',['nsap-cag-2023'],nd,ng)
namount=[amt(39.15,'lakh','Administrative approval and financial sanction for capital-city hoardings; not a separate confirmed delivery','June2017'),amt(2.44,'crore','Administrative approval and expenditure sanction for district/multi-scheme publicity; not a separate loss','August2017'),amt(2.83,'crore','CAG rounded total expenditure charged to NSAP IEC for other-scheme campaigns; overlaps sanctions above','2017 work orders; audit reported8August2023')]
rel('mord-nsap-iec','mord','nsap-iec','administers','Earmarked NSAP publicity head','The CAG explains administrative earmarking and the intended awareness purpose of NSAP IEC.',['nsap-cag-2023'],nd,['welfare','funding'],'nsap-davp-earmarking',asof='2023-08-08',g=ng)
rel('mord-davp-orders','mord','davp','work-order','June/September2017 publicity work orders','CAG records approvals of₹39.15lakh and₹2.44crore, followed by DAVP work orders; the approved expenditure head was NREGS.',['nsap-cag-2023'],nd,['procurement','funding'],'nsap-davp-earmarking',namount[:2],asof='2023-08-08',g=ng)
rel('nsap-davp-paid','nsap-iec','davp','payment','₹2.83 crore charged to NSAP; execution unconfirmed','CAG found the funds were actually incurred from NSAP and paid to DAVP before confirmation that the work was executed.',['nsap-cag-2023'],nd,['funding','review'],'nsap-davp-earmarking',[namount[2]],asof='2023-08-08',g=ng,limits=['An audit finding of irregular purpose/verification is not a criminal finding of personal enrichment.'])
rel('davp-other-schemes','davp','pmay-ddu-publicity','commissioned-service','Work-order content excluded NSAP','The orders named only PMAY-G and DDU-GKY. CAG concluded intended NSAP awareness activities had not been undertaken as envisaged.',['nsap-cag-2023'],nd,['services','procurement'],'nsap-davp-earmarking',asof='2023-08-08',g=ng,limits=['Actual hoarding installation is not established by the work order. No private advertising beneficiary is guessed.'])
record('nsap-davp-earmarking','NSAP → DAVP: publicity spending and missing work confirmation','CAG traced two approved publicity amounts into DAVP work orders, then found₹2.83crore charged to NSAP for other ministry schemes and paid before confirmation of execution. That documents an earmarking and delivery-verification failure. It does not prove partisan advertising or identify personal enrichment. Later parliamentary material checked here does not close this specific audit paragraph.',ns,['mord','nsap-iec','davp','pmay-ddu-publicity'],['mord-nsap-iec','mord-davp-orders','nsap-davp-paid','davp-other-schemes'],nd,['funding','procurement','welfare','services','review'],'June/August2017 sanctions; June/September2017 work orders; December2022 Ministry response; report8Aug2023','The Ministry told CAG in December2022 that it had taken the matter up with its IEC division. The2Apr2026 parliamentary action-taken report was also reviewed, but concerns recommendations of the Committee’s9threport and does not establish reconciliation, delivered-media receipts or recovery for CAG§5.5.1. This absence is not proof that no action exists elsewhere.',['Cross-scheme awareness can serve a legitimate public purpose; it still needs a lawful expenditure head and proof of delivery.','An accounting correction or subsequently supplied execution certificate could narrow or resolve the historical observation.'],'Produce the contemporaneous approved head-change, DAVP invoice and campaign execution certificates, payment ledger and a paragraph-specific accepted action-taken/recovery record.',namount,'documented','CAG finding with Ministry response; final paragraph-specific reconciliation or recovery not established','2023-08-08',None,None,ng,['The two sanctions and rounded₹2.83crore expenditure describe overlapping stages; never sum them.','This deep case re-examines the existing welfare-research:nsap-publicity finding. It is not a second independent incident or additional loss.','Government-agency payee is identified, but no media subcontractor or individual beneficiary is named by the cited paragraph.'])

# Per-entity and per-edge geography is not inherited from the case's service site.
def unknown_geography(src,note):
    return geo(src,scope='unknown',basis='unknown',note=note)

entities_by_id={row['id']:row for row in D['entities']}
relationships_by_id={row['id']:row for row in D['relationships']}
def entity_geo(id,g):entities_by_id[id]['geography']=g
def relationship_geo(id,g):relationships_by_id[id]['geography']=g

for id in ['glas','byju-alpha']:
    entity_geo(id,unknown_geography(bs,'US legal entity identified by the judgment; no Indian headquarters, delivery site or spending allocation is established.'))
entity_geo('think-learn',geo(bs,['KA'],basis='headquarters',note='Bengaluru corporate-debtor association stated in the tribunal record; not loan-use geography.'))
entity_geo('bcci',geo(bs,note='Indian national cricket governing body and operational creditor. No headquarters or school-delivery geography inferred from this record.'))
entity_geo('riju-ravindran',unknown_geography(bs,'Public litigation role only; personal residential geography is not mapped.'))
entity_geo('byju-coc',geo(bs,note='Collective creditors body for the Indian insolvency; no physical headquarters asserted.'))
entity_geo('nclat',geo(['byju-nclat-2026'],['TN'],basis='institution-location',note='The retained order is from NCLAT Chennai Bench. This marks the forum, not the debtor or loan use.'))
entity_geo('kartik-patel',geo(ks,['GJ'],basis='state-association',note='Public hospital-management and legal-case association; no personal residence asserted.'))
entity_geo('khyati-case',geo(ks,['GJ'],basis='state-association',note='Gujarat criminal proceeding associated with Ahmedabad hospital; court jurisdiction, not a service facility.'))
entity_geo('pmjay-gujarat',geo(ks,['GJ'],basis='programme-coverage',note='Gujarat implementation of the programme; the case concerns one named Ahmedabad hospital.'))
entity_geo('ahmedabad-bariatrics',geo(['khyati-operator-2025'],['GJ'],basis='state-association',note='Reported holding-company association with the Ahmedabad hospital, not a verified registered-office coordinate.'))
entity_geo('akshaya-patra',geo(asrc,['KA'],basis='headquarters',note='Foundation headquartered in Bengaluru; its financial figures cover multi-state operations, not only Karnataka.'))
entity_geo('thakkar-foundation',unknown_geography(asrc,'Named donor to Chikkajala kitchen; donor registered headquarters not independently established.'))
entity_geo('iskcon-bangalore',geo(['akshaya-annual-2025'],['KA'],basis='institution-location',note='The audited related-party note specifically identifies ISKCON Bangalore; no Chikkajala premises or all-India ISKCON allocation inferred.'))
for id in ['glas-alpha-credit','think-alpha-parent','riju-bcci-settlement','bcci-coc-escrow']:
    relationship_geo(id,unknown_geography(bs,'Cross-border corporate/legal relationship. No location of expenditure or individual payment is established.'))
for id in ['think-glas-guarantee','think-bcci-sponsorship']:
    relationship_geo(id,geo(bs,['KA'],basis='state-association',note='Association with the Bengaluru corporate debtor only; no allocation of the obligation to Karnataka services.'))
relationship_geo('nclat-glas-procedure',geo(['byju-nclat-2026'],['TN'],basis='institution-location',note='Chennai appellate forum; no relocation of GLAS or underlying assets is implied.'))
relationship_geo('sc-kartik-bail',geo(['khyati-sc-bail-2025'],note='Supreme Court order on a Gujarat proceeding. The Court is not located at the hospital.'))
relationship_geo('kartik-operator',geo(['khyati-operator-2025'],['GJ'],basis='state-association',note='Management role in the reported Ahmedabad hospital company, not a personal residence.'))
relationship_geo('tapf-iskcon-related',geo(['akshaya-annual-2025'],['KA'],basis='state-association',note='Bengaluru institutional relationship; no allocation to the Chikkajala kitchen.'))
for row in D['records']:
    if row['id']=='akshaya-meals-related-parties':
        row['geography']=geo(['akshaya-annual-2025'],note='Trust-wide financial disclosures are national/multi-state context and are not assigned to the kitchen.')+ag

def readable(value):
    if isinstance(value,dict):
        return {key:readable(item) for key,item in value.items()}
    if isinstance(value,list):
        return [readable(item) for item in value]
    if isinstance(value,str) and ' ' in value and not value.startswith('http'):
        value=re.sub(r'(?<=\d)(?=[A-Za-z])',' ',value)
        value=re.sub(r'(?<=[A-Za-z])(?=\d)',' ',value)
        value=re.sub(r'(?<=[A-Za-z])(?=§)',' ',value)
        value=value.replace('ScheduleB','Schedule B').replace('Committee’s9threport','Committee’s 9th report')
    return value

D=readable(D)
OUT.write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({k:len(D[k]) for k in ['sources','entities','relationships','records','localities']}))
