import {test} from 'node:test';
import assert from 'node:assert/strict';
import {loadInvestigation} from './load.mjs';
import {validateInvestigation,validateResearchSlice,validateManifestRows,validateInvestigationManifests,validateResearchSlices} from './validate.mjs';
import {readFileSync} from 'node:fs';
const api=await loadInvestigation();
const data=api.INVESTIGATION_REGISTRY;
const clone=()=>structuredClone(data);

test('registry joins the substantive existing corpus without dropping namespaces or sources',()=>{assert.deepEqual(validateInvestigation(data),[]);assert.ok(data.entities.length>1800);assert.ok(data.relationships.length>3500);assert.ok(data.records.length>5000);assert.ok(data.sources.length>2800);for(const name of ['legacy','education','water','public-works','welfare','pmcares','justice-research','welfare-research','finance-research'])assert.ok(data.coverage.some(row=>row.namespace===name),name);assert.ok(data.held.length>250);});
test('IDs and every relationship endpoint remain unique even when legacy claim IDs recur across fleets',()=>{for(const key of ['entities','relationships','records','sources'])assert.equal(new Set(data[key].map(row=>row.id)).size,data[key].length);const repeated=data.relationships.filter(row=>row.id.includes('literature:c001'));assert.ok(repeated.length>=2);assert.ok(new Set(repeated.map(row=>row.id)).size===repeated.length);const entities=new Set(data.entities.map(row=>row.id));assert.ok(data.relationships.every(edge=>entities.has(edge.from)&&entities.has(edge.to)));});
test('modern state codes retain Ladakh and merged UT while ambiguous legacy boundaries remain unassigned',()=>{assert.equal(data.states.length,36);assert.equal(api.normalizeInvestigationState('LA'),'LA');assert.equal(api.normalizeInvestigationState('DN'),'DN');for(const code of ['jk','dn','dd'])assert.equal(api.normalizeInvestigationState(code),null);assert.equal(api.normalizeInvestigationState('ct'),'CG');assert.equal(api.normalizeInvestigationState('or'),'OD');assert.ok(!data.states.some(row=>row.code==='DD'));assert.ok(data.entities.filter(row=>row.namespace==='legacy').every(row=>row.geography.every(geo=>!['project-location','programme-coverage'].includes(geo.basis))));});
test('India school totals stay national and district counts do not fabricate population comparisons',()=>{const national=data.records.filter(row=>row.id.includes('education:school-count:schools-IN:'));assert.equal(national.length,5);assert.ok(national.every(row=>row.geography.every(geo=>geo.scope==='national'&&geo.stateCodes.length===0)));assert.ok(national.every(row=>/do not identify closure/.test(row.summary)));});
test('empty layer and tier selections mean no matches, not silently all data',()=>{for(const filters of [{layers:[]},{tiers:[]}]){const view=api.getInvestigationView(filters);assert.equal(view.records.length,0);assert.equal(view.relationships.length,0);assert.equal(view.entities.length,0);}assert.ok(api.getInvestigationView().records.length>5000);});
test('state coverage separates recorded programme/site coverage from entity associations and national context',()=>{const rows=api.getInvestigationStateCoverage({domains:['education']});assert.equal(rows.length,36);assert.ok(rows.every(row=>row.records>=row.coverageRecords&&row.records<=row.coverageRecords+row.associationRecords));assert.ok(rows.every(row=>row.nationalContextRecords>0));const coverage=api.getInvestigationStateCoverage({domains:['capital'],geographyMode:'coverage'});const associations=api.getInvestigationStateCoverage({domains:['capital'],geographyMode:'associations'});assert.ok(associations.reduce((n,row)=>n+row.records,0)>coverage.reduce((n,row)=>n+row.records,0));assert.deepEqual(api.getInvestigationStateCoverage({stateCode:'KA'}),api.getInvestigationStateCoverage({stateCode:'TN'}));});
test('unknown state and impossible domain filters yield empty views without synthetic records',()=>{assert.equal(api.getInvestigationView({stateCode:'NOT-A-STATE'}).records.length,0);assert.equal(api.getInvestigationView({domains:['made-up-domain']}).records.length,0);});
test('exact date filters preserve undated controls and do not turn publication into legal commencement',()=>{const dated=api.getInvestigationView({from:'2024-01-01',to:'2024-12-31',includeUndated:false});assert.ok(dated.records.length>0);assert.ok(dated.records.every(row=>row.fromDate||row.toDate));const wider=api.getInvestigationView({from:'2024-01-01',to:'2024-12-31',includeUndated:true});assert.ok(wider.records.length>dated.records.length);assert.ok(data.records.some(row=>row.kind==='rule'&&/effective/.test(row.dateBasis)));});
test('search resolves entity names and retained source titles without converting addresses to work geography',()=>{const company=data.entities.find(row=>row.originalId==='co:larsen-toubro');assert.ok(company);const view=api.getInvestigationView({q:'Larsen'});assert.ok(view.entities.some(row=>row.id===company.id));assert.ok(company.geography.every(geo=>geo.basis==='headquarters'));assert.ok(data.records.some(row=>row.namespace==='education'&&row.geography.some(geo=>geo.basis==='programme-coverage')));});
test('neighbor expansion is bounded and does not use denials, supersession or analytic links as connectors',()=>{const edge=data.relationships.find(api.isInvestigationConnectivityEdge);assert.ok(edge);const view=api.getInvestigationNeighbors(edge.from,1,{},1);assert.equal(view.entities.length,1);assert.ok(view.totalEntities>=2);assert.equal(view.truncated,true);assert.equal(api.isInvestigationConnectivityEdge({...edge,kind:'contra'}),false);assert.equal(api.isInvestigationConnectivityEdge({...edge,kind:'supersede'}),false);assert.equal(api.isInvestigationConnectivityEdge({...edge,tier:'analytic'}),false);});
test('directed shortest paths contain only retained sourced edges and respect caps',()=>{const edge=data.relationships.find(row=>api.isInvestigationConnectivityEdge(row)&&row.from!==row.to);const result=api.findInvestigationPaths(edge.from,edge.to,{}, {maxDepth:1});assert.ok(result.paths.some(path=>path.relationshipIds.includes(edge.id)));const byId=new Map(data.relationships.map(row=>[row.id,row]));for(const path of result.paths){assert.equal(path.entityIds.length,path.relationshipIds.length+1);for(let i=0;i<path.relationshipIds.length;i++){const leg=byId.get(path.relationshipIds[i]);assert.equal(leg.from,path.entityIds[i]);assert.equal(leg.to,path.entityIds[i+1]);assert.ok(leg.sourceIds.length);assert.ok(api.isInvestigationConnectivityEdge(leg));}}const capped=api.findInvestigationPaths(edge.from,edge.to,{}, {maxVisited:1});assert.equal(capped.paths.length,0);assert.equal(capped.truncated,true);assert.match(capped.reason,/not proof/);});
test('unavailable endpoints and same-entity paths return explicit non-inferential outcomes',()=>{const id=data.entities[0].id;assert.equal(api.findInvestigationPaths('not-real',id).paths.length,0);const same=api.findInvestigationPaths(id,id);assert.deepEqual(same.paths,[{entityIds:[id],relationshipIds:[]}]);});
test('counter-evidence remains inspectable even when a claim-target edge cannot be drawn',()=>{const held=data.records.filter(row=>row.kind==='counter-evidence');assert.ok(held.length>0);assert.ok(held.every(row=>row.sourceIds.length>0));const responses=data.relationships.filter(row=>row.responseIds.length>0);assert.ok(responses.length>0);for(const row of responses)assert.ok(row.responseIds.every(id=>data.records.some(record=>record.id===id)));});
test('structural review questions state their population, alternative and falsifier without misconduct scores',()=>{const questions=api.getInvestigationReviewQuestions();assert.ok(questions.length>0);for(const row of questions){assert.ok(row.denominator>=row.numerator);assert.ok(row.denominatorLabel);assert.ok(row.alternativeExplanations.length);assert.ok(row.falsifier);assert.ok(!('riskScore' in row));}const mixed=questions.find(row=>row.kind==='accounting-comparability');assert.ok(mixed);assert.ok(mixed.recordIds.every(id=>data.records.find(row=>row.id===id).amounts.length>1));});
test('invalid sources, endpoints, monetary stages and geography fail validation',()=>{const broken=clone();broken.relationships[0].to='unresolved-id';broken.records[0].sourceIds=['missing-source'];broken.records[0].amounts=[{value:1,currency:'INR',unit:'crore',period:'2024'}];broken.records[0].geography[0].stateCodes=['DD'];const errors=validateInvestigation(broken);for(const term of ['orphan graph endpoint','missing or orphan source','amount needs','current state code'])assert.ok(errors.some(error=>error.includes(term)),term);});
test('source identifiers and original route links remain recoverable for saved-item closure',()=>{const entity=data.entities[0],relationship=data.relationships[0],record=data.records[0];assert.equal(api.getInvestigationItem('entity',entity.id),entity);assert.equal(api.getInvestigationItem('relationship',relationship.id),relationship);assert.equal(api.getInvestigationItem('record',record.id),record);assert.ok(api.getInvestigationSource(record.sourceIds[0]));assert.equal(api.getRouteLens('/education').domains[0],'education');assert.equal(api.getRouteLens('/justice').domains[0],'justice');assert.equal(api.getRouteLens('/debt').domains[0],'debt-relief');assert.deepEqual(api.getRouteLens('/investigate').domains,[]);});

test('malformed collection metadata is rejected without throwing or silently treating strings as arrays',()=>{for(const mutation of [row=>row.records[0].sourceIds='source',row=>row.relationships[0].recordIds={},row=>row.entities[0].geography[0].stateCodes='KA',row=>row.relationships[0].amounts='100',row=>row.records.push(null)]){const broken=clone();mutation(broken);let errors;assert.doesNotThrow(()=>{errors=validateInvestigation(broken);});assert.ok(errors.length>0);}});
test('new raw research cannot omit tiers, resolved identity, amounts or dated-status fields',()=>{const raw=JSON.parse(readFileSync(new URL('../../research/raw/investigation/finance-research.json',import.meta.url),'utf8'));assert.deepEqual(validateResearchSlice(raw,'finance'),[]);delete raw.sources[0].tier;delete raw.entities[0].resolved;delete raw.relationships[0].amounts;delete raw.records[0].statusAsOf;const errors=validateResearchSlice(raw,'finance');for(const term of ['explicit tier','resolved identity','amounts array','nullable statusAsOf'])assert.ok(errors.some(error=>error.includes(term)),term);assert.deepEqual(validateResearchSlices(),[]);});
test('all three evidence manifests are required and retained bytes match their hashes',()=>{assert.deepEqual(validateInvestigationManifests(),[]);const file='research/raw/investigation/finance-research.json';const bytes=readFileSync(new URL(`../../${file}`,import.meta.url));const errors=validateManifestRows([{path:file,bytes:bytes.length,sha256:'0'.repeat(64)}]);assert.ok(errors.some(error=>error.includes('digest mismatch')));assert.ok(validateManifestRows([{path:file}]).length>0);assert.ok(validateManifestRows([]).length>0);});
test('malformed date queries and unknown role end dates do not imply indefinite office tenure',()=>{for(const filters of [{from:'2024-02-30'},{to:'2024-13-01'},{from:'2025-01-01',to:'2024-01-01'}])assert.equal(api.getInvestigationView(filters).records.length,0);const future=api.getInvestigationView({from:'2099-01-01',includeUndated:false});assert.equal(future.records.length,0);const edge=data.relationships.find(row=>api.isInvestigationConnectivityEdge(row));for(const kind of ['denial','comparison'])assert.equal(api.isInvestigationConnectivityEdge({...edge,kind}),false);});
test('relationship record titles identify their endpoints and geography sources survive filtered ledger closure',()=>{const record=data.records.find(row=>row.namespace==='legacy'&&row.kind==='relationship-record');assert.ok(record);for(const id of record.entityIds)assert.ok(record.title.includes(api.getInvestigationItem('entity',id).label));const view=api.getInvestigationView({domains:['justice']});const sources=new Set(view.sources.map(row=>row.id));for(const row of [...view.entities,...view.relationships,...view.records])for(const geo of row.geography)for(const id of geo.sourceIds)assert.ok(sources.has(id));assert.ok(data.records.filter(row=>row.namespace==='public-works'&&row.kind==='reported-event').every(row=>row.tier==='reported'));});

test('topic route lenses reflect dossier imports while cross-domain methods remain intentionally broad',()=>{for(const [route,domains] of Object.entries({'/industries':['capital'],'/media':['capital'],'/interlocks':['capital','governance'],'/resources':['energy','capital','governance'],'/allocation':['capital','energy','public-works','governance'],'/competition':['public-works','energy','security'],'/states/ka':['capital','governance'],'/security':['security']}))assert.deepEqual(api.getRouteLens(route).domains,domains,route);for(const route of ['/method','/patterns','/provenance','/base-rates','/capture','/motifs','/prospector','/desk','/network','/geograph','/atlas'])assert.deepEqual(api.getRouteLens(route).domains,[],route);});

test('reviewed public-works sector tags expose electricity and school evidence in corresponding route lenses',()=>{const energy=api.getInvestigationView({domains:['energy'],q:'DDUGJY'});const energyRecords=new Set(energy.records.map(row=>row.id));for(const id of ['public-works:document:svc-up-electricity-audit','public-works:case:svc-overlapping-manpower','public-works:case:svc-duplicate-connections',...Array.from({length:4},(_,i)=>`public-works:relationship-record:svc-manpower-contract-${i}`)])assert.ok(energyRecords.has(id),id);assert.equal(energy.records.filter(row=>row.namespace==='public-works').length,7);assert.ok(energy.relationships.some(row=>row.id==='public-works:relationship:svc-manpower-contract-0'));const schools=api.getInvestigationView({domains:['education'],q:'Azamgarh'});assert.ok(schools.records.some(row=>row.id==='public-works:case:svc-school-rework'));assert.ok(schools.records.some(row=>row.id==='public-works:document:svc-up-school-audit'));assert.ok(api.getInvestigationView({domains:['energy']}).records.some(row=>row.id==='public-works:rule:svc-electricity-rule-change'));assert.ok(api.getInvestigationView({domains:['education']}).records.some(row=>row.id==='public-works:rule:svc-ka-rte-background'));assert.ok(!energyRecords.has('public-works:case:svc-school-rework'));assert.ok([...energy.records,...schools.records].filter(row=>row.namespace==='public-works').every(row=>row.domains.includes('public-works')));});

test('procurement trail cohorts remain sourced pinnable records with distinct populations and no supplier graph identities',()=>{const records=data.records.filter(row=>row.namespace==='procurement-trails');assert.equal(records.length,156);assert.ok(records.every(row=>row.kind==='procurement-cohort'&&row.amounts.length===0&&row.entityIds.length===0&&row.relationshipIds.length===0));assert.ok(records.every(row=>row.geography.every(geo=>geo.scope==='national'&&geo.stateCodes.length===0)));assert.equal(data.entities.filter(row=>row.namespace==='procurement-trails').length,0);assert.equal(data.relationships.filter(row=>row.namespace==='procurement-trails').length,0);for(const record of records){assert.equal(api.getInvestigationItem('record',record.id),record);assert.ok(record.sourceIds.every(id=>api.getInvestigationSource(id)));assert.ok(record.route.includes('trail='));}assert.ok(records.some(row=>/Concentration is outside/.test(row.summary)));});


test('corpus procurement audit cards are source-closed analytical findings, independent of buyer cohorts',()=>{const records=data.records.filter(row=>row.namespace==='procurement-audit');assert.equal(records.length,9);assert.ok(records.every(row=>row.kind==='procurement-source-audit'&&row.tier==='analytic'&&row.amounts.length===0&&row.entityIds.length===0&&row.relationshipIds.length===0));assert.equal(data.entities.filter(row=>row.namespace==='procurement-audit').length,0);assert.equal(data.relationships.filter(row=>row.namespace==='procurement-audit').length,0);for(const record of records){assert.ok(record.sourceIds.every(id=>api.getInvestigationSource(id)));assert.ok(record.geography.every(geo=>geo.basis==='national-context'&&geo.stateCodes.length===0));}const semantic=api.getInvestigationItem('record','procurement-audit:record:closing-field-semantics');assert.ok(semantic);assert.match(semantic.summary,/1,709 of 1,714/);assert.ok(semantic.limitations.some(text=>/not representative/.test(text)));});
