#!/usr/bin/env node
/** Workspace-specific source closure, exact identity, URL history and mobile inspection acceptance. */
import assert from 'node:assert/strict';
import {existsSync, readFileSync, mkdirSync} from 'node:fs';
import {createServer} from 'node:http';
import {resolve, extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright';
import {loadInvestigation} from './load.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url));
const dist=resolve(root,process.env.INVESTIGATION_DIST??'dist');
const out=resolve(root,process.env.INVESTIGATION_WORKSPACE_ARTIFACTS??'/tmp/investigation-workspace-review');mkdirSync(out,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.woff2':'font/woff2'};
const server=createServer((req,res)=>{const path=new URL(req.url,'http://localhost').pathname;const file=resolve(dist,`.${path==='/'?'/index.html':path}`);if(!file.startsWith(`${dist}/`))return res.writeHead(403).end();try{res.writeHead(200,{'content-type':mime[extname(file)]??'application/octet-stream'}).end(readFileSync(file));}catch{res.writeHead(404).end();}});
let base=process.env.INVESTIGATION_BASE_URL;let listening=false;
if(!base){await new Promise(done=>server.listen(0,'127.0.0.1',done));listening=true;base=`http://127.0.0.1:${server.address().port}`;}base=base.replace(/\/$/u,'');
const api=await loadInvestigation();const data=api.INVESTIGATION_REGISTRY;
const edge=data.relationships.find(item=>api.isInvestigationConnectivityEdge(item)&&item.from!==item.to&&item.fromDate);
const sourceRecord=data.records.find(item=>item.namespace==='public-works'&&item.sourceIds.length);
const binary=process.env.PLAYWRIGHT_CHROMIUM_PATH??'/usr/bin/chromium';
const browser=await chromium.launch(existsSync(binary)?{executablePath:binary}:{});
let checks=0;let lastPass='';const ok=(v,msg)=>{assert.ok(v,msg);checks++;lastPass=msg;};
const errors=[];const page=await browser.newPage({viewport:{width:1440,height:980},acceptDownloads:true,reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));
const go=async(path)=>{
 const target=new URL(path,'http://workspace.local');const p=target.searchParams;
 const surface=['map','connections','evidence','casebook','dossier'].includes(p.get('iw_view'))?p.get('iw_view'):'map';
 const state=p.has('iw_state')?(data.states.some(row=>row.code===p.get('iw_state'))?p.get('iw_state'):''):(api.normalizeInvestigationState(/^\/states\/([^/]+)$/u.exec(target.pathname)?.[1])??'');
 const validLayers=api.INVESTIGATION_LAYERS.map(row=>row.value).filter(value=>(p.get('iw_layers')??'').split(',').includes(value));
 const lens=api.getRouteLens(target.pathname);const expectedRecords=api.getInvestigationView({stateCode:state||undefined,q:p.get('iw_q')?.trim()||undefined,domains:p.get('iw_scope')==='all'||!lens.domains.length?undefined:lens.domains,layers:p.get('iw_layers')==='none'?[]:validLayers.length?validLayers:undefined}).records.length;
 const id=[p.get('iw_edge'),p.get('iw_record'),p.get('iw_node')].find(id=>id&&[...data.entities,...data.relationships,...data.records].some(row=>row.id===id))??null;
 await page.goto(`${base}/#${path}`);
 await page.waitForFunction(({route,surface,state,q,id,expectedRecords})=>{const workspace=document.querySelector('[data-investigation-workspace]');return workspace?.getAttribute('data-workspace-route')===route&&workspace.classList.contains(`iw-surface-${surface}`)&&Number(document.querySelector('.iw-result-bar strong')?.textContent?.replace(/,/gu,''))===expectedRecords&&document.querySelector('#iw-global-query')?.value===q&&document.querySelector('select[aria-labelledby="iw-state-label"]')?.value===state&&(surface==='casebook'||surface==='dossier'||(document.querySelector('[data-investigation-selection]')?.getAttribute('data-investigation-selection')??null)===id);},{route:target.pathname,surface,state,q:p.get('iw_q')??'',id,expectedRecords},{timeout:45000});
 await page.evaluate(()=>document.fonts.ready);
};
function parseCsv(csv){
 const rows=[];let row=[],cell='',quoted=false;const text=csv.replace(/^\uFEFF/u,'');
 for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(char===','&&!quoted){row.push(cell);cell='';}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';}else cell+=char;}
 if(cell||row.length){row.push(cell);rows.push(row);}assert.equal(quoted,false);const [headers,...values]=rows;return values.map(values=>Object.fromEntries(headers.map((header,i)=>[header,values[i]])));
}
const exportCsv=async()=>{const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Export records CSV',exact:true}).click();return parseCsv(readFileSync(await(await downloaded).path(),'utf8'));};
const params=()=>new URLSearchParams(new URL(page.url()).hash.split('?')[1]);
try{
 await go('/public-works?sector=water&state=KA&networkView=table');
 await page.getByLabel('Place',{exact:true}).selectOption('MH');ok(params().get('state')==='KA'&&params().get('sector')==='water'&&params().get('networkView')==='table','Workspace geographic selection preserves legacy query state');
 await page.getByRole('button',{name:'Layers & dates',exact:true}).click();
 await page.getByLabel('Compare state coverage',{exact:true}).selectOption('KA');ok((await page.getByRole('region',{name:'State evidence coverage comparison'}).innerText()).includes('Karnataka'),'State comparison exposes coverage and association denominators');
 await page.getByRole('button',{name:'Reset workspace',exact:true}).click();ok(!params().has('iw_state')&&params().get('state')==='KA','Reset removes only workspace keys');
 await page.getByLabel('Search across people, companies, cases and schemes',{exact:true}).fill('PM CARES');await page.getByRole('search').getByRole('button',{name:'Search',exact:true}).click();ok(params().get('iw_scope')==='all','Global search explicitly broadens topic scope');ok(!(await page.locator('.iw-result-bar').innerText()).startsWith('0 /'),'Cross-domain search finds retained evidence');
 await page.goBack();await page.waitForFunction(()=>document.querySelector('#iw-global-query')?.value==='');ok(!params().has('iw_q'),'Browser history restores the prior search state');
 for(let cycle=0;cycle<5;cycle++){
  await go('/investigate');await page.locator('#iw-global-query').fill(`workspace-history-regression-${cycle}`);await page.getByRole('search').getByRole('button',{name:'Search',exact:true}).click();await page.goBack();await page.waitForFunction(()=>!new URLSearchParams(location.hash.split('?')[1]).has('iw_q')&&document.querySelector('#iw-global-query')?.value==='');ok(!params().has('iw_q')&&await page.locator('#iw-global-query').inputValue()==='',`Rapid global Search/Back cycle ${cycle+1} restores both URL and input`);
 }
 await go('/pmcares');ok(await page.getByLabel('Topic scope',{exact:true}).inputValue()==='route'&&(await page.locator('.iw-result-bar').innerText()).includes('PM CARES'),'PM CARES route starts with its own registry lens');
 await go('/states/mh');ok(await page.getByLabel('Place',{exact:true}).inputValue()==='MH','State profile defaults map to unambiguous modern state');await page.getByLabel('Place',{exact:true}).selectOption('');await page.waitForURL(/iw_state=all/);await page.waitForFunction(()=>document.querySelector('select[aria-labelledby="iw-state-label"]')?.value==='');ok(params().get('iw_state')==='all'&&await page.getByLabel('Place',{exact:true}).inputValue()==='','All India overrides a state route explicitly');
 await go('/states/ka');await page.getByRole('navigation',{name:'Primary navigation',exact:true}).getByRole('link',{name:'Education',exact:true}).click();await page.waitForURL(/education/);await page.waitForFunction(()=>document.querySelector('select[aria-labelledby="iw-state-label"]')?.value==='KA');ok(params().get('iw_state')==='KA','Cross-lens navigation preserves the implicit modern state route context');
 await go('/states/ka?iw_state=all');await page.getByRole('navigation',{name:'Primary navigation',exact:true}).getByRole('link',{name:'Education',exact:true}).click();await page.waitForURL(/education/);ok(params().get('iw_state')==='all','Cross-lens navigation retains an explicit All India override');
 await go('/states/ka');await page.locator('.atlas-case-title').first().click();await page.locator('.iw-selected-record').waitFor();const dossierHref=await page.locator('.iw-selected-record').getByRole('link',{name:'Open dossier',exact:true}).getAttribute('href');ok(dossierHref.includes('iw_state=KA'),'Selected-record dossier link retains an implicit state route');await page.locator('.iw-workspace-footer').getByRole('link',{name:'Evidence method',exact:true}).click();await page.waitForURL(/method/);await page.locator('.iw-dossier-content').waitFor();ok(params().get('iw_state')==='KA'&&params().get('iw_view')==='dossier','Workspace method link carries implicit state into the full dossier');
 await go('/states/jk');ok((await page.locator('.iw-invalid').innerText()).includes('legacy state dossier'),'Ambiguous legacy state boundary does not silently become modern Jammu and Kashmir');
 for(const [prefix,kind] of [['/company/','co:'],['/conglomerates/','grp:']]){
  const entity=data.entities.find(item=>item.namespace==='legacy'&&item.resolved&&item.originalId.startsWith(kind));assert.ok(entity);
  await go(`${prefix}${entity.originalId.slice(kind.length)}`);ok(!params().has('iw_node')&&await page.locator('[data-investigation-selection]').count()===0,`${kind} route does not silently select a named graph focus`);
  await page.getByRole('button',{name:`Focus ${entity.label} in connections`,exact:true}).click();await page.waitForURL(url=>new URLSearchParams(url.hash.split('?')[1]).get('iw_node')===entity.id);await page.locator(`[data-investigation-selection="${entity.id}"]`).waitFor();ok(params().get('iw_view')==='connections',`${kind} route explicitly focuses its exact canonical ID`);
 }
 await page.setViewportSize({width:768,height:1000});await go('/public-works');ok(await page.getByLabel('Place',{exact:true}).evaluate(element=>element.getBoundingClientRect().width)>=160&&await page.getByLabel('Topic scope',{exact:true}).evaluate(element=>element.getBoundingClientRect().width)>=160,'768px state and topic controls retain readable widths');await page.setViewportSize({width:1440,height:980});
 await go('/public-works?iw_layers=none');ok((await page.locator('.iw-result-bar').innerText()).startsWith('0 /'),'Empty layer selection produces a real zero view');
 await go('/public-works?iw_layers=bogus&iw_from=2026-02-30&iw_node=absent');ok((await page.locator('.iw-invalid').innerText()).includes('start date'),'Malformed URL values are explained');ok(!(await page.locator('.iw-result-bar').innerText()).startsWith('0 /'),'Unknown-only layer input uses stated default');
 await go('/education?iw_view=evidence');const fastDownload=page.waitForEvent('download');await page.evaluate(()=>{const scope=document.querySelector('select[aria-labelledby="iw-scope-label"]');scope.value='all';scope.dispatchEvent(new Event('change',{bubbles:true}));[...document.querySelectorAll('.iw-evidence-ledger button')].find(button=>button.textContent==='Export records CSV').click();});const allRows=parseCsv(readFileSync(await(await fastDownload).path(),'utf8'));ok(allRows.length===data.records.length,'Same-task scope change/export serializes the current URL and every record beyond the visible page');
 const geoRecord=data.records.find(row=>row.geography.some(geo=>geo.sourceIds.some(id=>!row.sourceIds.includes(id))));assert.ok(geoRecord,'Fixture has independently sourced geography');
 await go(`/investigate?iw_view=evidence&iw_q=${encodeURIComponent(geoRecord.id)}&iw_record=${encodeURIComponent(geoRecord.id)}`);
 const geoRows=await exportCsv();const geoRow=geoRows.find(row=>row.id===geoRecord.id);assert.ok(geoRow);const geoSources=JSON.parse(geoRow.sources);ok(geoRecord.geography.every(geo=>geo.sourceIds.every(id=>geoSources.some(source=>source.id===id&&source.url&&source.locator))),'CSV closes independent geographic source metadata');ok(geoRecord.geography.flatMap(geo=>geo.sourceIds).every(id=>data.sources.some(source=>source.id===id)),'Geographic citations resolve to real registry source IDs');
 const edgeById=new Map(data.relationships.map(edge=>[edge.id,edge]));
 const claim=data.records.find(row=>row.relationshipIds.some(id=>edgeById.get(id)?.responseIds.length));assert.ok(claim,'Fixture has an exact linked response');
 await go(`/investigate?iw_view=evidence&iw_q=${encodeURIComponent(claim.id)}&iw_record=${encodeURIComponent(claim.id)}`);
 const claimRows=await exportCsv();const claimRow=claimRows.find(row=>row.id===claim.id);assert.ok(claimRow);const responseIds=[...new Set(claim.relationshipIds.flatMap(id=>edgeById.get(id)?.responseIds??[]))];const responses=JSON.parse(claimRow.linkedResponses);ok(responseIds.every(id=>responses.some(response=>response.id===id&&response.sources.length)),'Filtered CSV retains exact linked responses and their sources outside filters');ok(JSON.parse(claimRow.entityIds).length===claim.entityIds.length&&JSON.parse(claimRow.relationshipIds).length===claim.relationshipIds.length,'CSV retains identity and relationship pointers');ok((await page.locator('.iw-selected-record').textContent()).includes('Linked responses outside filter limits'),'Record inspector exposes exact linked responses directly');
 await go(`/public-works?iw_scope=all&iw_record=${encodeURIComponent(sourceRecord.id)}`);await page.locator('[data-investigation-selection]').waitFor();ok((await page.locator('.iw-selected-record').innerText()).includes(sourceRecord.title),'Direct record deep link restores full inspector');await page.getByRole('button',{name:'Pin evidence',exact:true}).click();await page.getByRole('button',{name:'Clear evidence selection',exact:true}).click();await page.getByRole('button',{name:'Open local casebook',exact:true}).click();await page.locator('[data-casebook-pin]').first().waitFor();ok(await page.locator('[data-casebook-pin]').count()===1,'Selected source record pins into browser-local casebook');
 await page.getByLabel('Question or hypothesis',{exact:true}).fill('Which records resolve this comparison?');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export evidence JSON',exact:true}).click();const result=JSON.parse(readFileSync(await(await download).path(),'utf8'));ok(result.casebook.question.includes('Which records')&&result.sources.length>0,'Evidence packet includes analyst question and source closure');
 await page.getByRole('button',{name:'Inspect source record',exact:true}).click();await page.waitForURL(/iw_view=evidence/);await page.locator('[data-investigation-selection]').waitFor();ok(params().get('iw_view')==='evidence'&&params().get('iw_record')===sourceRecord.id,'Casebook inspection composes both URL changes without losing selection');
 await go('/investigate?iw_view=connections');await page.locator('.iw-trace>summary').click();
 for(const [index,id] of [[0,edge.from],[1,edge.to]]){const picker=page.locator('.iw-identity-picker').nth(index);await picker.locator('summary').click();await picker.locator('input').fill(id);await picker.locator('li button').filter({has:page.getByText(id,{exact:true})}).click();}
 await page.locator('.iw-path-results').waitFor();ok(params().get('iw_pathFrom')===edge.from&&params().get('iw_pathTo')===edge.to,'Identity picker requires explicit canonical endpoint choices');
 await go(`/investigate?iw_view=connections&iw_pathFrom=${encodeURIComponent(edge.from)}&iw_pathTo=${encodeURIComponent(edge.to)}&iw_direction=directed`);ok((await page.locator('.iw-path-results').innerText()).includes('recorded steps'),'Resolved endpoint deep link returns inspectable bounded path');ok(await page.locator('.iw-graph-edge.is-path').count()>0,'Returned path highlights exact relationship edges');
 await go(`/public-works?iw_scope=all&iw_record=${encodeURIComponent(sourceRecord.id)}&iw_q=zzzz_no_record_zzzz`);ok((await page.locator('.iw-selected-record .iw-notice').innerText()).includes('outside the current filters'),'Linked artifact outside filters remains explicitly distinguished');
 for(const width of [390,320]){
  await page.setViewportSize({width,height:900});await go(`/public-works?iw_scope=all&iw_view=evidence&iw_record=${encodeURIComponent(sourceRecord.id)}`);await page.locator('.iw-inspector-open').waitFor();ok(await page.locator('.iw-inspector').isVisible(),`${width}px shared record opens readable inspector`);ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${width}px inspector has no horizontal page overflow`);await page.getByRole('button',{name:'Back to evidence list',exact:true}).click();ok(await page.locator('.iw-evidence-ledger').isVisible(),`${width}px back returns to evidence while preserving selection`);await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-pressed')==='true');ok(await page.locator('.iw-surfaces button[aria-pressed=true]').evaluate(element=>element===document.activeElement),`${width}px inspector return restores keyboard surface focus`);await page.getByRole('button',{name:'Inspect selected evidence',exact:true}).click();ok(await page.locator('.iw-inspector').isVisible(),`${width}px selected artifact remains reachable`);await page.screenshot({path:resolve(out,`inspector-${width}.png`)});
 }
 await page.setViewportSize({width:390,height:844});await go('/energy?iw_view=dossier');await page.waitForFunction(()=>document.activeElement===document.querySelector('.iw-dossier-content h1'));ok(await page.locator('.iw-dossier-content h1').evaluate(heading=>{const rect=heading.getBoundingClientRect();return rect.top>=0&&rect.bottom<300;}),'Explicit mobile dossier entry focuses the lazy reading heading within the first screen');
 const enteredScroll=await page.locator('main').evaluate(main=>main.scrollTop);await page.locator('main').evaluate(main=>{main.scrollTop+=100;});await page.locator('#gq').fill('coal');await page.waitForURL(url=>new URLSearchParams(url.hash.split('?')[1]).get('q')==='coal');await page.waitForTimeout(120);ok(await page.locator('main').evaluate((main,start)=>main.scrollTop>=start+75,enteredScroll)&&await page.locator('#gq').evaluate(input=>document.activeElement===input),'Dossier filter edits preserve the reader position and active input instead of repeating entry focus');
 ok(errors.length===0,`No browser runtime exceptions: ${errors.join(' | ')}`);console.log(JSON.stringify({passed:true,checks}));
}catch(error){console.error(JSON.stringify({passed:false,checks,lastPass,url:page.url(),message:error.message}));throw error;}finally{await browser.close();if(listening)await new Promise(done=>server.close(done));}
