#!/usr/bin/env python3
"""Two source-bounded allegation/adjudication networks; no inferred guilt or money receipts."""
import json, pathlib
ROOT=pathlib.Path(__file__).resolve().parent
OUT=ROOT.parent/'policy.json'
D={'sources':[],'entities':[],'relationships':[],'records':[],'localities':[]}
ROUTE='/allegations'
P=['finance','capital','debt-relief','justice']
T=['transport','public-works','public-funds','justice']

def src(i,title,url,publisher,date,loc,summary,limits=(),tier='documented'):
 D['sources'].append(dict(id=i,title=title,url=url,publisher=publisher,publishedAt=date,retrievedAt='2026-10-07',locator=loc,summary=summary,tier=tier,limitations=list(limits)))
def geo(s,states=None,note=None):
 return [dict(scope='state' if states and len(states)==1 else 'multi-state' if states else 'national',stateCodes=states or [],localityIds=[],basis='project-location' if states else 'national-context',note=note or ('Explicit project or auction jurisdiction; no coordinates inferred.' if states else 'India institutional or investor-scheme context; not evidence of a payment in every state.'),sourceIds=s)]
def dims(s,dom,states=None,layers=None,limits=()):
 return dict(sourceIds=s,domains=dom,layers=layers or ['organisations','funding','legal'],route=ROUTE,geography=geo(s,states),limitations=list(limits))
def ent(i,label,typ,summary,s,dom,states=None,resolved=True,limits=()):
 D['entities'].append(dict(id=i,label=label,type=typ,resolved=resolved,identityBasis='Exact named entity or expressly labelled source-defined cohort/instrument; no name-only corporate crosswalk.',summary=summary,**dims(s,dom,states,limits=limits)))
def amt(v,u,stage,period):return dict(value=v,currency='INR',unit=u,stage=stage,period=period)
def rel(i,a,b,label,summary,s,dom,date,records,responses=(),amounts=(),tier='documented',kind='documented-relationship',status=None,asof=None,end=None,states=None,limits=(),alts=(),falsifier=None):
 D['relationships'].append(dict(id=i,**{'from':a,'to':b},kind=kind,label=label,tier=tier,status=status or 'Dated source-supported relationship; see financial stage and response',statusAsOf=asof or date,fromDate=date,toDate=end or date,dateBasis='Date of the specified instrument, finding or observation, not an inferred transaction or continuing status.',summary=summary,alternativeExplanations=list(alts),falsifier=falsifier or 'A corrected original instrument, transaction reconciliation or later reasoned order changing this specific assertion would require revision.',responseIds=list(responses),recordIds=list(records),amounts=list(amounts),**dims(s,dom,states,limits=limits)))
def rec(i,title,summary,s,dom,date,ents,rels,period,response,kind='evidence-record',tier='documented',status=None,asof=None,end=None,amounts=(),states=None,limits=(),alts=(),falsifier=None):
 D['records'].append(dict(id=i,title=title,summary=summary,kind=kind,tier=tier,status=status or 'Dated finding or response; current limits stated',statusAsOf=asof or date,fromDate=date,toDate=end or date,dateBasis='Event dates and last verified status are distinct; historical aggregates are expressly labelled in the amount period.',entityIds=ents,relationshipIds=rels,period=period,response=response,alternativeExplanations=list(alts),falsifier=falsifier or 'Check the cited original against any subsequent order and trace receipts separately from assessed amounts or asset values.',amounts=list(amounts),**dims(s,dom,states,layers=['organisations','funding','legal','review'],limits=limits)))

src('pacl-order-2014','SEBI: Order in the matter of PACL Limited, 22 August 2014','https://www.sebi.gov.in/sebi_data/attachdocs/1408704987673.pdf','Securities and Exchange Board of India','2014-08-22','Original PDF pp 27,70–80,87–92; paragraphs 35–42','SEBI found the land-linked plans to be unregistered collective investment schemes, directed winding up and refund, recorded PACL defences and preserved genuinely certified sale deeds.',[
 'Archive: policy-evidence/pacl-order-2014-retry.receipt.json, original PDF and page-marked text. Initial incomplete HTTP read is separately logged.',
 'The approximately ₹49,100 crore figure includes pre-window collections and an expressly missing April 2012–25 February 2013 period; it is not a 2011–2026 loss, current liability or refund denominator.',
 'Regulatory finding and directions are not a criminal conviction. Section 37 preserves sale deeds certified as genuine by Justice K. Swamidurai.'])
src('pacl-board-2026','SEBI Board memorandum: developments of the Justice R.M. Lodha Committee','https://www.sebi.gov.in/sebi_data/meetingfiles/jul-2026/1782895902429_1.pdf','Securities and Exchange Board of India',None,'July 2026 archive; current memorandum PDF pp 1–4, paragraphs 2.2–2.9; prior memorandum pp 5–9','Reports cumulative refunds of ₹3,720.67 crore to 35,74,401 eligible applications as of 5 May 2026; separately reports auctioned property value and designated-bank balance.',[
 'Archive: policy-evidence/pacl-board-2026.receipt.json; original 3.44 MB PDF in /workspace/research-cache/allegations-policy; full text and excerpt retained.',
 'Exact publication day is not supplied. The 5 May 2026 observation date is not presented as publication date.',
 'The PDF also embeds an older memorandum. Its ₹1,163 crore/22,16,132-application figures are dated 31 March 2025 and are not current totals.',
 'The statement about eligible claims does not mean every PACL investor was repaid: later notice expressly identifies deficient bank-verification applications.'])
src('pacl-refund-extension','PACL public notice: bank-account rectification deadline extended to 6 October 2026','https://www.sebi.gov.in/documents/extension%20of%20time.pdf','Justice (Retd.) R.M. Lodha Committee / SEBI','2026-08-03','Original PDF p 1, paragraphs 1–3','Certain applications could not be processed because of deficiencies; bank-verification rectification window extended through 6 October 2026.',[
 'Archive: policy-evidence/pacl-refund-extension.receipt.json.',
 'A procedural rectification opportunity is neither a new refund total nor assurance that every applicant qualifies. No subsequent extension established in this review.'])
src('pacl-sc-sep2026','Supreme Court: Subrata Bhattacharya v SEBI, 9 September 2026 order','https://www.sebi.gov.in/documents/Order-34668_2015-09-09-2026.pdf','Supreme Court of India; official SEBI archive','2026-09-09','Original PDF pp 19–21; Civil Appeal 13301/2015 and connected applications','Court accepts specified property-objection recommendations, directs reports on other applications and lists the matter for 8 October 2026.',[
 'Archive: policy-evidence/pacl-sc-2026.receipt.json.',
 'This resolves identified interlocutory applications and does not declare all assets PACL-owned, all investors repaid or the entire proceeding closed.',
 '8 October 2026 is a scheduled hearing after this atlas observation window, not a completed outcome.'])
src('pacl-bengaluru-rfp','Lodha Committee: Bengaluru Rural property e-auction tender JRMLC/KAR/BENRUR','https://www.sebi.gov.in/documents/RFP%20of%20Bangaluru_Rural%20dated-30sep2026.pdf','Justice (Retd.) R.M. Lodha Committee / SEBI','2026-09-30','Original PDF pp 1–5, clauses 1.1,1.11; tender schedule section 3','Appoints StockHolding Document Management Services Limited to assist the Committee and C1 India Private Limited as tender service provider for Bengaluru Rural auction; expressly says the Committee is not owner.',[
 'Archive: policy-evidence/pacl-bengaluru-rfp.receipt.json.',
 'Tender issued 30 September; November 2026 bid and auction dates are future milestones. No buyer, realised receipt, completed sale or provider fee is established.',
 'Auction-service roles are lawful recovery administration, not allegations against the service providers.'])
src('chapwa-dhc-official','Delhi High Court: Ganeshgarhia Construction v NHAI, W.P.(C) 9232/2025','https://delhihighcourt.nic.in/app/showFileJudgment/58711122025CW92322025_135032.pdf','Delhi High Court','2025-12-11','2025:DHC:11216; paragraphs 1–23 (allegations and submissions),30–42 (decision)','Records the alleged unrecorded toll collection, contractor defence, ₹10 lakh penalty and one-year debarment. Sets aside only debarment for procedural defects, leaving contractual remedies for termination/penalty.',[
 'Official URL was opened through indexed full-text fetch and retained as policy-evidence/dhc-toll-2025.official-indexed.txt with receipt. Direct official-host PDF GET attempts timed out; those failures are preserved.',
 'Downloaded PDF bytes are supplied under the separate mirror source, not misrepresented as a successful official-host download.',
 'Paragraph 41 calls the contract 25 July 2025, while paragraphs 1–2 and reproduced work order identify 25 July 2024. The latter identifies the contract here; discrepancy is not a second contract.',
 'The judgment expressly refrains from underlying factual conclusions at paragraph 34. No later appeal, penalty recovery or contractual award was established by the current search.'])
src('chapwa-dhc-mirror','Mirror of Delhi High Court judgment: Ganeshgarhia Construction v NHAI','https://rawlaw.in/wp-content/uploads/2025/12/GANESHGARHIA.pdf','Delhi High Court; PDF hosted by Rawlaw','2025-12-11','Original-format 24-page judgment; pages 1–7,10–14,20–24','Downloaded court-document PDF, cross-checked against the official-host indexed judgment including both parties’ submissions and dispositive paragraphs.',[
 'Archive: policy-evidence/dhc-toll-2025-mirror.receipt.json, PDF and full text.',
 'Publisher is the court; byte host is a third-party mirror. No claim of byte-for-byte equality with the inaccessible official download.',
 'The official document’s conflicting contract year in paragraph 41 remains disclosed; no silent correction of the original.'])
src('pacl-reuters-2015','Reuters: tribunal upholds PACL refund order','https://www.reuters.com/article/world/india/securities-appellate-tribunal-upholds-75-billion-refund-order-against-pacl-idUSKCN0QN0IA/','Reuters','2015-08-18','Opened public indexed article heading and lead; authored corroboration note only','Contemporaneous Reuters lead reports that SAT upheld SEBI’s refund order against PACL.',[
 'Only the accessible heading/lead was returned on opening. No unreturned article text or dollar-to-rupee calculation is used.',
 'policy-evidence/pacl-reuters-2015.receipt.json hashes an authored access note, not commercial article bytes; full commercial text is not archived.'],tier='reported')

PO=['pacl-order-2014'];PB=['pacl-board-2026'];PC=['pacl-sc-sep2026'];PR=['pacl-bengaluru-rfp'];CH=['chapwa-dhc-official','chapwa-dhc-mirror']
ent('pacl-ltd','PACL Limited','company','Exact company formerly Gurwant Agrotech Limited and Pearls Agrotech Corporation Limited, as identified in SEBI’s order; not Punjab Alkalies & Chemicals Limited.',PO,P)
ent('pacl-investors','PACL scheme customers / investors','source-defined-cohort','Source-defined investor cohort, not a named legal person; individual identities, counts and eligibility differ across source periods.',PO+PB,P,resolved=False,limits=['No private investor names, account details or geographic distribution inferred.'])
ent('pacl-agents','PACL agents and field associates','source-defined-cohort','Commission-recipient cohort described by PACL and SEBI. No single agent is assigned the aggregate and commission receipt alone is not misconduct.',PO,P,resolved=False)
ent('pacl-sellers','PACL land sellers','source-defined-cohort','Unnamed seller cohort in PACL director’s statement that purchase money went directly to sellers rather than associate companies.',PO,P,resolved=False)
ent('pacl-associates','PACL approximately 250 land-holding associates','source-defined-cohort','Aggregate associated-company cohort identified in SEBI’s 2014 finding; individual legal companies and title documents are not resolved here.',PO,P,resolved=False)
ent('pacl-assets','PACL / associate property recovery pool','asset-pool','Property documents and interests administered in the recovery process; contested ownership and objections remain possible.',PB+PR+PC,P,resolved=False,limits=['Neither Committee ownership nor PACL ownership of every restrained property is inferred.'])
ent('sebi','Securities and Exchange Board of India','regulator','Issued the 2014 regulatory order and supports the court-directed recovery administration.',PO+PB,P)
ent('supreme-court','Supreme Court of India','court','Directed constitution of the Lodha Committee and continues property-related proceedings.',PR+PC,P)
ent('lodha-committee','Justice (Retd.) R.M. Lodha Committee (PACL)','court-appointed-committee','Court-directed disposal and refund administrator; expressly not owner of auctioned properties.',PB+PR,P)
ent('stockholding-dms','StockHolding Document Management Services Limited','company','Named auction-assistance agency in September 2026 Bengaluru Rural tender. No allegation is made against this provider.',PR,P,['KA'])
ent('c1-india','C1 India Private Limited','company','Named e-auction service provider in the Bengaluru Rural tender; no purchase or beneficial ownership inferred.',PR,P,['KA'])
ent('bengaluru-auction','Bengaluru Rural PACL property auction, September 2026 tender','auction-instrument','Tender JRMLC/KAR/BENRUR is a planned recovery sale; bid/auction dates occur in November 2026.',PR,P,['KA'])
ent('nhai','National Highways Authority of India','public-authority','Contracting and enforcement authority in the Chapwa toll dispute; court scrutinised its decision-making process.',CH,T,['UP'])
ent('ganeshgarhia','Ganeshgarhia Construction Private Limited','company','Exact petitioner and Chapwa user-fee collection contractor in W.P.(C) 9232/2025; allegations disputed and debarment set aside.',CH,T,['UP'])
ent('chapwa-contract','Chapwa Fee Plaza user-fee contract, 25 July 2024','contract-instrument','Competitive-bid collection contract for NH-24 Sonauli–Gorakhpur section at Chapwa, Maharajganj, Uttar Pradesh; ₹6,82,10,000 annual remittance obligation.',CH,T,['UP'])
ent('ihmcl','Indian Highways Management Company Limited','company','Named nodal toll-operations agency whose communication prompted the Chapwa inspection; no allegation of wrongdoing against it.',CH,T,['UP'])
ent('delhi-hc','High Court of Delhi','court','Decided the Chapwa writ on 11 December 2025, distinguishing debarment procedure from contractual remedies.',CH,T)

refund=amt(3720.67,'crore','cumulative refunds effected; 35,74,401 eligible applications','As of 2026-05-05')
auction=amt(3894,'crore','approximate value of properties auctioned, not independently reconciled cash receipts','Current memorandum in July 2026 archive; exact auction/balance cutoff not stated')
bank=amt(1200,'crore','approximate designated-bank account balance, not additional refund expenditure','Current memorandum in July 2026 archive; exact auction/balance cutoff not stated')
newcollections=amt(43647808345,'rupees','PACL-admitted collections recorded by SEBI; not adjudicated net loss','2013-02-26 through 2014-06-15')
historic=amt(49100,'crore','approximate incomplete historical amount mobilised; not current debt/loss/refund denominator','Through March 2012 plus 2013-02-26–2014-06-15; intervening period missing')
commission=amt(7893.80,'crore','PACL-reported commissions paid, recorded by SEBI; not amount proved stolen','Historical aggregate through 2012-03-31, includes years before atlas window')
annual=amt(68210000,'rupees','annual remittance commitment from collection contractor to NHAI; not authority payment','Contract period 2024-07-29–2025-07-29')
penalty=amt(1000000,'rupees','penalty imposed; actual recovery unverified; petitioner said not implemented','NHAI letter 2025-02-12; submissions recorded 2025-12-11')
cash=amt(50,'rupees','single inspection cash collection alleged to be unrecorded; factual conclusion reserved','Inspection 2025-02-08')

rel('pacl-collections','pacl-investors','pacl-ltd','Land-linked scheme collections recorded by SEBI','SEBI recorded PACL’s admission of ₹43,647,808,345 collected from 39,97,357 customers between 26 February 2013 and 15 June 2014. The regulatory finding concerns unregistered CIS operation, not proof that every rupee was stolen.',PO,P,'2013-02-26',['pacl-land-cis-refunds','pacl-money-stages'],['pacl-response-and-genuine-deeds'],[newcollections],end='2014-06-15',kind='scheme-collections',asof='2014-08-22')
rel('pacl-agent-commissions','pacl-ltd','pacl-agents','Historical commissions paid, as admitted by PACL','PACL stated commissions paid through 31 March 2012 totalled ₹7,893.80 crore. SEBI questioned the advance-commission model; this is distinct from ₹8,874.15 crore described as prepaid commission and from current recoveries.',PO,P,'2014-08-22',['pacl-land-cis-refunds','pacl-money-stages'],['pacl-response-and-genuine-deeds'],[commission],kind='commission-payments',limits=['Evidence date is the 2014 order. Historical payment aggregate partly predates the atlas window; individual recipients not resolved.'])
rel('pacl-seller-payments','pacl-ltd','pacl-sellers','Director describes direct land-purchase payments','SEBI pp79–80 records PACL’s explanation that money went directly to sellers, while land was held through associate companies under custodian agreements. Amount, sellers and parcel-level bank trails are not supplied for this aggregate.',PO,P,'2014-08-22',['pacl-land-cis-refunds'],['pacl-response-and-genuine-deeds'],tier='self-reported',kind='reported-payment-route',limits=['Company explanation within regulatory record; not a verified parcel-by-parcel transfer ledger.'])
rel('pacl-associate-land','pacl-ltd','pacl-associates','SEBI finding on approximately 250 associate land holders','SEBI found PACL arranged purchases through approximately 250 associates to circumvent applicable land-ceiling laws and called for reference to state authorities. PACL described associate ownership and custodian agreements as its land-purchase arrangement.',PO,P,'2014-08-22',['pacl-land-cis-refunds'],['pacl-response-and-genuine-deeds'],kind='regulatory-finding',status='SEBI regulatory finding; no separate state land-ceiling conviction established',limits=['No individual associate-company identities, holdings or state prosecution outcomes inferred.'])
rel('sebi-pacl-order','sebi','pacl-ltd','Unregistered-CIS finding and winding-up/refund directions','SEBI held the schemes met section 11AA and directed PACL/promoters/directors to stop collections, wind up the schemes and refund monies with contractual returns within three months. The direction is not proof of compliance or a payment.',PO,P,'2014-08-22',['pacl-land-cis-refunds'],['pacl-response-and-genuine-deeds','pacl-current-recovery'],kind='regulatory-finding')
rel('sc-lodha-mandate','supreme-court','lodha-committee','Court-directed disposal and investor-refund mandate','The official 2026 tender restates the Supreme Court’s 2 February 2016 direction to SEBI to constitute the Lodha Committee to dispose of properties and return sale proceeds to investors.',PR,P,'2016-02-02',['pacl-land-cis-refunds','pacl-current-recovery'],['pacl-current-recovery'],kind='recovery-mandate',limits=['2016 mandate verified through later primary tender and board record, not a newly downloaded 2016 order.'])
rel('lodha-asset-administration','lodha-committee','pacl-assets','Recovery administration over property documents and interests','The board memorandum reports approximately 43,000 property documents across 22 states and objections to restraints. Administration, restraint and documents do not establish Committee title or uncontested PACL ownership of each property.',PB+PC+PR,P,'2026-05-05',['pacl-land-cis-refunds','pacl-current-recovery'],['pacl-current-recovery'],[auction,bank],kind='asset-recovery-administration',limits=['Auction value and bank balance are contextual stock/stage measures, not payments to the asset pool or additive refunds.'])
rel('lodha-refunds','lodha-committee','pacl-investors','₹3,720.67 crore cumulative investor refunds effected','The current board memorandum reports refunds against 35,74,401 eligible applications totalling ₹3,720.67 crore as of 5 May 2026. Deficient bank-verification applications continued to require rectification under the August notice.',PB+['pacl-refund-extension'],P,'2026-05-05',['pacl-land-cis-refunds','pacl-current-recovery'],['pacl-current-recovery'],[refund],kind='refund-payments',limits=['Applications are not assumed to equal distinct investors. No percentage recovered is computed against the incompatible 2014 mobilisation estimate.'])
rel('lodha-stockholding','lodha-committee','stockholding-dms','Engaged to assist Bengaluru Rural property sale','Tender clause 1.1 names StockHolding Document Management Services Limited as the agency assisting the Committee in disposing of specified properties.',PR,P,'2026-09-30',['pacl-bengaluru-auction'],[],kind='auction-administration',states=['KA'],limits=['No provider fee, property purchase or misconduct inferred.'])
rel('c1-auction-platform','c1-india','bengaluru-auction','Named e-auction service provider','Tender clause 1.11 appoints C1 India Private Limited as e-auction service provider. The provider supplies the tender platform, not the purchase funds.',PR,P,'2026-09-30',['pacl-bengaluru-auction'],[],kind='auction-service',states=['KA'])
rel('lodha-bengaluru-tender','lodha-committee','bengaluru-auction','Issued September 2026 recovery-sale tender','The Bengaluru Rural tender opens a prospective sale process and expressly states the Committee is not owner. November auction and payment milestones remain prospective at the research cutoff.',PR,P,'2026-09-30',['pacl-land-cis-refunds','pacl-bengaluru-auction'],['pacl-current-recovery'],kind='tender-issued',states=['KA'],limits=['No awardee, receipt, completed transfer or invented map coordinates.'])
rel('nhai-chapwa-contract','nhai','chapwa-contract','Competitive-bid user-fee collection instrument','The court identifies the contract dated 25 July 2024 and collection period 29 July 2024–29 July 2025 for Chapwa Fee Plaza and adjacent toilet upkeep.',CH,T,'2024-07-25',['chapwa-toll-debarment'],[],kind='contract-award',states=['UP'])
rel('ganeshgarhia-remittance','ganeshgarhia','nhai','₹6.821 crore annual remittance commitment','As collection contractor, Ganeshgarhia owed the stated annual remittance to NHAI under the Chapwa contract. It is not a ₹6.821 crore public payment to the contractor or measured diversion.',CH,T,'2024-07-29',['chapwa-toll-debarment','chapwa-money-stages'],[],[annual],end='2025-07-29',kind='contractual-remittance-obligation',states=['UP'])
rel('ihmcl-inspection-referral','ihmcl','nhai','Communication prompted Chapwa surprise inspection','The judgment’s factual matrix records IHMCL’s communication concerning unauthorised handheld cash machines and NHAI’s subsequent 8 February 2025 inspection.',CH,T,'2025-02-08',['chapwa-toll-debarment'],['chapwa-company-response','chapwa-court-outcome'],kind='oversight-referral',states=['UP'],limits=['Judgment mentions communication dates 3 and 4 February in different passages; edge dates the undisputed inspection, not the email.'])
rel('nhai-chapwa-allegation','nhai','ganeshgarhia','Alleged unrecorded toll and false exemption entry','NHAI alleged its inspection vehicle paid ₹50 on ingress without a receipt and was entered as exempt, while the return transaction was recorded. NHAI said bypassing ETC impaired its contractual entitlement to 50% of the specified non-FASTag collections. The court reserved the underlying factual issues.',CH,T,'2025-02-08',['chapwa-toll-debarment','chapwa-money-stages'],['chapwa-company-response','chapwa-court-outcome'],[cash],tier='alleged',kind='contractual-fraud-allegation',status='Disputed NHAI allegation; debarment later set aside; facts not finally adjudicated',asof='2025-12-11',states=['UP'],alts=['Contractor described a local-resident exchange/exemption and relied on the properly recorded return trip as inconsistent with systematic evasion.'],limits=['No aggregate loss or ₹25 actual loss is calculated from the contractual percentage. The inspection amount does not prove a wider national network.'])
rel('nhai-chapwa-penalty','nhai','ganeshgarhia','₹10 lakh penalty imposed; recovery unverified','NHAI’s 12 February 2025 letter imposed ₹10 lakh for alleged contractual violations. The petitioner stated in the writ that it had not been implemented. The court did not interfere with penalty in writ jurisdiction and left prescribed contractual/civil remedies.',CH,T,'2025-02-12',['chapwa-toll-debarment','chapwa-money-stages'],['chapwa-company-response','chapwa-court-outcome'],[penalty],kind='penalty-imposition',asof='2025-12-11',states=['UP'],limits=['Direction is authority-to-contractor enforcement, not a money transfer. No bank-guarantee encashment or penalty cash receipt established.'])
rel('nhai-chapwa-debarment','nhai','ganeshgarhia','30 June 2025 termination and one-year debarment','NHAI terminated the contract and debarred the contractor for one year after rejecting its reply. On 11 December 2025 the High Court set aside the debarment portion; termination/penalty were left for contractual remedies.',CH,T,'2025-06-30',['chapwa-toll-debarment'],['chapwa-company-response','chapwa-court-outcome'],kind='debarment-order',status='Debarment set aside on 2025-12-11; not shown as a continuing ban',asof='2025-12-11',states=['UP'])
rel('dhc-chapwa-relief','delhi-hc','ganeshgarhia','Debarment set aside for failure to address defence','The High Court found the debarment unreasoned, noted no POS system/device was actually seized and held that the contractor’s reply and undisclosed complaints required meaningful consideration. It expressly refrained from underlying factual conclusions and did not interfere with termination or penalty.',CH,T,'2025-12-11',['chapwa-toll-debarment','chapwa-court-outcome'],['chapwa-court-outcome'],kind='judicial-relief',states=['UP'],limits=['Procedural relief is not a criminal acquittal, a finding that every collection was proper or an order refunding the penalty.'])

rec('pacl-land-cis-refunds','PACL: unregistered land-linked schemes, agent payments and investor recovery','SEBI found PACL’s land-linked plans to be unregistered collective investment schemes in August 2014. The source records ₹43.6478 billion of collections during 26 February 2013–15 June 2014, a separate historical commission route, and associate land-holding arrangements. Court-directed recovery subsequently produced ₹3,720.67 crore of cumulative refunds against 35,74,401 eligible applications by 5 May 2026; property objections and auction work continued in September 2026.',PO+PB+PC+PR+['pacl-refund-extension','pacl-reuters-2015'],P,'2014-08-22',['pacl-ltd','pacl-investors','pacl-agents','pacl-sellers','pacl-associates','sebi','supreme-court','lodha-committee','pacl-assets'],['pacl-collections','pacl-agent-commissions','pacl-seller-payments','pacl-associate-land','sebi-pacl-order','sc-lodha-mandate','lodha-asset-administration','lodha-refunds','lodha-bengaluru-tender'],'2013–2014 collections and 2014 regulatory finding; recovery observations through September 2026','PACL argued that it sold/developed land and relied on judicially verified deeds. SEBI rejected the CIS defence but expressly preserved genuinely certified sale deeds. SAT upheld the order in 2015. The September 2026 Supreme Court order disposes of specific property objections, not the whole case; bank-deficient refund applications had a rectification window through 6 October 2026.',kind='investigation-case',status='Regulatory finding with ongoing court-directed recovery; no criminal-conviction claim',asof='2026-09-30',end='2026-09-30',amounts=[newcollections,refund],limits=['Historical mobilisation, current liability, auction value, bank balance and refunds are different quantities; no net-loss estimate or recovery percentage derived.','This is a bounded public-source case, not a complete ledger of PACL entities, investors or criminal proceedings.'],alts=['Some certified land transactions were genuine and are expressly protected by the 2014 order.','Bank-account deficiencies and property-title objections can delay payments without themselves proving fresh diversion.'],falsifier='Reconcile scheme bank ledgers, paid commission schedules, genuine registered deeds, auction sale receipts and application-level refund acknowledgements without exposing investors’ private account data; later reasoned orders may change property eligibility or recovery status.')
rec('pacl-response-and-genuine-deeds','PACL response: land-sale defence and genuine-deed protection','PACL claimed a real-estate business, invoked Justice K. Swamidurai’s verification of 19,284 sale deeds and proposed a five-year repayment arrangement. SEBI rejected the broader CIS defence, citing the 500-customer sample with no completed sale deed, while paragraph 37 expressly protects sale deeds certified as genuine.',PO,P,'2014-08-22',['pacl-ltd','sebi','pacl-investors'],['pacl-collections','pacl-agent-commissions','pacl-seller-payments','pacl-associate-land','sebi-pacl-order'],'2014 submissions and order','The order cannot be paraphrased as finding every land sale fictitious. Historical certified deeds are counter-evidence to that overbroad claim; they did not defeat the scheme-level CIS finding.',kind='respondent-response',limits=['The 500-customer sample finding does not mean no customer ever received land. No outcome of a distinct criminal prosecution is asserted.'])
rec('pacl-money-stages','PACL amounts: in-window collections versus historical mobilisation and commissions','SEBI records exact collections of ₹43,647,808,345 during 26 February 2013–15 June 2014. Its approximately ₹49,100 crore historical mobilisation combines a through-March-2012 aggregate with that period while expressly missing April 2012–25 February 2013. PACL-reported ₹7,893.80 crore paid commissions through March 2012 differ from prepaid-commission accounting figures.',PO,P,'2014-08-22',['pacl-ltd','pacl-investors','pacl-agents'],['pacl-collections','pacl-agent-commissions'],'Amounts carry different historical periods; the evidence event is the August 2014 order','PACL explained commissions as payments to agents under its land plans. SEBI questioned the advance-commission structure. The amounts cannot be summed as separate investor losses.',kind='financial-stage-control',amounts=[newcollections,historic,commission],limits=['No audited net-loss or current unpaid principal is supplied by these aggregates. Historical commissions partly predate the atlas window.'])
rec('pacl-current-recovery','PACL recovery status: paid refunds, auction values and unresolved eligibility','The May 2026 observation reports ₹3,720.67 crore cumulative refunds, approximately ₹3,894 crore of property auction value and approximately ₹1,200 crore in the designated bank account. The August notice confirms some applications could not be processed because of bank-verification deficiencies. On 9 September the Supreme Court accepted specified objection recommendations, sought verification for others and listed the matter for 8 October 2026.',PB+PC+['pacl-refund-extension'],P,'2026-05-05',['lodha-committee','pacl-investors','pacl-assets','supreme-court','sebi'],['lodha-asset-administration','lodha-refunds','sc-lodha-mandate'],'Financial observation as of 5 May 2026; procedural updates 3 August and 9 September 2026','The board’s reference to eligible claims must be read with the subsequent deficient-application notice. Neither ₹3,894 crore auction value nor ₹1,200 crore bank balance is another refund payment. The court’s acceptance of particular property objections limits any blanket assertion that restrained assets all belong to PACL.',kind='outcome-record',asof='2026-09-09',end='2026-09-09',amounts=[refund,auction,bank],limits=['No later cumulative refund figure or independently reconciled auction-cash figure established. Scheduled 8 October hearing is not treated as completed.'])
rec('pacl-bengaluru-auction','Bengaluru Rural: named recovery-sale administrators, no completed sale yet','The 30 September 2026 tender identifies StockHolding Document Management Services Limited as auction-assistance agency and C1 India Private Limited as e-auction service provider. It expressly says the Lodha Committee is not the property owner. November 2026 bid/auction dates are prospective.',PR,P,'2026-09-30',['lodha-committee','stockholding-dms','c1-india','bengaluru-auction'],['lodha-stockholding','c1-auction-platform','lodha-bengaluru-tender'],'Tender issuance 30 September 2026; future auction schedule','These companies are named only for recovery administration. The source establishes no wrongdoing, auction purchase, fee amount or receipt by either provider.',kind='recovery-process',states=['KA'],limits=['Bengaluru Rural location is explicitly sourced; no parcel centroid or map coordinate invented.'])
rec('chapwa-toll-debarment','Chapwa toll collection: disputed ₹50 transaction and debarment set aside','NHAI alleged an unrecorded ₹50 cash collection and false exemption entry during a Chapwa inspection, imposed a ₹10 lakh penalty and later terminated/debarred Ganeshgarhia. The ₹6.821 crore annual remittance was the contractor’s obligation to NHAI. On 11 December 2025 the Delhi High Court set aside only the debarment for failure to consider the defence and give reasons; it reserved factual conclusions and left contractual remedies for termination and penalty.',CH,T,'2024-07-25',['nhai','ganeshgarhia','chapwa-contract','ihmcl','delhi-hc'],['nhai-chapwa-contract','ganeshgarhia-remittance','ihmcl-inspection-referral','nhai-chapwa-allegation','nhai-chapwa-penalty','nhai-chapwa-debarment','dhc-chapwa-relief'],'Contract July 2024; inspection February 2025; enforcement June 2025; judgment December 2025','Ganeshgarhia denied unauthorised software use and disputed the fraud inference, pointing to local-resident treatment and the correctly recorded return journey. NHAI said the inspection vehicle was not local and a valid exemption pass was necessary. Court relief addresses the defective decision process; no final factual finding or later penalty recovery is established.',kind='investigation-case',tier='alleged',status='Disputed contractual allegation; one-year debarment set aside 11 December 2025',asof='2025-12-11',end='2025-12-11',amounts=[annual,cash,penalty],states=['UP'],limits=['Later status search through 7 October 2026 did not establish an appeal or separate contractual outcome. This is last verified judicial status, not a guarantee that nothing else occurred.','This is a specific Chapwa case; do not merge it into March 2025 nationwide debarments or September 2026 ED searches without source evidence.'],alts=['The contractor described a local-resident exchange/exemption rather than systematic diversion.','The authority relied on different ingress and egress accounting and its interpretation of the contractual requirements.'],falsifier='Compare timestamped official ETC records, camera evidence, exemption eligibility, receipts and contractor remittance ledgers; require a reasoned order addressing the contractor’s actual reply before upgrading disputed facts.')
rec('chapwa-company-response','Ganeshgarhia response: disputed software allegation and unaddressed defence','The contractor denied unauthorised software use, said no device had been seized and complained that particulars and supporting materials were not supplied. It relied on its local-resident/exemption explanation and the ₹70 return trip recorded by NHAI’s system, and argued the ₹10 lakh penalty had not been implemented.',CH,T,'2025-05-15',['ganeshgarhia','nhai','delhi-hc'],['nhai-chapwa-allegation','nhai-chapwa-penalty','nhai-chapwa-debarment'],'15 May 2025 reply and submissions recorded in 11 December 2025 judgment','NHAI disputed the local exemption, characterised the vehicle as its deployed inspection vehicle, and maintained that accounting irregularity justified action. The court required these points to be addressed, without resolving the underlying factual dispute.',kind='respondent-response',asof='2025-12-11',end='2025-12-11',states=['UP'],limits=['A defence recorded by a court is not necessarily a finding accepting its truth.'])
rec('chapwa-court-outcome','Delhi High Court outcome: debarment set aside, contractual claims left open','Paragraphs 30–40 hold the debarment order unreasoned and procedurally deficient; paragraph 36 notes no POS machine/system/device was seized. Paragraph 34 expressly refrains from factual conclusions. Paragraph 41 declines interference with contract termination and penalty because contractual/civil remedies must be used.',CH,T,'2025-12-11',['delhi-hc','ganeshgarhia','nhai'],['dhc-chapwa-relief','nhai-chapwa-debarment','nhai-chapwa-penalty'],'Judgment pronounced 11 December 2025','The result is neither a continuing one-year ban nor a merits finding that no irregularity occurred. Non-interference with penalty is not proof of its recovery or a judgment affirming all NHAI factual allegations.',kind='outcome-record',states=['UP'],limits=['The judgment’s concluding paragraph contains a contract-year discrepancy; original 25 July 2024 contract date is identified from paragraphs 1–2 and reproduced work order.'])
rec('chapwa-money-stages','Chapwa amounts: remittance obligation, disputed collection and assessed penalty','₹6,82,10,000 is the annual contractual remittance from Ganeshgarhia to NHAI, ₹50 is the disputed single inspection collection and ₹10,00,000 is an imposed penalty with actual recovery unverified. They are not additive diversion amounts.',CH,T,'2025-12-11',['ganeshgarhia','nhai','chapwa-contract'],['ganeshgarhia-remittance','nhai-chapwa-allegation','nhai-chapwa-penalty'],'Separate contract, inspection and penalty stages','The contractor said the penalty was not implemented; the High Court left penalty/termination to contractual remedies. No bank evidence establishes paid annual remittances, penalty encashment or total loss.',kind='financial-stage-control',amounts=[annual,cash,penalty],states=['UP'],limits=['Do not portray a ₹6.821 crore NHAI payment to the contractor or calculate a ₹25 loss by applying the 50% clause to an unresolved fact pattern.'])

# Final reviewer corrections: distinguish cohort identity, payment dates, and observation cutoffs.
for row in D['entities']:
 if row['id'] in {'pacl-investors','pacl-agents','pacl-sellers','pacl-associates','pacl-assets'}:
  row['resolved']=True
  if row['type']=='source-defined-cohort': row['type']='cohort'
  row['identityBasis']='Resolved only as the exact source-bounded PACL '+{'pacl-investors':'scheme-investor cohort','pacl-agents':'agents/field-associates cohort','pacl-sellers':'land-seller cohort described in the director statement','pacl-associates':'approximately 250 land-holding associate-company cohort','pacl-assets':'property-document/recovery-interest pool'}[row['id']]+'. Individual members, parcel title and legal-company identities are not resolved or globally merged.'
  row['limitations'].append('Aggregate/cohort identity only; resolved does not assert resolution of individual people, companies or parcels. No canonical bridge.')
for row in D['relationships']:
 if row['id']=='pacl-agent-commissions':
  row['fromDate']=None;row['toDate']='2012-03-31'
  row['dateBasis']='Unknown start of historical commission payments; reported aggregate ends 31 March 2012. The 22 August 2014 order is evidence/status date, not payment date.'
 if row['id']=='pacl-seller-payments':
  row['fromDate']=None;row['toDate']=None
  row['dateBasis']='Transaction dates unknown. Director statement recorded in SEBI order of 22 August 2014 supplies a described route, not a dated bank transfer.'
 if row['id']=='lodha-asset-administration':
  row['fromDate']=None;row['toDate']=None;row['statusAsOf']=None;row['amounts']=[]
  row['dateBasis']='Current memorandum in July 2026 archive gives no explicit cutoff for property-auction value or bank balance. Do not reuse 5 May refund observation as their date.'
for row in D['records']:
 if row['id']=='pacl-land-cis-refunds':row['fromDate']='2013-02-26'
 if row['id']=='pacl-current-recovery':
  row['summary']=row['summary'].replace('The May 2026 observation reports ₹3,720.67 crore cumulative refunds, approximately ₹3,894 crore of property auction value and approximately ₹1,200 crore in the designated bank account.', 'The memorandum expressly dates ₹3,720.67 crore cumulative refunds to 5 May 2026. Separately, its current text reports approximately ₹3,894 crore of property auction value and approximately ₹1,200 crore in the designated bank account without an exact observation date for those two measures.')
  row['period']='Refund observation as of 5 May 2026; auction-value/bank-balance cutoff unspecified in current July-archive memorandum; procedural updates 3 August and 9 September 2026'
for row in D['sources']:
 if row['id']=='chapwa-dhc-mirror':row['tier']='reported'

OUT.write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({k:len(v) for k,v in D.items()}))
