#!/usr/bin/env node
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import {chromium} from 'playwright';
import {loadInvestigation} from '../investigation/load.mjs';
import {loadAllegations} from './load.mjs';
const {INVESTIGATION_REGISTRY:registry}=await loadInvestigation(),api=await loadAllegations();
const dist=resolve(process.env.INVESTIGATION_DIST??'dist'),out=resolve(process.env.ALLEGATIONS_ARTIFACTS??'/tmp/allegations-browser');mkdirSync(out,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.woff2':'font/woff2'};
let server,base=process.env.INVESTIGATION_BASE_URL;
if(!base){server=createServer((req,res)=>{const file=resolve(dist,`.${new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname}`);if(!file.startsWith(`${dist}/`))return res.writeHead(403).end();try{res.writeHead(200,{'content-type':mime[extname(file)]??'application/octet-stream'}).end(readFileSync(file));}catch{res.writeHead(404).end();}});await new Promise(done=>server.listen(0,'127.0.0.1',done));base=`http://127.0.0.1:${server.address().port}`;}
base=base.replace(/\/$/u,'');
const binary=process.env.PLAYWRIGHT_CHROMIUM_PATH??'/usr/bin/chromium',browser=await chromium.launch(existsSync(binary)?{executablePath:binary}:{});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce',acceptDownloads:true}),errors=[],checks=[];
page.on('pageerror',error=>errors.push(error.message));page.setDefaultTimeout(30000);
const check=(value,label)=>{assert.ok(value,label);checks.push(label);};
const open=async(query='')=>{await page.goto(`${base}/#/allegations${query?'?'+query:''}`,{waitUntil:'domcontentloaded'});await page.locator('[data-allegations-page]').waitFor();await page.locator('.iw-map-state').first().waitFor();};
const params=()=>new URLSearchParams(new URL(page.url()).hash.split('?')[1]??'');
const popup=page.locator('.atlas-evidence-popover'),hubPanel=page.locator('.map-hub-panel');
const overflow=async(label)=>check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${label}: no horizontal page overflow`);
try{
 const fresh=api.getAllegationsView(registry);check(fresh.counts.cases>=5,'At least five newly reviewed source-backed case files integrated');check(fresh.missingIds.length===0,'New review evidence closure has no missing identifiers');
 await open();check(await page.getByRole('heading',{level:1}).textContent()==='Allegations atlas','Dedicated page title');check(await page.getByRole('combobox',{name:'Review scope'}).inputValue()==='new','Newly reviewed scope is the default');check(Number((await page.locator('.al-scope-line strong').textContent()).replaceAll(',',''))===fresh.entries.length,'Index count matches typed new records, not all closure records');check(await page.getByRole('button',{name:'3D atlas',exact:true}).count()===0,'No 3D control on allegations map');await overflow('Desktop');
 const record= fresh.entries.find(row=>row.category==='case'&&row.entityIds.length),card=page.locator(`[data-allegation-entry="${record.id}"]`);
 // Use the exact URL if the case falls outside the first page; it is still a stable public selection.
 if(await card.count())await card.click();else await open(`al_selection=${encodeURIComponent(`record:${record.id}`)}`);
 await popup.waitFor();check(await popup.getAttribute('data-selection-id')===record.id,'Case index opens exact evidence');check((await popup.textContent()).includes(record.record.response),'Case response is visible without a second lookup');check(await page.getByRole('dialog').count()===1,'Only one evidence reader is open');
 const download=page.waitForEvent('download');await popup.getByRole('button',{name:/Export evidence \+ linked responses/}).click();const packet=JSON.parse(readFileSync(await(await download).path(),'utf8'));check(packet.missingIds.length===0,'Popup export is source-closed');const responseIds=new Set(packet.records.map(row=>row.id));check(packet.relationships.every(edge=>edge.responseIds.every(id=>responseIds.has(id))),'Every exported edge preserves linked responses');
 await popup.getByRole('tab',{name:/Connections/}).click();check(await popup.getByRole('tabpanel').getByRole('searchbox').isVisible(),'Full exact connections are searchable');await popup.getByRole('searchbox').fill('zz-no-retained-identity-zz');check((await popup.textContent()).includes('No exact connection matches'),'Connection search has an honest empty state');await popup.getByRole('tab',{name:/Overview/}).click();
 const neighbor=popup.locator('[data-neighbor-id]').first();check(await neighbor.count()===1,'Connected identity is directly clickable');const neighborId=await neighbor.getAttribute('data-neighbor-id');await neighbor.click();await page.waitForFunction(id=>document.querySelector('.atlas-evidence-popover')?.getAttribute('data-selection-id')===id,neighborId);check(params().get('al_selection')===`entity:${neighborId}`,'Neighbor navigation updates shared selection URL');await popup.getByRole('button',{name:'Back to previous evidence'}).click();check(await popup.getAttribute('data-selection-id')===record.id,'Reader Back restores exact previous evidence');await popup.press('Escape');check(await popup.count()===0&&!params().has('al_selection'),'Escape closes popup and clears linked selection');
 await open();const hub=page.locator('[data-flat-map-hub]').first();check(await hub.count()===1,'New review populates geographic evidence hubs');const hubId=await hub.getAttribute('data-flat-map-hub');await hub.click();await hubPanel.waitFor();check(!params().has('al_state'),'Hub inspection does not silently filter global state');check(params().get('al_selection')===`state:${hubId}`,'Hub identity is shareable');check((await hubPanel.textContent()).includes('Schematic'),'Hub reader discloses schematic placement');await page.keyboard.press('Escape');await hubPanel.waitFor({state:'hidden'});check(await hubPanel.count()===0,'Hub Escape closes reader');
 await open('al_cohort=all');await page.locator('.map-evidence-index>summary').click();await page.locator('.map-unplaced-records>summary').click();const unplaced=page.locator('.map-unplaced-records');await unplaced.getByRole('searchbox',{name:'Search unplaced records'}).fill('no-unplaced-match-888');await unplaced.getByText('No unplaced records match this search.',{exact:true}).waitFor();check(await unplaced.locator('li').count()===0,'Unplaced evidence has a direct searchable list without invented map pins');await unplaced.getByRole('searchbox').fill('');await unplaced.locator('li button').first().click();await popup.waitFor();check(await popup.getAttribute('data-selection-id')!==null,'Unplaced record opens its exact evidence reader');await popup.press('Escape');
 await open();await page.getByRole('combobox',{name:'Review scope'}).selectOption('retained');check(params().get('al_cohort')==='retained','Retained archive is explicit');await page.getByRole('searchbox',{name:'Search allegations and records'}).fill('Waaree');await page.locator('.al-toolbar form').getByRole('button',{name:'Search',exact:true}).click();const correction=page.locator('[data-allegation-entry]').filter({hasText:/withdrawn/i});await correction.first().waitFor();check(await correction.count()>0,'Withdrawn legacy claim remains discoverable as correction');check((await page.locator('.al-record-index').textContent()).includes('withdrawn'),'Correction is not promoted as active allegation');
 await page.getByRole('searchbox',{name:'Search allegations and records'}).fill('no-match-unknown-corpus-999');await page.locator('.al-toolbar form').getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('heading',{name:'No matching records',exact:true}).waitFor();check(await page.getByRole('heading',{name:'No matching records',exact:true}).isVisible(),'Empty filter keeps an explanatory state');check(await page.locator('[data-flat-map-hub]').count()===0,'Empty query creates no invented map hubs');
 await open(`al_selection=${encodeURIComponent(`record:${record.id}`)}`);await popup.waitFor();await popup.getByRole('button',{name:'Close evidence details'}).click();await page.locator('.al-view-switch').getByRole('button',{name:'Network',exact:true}).click();await page.locator('.atlas-network').waitFor();check(params().get('al_view')==='network','Map and network share route state');check(await page.locator('.atlas-network .iw-graph-node').count()<=80,'Network preview is bounded');await page.locator('.al-view-switch').getByRole('button',{name:'Map',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.iw-map-state').length===36);check(await page.locator('.iw-map-state').count()===36,'Returning to map restores all current boundary selectors');
 for(const width of [768,390,320]){await page.setViewportSize({width,height:900});await open(`al_selection=${encodeURIComponent(`record:${record.id}`)}`);await popup.waitFor();await overflow(`${width}px`);const box=await popup.boundingBox();check(box.x>=0&&box.x+box.width<=width+1,`${width}px evidence sheet stays inside viewport`);check(box.y>=0&&box.y+box.height<=901,`${width}px evidence sheet stays vertically reachable`);await page.screenshot({path:resolve(out,`allegations-${width}.png`)});await popup.press('Escape');}
 await page.setViewportSize({width:1440,height:1000});await open();await page.screenshot({path:resolve(out,'allegations-desktop.png')});check(errors.length===0,`No runtime exceptions (${errors.length})`);
 writeFileSync(resolve(out,'acceptance.json'),JSON.stringify({base,checks,errors},null,2)+'\n');console.log(`Allegations browser: ${checks.length} checks passed; ${out}`);
}finally{await browser.close();if(server)await new Promise(done=>server.close(done));}
