import {test} from 'node:test';
import assert from 'node:assert/strict';
import {loadAllegations} from './load.mjs';
import {loadInvestigation} from '../investigation/load.mjs';
const api=await loadAllegations(),{INVESTIGATION_REGISTRY:registry}=await loadInvestigation();
const source={id:'s',title:'Original source',url:'https://example.gov.in/source',tier:'documented',limitations:[]};
const geo=(stateCodes=[],basis='unknown',scope=stateCodes.length?'state':'unknown')=>({stateCodes,basis,scope,sourceIds:['s'],localityIds:[],note:'Exact stated scope'});
const dims={domains:['finance'],layers:['funding'],sourceIds:['s'],limitations:[],route:'/allegations',geography:[geo()]};
const entity=(id,patch={})=>({...dims,id,namespace:'test',label:id,type:'company',resolved:true,identityBasis:'Source legal identity',...patch});
const edge=(id,from,to,patch={})=>({...dims,id,namespace:'allegations-policy',from,to,label:id,summary:'Attributed assertion',kind:'loan',tier:'alleged',status:'provisional-attachment',statusAsOf:'2026-09-01',fromDate:'2024-01-01',toDate:null,dateBasis:'Dated event',amounts:[],recordIds:[],responseIds:[],...patch});
const record=(id,patch={})=>({...dims,id,namespace:'allegations-policy',title:id,summary:'Attributed source',kind:'investigation-case',tier:'reported',status:'proceedings-pending',statusAsOf:'2026-09-01',fromDate:'2024-01-01',toDate:null,entityIds:[],relationshipIds:[],response:'Disputed; pending',amounts:[],alternativeExplanations:[],falsifier:'Exact contrary record',...patch});
const fixture=(entities=[],relationships=[],records=[])=>({entities,relationships,records,sources:[source],states:[{code:'TN',name:'Tamil Nadu'},{code:'MH',name:'Maharashtra'}],localities:[],coverage:[],held:[],updatedAt:'2026-10-07'});

test('schematic hubs never assign entity coordinates and preserve unknown incident geography as unplaced',()=>{const a=entity('a',{type:'person',geography:[geo(['TN'],'constituency')]}),b=entity('b',{geography:[geo(['MH'],'headquarters')]}),r=fixture([a,b],[edge('claim','a','b')],[record('case',{entityIds:['a','b'],relationshipIds:['claim']})]),scene=api.buildMapEvidenceScene(r,{}, {selectedEntityId:'a'});assert.equal(scene.stateHubs.length,2);assert.ok(scene.stateHubs.every(hub=>hub.placement==='schematic-state-association'&&!('lon' in hub)&&!('lat' in hub)));assert.deepEqual(scene.populations.unplaced.relationshipIds,['claim']);assert.deepEqual(scene.populations.unplaced.recordIds,['case']);assert.equal(scene.stateHubs[0].coverageRecordIds.length,0);assert.deepEqual(scene.stateHubs[0].associationRecordIds,['case']);assert.equal(scene.trails[0].fromPlacementId,'state:TN');assert.equal(scene.trails[0].toPlacementId,'state:MH');assert.equal(scene.sites.length,0);});

test('multiple geographic associations remain ambiguous instead of choosing an invented trail endpoint',()=>{const a=entity('a',{geography:[geo(['TN','MH'],'state-association','multi-state')]}),b=entity('b'),scene=api.buildMapEvidenceScene(fixture([a,b],[edge('claim','a','b')]),{},{selectedEntityId:'a'});assert.equal(scene.trails[0].fromPlacementId,undefined);assert.deepEqual(scene.trails[0].fromPlacementIds,['state:TN','state:MH']);assert.equal(scene.trails[0].toPlacementId,undefined);assert.deepEqual(scene.trails[0].toPlacementIds,[]);assert.equal(scene.trails.length,1);});

test('state and site selections retain exact incident trails; source holes never produce map nodes',()=>{const a=entity('a',{geography:[geo(['TN'],'headquarters')]}),b=entity('b',{geography:[geo(['MH'],'headquarters')]}),r=fixture([a,b],[edge('valid','a','b'),edge('unsourced','a','b',{sourceIds:['missing']})]),scene=api.buildMapEvidenceScene(r,{},{selectedPlacementId:'state:TN'});assert.deepEqual(scene.trails.map(row=>row.id),['valid']);assert.equal(scene.counts.relationships,1);assert.equal(scene.selectedPlacementId,'state:TN');const initial=api.buildMapEvidenceScene(registry,{domains:['transport']});assert.ok(initial.sites.length);const site=api.buildMapEvidenceScene(registry,{domains:['transport']},{selectedPlacementId:initial.sites[0].id});assert.equal(site.selectedPlacementId,initial.sites[0].id);assert.ok(site.trails.length);assert.ok(site.sites.every(row=>row.entityIds.every(id=>registry.entities.find(entity=>entity.id===id)?.type!=='person')));});

test('national, international and unplaced evidence remain explicit and empty filters do not silently restore all rows',()=>{const r=fixture([],[],[record('national',{geography:[geo([],'national-context','national')]}),record('foreign',{geography:[{...geo([],'country-context','country'),countryCodes:['PH']}]}),record('unknown')]);const scene=api.buildMapEvidenceScene(r);assert.deepEqual(scene.populations.national.recordIds,['national']);assert.deepEqual(scene.populations.international.recordIds,['foreign']);assert.deepEqual(scene.populations.unplaced.recordIds,['unknown']);assert.equal(scene.stateHubs.length,0);assert.equal(api.buildMapEvidenceScene(r,{domains:[]}).counts.records,0);assert.equal(api.buildMapEvidenceScene(r,{from:'2099-01-01',includeUndated:false}).counts.records,0);});

test('reader exposes all exact connections across pages and search finds endpoint names and source titles',()=>{const nodes=[entity('hub'),...Array.from({length:237},(_,i)=>entity(`neighbor${i}`))],edges=nodes.slice(1).map(row=>edge(`edge-${row.id}`,'hub',row.id)),r=fixture(nodes,edges),reader=api.getEvidenceReaderModel(r,{kind:'entity',id:'hub'});assert.equal(reader.relationships.length,237);assert.equal(reader.neighbors.length,237);const seen=new Set();for(let page=1;page<=20;page++)for(const row of api.searchEvidenceConnections(r,reader.relationships,'',page).entries)seen.add(row.id);assert.equal(seen.size,237);assert.equal(api.searchEvidenceConnections(r,reader.relationships,'neighbor236').entries[0].id,'edge-neighbor236');assert.equal(api.searchEvidenceConnections(r,reader.relationships,'Original source').total,237);assert.equal(api.searchEvidenceConnections(r,reader.relationships,'no-match').total,0);});

test('allegations default to new research, separate link and record counts, and preserve inherited unknown/superseded status',()=>{const r=fixture([entity('a'),entity('b')],[edge('new','a','b'),edge('old','a','b',{namespace:'legacy',status:'allegation'}),edge('superseded','a','b',{namespace:'legacy',status:'superseded'})],[record('new-case'),record('old-case',{namespace:'deep-governance'}),record('generic',{kind:'relationship-record',tier:'alleged'}),record('correction',{namespace:'legacy',kind:'withdrawn-correction',status:'withdrawn-unsupported-claim'})]);const fresh=api.getAllegationsView(r);assert.deepEqual(fresh.entries.map(row=>row.id).sort(),['new','new-case']);assert.equal(fresh.counts.cases,1);assert.equal(fresh.counts.allegedLinks,1);assert.equal(fresh.counts.active,2);const retained=api.getAllegationsView(r,{}, {cohort:'retained'});assert.equal(retained.entries.find(row=>row.id==='old').claimState,'unknown');assert.equal(retained.entries.find(row=>row.id==='superseded').claimState,'superseded');assert.equal(retained.entries.find(row=>row.id==='correction').claimState,'withdrawn');assert.equal(api.getAllegationsView(r,{domains:[]},{cohort:'all'}).counts.total,0);});

test('withdrawn Waaree assertion keeps exact correction history and source limits without a payment arrow or definitive negative claim',()=>{const suffix='7afac8eb483ff991|waaree|direct|bjp',record=registry.records.find(row=>row.id===`legacy:record:${suffix}`);assert.equal(record.kind,'withdrawn-correction');assert.equal(record.status,'withdrawn-unsupported-claim');assert.equal(record.amounts.length,0);assert.equal(record.relationshipIds.length,0);assert.ok(!registry.relationships.some(row=>row.id===`legacy:relationship:${suffix}`));assert.ok(registry.held.some(row=>row.id===`legacy:relationship:${suffix}`));assert.match(record.response,/cannot|unsupported|not|source gap/);const entry=api.getAllegationsView(registry,{}, {cohort:'retained'}).entries.find(row=>row.id===record.id);assert.equal(entry.claimState,'withdrawn');assert.ok(entry.sourceIds.length);});

test('response closure survives a display date limit and does not become an additional allegation',()=>{const response=record('response',{kind:'response',fromDate:'2026-09-01'}),claim=edge('claim','a','b',{responseIds:['response']}),r=fixture([entity('a'),entity('b')],[claim],[response]),view=api.getAllegationsView(r,{to:'2024-12-31'});assert.equal(view.counts.allegedLinks,1);assert.ok(view.records.some(row=>row.id==='response'));assert.ok(!view.entries.some(row=>row.id==='response'));assert.deepEqual(view.missingIds,[]);});

test('new outcomes remain independently findable while controls and ordinary finance cases are not relabelled as allegations',()=>{const view=api.getAllegationsView(registry);assert.equal(view.entries.filter(row=>row.category==='case'&&row.record?.namespace.startsWith('allegations-')).length,5);assert.equal(view.entries.filter(row=>row.category==='outcome'&&row.record?.namespace.startsWith('allegations-')).length,2);const outcomes=api.getAllegationsView(registry,{}, {category:'outcome'});for(const suffix of ['pacl-current-recovery','chapwa-court-outcome'])assert.ok(outcomes.entries.some(row=>row.id===`allegations-policy:record:${suffix}`));assert.ok(!view.entries.some(row=>['financial-stage-control','recovery-process','respondent-response','response'].includes(row.record?.kind)));const retained=api.getAllegationsView(registry,{}, {cohort:'retained'});for(const suffix of ['atlas-international-finance:record:ifc-mahindra-cash','deep-corporate:record:air-india-talace','atlas-defence-trade:record:c295-spain-india'])assert.ok(!retained.entries.some(row=>row.id===suffix));assert.ok(retained.entries.some(row=>row.id==='deep-services:record:nsap-davp-earmarking'));});

test('source-less assertions cannot enter the dedicated allegation population',()=>{const r=fixture([entity('a'),entity('b')],[edge('missing','a','b',{sourceIds:['unavailable']}),edge('unresolved','a','absent')],[record('unsourced',{sourceIds:[]})]);assert.equal(api.getAllegationsView(r).counts.total,0);});

test('reviewed reported audit observations stay discoverable without promoting their evidence tier',()=>{const r=fixture([],[],[record('reviewed-audit',{namespace:'metro-mumbai-security',kind:'audit-finding',tier:'reported'})]);const view=api.getAllegationsView(r);assert.equal(view.counts.findings,1);assert.equal(view.entries[0].tier,'reported');assert.equal(view.entries[0].record.kind,'audit-finding');});

test('BSF judicial outcome preserves count-specific acquittal and special-leave limits',()=>{const view=api.getAllegationsView(registry);const row=view.entries.find(entry=>entry.id==='metro-defence:record:bsf-sharma-result');assert.equal(row.claimState,'outcome-record');assert.match(row.statusBasis,/acquittal on charge 1/);assert.match(row.statusBasis,/not a new trial/);});
