"""Rebuild the reviewed Delhi police slice; no automatic inference of misconduct."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'delhi-security.json'
TODAY = '2026-10-07'
S = {'sources': [], 'entities': [], 'relationships': [], 'records': [], 'localities': [{'id': 'delhi', 'name': 'Delhi', 'stateCode': 'DL', 'kind': 'city', 'aliases': ['New Delhi', 'NCT of Delhi']}]}
DOM = ['security', 'public-funds', 'justice']

def source(id, title, url, publisher, date, locator, summary, limitations=None, tier='documented'):
    S['sources'].append(dict(id=id, title=title, url=url, publisher=publisher, publishedAt=date, retrievedAt=TODAY, locator=locator, summary=summary, tier=tier, limitations=limitations or []))

def geo(ids, national=False):
    return [dict(scope='national' if national else 'city', stateCodes=[] if national else ['DL'], localityIds=[] if national else ['delhi'], basis='national-context' if national else 'programme-coverage', note='National institution or funding framework; no national expenditure is allocated to Delhi merely because the institution has a Delhi office.' if national else 'Delhi Police programme or public procurement in the NCT; city association, not a building, person, operational site or exact asset coordinate.', sourceIds=ids)]

def dims(ids, layers=None, national=False, limitations=None):
    return dict(domains=DOM.copy(), layers=layers or ['procurement', 'funding', 'review'], geography=geo(ids, national), route='/allegations', sourceIds=ids, limitations=limitations or [])

def entity(id, label, typ, summary, ids, national=False, resolved=True, identity=None):
    S['entities'].append(dict(id=id, label=label, type=typ, resolved=resolved, identityBasis=identity or 'Exact public institution or programme name in the cited primary document; no ownership, political, family or beneficial-owner inference.', summary=summary, **dims(ids, ['organisations'], national)))

def amount(value, unit, stage, period):
    return dict(value=value, currency='INR', unit=unit, stage=stage, period=period)

def record(id, title, summary, ids, entities, relationships, response, kind='investigation-case', tier='documented', date='2020-09-23', period='2013–2019 audit period; dated responses through July 2020', amounts=None, alternatives=None, limitations=None):
    S['records'].append(dict(id=id, title=title, summary=summary, kind=kind, tier=tier, status='historical-audit-finding-with-dated-response' if kind in ['investigation-case', 'audit-finding'] else 'dated-public-record-not-allegation', statusAsOf=date, fromDate=None, toDate=None, dateBasis='Date is the latest retained specific source or response. Conduct and fiscal periods are separate; publication does not establish continuing misconduct.', entityIds=entities, relationshipIds=relationships, period=period, response=response, alternativeExplanations=alternatives or ['An audit or procurement concern establishes the stated control issue, not bribery, diversion, a criminal conviction or a quantified financial loss.'], falsifier='Revise on authenticated procurement files, reconciled ledgers, subsequent audit acceptance, contract completion records or a contrary court determination. A missing response is not an admission.', amounts=amounts or [], **dims(ids, limitations=limitations)))

def edge(id, frm, to, label, summary, ids, records, responseids=None, kind='procurement', date='2020-09-23', amounts=None, tier='documented', national=False, alternatives=None):
    S['relationships'].append(dict(id=id, **{'from': frm, 'to': to}, kind=kind, label=label, summary=summary, tier=tier, status='dated-source-record-not-proof-of-corruption', statusAsOf=date, fromDate=None, toDate=None, dateBasis='Source/status date only; historic tender and financial periods stated explicitly.', alternativeExplanations=alternatives or ['Institutional role or commercial participation alone does not establish wrongdoing. Read the linked audit scope, departmental response and financial stage.'], falsifier='Corrected original documents or proof of a different contracting legal entity would require revision; no hidden ownership or payment route is inferred.', responseIds=responseids or [], recordIds=records, amounts=amounts or [], **dims(ids, national=national)))

C6='https://cag.gov.in/uploads/download_audit_report/2020/6.%20Operations%20and%20Communications-05f911198e1c433.79585032.pdf'
C9='https://cag.gov.in/uploads/download_audit_report/2020/9.%20Digital%20Initiatives%20of%20Delhi%20Police-05f911198e45a25.81448827.pdf'
P140='https://sansad.in/getFile/lsscommittee/Public%20Accounts/17_Public_Accounts_140.pdf?source=loksabhadocs'
P32='https://sansad.in/getFile/lsscommittee/Public%20Accounts/18_Public_Accounts_32.pdf?source=loksabhadocs'
indexed=['Original CAG URL returned HTTP 503 during direct retrieval. Source-host indexed chapter text is retained with hash and section locators; it is not falsely labelled a downloaded original PDF. Audit opinions are attributed, not criminal findings.']
source('cag-comms-2020', 'CAG Report 15/2020, chapter 6: procurement and CCTV contract management', C6, 'Comptroller and Auditor General of India', '2020-09-23', 'Chapter 6 §§6.2, 6.3 and 6.3.1; printed pp 49–56', 'Records single-vendor specification concerns, retender history, ECIL CCTV expenditure and missing connectivity provision; includes June 2020 police responses.', indexed)
source('cag-digital-2020', 'CAG Report 15/2020, chapter 9: digital procurement and citizen applications', C9, 'Comptroller and Auditor General of India', '2020-09-23', 'Chapter 9 §§9.2.1–9.2.3, 9.3.1–9.3.2; printed pp 63–79', 'Documents Himmat nomination, MV Theft split works, lost grant opportunity, CCTNS governance and Safe City design questions, with departmental responses.', indexed)
source('pac140-2024', 'PAC 140th report: Delhi Police audit and updated responses', P140, 'Lok Sabha Secretariat, Public Accounts Committee', '2024-07-24', 'Submitted to Speaker 29 April 2024; tabled 24 July 2024. Printed pp 12–20: radio, Safe City and CCTV', 'Parliamentary follow-up records technology-neutral retender, Safe City delay and substantial CCTV functionality improvement.', ['Original PDF retrieved. Departmental progress statements are attributed and not an independent outcome evaluation.'])
source('pac32-2025', 'PAC 32nd action-taken report on Delhi Police', P32, 'Lok Sabha Secretariat, Public Accounts Committee', '2025-08-05', 'Introduction; chapter I p 1; printed pp 12, 20–21 and 36; Ministry final replies dated 30 January 2025', 'All twelve recommendations are categorized accepted by Government. Final replies update Safe City projected completion, CCTV maintenance committees and a ₹185 crore radio bid against ₹120 crore estimate.', ['Accepted recommendations do not mean every project was complete or every historic procurement issue resolved. The radio figure is a quoted bid, not a contract award or payment.'])
source('police-budget-2026', 'Union Budget 2026–27: Demand 51, Police', 'https://www.indiabudget.gov.in/doc/eb/sbe51.pdf', 'Ministry of Finance, Government of India', '2026-02-01', 'Printed pp 176–177, item 5 Delhi Police and item 14.02 Delhi Police infrastructure; explanatory notes', 'Separates 2024–25 actuals, 2025–26 BE/RE and 2026–27 BE for Delhi Police and the separate infrastructure scheme.', ['Already present in the retained force/union-home corpus; this city reader is explicit budget lineage, not newly alleged expenditure. Union Police demand totals and other forces are not Delhi spending.'])
source('pib-safe-city-2026', 'Delhi Police raising day: Safe City first phase inaugurated', 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2228674', 'Press Information Bureau, Ministry of Home Affairs', '2026-02-16', 'Paragraph beginning “Union Home Minister said that today the foundation stones”; separate Special Cell project paragraph', 'Government announces first phase inauguration at about ₹857 crore, 2,100 new cameras live and integration of more than 15,000 existing cameras; separately announces ₹368 crore Special Cell headquarters project.', ['Official announcement, not audited final expenditure, full-project completion or evidence of effectiveness. ₹857 crore rounded announced project cost is not silently reconciled with the older ₹858 crore sanction. No operational-site details are mapped.'])
source('dphcl-projects-2025', 'Delhi Police Housing Corporation: ongoing projects as at 30 May 2025', 'https://www.dphcl.com/uploaded_files/project-status/1748948127.pdf', 'Delhi Police Housing Corporation Limited', '2025-05-30', 'Ongoing Projects FY 2024–25, rows 1, 3 and 5, page 1', 'Official project list supplies tender amounts for public-facility lift maintenance and water-line replacement, but no named awarded vendor or payment ledger.', ['Downloaded source hash retained; original contains residential quarter identifiers and is excluded from committed artifacts. Selected non-residential/aggregate extracts only. Tender Amount column is not proof of an awarded contract or actual expenditure.'])

entity('delhi-police', 'Delhi Police', 'public-body', 'Union-funded police force serving the NCT of Delhi; buyer and implementing body in the cited audit and budget records.', ['police-budget-2026','pac140-2024'])
entity('mha', 'Ministry of Home Affairs', 'ministry', 'Union ministry administering the Police demand and overseeing Delhi Police procurement.', ['police-budget-2026','pac32-2025'], True)
entity('cag', 'Comptroller and Auditor General of India', 'public-body', 'Constitutional auditor; findings are audit conclusions, not criminal judgments.', ['cag-comms-2020','cag-digital-2020'], True)
entity('pac', 'Public Accounts Committee, Parliament', 'parliamentary-committee', 'Parliamentary committee examining the audit and Government action taken; membership creates no misconduct inference.', ['pac140-2024','pac32-2025'], True)
entity('radio-upgrade', 'Delhi Police radio upgrade procurement', 'procurement-project', 'Historic tender and retender chain; bid evaluation and price stage are separated from awards and payment.', ['cag-comms-2020','pac32-2025'])
entity('motorola-named', 'Motorola — firm named in the 2018 tender audit', 'named-vendor', 'CAG names M/s Motorola as the sole bidder in the scrapped 2018 procurement. No exact corporate subsidiary or later award is inferred.', ['cag-comms-2020'], True, False, 'Source names only M/s Motorola. Legal contracting subsidiary, CIN and ownership are unresolved; do not merge automatically with Motorola Solutions or another group company.')
entity('mobile-communication', 'Mobile Communication India — named radio bidder', 'named-vendor', 'PAC140 calls the bidder Mobile Communication India Pvt. Ltd; PAC32 abbreviates it Mobile Communication India Ltd. Same expressly described tender chronology; legal suffix unresolved.', ['pac140-2024','pac32-2025'], True, False, 'Same project, bid dates and procurement chronology establish a case-local bidder reference; Pvt Ltd/Ltd variation is preserved, not silently canonicalized.')
entity('ecil', 'Electronics Corporation of India Limited (ECIL)', 'public-sector-company', 'Cited CCTV installation and maintenance contractor. Contractor role is separate from audit-attributed failings and third-party damage explanations.', ['cag-comms-2020','pac32-2025'], True)
entity('cctv-project', 'Delhi Police legacy CCTV programme', 'public-project', 'Four historic ECIL camera phases; pilot connectivity failure and later citywide maintenance follow-up.', ['cag-comms-2020','pac140-2024'])
entity('himmat', 'Himmat / Himmat Plus applications', 'public-project', 'Women’s safety app procurement, development/AMC and publicity spending subject to CAG review.', ['cag-digital-2020'])
entity('smart-cloud', 'Smart Cloud Infotech — audit-named firm', 'named-vendor', 'Firm named by CAG for Himmat nomination procurement; corporate registration, ownership and personal links not established.', ['cag-digital-2020'], True, False, 'CAG alternates Smartcloud Infotech / Smart Cloud Infotech / Smart Cloud InfoTech; retained as one case-local named firm, without inferred corporate registration.')
entity('mv-theft', 'Delhi Police MV Theft application', 'public-project', 'Citizen e-FIR application whose split development and hosting procurement was reviewed by CAG.', ['cag-digital-2020'])
entity('pc-solutions', 'PC Solutions — audit-named supplier', 'named-vendor', 'CAG names M/s PC Solutions for thirteen MV Theft-related works. No corporate suffix, owner, politician or beneficial-owner link is inferred.', ['cag-digital-2020'], True, False, 'Exact audit supplier label only; legal registration and cross-corpus identity require independent verification.')
entity('safe-secure', 'Safe & Secure Delhi (2013 proposal)', 'public-project', 'Abandoned data-integration project under World Bank-funded e-delivery programme; distinct from later Nirbhaya Safe City.', ['cag-digital-2020'])
entity('meity', 'Ministry of Electronics and Information Technology', 'ministry', 'Ministry administering proposed e-delivery project support and review.', ['cag-digital-2020'], True)
entity('world-bank-programme', 'World Bank-funded e-delivery of public services programme', 'funding-programme', 'Programme named in CAG’s funding chain. Exact IBRD/IDA facility, disbursement instrument and Delhi drawdown are not established by this chapter.', ['cag-digital-2020'], True, True)
entity('safe-city', 'Delhi Safe City project', 'public-project', 'Women’s safety project under Nirbhaya funding, separately sanctioned in 2019 and partially inaugurated in 2026.', ['cag-digital-2020','pib-safe-city-2026'])
entity('nirbhaya', 'Nirbhaya Fund — Safe City funding context', 'public-fund', 'Named funding framework for the eight-city programme; this slice records only Delhi-specific sanction context.', ['pac140-2024'], True)
entity('cdac', 'Centre for Development of Advanced Computing (C-DAC), Pune', 'public-body', 'Scientific society under MeitY, engaged as Delhi Safe City total service provider. No unsupported subcontractors or private recipients are added.', ['pac32-2025'], True)
entity('cctns', 'Delhi CCTNS implementation', 'public-project', 'Delhi implementation of the national crime records system; performance and consultant handover reviewed.', ['cag-digital-2020'])
entity('tech-mahindra', 'Tech Mahindra — CCTNS system integrator', 'company', 'Named November 2012 Delhi CCTNS system integrator, a documented role and not an allegation of criminal conduct.', ['cag-digital-2020'], True)
entity('deloitte-named', 'Deloitte — CCTNS programme management unit', 'named-vendor', 'Named consultant for Delhi CCTNS; exact legal member firm is not specified in the audit.', ['cag-digital-2020'], True, False)
entity('dphcl', 'Delhi Police Housing Corporation Limited', 'public-sector-company', 'Publishes the ongoing civil-work and maintenance project list; vendor and disbursement chain remain unpublished in this source.', ['dphcl-projects-2025'])
entity('police-infrastructure', 'Delhi Police office and residential infrastructure budget', 'budget-head', 'Separate Demand51 item14.02; do not merge with item5 or assign it wholly to one project.', ['police-budget-2026'])
entity('special-cell-hq-project', 'Delhi Police Special Cell headquarters project', 'public-project', 'Public announcement of a planned construction project; no operational layout or precise site coordinates retained.', ['pib-safe-city-2026'])

record('radio-case', 'Delhi Police radio tenders: vendor-specific clauses → repeated single bids → price negotiation', 'CAG found the 2011–2019 upgrade proposal and tender specifications insufficiently justified, including reversals of pre-bid amendments; the 2018 tender drew only Motorola and was scrapped. PAC140 records a technology-neutral retender approved in 2022, again with one bidder. PAC32 records Mobile Communication India’s 27 August 2024 bid at ₹185 crore inclusive of taxes against a ₹120 crore estimate; negotiation was being examined. Neither a ₹65 crore loss nor an award is established.', ['cag-comms-2020','pac140-2024','pac32-2025'], ['delhi-police','mha','radio-upgrade','motorola-named','mobile-communication','cag','pac'], ['radio-motorola','radio-mci','radio-mha'], 'Delhi Police justified same-maker requirements by acceptance-testing concerns; CAG disagreed with that explanation. Later Government replies describe the technology-neutral RFP and continuing evaluation/negotiation, not a finalized payment. No vendor-specific reply was located.', date='2025-08-05', period='2011–2019 tender design; 2022–2024 retender; 30 January 2025 response tabled 5 August 2025', alternatives=['Compatibility/testing and limited qualified competition may help explain a single bid; price above estimate is not itself overpricing or bribery.'], limitations=['No later award/cancellation/payment was found in the bounded search through 7 October 2026. The ₹102 crore 2022 approximate tender approval and ₹120 crore 2024 estimate are distinct dated figures, not reconciled or added.'])
record('radio-response', 'Radio procurement: technology-neutral retender and latest quoted-price stage', 'PAC32 reproduces the Ministry’s final response: qualified bidder price opened 27 August 2024; ₹185 crore including taxes versus ₹120 crore estimated cost including taxes, with negotiation being examined.', ['pac140-2024','pac32-2025'], ['delhi-police','mha','mobile-communication'], ['radio-mci'], 'Explicitly a bid/estimate comparison; no established overpayment.', kind='departmental-response', date='2025-08-05', amounts=[amount(185,'crore','quoted bid including taxes; not award or payment','27 August 2024'),amount(120,'crore','departmental estimate including taxes; not expenditure','2024 tender price comparison')])
edge('radio-motorola','delhi-police','motorola-named','2018 sole bid; tender scrapped', 'CAG records one Motorola bid and criticism of tender specifications and retender due diligence. No bribery or award finding.', ['cag-comms-2020'], ['radio-case'], ['radio-response'], kind='tender-participation')
edge('radio-mci','delhi-police','mobile-communication','₹185 crore quoted bid, not award', 'Latest retained parliamentary response identifies the bidder and price stage. ₹120 crore is the departmental estimate, not an amount paid.', ['pac140-2024','pac32-2025'], ['radio-case','radio-response'], ['radio-response'], date='2025-08-05', amounts=[amount(185,'crore','quoted bid including taxes; not award or payment','27 August 2024')], kind='tender-participation')
edge('radio-mha','mha','radio-upgrade','Oversight and technology-neutral tender approval', 'The Ministry required technology-neutral procurement and evaluated the proposal. Oversight role is not a claim of personal or ministerial corruption.', ['pac140-2024','pac32-2025'], ['radio-case'], ['radio-response'], date='2025-08-05', kind='oversight')

record('cctv-case', 'Legacy CCTV: ₹5.61 crore pilot audit finding, followed by documented repair improvement', 'CAG found the pilot contract omitted connectivity provision, leaving the commissioned system ineffective and ultimately dismantled; it called ₹5.61 crore expenditure wasteful. The wider programme also had maintenance and reserve-camera concerns. These historic findings are paired with Government-reported improvement to 84–87% citywide functionality in 2023 and subsequent maintenance-committee action. They are not a claim of present-day blind spots or theft by ECIL.', ['cag-comms-2020','pac140-2024','pac32-2025'], ['delhi-police','ecil','cctv-project','cag','pac'], ['cctv-ecil','cctv-audit'], 'Delhi Police said approval for connectivity reimbursement was not obtained before dismantling following third-party damage, and later phases included the provision. PAC140 reports substantial improvement; PAC32 describes maintenance committees and liaison with civic agencies. No separate ECIL response to the pilot issue was located.', date='2025-08-05', period='2009 contract is background; 2012–2018 commissioning/failure; 2020 audit; 2023 improvement; 2025 action-taken report', amounts=[amount(5.61,'crore','historical expenditure characterized as wasteful by CAG; not theft or recoverable judgment','pilot, as audited in 2019–2020')], alternatives=['Contract omissions, third-party damage and slow inter-agency approvals are documented explanations; not every maintenance failure is contractor fraud.'], limitations=['Historic network coverage figures are not presented as current vulnerabilities; precise equipment locations and operational detail are excluded. Pilot amount must not be added again to the aggregate legacy programme cost.'])
record('cctv-response','CCTV follow-up: 2023 improvement and maintenance committees','PAC140 gives Government-reported functionality of 84–87% in 2023, compared with earlier audit-era figures. PAC32 reproduces the January 2025 description of maintenance committees; audit sought details of the dedicated task-force recommendation.', ['pac140-2024','pac32-2025'], ['delhi-police','ecil','pac'], ['cctv-ecil'], 'Improvement is material counterevidence to a blanket claim of continuing failure; not an independent certification of every camera.', kind='departmental-response', date='2025-08-05')
edge('cctv-ecil','delhi-police','ecil','CCTV installation/maintenance contract; pilot omission audited','ECIL is the named contractor. Contract scope, connectivity approval and third-party damage explanations must be read together; no illicit transfer is established.', ['cag-comms-2020','pac32-2025'], ['cctv-case'], ['cctv-response'], date='2025-08-05', kind='contract')
edge('cctv-audit','cag','cctv-project','₹5.61 crore pilot expenditure called wasteful','Attributed audit conclusion on contractual omission and failed service, not a criminal conviction or a distinct new payment.', ['cag-comms-2020'], ['cctv-case'], ['cctv-response'], kind='audit-finding')

record('himmat-case','Himmat: nomination procurement, console pricing and publicity outcomes','CAG records the December 2014 nomination purchase from Smart Cloud Infotech without competing proposals, weak independent assessment of console requirements and promised features not supplied. Development/AMC expenditure was ₹83.5 lakh by August 2019; separate publicity expenditure was ₹6.82 crore over FY2014–15 to FY2018–19. Audit questioned value and adoption, not an established ₹7.655 crore corruption loss.', ['cag-digital-2020'], ['delhi-police','smart-cloud','himmat','cag'], ['himmat-contract','himmat-publicity'], 'In June 2020 Delhi Police said comparative evaluations and field tests occurred, but supporting records were not furnished to audit. It explained the console allocation and said recovery for missing features would be taken up with the firm; no recovered amount or adjudication was found.', amounts=[amount(83.5,'lakh','development and AMC expenditure; not quantified loss','as of August 2019'),amount(6.82,'crore','publicity expenditure, distinct from developer payment','FY2014–15 to FY2018–19')], alternatives=['A working emergency service and advertising reach can have benefits beyond installation counts; low retention alone does not establish diversion.'], limitations=['Publicity agencies/recipients are not identified here; no ₹6.82 crore payment to Smart Cloud is inferred. Later PAC material mentions the app but does not specifically resolve the historic procurement questions.'])
record('himmat-response','Himmat: comparative evaluation, console-use and proposed recovery response','CAG records Delhi Police’s June 2020 explanation that comparative evaluation and field testing occurred, the console configuration served different staff roles, and amounts for missing functionalities would be pursued with the firm. CAG states supporting evaluation/testing documents were not furnished.', ['cag-digital-2020'], ['delhi-police','smart-cloud'], ['himmat-contract'], 'This is the recorded departmental response; there is no proven recovery or vendor admission.', kind='departmental-response')
edge('himmat-contract','delhi-police','smart-cloud','Himmat nomination purchase; ₹45 lakh initial development','CAG identifies the nominated firm and original development cost; later combined development/AMC and unrelated publicity figures are not assigned wholesale to it.', ['cag-digital-2020'], ['himmat-case'], ['himmat-response'], kind='contract', amounts=[amount(45,'lakh','initial Himmat app development expenditure','December 2014 procurement / January 2015 launch')])
edge('himmat-publicity','delhi-police','himmat','₹6.82 crore publicity; recipients unresolved','Programme-level publicity expenditure, not a transfer to a known vendor. The source does not name the advertising recipients.', ['cag-digital-2020'], ['himmat-case'], ['himmat-response'], kind='programme-expenditure', amounts=[amount(6.82,'crore','programme publicity expenditure; recipient chain unresolved','FY2014–15 to FY2018–19')])

record('mv-theft-case','MV Theft: thirteen works to one supplier, split bids and same-day completion records','CAG found thirteen MV Theft-related works totalling ₹44.50 lakh awarded to PC Solutions through separate bids; three modules were recorded awarded and completed on 31 March 2015, which audit found infeasible. Server rental initially intended for two months ran for 34 months, costing ₹14.10 lakh plus taxes without fresh tender price discovery. These are control findings; the total and its components overlap and are not added.', ['cag-digital-2020'], ['delhi-police','pc-solutions','mv-theft','cag'], ['mv-pc','mv-hosting'], 'The chapter records Delhi Police’s January 2020 promise to rectify data validation and June 2020 technical assurances. It supplies no specific rebuttal to split procurement or same-day work certification and no separate supplier response. No later procurement adjudication was located.', amounts=[amount(44.5,'lakh','cumulative thirteen awarded works; not quantified loss','2014–2017 procurement chain')], alternatives=['Incremental development and genuine delivered services may explain parts of the work; the audit specifically disputes planning, price discovery and certification evidence rather than proving all work fictitious.'], limitations=['Hosting and development are components of the cumulative contract cohort; no additive loss calculation. No current application-security vulnerabilities or personal complainant records included.'])
record('mv-response','MV Theft response boundary: technical remedies do not settle procurement issues','The retained report includes departmental technical-remediation statements but no specific explanation of the split tenders and same-day award/completion issue. A missing response is recorded as a gap, not admission.', ['cag-digital-2020'], ['delhi-police','pc-solutions'], ['mv-pc','mv-hosting'], 'Specific procurement rebuttal, vendor response, payment reconciliation and later adjudication remain missing.', kind='response-gap')
edge('mv-pc','delhi-police','pc-solutions','Thirteen MV Theft works: ₹44.50 lakh awarded','CAG identifies one supplier across thirteen separately bid works and questions fair price discovery and certification chronology.', ['cag-digital-2020'], ['mv-theft-case'], ['mv-response'], kind='contract', amounts=[amount(44.5,'lakh','cumulative awarded works, not loss','2014–2017')])
edge('mv-hosting','pc-solutions','mv-theft','Hosting provision: ₹14.10 lakh plus taxes, component only','Supplier-to-project service edge, not a money transfer direction. CAG records 34 months of server rental after a two-month initial proposal; this amount overlaps the thirteen-work cohort.', ['cag-digital-2020'], ['mv-theft-case'], ['mv-response'], kind='service-provision', amounts=[amount(14.1,'lakh','server rental expenditure plus taxes; overlapping component','November 2014–September 2017')])

record('safe-secure-case','Safe & Secure Delhi: procurement delay and lost grant opportunity','CAG reports an estimated ₹40 crore project under a World Bank-funded public-service e-delivery programme. MeitY’s July 2013 administrative approval was ₹14.75 crore; acceptance took ten months and the review group recommended closure in November 2017 after delay in selecting the integrator. CAG calls this avoidable loss of grants, not theft or a verified ₹40 crore cash outflow.', ['cag-digital-2020'], ['delhi-police','mha','meity','world-bank-programme','safe-secure'], ['safe-secure-programme','safe-secure-aa','safe-secure-implementation'], 'The retained paragraph gives no separate departmental rebuttal to this closure finding. The later Nirbhaya-funded Safe City project is a different scheme and cannot silently be treated as completion or recovery of this grant.', amounts=[amount(40,'crore','estimated grant opportunity lost per CAG; not disbursed expenditure','January 2013 proposal / November 2017 closure recommendation'),amount(14.75,'crore','administrative approval; not cash release','July 2013')], alternatives=['Failed procurement can reflect administrative capacity and unrealistic project timing without personal enrichment.'], limitations=['The phase footnote gives ₹14.745 crore and ₹25.285 crore, summing ₹40.03 crore while prose rounds to ₹40 crore; preserved as a source rounding discrepancy. No direct World Bank-to-Delhi cash transfer, IBRD/IDA identity, loan balance or contractor is inferred.'])
record('safe-secure-response','Safe & Secure Delhi: response and disbursement gaps','The source gives closure recommendation and grant opportunity but no cash-release ledger, named selected contractor or specific departmental rebuttal. These are explicit unresolved evidence gaps.', ['cag-digital-2020'], ['delhi-police','meity'], ['safe-secure-aa'], 'No response located in retained paragraph; do not interpret silence as proof of diversion.', kind='response-gap')
edge('safe-secure-programme','world-bank-programme','safe-secure','Proposed programme support; no verified cash transfer','CAG identifies the World Bank-funded e-delivery umbrella; this is a programme association, not a bank payment or proven loan to Delhi Police.', ['cag-digital-2020'], ['safe-secure-case'], ['safe-secure-response'], kind='funding-context')
edge('safe-secure-aa','meity','safe-secure','₹14.75 crore administrative approval','Approval in July 2013 was accepted in May 2014; no disbursement or recoverable loss is asserted.', ['cag-digital-2020'], ['safe-secure-case'], ['safe-secure-response'], kind='funding-approval', amounts=[amount(14.75,'crore','administrative approval; not release/payment','July 2013')])
edge('safe-secure-implementation','delhi-police','safe-secure','Integrator selection delay; closure recommended','CAG attributes the failed selection process to Delhi Police; no named beneficiary of illicit money is identified.', ['cag-digital-2020'], ['safe-secure-case'], ['safe-secure-response'], kind='implementation')

record('safe-city-case','Safe City: design and delay questions, with 2026 first-phase inauguration','The 2019 Delhi Safe City sanction was ₹858 crore under Nirbhaya funding. CAG questioned surveillance-heavy design and missing impact assessment; Delhi Police described community initiatives. PAC follow-up traces missed completion targets through a June 2025 projection. PIB then announced first-phase inauguration on 16 February 2026, about ₹857 crore project cost, 2,100 new cameras live and integration of over 15,000 existing cameras. Partial delivery is substantive counterevidence to a claim that nothing was built; full completion and independently measured effectiveness remain separate questions.', ['cag-digital-2020','pac140-2024','pac32-2025','pib-safe-city-2026'], ['delhi-police','safe-city','nirbhaya','cdac','mha','pac'], ['safe-city-sanction','safe-city-cdac','safe-city-firstphase'], 'Delhi Police cited community initiatives and C-DAC implementation. Government later reported first-phase inauguration. This record makes no finding of embezzlement, vendor fraud or a ₹858 crore loss.', date='2026-02-16', period='2017 proposal; 2019 sanction; 2023–2025 revised deadlines; first phase inaugurated 16 February 2026', alternatives=['Delayed delivery and revised technology scope can coexist with functioning assets and community measures; effectiveness needs independent outcome evidence.'], limitations=['₹858 crore older sanction and about ₹857 crore announced 2026 project cost are not reconciled final accounts and must not be added. Phase-one launch is not full-project acceptance. No operational layout or blind spots shown.'])
record('safe-city-response','Safe City: first phase inaugurated in February 2026','PIB records the Home Minister’s announcement of first-phase inauguration, 2,100 cameras live and integration of more than 15,000 existing cameras. It describes the project at about ₹857 crore, not a certified payment ledger.', ['pib-safe-city-2026'], ['delhi-police','safe-city','mha'], ['safe-city-firstphase'], 'Material subsequent delivery evidence; does not independently settle the original design critique or establish full completion.', kind='departmental-response', date='2026-02-16')
edge('safe-city-sanction','nirbhaya','safe-city','₹858 crore Delhi project sanction, not expenditure','PAC records the February 2019 approval under Nirbhaya funding. This is Delhi-specific scheme authorization, not every national Nirbhaya allocation.', ['pac140-2024'], ['safe-city-case'], ['safe-city-response'], kind='funding-approval', date='2024-07-24', amounts=[amount(858,'crore','approved project value; not actual spending or loss','February 2019')])
edge('safe-city-cdac','delhi-police','cdac','C-DAC total service provider; staged implementation','PAC identifies C-DAC as public scientific society and turnkey provider. No private subcontractor chain or illicit proceeds is supplied.', ['pac140-2024','pac32-2025'], ['safe-city-case'], ['safe-city-response'], kind='contract', date='2025-08-05')
edge('safe-city-firstphase','mha','safe-city','2026 first-phase inauguration announced','Official progress statement supplies partial delivery context; no inference of full completion or independent evaluation.', ['pib-safe-city-2026'], ['safe-city-case','safe-city-response'], ['safe-city-response'], kind='project-status', date='2026-02-16')

record('cctns-audit','CCTNS: delayed rollout and consultant-to-in-house handover','CAG records Tech Mahindra as system integrator and Deloitte as programme management unit from November 2012. It attributes delayed go-live partly to MHA’s late stable core software; the three-year management engagement continued while implementation remained incomplete. Delhi Police subsequently reported the consultant contract ended in September 2019 and an in-house team assumed monitoring. These are delivery/governance findings, not a claim that either named firm stole money.', ['cag-digital-2020'], ['delhi-police','mha','cctns','tech-mahindra','deloitte-named'], ['cctns-integrator','cctns-consultant'], 'Delhi Police’s June 2020 response says in-house monitoring began after September 2019 and 43,611 personnel had been trained. It also reported progress validating migrated records. No payment amount or vendor misconduct conclusion is supported here.', kind='audit-finding', alternatives=['Central core-software rollout delays and legitimate implementation support may explain an extended consultant engagement.'])
record('cctns-response','CCTNS: consultant engagement ended and monitoring moved in-house','The June 2020 departmental response states the SPMU contract expired in September 2019 and an in-house team monitored the system thereafter; training and data-validation progress were reported.', ['cag-digital-2020'], ['delhi-police','cctns'], ['cctns-consultant'], 'The handover is specific counterevidence to treating the historical consultant dependency as indefinitely continuing.', kind='departmental-response')
edge('cctns-integrator','delhi-police','tech-mahindra','CCTNS system integrator role','Documented November 2012 engagement; no adverse claim of vendor bribery or theft and no amount assigned.', ['cag-digital-2020'], ['cctns-audit'], ['cctns-response'], kind='contract')
edge('cctns-consultant','delhi-police','deloitte-named','CCTNS programme management; contract ended September 2019','Named role and historic extension are paired with the departmental handover response; exact Deloitte legal member firm remains unresolved.', ['cag-digital-2020'], ['cctns-audit'], ['cctns-response'], kind='contract')

record('budget-be-2026','Delhi Police: ₹12,503.65 crore FY2026–27 budget estimate','Demand51 item5 gives ₹11,881.55 crore revenue plus ₹622.10 crore capital, totalling ₹12,503.65 crore BE. It is an allocation for the force, not proved expenditure, loss or tender award. This refreshes city-reader lineage to the budget already in the retained force corpus.', ['police-budget-2026'], ['mha','delhi-police'], ['budget-mha-police'], 'Ordinary funding context; no adverse claim.', kind='budget-allocation', date='2026-02-01', period='FY2026–27', amounts=[amount(12503.65,'crore','budget estimate allocation, Demand51 item5','FY2026–27')], alternatives=['Budget authority finances routine service and schemes; allocation itself is not evidence of corruption.'])
record('budget-actual-2024','Delhi Police: ₹12,133.16 crore FY2024–25 actual expenditure','The 2026–27 demand reports ₹11,595.91 crore revenue plus ₹537.25 crore capital as actual FY2024–25 expenditure under item5. This is a force-level accounting amount, not supplier-level payment tracing.', ['police-budget-2026'], ['mha','delhi-police'], ['budget-mha-police'], 'Ordinary accounting context; financial audit and transactions must be tested separately.', kind='budget-expenditure', date='2026-02-01', period='FY2024–25 actual reported in Budget2026–27', amounts=[amount(12133.16,'crore','actual expenditure, Demand51 item5','FY2024–25')])
record('budget-infra-2026','Delhi Police infrastructure: separate ₹342.50 crore FY2026–27 provision','Demand51 item14.02 separately provides ₹342.50 crore BE for office and residential building projects. Item5 is not silently treated as containing this separate scheme line; neither line is allocated to an individual construction project.', ['police-budget-2026'], ['mha','police-infrastructure','delhi-police'], ['budget-infrastructure'], 'Budget allocation, not expenditure or corruption finding.', kind='budget-allocation', date='2026-02-01', period='FY2026–27', amounts=[amount(342.5,'crore','separate infrastructure budget estimate, item14.02','FY2026–27')])
edge('budget-mha-police','mha','delhi-police','Union Police demand: Delhi Police budget line','Ordinary funding/administrative relationship; retained budget lineage, not an allegation or inferred vendor payment.', ['police-budget-2026'], ['budget-be-2026','budget-actual-2024'], kind='budget-context', date='2026-02-01')
edge('budget-infrastructure','mha','police-infrastructure','Separate Delhi Police infrastructure allocation','Item14.02 is a separate capital scheme for office/residential buildings. No project-level payment recipient can be inferred from this line alone.', ['police-budget-2026'], ['budget-infra-2026'], kind='budget-context', date='2026-02-01')
record('dphcl-context','Police buildings and water services: three public procurement leads','DPHCL’s 30 May 2025 ongoing-project list records ₹13,16,500 for public police-station lift repair/AMC, ₹47,90,983 for aggregate raw/drinking water supply-line replacement, and ₹8,43,640 for seven passenger lifts in a police-training building. These are selected tender-value leads, not suspicious duplicate works, certified payments or identified awarded vendors.', ['dphcl-projects-2025'], ['dphcl','delhi-police'], ['dphcl-police'], 'No irregularity established. To test repeated work, obtain exact tender IDs, award documents, scope/BOQ, measurement books and prior maintenance periods; similar titles alone are insufficient.', kind='procurement-context', date='2025-05-30', period='Ongoing FY2024–25 list as at30May2025', amounts=[amount(1316500,'rupees','listed tender amount, row1; no award/payment verified','30 May 2025 snapshot'),amount(4790983,'rupees','listed tender amount, row3; no award/payment verified','30 May 2025 snapshot'),amount(843640,'rupees','listed tender amount, row5; no award/payment verified','30 May 2025 snapshot')], limitations=['No private residential quarter identifiers are retained. The sample is three rows, not all police tenders or a spending total.'])
edge('dphcl-police','dphcl','delhi-police','Publishes police-facility maintenance and water-work tender leads','Public infrastructure delivery relationship. Source list does not identify vendors, payment certifications or corrupt conduct.', ['dphcl-projects-2025'], ['dphcl-context'], kind='procurement-context', date='2025-05-30')
record('special-cell-context','Special Cell headquarters: ₹368 crore announced project cost','PIB’s February 2026 release reports foundation-stone laying and approximately ₹368 crore for the integrated headquarters project. This is an announced construction-project cost, not a contract award or actual expenditure.', ['pib-safe-city-2026'], ['delhi-police','special-cell-hq-project','mha'], ['special-cell-project'], 'Ordinary project context; no allegation. Awarded contractor, approved detailed cost and payment records remain to be obtained.', kind='procurement-context', date='2026-02-16', period='16 February 2026 announcement', amounts=[amount(368,'crore','approximately announced project cost; not verified expenditure','February 2026')])
edge('special-cell-project','delhi-police','special-cell-hq-project','Headquarters project announced; vendor unresolved','A public project association with no precise operational location, plans, private addresses or implied corruption.', ['pib-safe-city-2026'], ['special-cell-context'], kind='project-context', date='2026-02-16')
record('pac-followup','PAC action taken: government accepts twelve recommendations','PAC32 categorizes all twelve PAC140 recommendations as accepted by Government, with no recommendations listed in its rejected or interim/no-reply categories. The report nevertheless contains implementation work and negotiation in progress. Acceptance is a response classification, not a clean chit, criminal verdict or proof every project finished.', ['pac32-2025'], ['mha','delhi-police','pac'], ['pac-review'], 'Specific case records retain their own later dates and counterevidence; this general follow-up does not erase historical audit findings.', kind='departmental-response', date='2025-08-05')
edge('pac-review','pac','delhi-police','Audit follow-up and action-taken scrutiny','Parliamentary oversight role; not a funding transfer or culpability edge.', ['pac140-2024','pac32-2025'], ['pac-followup'], kind='oversight', date='2025-08-05')

source('sc-safety-2026', 'Supreme Court: institutional safety review, 2026 INSC 1063', 'https://www.sci.gov.in/sci-get-pdf/?diary_no=604872026&type=j&order_date=2026-09-28&from=latest_judgements_order', 'Supreme Court of India', '2026-09-28', 'In Re: Recent Rape Incidents in Delhi NCR, SMW(Crl)6/2026; §8 no individual culpability determination; §9(v)(c) printed p8 Safe City functioning; §§10–12 measured reporting and infrastructure audit', 'Court seeks actual functioning, coverage and accountability for safety mechanisms including Safe City, rather than scheme names alone. Individual criminal culpability is expressly outside this institutional review.', ['Original official PDF retrieved and hashed. Only institutional extracts retained; sensitive incident narratives are excluded. Interim directions are not a corruption or vendor-liability finding.'])
source('sc-hearing-report-2026', '5 October hearing: monitoring and implementation of Delhi safety measures', 'https://www.thehindu.com/news/national/set-up-24-hour-monitoring-cells-to-prevent-sexual-offences-supreme-court-tells-delhi-police/article71547571.ece', 'The Hindu, Aaratrika Bhaumik', '2026-10-05', 'Opening institutional-monitoring paragraphs and final departmental-assurance / next-listing paragraphs', 'Reports the follow-up hearing, court questions on continuous monitoring and police counsel’s assurance that vigilance measures had been taken; reports next hearing on 16 November.', ['Reported hearing, not a retrieved 5 October written order. Oral remarks are not a final finding or proof of financial misconduct. No commercial article body or sensitive incident details retained.'], tier='reported')
entity('supreme-court', 'Supreme Court of India', 'court', 'Court supervising institutional accountability in the cited public proceedings; not a funding recipient or alleged wrongdoer.', ['sc-safety-2026'], True)
record('safe-city-court-order', 'Supreme Court asks whether Delhi safety schemes work on the ground', 'The 28 September 2026 written order asks for the actual functioning and coverage of Safe City, ERSS112, Women Helpline181, Women Help Desks and One Stop Centres. It requires measurable implementation reporting and infrastructure audits. Section8 expressly says the proceedings do not determine individual criminal culpability. No missing-money or contractor-corruption conclusion follows from the direction.', ['sc-safety-2026'], ['supreme-court','delhi-police','mha','safe-city'], ['sc-safe-city','sc-delhi-police'], 'The subsequent 5 October hearing is separately attributed to news reporting; a written compliance determination has not been retrieved. Government’s February 2026 first-phase inauguration remains material delivery context.', kind='court-order', date='2026-09-28', period='Written interim institutional directions, 28 September 2026', limitations=['This proceeding concerns safety and institutional effectiveness, not adjudication of the financial audit cases. No survivor/accused identities, minor details or precise vulnerable sites are reproduced.'])
record('safe-city-hearing-update', '5 October 2026 follow-up: monitoring questions and police assurances', 'The Hindu reports that the Supreme Court questioned how CCTV installation prevents harm without continuous monitoring and sought practical implementation. Police counsel assured the court that several vigilance steps had been taken. The article reports a further hearing on 16 November 2026; that future date is not treated as an outcome.', ['sc-hearing-report-2026'], ['supreme-court','delhi-police','safe-city'], ['sc-delhi-police'], 'Departmental counsel’s assurance is retained. This is an attributed report of a hearing; the 5 October written order and resulting compliance report remain unverified.', kind='procedural-status', tier='reported', date='2026-10-05', period='Reported hearing, 5 October 2026', limitations=['No final corruption finding, personal culpability or financial loss determination.'])
edge('sc-safe-city','supreme-court','safe-city','Court requests actual functioning and coverage report','Written §9(v)(c) directs institutional reporting; it does not conclude that every installation failed or that money was stolen.', ['sc-safety-2026'], ['safe-city-case','safe-city-court-order'], ['safe-city-response','safe-city-hearing-update'], kind='audit-direction', date='2026-09-28')
edge('sc-delhi-police','supreme-court','delhi-police','Institutional oversight; individual guilt reserved','Written §8 preserves due process and excludes individual culpability determination; latest reported hearing carries the police assurance.', ['sc-safety-2026','sc-hearing-report-2026'], ['safe-city-court-order','safe-city-hearing-update'], ['safe-city-response','safe-city-hearing-update'], kind='legal-outcome', date='2026-10-05')
for x in S['records']:
    if x['id']=='safe-city-case':
        x['relationshipIds'].extend(['sc-safe-city','sc-delhi-police'])
        x['sourceIds'].extend(['sc-safety-2026','sc-hearing-report-2026'])
        x['statusAsOf']='2026-10-05'
        x['summary']+=' The September 2026 Supreme Court order requests actual functioning and coverage; the 5 October follow-up hearing is reported separately, without any finding of financial corruption.'
        x['period']+='; September 2026 written institutional review / October 2026 reported hearing'
for x in S['entities']:
    if x['id']=='delhi-police':
        x['canonicalId']='legacy:entity:force:delhi-police'
        x['identityBasis']+=' Identity-only bridge checked against retained force:delhi-police: exact Delhi Police institution, same Union Demand51 item5 source; no amounts or allegations are merged.'
    if x['id']=='mha':
        x['canonicalId']='atlas-policy:entity:home-ministry'
        x['identityBasis']+=' Identity-only bridge checked against atlas-policy home-ministry: exact Ministry of Home Affairs, Government of India institution. Different portfolios are not different ministries; no amounts or allegations are merged.'

# Exact response/announcement events and fiscal periods are distinct from source
# publication dates, the duration of historical conduct, and payment timestamps.
response_periods={
    'radio-response': '27 August 2024 price bid; 30 January 2025 Ministry final response, tabled 5 August 2025',
    'cctv-response': '2023 functionality reported in PAC140; 30 January 2025 maintenance-committee response, tabled 5 August 2025',
    'safe-city-response': 'First-phase inauguration and official announcement, 16 February 2026',
    'pac-followup': 'Action taken on PAC140 (2024); January 2025 final replies; PAC32 tabled 5 August 2025',
    'himmat-response': 'June 2020 departmental response reproduced in the report tabled 23 September 2020',
    'cctns-response': 'September 2019 consultant-contract expiry; June 2020 departmental handover response',
    'mv-response': 'January and June 2020 technical responses; specific 2014–2017 procurement rebuttal remains absent',
    'safe-secure-response': '2013 proposal and approval; November 2017 closure recommendation; response/disbursement gap in 2020 audit',
    'dphcl-context': 'Ongoing FY2024–25 project list, snapshot dated 30 May 2025',
}
fiscal_periods={
    'budget-be-2026': ('2026-04-01','2027-03-31'),
    'budget-actual-2024': ('2024-04-01','2025-03-31'),
    'budget-infra-2026': ('2026-04-01','2027-03-31'),
}
record_events={
    'radio-response': ('2025-01-30','Ministry final response date, not the 27 August 2024 bid date or a payment; report publication remains 5 August 2025.'),
    'cctv-response': ('2025-01-30','Ministry final response date; cited 2023 performance is historical and report publication remains 5 August 2025.'),
    'safe-city-response': ('2026-02-16','Official first-phase inauguration/announcement event date; not project start, completion, payment or full acceptance.'),
    'special-cell-context': ('2026-02-16','Official foundation-stone/project announcement event date; not contract award, payment or construction completion.'),
    'pac-followup': ('2025-08-05','PAC32 tabling event, not the period of underlying conduct or an assertion that every recommendation was implemented that day.'),
    'dphcl-context': ('2025-05-30','Date of the published ongoing-project snapshot; not individual tender, award, completion or payment dates.'),
    'safe-city-court-order': ('2026-09-28','Exact date of the retrieved written interim court order; not a criminal verdict or financial-loss finding.'),
    'safe-city-hearing-update': ('2026-10-05','Exact reported hearing date; written order not retrieved, no final guilt/compliance determination and no inference from the future listing.'),
}
for x in S['records']:
    if x['id'] in response_periods:
        x['period']=response_periods[x['id']]
    if x['id'] in fiscal_periods:
        x['fromDate'],x['toDate']=fiscal_periods[x['id']]
        x['dateBasis']='Fiscal appropriation/accounting period, not payment dates. statusAsOf is publication of the 2026–27 budget reporting this distinct BE or actual amount.'
    if x['id'] in record_events:
        day,basis=record_events[x['id']]
        x['fromDate']=x['toDate']=day
        x['dateBasis']=basis
edge_events={
    'radio-mci': ('2024-08-27','Exact quoted-price bid-opening event; no award or payment inferred. Latest retained publication is PAC32 in August 2025.'),
    'safe-city-firstphase': ('2026-02-16','Exact official first-phase inauguration announcement date; not full-project completion or a payment.'),
    'special-cell-project': ('2026-02-16','Exact official project/foundation-stone announcement event; not contract award or expenditure.'),
    'dphcl-police': ('2025-05-30','Published project-list snapshot date; individual tender award and payment dates are not provided.'),
    'sc-safe-city': ('2026-09-28','Exact written order event directing institutional reporting; no individual criminal or financial culpability determination.'),
    'sc-delhi-police': ('2026-09-28','Written institutional-order event date. statusAsOf separately reflects the 5 October reported hearing; no continuous misconduct interval is inferred.'),
}
for x in S['relationships']:
    if x['id'] in edge_events:
        day,basis=edge_events[x['id']]
        x['fromDate']=x['toDate']=day
        x['dateBasis']=basis
    if x['id']=='budget-infrastructure':
        x['fromDate']='2026-04-01'
        x['toDate']='2027-03-31'
        x['dateBasis']='Fiscal appropriation period FY2026–27, not payment dates; publication is 1 February 2026.'

# These are evidence objects for an exact source text, not legally resolved
# companies. Keep source attribution visible in nodes and every connected edge.
source_mentions={
    'motorola-named': 'Motorola',
    'mobile-communication': 'Mobile Communication India',
    'smart-cloud': 'Smart Cloud Infotech',
    'pc-solutions': 'PC Solutions',
    'deloitte-named': 'Deloitte',
}
mention_limit='Source-mention evidence object only: the cited document contains this vendor name, but the contracting legal entity, corporate identifier and beneficial owners are unverified. No legal-person resolution, canonical corporate merge or recipient-bank identity is asserted.'
for x in S['entities']:
    if x['id'] in source_mentions:
        x['type']='source-mention'
        x['resolved']=True
        x['label']=source_mentions[x['id']]+' — source-named vendor; legal entity unverified'
        x['identityBasis']='Resolved only as an exact vendor-name mention in the listed source document(s), not as a legal company. '+x['identityBasis']
        x['summary']='Evidence object for a cited vendor-name mention. '+x['summary']
        x['limitations'].append(mention_limit)
        assert 'canonicalId' not in x
for x in S['relationships']:
    if x['from'] in source_mentions or x['to'] in source_mentions:
        x['kind']='attributed-procurement-mention'
        x['label']='Source-attributed: '+x['label']
        x['summary']+=' This edge attributes procurement/service information to the source-named vendor mention; it does not verify a legal-company recipient or a bank payment.'
        x['limitations'].append(mention_limit)
for x in S['records']:
    if set(x['entityIds']) & set(source_mentions):
        x['limitations'].append('Named-vendor graph endpoints are source-mention evidence objects, visibly labelled legal entity unverified. Exact contracting legal party and ownership require further records; no corporate merge or bank-recipient inference is made.')

for category in ['sources','entities','relationships','records','localities']:
    ids=[x['id'] for x in S[category]]
    assert len(ids)==len(set(ids)), category
valid={k:{x['id'] for x in S[k]} for k in S}
for category in ['entities','relationships','records']:
    for x in S[category]:
        assert set(x['sourceIds']) <= valid['sources'], x['id']
        for g in x['geography']:
            assert set(g['sourceIds']) <= valid['sources'], x['id']
            assert set(g['localityIds']) <= valid['localities'], x['id']
for x in S['relationships']:
    assert {x['from'],x['to']} <= valid['entities'],x['id']
    assert set(x['recordIds']+x['responseIds']) <= valid['records'],x['id']
for x in S['records']:
    assert set(x['entityIds']) <= valid['entities'],x['id']
    assert set(x['relationshipIds']) <= valid['relationships'],x['id']
OUT.write_text(json.dumps(S,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({k:len(v) for k,v in S.items()}))
