#!/usr/bin/env node
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import {chromium} from 'playwright';
const compiled=await build({stdin:{contents:"export * from './src/data/researchRadar';",resolveDir:fileURLToPath(new URL('../..',import.meta.url)),loader:'ts'},bundle:true,platform:'node',format:'cjs',write:false,logLevel:'silent',target:'node20'});
const module={exports:{}};new Function('module','exports',compiled.outputFiles[0].text)(module,module.exports);
const {RESEARCH_RADAR_DATA:data,RADAR_CITIES:cities,filterRadarCases,exportRadarCase,caseHasRecentSource}=module.exports;
const dist=resolve(process.env.INVESTIGATION_DIST??'dist'),out=resolve(process.env.RADAR_ARTIFACTS??'/tmp/research-radar-browser');mkdirSync(out,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.woff2':'font/woff2'};
let server,base=process.env.INVESTIGATION_BASE_URL;
if(!base){server=createServer((req,res)=>{const path=new URL(req.url,'http://localhost').pathname,file=resolve(dist,`.${path==='/'?'/index.html':path}`);if(!file.startsWith(`${dist}/`))return res.writeHead(403).end();try{res.writeHead(200,{'content-type':mime[extname(file)]??'application/octet-stream'}).end(readFileSync(file));}catch{res.writeHead(404).end();}});await new Promise(done=>server.listen(0,'127.0.0.1',done));base=`http://127.0.0.1:${server.address().port}`;}
base=base.replace(/\/$/u,'');const binary=process.env.PLAYWRIGHT_CHROMIUM_PATH??'/usr/bin/chromium',browser=await chromium.launch(existsSync(binary)?{executablePath:binary}:{});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce',acceptDownloads:true}),checks=[],errors=[];page.on('pageerror',error=>errors.push(error.message));page.setDefaultTimeout(45000);
const check=(value,label)=>{assert.ok(value,label);checks.push(label);};
const open=async(query='')=>{await page.goto(`${base}/#/research-radar${query?`?${query}`:''}`,{waitUntil:'domcontentloaded'});await page.waitForFunction(query=>document.querySelector('[data-research-radar-page]')?.getAttribute('data-radar-query')===query,new URLSearchParams(query).toString());await page.evaluate(()=>new Promise(done=>requestAnimationFrame(()=>{document.querySelector('.site-main')?.scrollTo(0,0);requestAnimationFrame(done); })));};
const param=async(key,value)=>{await page.waitForFunction(({key,value})=>{const params=new URLSearchParams(location.hash.split('?')[1]??'');return params.get(key)===value&&document.querySelector('[data-research-radar-page]')?.getAttribute('data-radar-query')===params.toString();},{key,value});};
const overflow=async(label)=>check(await page.evaluate(()=>{const root=document.querySelector('[data-research-radar-page]'),main=document.querySelector('.site-main');return document.documentElement.scrollWidth<=innerWidth+1&&(!root||root.scrollWidth<=root.clientWidth+1)&&(!main||main.scrollWidth<=main.clientWidth+1);}),`${label}: no horizontal overflow including app scroll container`);
const popup=page.getByRole('dialog');
try{
 check(data.cases.length>0,'Source-backed radar cases are present');await open();
 check(await page.locator('path[data-state-code]').count()===36,'All 36 pinned current administrative boundaries lead the default flat map');
 check(await page.locator('[data-radar-city]').count()===cities.length,'Every planned city navigation anchor appears without manufactured evidence');
 check(await page.getByRole('combobox',{name:'Research city',exact:true}).locator('option').count()===cities.length+1,'Equivalent city selector includes all planned anchors');
 check((await page.locator('.rr-stat-note').textContent()).includes('Untrained / uncalibrated'),'Untrained forecasting state is visible before the investigation');
 await page.screenshot({path:resolve(out,'radar-map-1440.png')});
 for(const record of data.cases){
  await open(`rr_case=${encodeURIComponent(record.id)}`);const dossier=page.locator('[data-radar-dossier]');
  check(await dossier.getAttribute('data-radar-dossier')===record.id,`${record.id}: exact saved case opens`);
  const text=await dossier.textContent();check(text.includes(record.summary)&&text.includes(record.question),`${record.id}: complete authored question and summary survive rendering`);
  check(await dossier.locator('[data-radar-observation]').count()===record.observations.length&&record.observations.every(item=>text.includes(item.text)),`${record.id}: every source-backed observation remains visible`);
  check(await dossier.locator('[data-radar-counterevidence]').count()===record.counterevidence.length&&record.counterevidence.every(item=>text.includes(item.text)),`${record.id}: every retained response and counter-record remains visible`);
  const scenario=page.locator('[data-radar-scenario]');check((await scenario.textContent()).includes(record.scenario.target)&&(await scenario.textContent()).includes(record.scenario.evaluationAt),`${record.id}: the scenario has the exact future target and evaluation date`);
  check((await scenario.textContent()).includes('Probability: not estimated'),`${record.id}: no numeric probability or guilt score is fabricated`);
  check(record.scenario.falsifiers.every(item=>text.includes(item))&&record.scenario.alternatives.every(item=>text.includes(item)),`${record.id}: alternatives and disproof tests survive the case reader`);
  check(await page.locator('[data-radar-node]').count()===record.entities.length,`${record.id}: graph nodes equal exact authored identities`);
  check(record.nextRecords.every(item=>text.includes(item.record)&&text.includes(item.holder)&&text.includes(item.purpose)),`${record.id}: acquisition gaps retain document, holder and purpose`);
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export complete radar research packet'}).click();const packet=JSON.parse(readFileSync(await(await download).path(),'utf8'));assert.deepEqual(packet,exportRadarCase(record.id));check(true,`${record.id}: downloaded packet equals full source-closed authored export`);
  if(record.sourceIds.length){const id=record.sourceIds[0],source=data.sources.find(row=>row.id===id);await page.locator(`[data-radar-source="${id}"]`).first().click();await popup.waitFor();check(await popup.getAttribute('data-radar-reader')===id&&((await popup.textContent()).includes(source.locator)),`${record.id}: source reader retains exact identity and locator`);const popupText=await popup.textContent();check(await popup.getByRole('link',{name:'Read original source'}).getAttribute('href')===source.url&&source.limitations.every(item=>popupText.includes(item)),`${record.id}: original link is exact`);await page.getByRole('button',{name:'Close radar evidence reader'}).click();await param('rr_reader',null);}
 }
 const first=data.cases.find(row=>row.entities.length&&row.links.length)??data.cases[0];await open(`rr_case=${encodeURIComponent(first.id)}`);
 if(first.entities.length){const entity=first.entities[0];await page.locator(`[data-radar-node="${entity.id}"]`).focus();await page.keyboard.press('Enter');await popup.waitFor();check(await popup.getAttribute('data-radar-reader')===entity.id,'Keyboard activation opens the exact network node');const links=first.links.filter(link=>link.from===entity.id||link.to===entity.id);check(await popup.locator('[data-radar-link]').count()===links.length,'Node reader exposes every exact authored connection');if(links.length){await popup.locator(`[data-radar-link="${links[0].id}"]`).click();await param('rr_reader',`link:${links[0].id}`);check((await popup.textContent()).includes(links[0].kind)&&(await popup.textContent()).includes(links[0].status),'Connection reader preserves role/payment distinction and evidence status');}await page.reload();await popup.waitFor();check(await popup.count()===1,'Saved reader deep link survives reload');await page.keyboard.press('Escape');await param('rr_reader',null);check(await popup.count()===0,'Escape closes native modal and clears only evidence selection');check(await page.locator('[data-radar-case]').getAttribute('data-radar-case')===first.id,'Closing the reader preserves selected case');}
 if(data.actors.length){const actor=data.actors[0];await open(`rr_case=${encodeURIComponent(first.id)}&rr_reader=${encodeURIComponent(`actor:${actor.id}`)}`);await popup.waitFor();const text=await popup.textContent();check(await popup.locator('[data-radar-timeline]').count()===actor.timeline.length&&actor.timeline.every(entry=>text.includes(entry.outcome)), 'Actor reader retains every dated outcome and response without a character score');await page.getByRole('button',{name:'Close radar evidence reader'}).click();}
 const populated=cities.find(city=>data.cases.some(record=>record.cityIds.includes(city.id))),empty=cities.find(city=>!data.cases.some(record=>record.cityIds.includes(city.id)));
 if(populated){await open();await page.getByRole('combobox',{name:'Research city',exact:true}).selectOption(populated.id);await param('rr_city',populated.id);check(await page.locator('[data-radar-case-card]').count()===filterRadarCases({cityId:populated.id}).length,'City selector filters to authored city associations only');await page.reload();await page.locator('[data-research-radar-page]').waitFor();check(await page.getByRole('combobox',{name:'Research city',exact:true}).inputValue()===populated.id,'City filter survives reload');await page.goBack();await param('rr_city',null);await page.goForward();await param('rr_city',populated.id);check(true,'Browser Back/Forward restores the selected city');}
 if(empty){await open();await page.locator(`[data-radar-city="${empty.id}"]`).focus();await page.keyboard.press('Enter');await param('rr_city',empty.id);check(await page.locator('[data-radar-case-card]').count()===0&&(await page.locator('.rr-empty').textContent()).includes('missing research'),'An unresearched city opens a neutral acquisition gap, never a low-risk score');}
 await open();await page.getByRole('combobox',{name:'Source publication window'}).selectOption('latest-window');await param('rr_recency','latest-window');check(await page.locator('[data-radar-case-card]').count()===data.cases.filter(caseHasRecentSource).length,'Recent filter uses source publication dates, not today’s retrieval timestamp');
 await page.getByRole('searchbox',{name:'Search radar research'}).fill('zzzz-not-a-record-unique');await param('rr_q','zzzz-not-a-record-unique');check(await page.locator('[data-radar-case-card]').count()===0,'Search reports no match without inventing a related entity');await page.getByRole('button',{name:'Reset',exact:true}).click();await param('rr_q',null);check(await page.locator('[data-radar-case-card]').count()===data.cases.length,'Reset restores full research scope');
 await open('rr_case=missing-case');check((await page.getByRole('status').textContent()).includes('saved case is unavailable'),'Stale saved case is disclosed');await open(`rr_case=${encodeURIComponent(first.id)}&rr_reader=entity:missing-entity`);await popup.waitFor();check((await popup.textContent()).includes('identities have not been substituted'),'Stale reader is disclosed without false identity matching');await page.keyboard.press('Escape');
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});await open(`rr_case=${encodeURIComponent(first.id)}`);await overflow(`${width}px map`);await page.evaluate(()=>document.fonts.ready);for(const [left,right] of [['bengaluru','chennai'],['ahmedabad','gandhinagar'],['chandigarh','dehradun']]){const a=await page.locator(`[data-radar-city="${left}"] text`).boundingBox(),b=await page.locator(`[data-radar-city="${right}"] text`).boundingBox();check(a&&b&&(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y),`${width}px: ${left}/${right} city labels do not overlap`);}await page.screenshot({path:resolve(out,`radar-map-${width}.png`)});await page.getByRole('button',{name:'Read selected investigation'}).click();check(await page.evaluate(()=>document.activeElement===document.querySelector('.rr-dossier-header h2')),`${width}px reader jump moves keyboard focus to the actual case heading`);await page.screenshot({path:resolve(out,`radar-case-${width}.png`)});await overflow(`${width}px case`);await open(`rr_case=${encodeURIComponent(first.id)}&rr_reader=${encodeURIComponent(`source:${first.sourceIds[0]}`)}`);await popup.waitFor();const box=await popup.boundingBox();check(box.x>=0&&box.x+box.width<=width+1&&box.y>=0&&box.y+box.height<=1001,`${width}px source modal stays inside viewport`);await page.screenshot({path:resolve(out,`radar-reader-${width}.png`)});await page.keyboard.press('Escape');}
 check(errors.length===0,`No runtime exceptions (${errors.length})`);writeFileSync(resolve(out,'acceptance.json'),JSON.stringify({base,cases:data.cases.map(row=>row.id),checks,errors},null,2)+'\n');console.log(`Research radar browser: ${checks.length} checks passed; ${out}`);
}finally{await browser.close();if(server)await new Promise(done=>server.close(done));}
