import json
from pathlib import Path
rows=[
('delhi','Delhi / New Delhi','DL',28.61,77.21,'metro,union-territory-capital','DL'),('mumbai','Mumbai','MH',19.08,72.88,'metro,state-capital','MH'),('kolkata','Kolkata','WB',22.57,88.36,'metro,state-capital','WB'),('chennai','Chennai','TN',13.08,80.27,'metro,state-capital','TN'),('bengaluru','Bengaluru','KA',12.97,77.59,'metro,state-capital','KA'),('hyderabad','Hyderabad','TS',17.39,78.49,'metro,state-capital','TS'),('ahmedabad','Ahmedabad','GJ',23.02,72.57,'metro',''),('pune','Pune','MH',18.52,73.86,'metro',''),
('amaravati','Amaravati','AP',16.52,80.52,'state-capital','AP'),('itanagar','Itanagar','AR',27.08,93.61,'state-capital','AR'),('dispur','Dispur','AS',26.14,91.79,'state-capital','AS'),('patna','Patna','BR',25.59,85.14,'state-capital','BR'),('raipur','Raipur','CG',21.25,81.63,'state-capital','CG'),('panaji','Panaji','GA',15.49,73.83,'state-capital','GA'),('gandhinagar','Gandhinagar','GJ',23.22,72.65,'state-capital','GJ'),('chandigarh','Chandigarh','CH',30.73,76.78,'state-capital,union-territory-capital','CH,PB,HR'),('shimla','Shimla','HP',31.10,77.17,'state-capital','HP'),('ranchi','Ranchi','JH',23.34,85.31,'state-capital','JH'),('thiruvananthapuram','Thiruvananthapuram','KL',8.52,76.94,'state-capital','KL'),('bhopal','Bhopal','MP',23.26,77.41,'state-capital','MP'),('imphal','Imphal','MN',24.82,93.94,'state-capital','MN'),('shillong','Shillong','ML',25.58,91.89,'state-capital','ML'),('aizawl','Aizawl','MZ',23.73,92.72,'state-capital','MZ'),('kohima','Kohima','NL',25.67,94.11,'state-capital','NL'),('bhubaneswar','Bhubaneswar','OD',20.30,85.82,'state-capital','OD'),('jaipur','Jaipur','RJ',26.91,75.79,'state-capital','RJ'),('gangtok','Gangtok','SK',27.34,88.61,'state-capital','SK'),('agartala','Agartala','TR',23.83,91.29,'state-capital','TR'),('lucknow','Lucknow','UP',26.85,80.95,'state-capital','UP'),('dehradun','Dehradun','UK',30.32,78.03,'state-capital','UK'),('srinagar','Srinagar','JK',34.08,74.80,'union-territory-capital','JK'),('jammu','Jammu','JK',32.73,74.86,'seasonal-capital','JK'),('leh','Leh','LA',34.15,77.58,'union-territory-capital','LA'),('kavaratti','Kavaratti','LD',10.56,72.64,'union-territory-capital','LD'),('puducherry','Puducherry','PY',11.94,79.81,'union-territory-capital','PY'),('daman','Daman','DN',20.40,72.83,'union-territory-capital','DN'),('sri-vijaya-puram','Sri Vijaya Puram','AN',11.62,92.73,'union-territory-capital','AN'),
('dharamshala','Dharamshala','HP',32.22,76.32,'seasonal-capital','HP'),('gairsain','Gairsain / Bhararisain','UK',30.08,79.28,'seasonal-capital','UK'),('nagpur','Nagpur','MH',21.15,79.09,'seasonal-capital','MH'),('guwahati','Guwahati','AS',26.14,91.74,'metro-region',''),('kochi','Kochi','KL',9.93,76.27,'metro-region',''),('surat','Surat','GJ',21.17,72.83,'metro-region',''),('visakhapatnam','Visakhapatnam','AP',17.69,83.22,'metro-region',''),('kargil','Kargil','LA',34.55,76.13,'administrative-centre','LA'),('shivpuri','Shivpuri','MP',25.42,77.66,'project-city','')]
sectors=['energy','water','welfare','loans','tax','infrastructure','resources','police','defence','foreign-investment','health','education','administration','justice','media']
source={'id':'radar-coverage:capital-list','title':'State and union territory capitals: administrative and legislative roles','url':'https://en.wikipedia.org/wiki/List_of_state_and_union_territory_capitals_in_India','publisher':'Wikipedia contributors','publishedAt':None,'retrievedAt':'2026-10-07','family':'wikipedia-capital-list','kind':'dataset','summary':'Reference inventory of 28 states and eight union territories, administrative capitals and seasonal legislative centres. Used for navigation coverage; specific corrections are bound separately.','locator':'States and Union territories tables; introductory administrative-capital note','limitations':['Secondary, changeable compilation; not a legal notification.','The fetched table retains Port Blair; the primary 2024 renaming source supersedes that label.','Two-decimal city coordinates are manually curated approximate navigation anchors, not validated sites of incidents, offices, people or payments.'],'access':'full-text'}
sources=[source,{**source,'id':'radar-coverage:svpuram','title':'Government renames Port Blair as Sri Vijaya Puram','url':'https://www.pib.gov.in/Pressreleaseshare.aspx?PRID=2054647','publisher':'Ministry of Home Affairs / PIB','publishedAt':'2024-09-13','family':'mha-renaming-2054647','kind':'official','summary':'Official announcement renames the Andaman and Nicobar Islands capital Sri Vijaya Puram.','locator':'Opening paragraph','limitations':['Name correction only; not evidence of funding or a case.']},{**source,'id':'radar-coverage:uk-capitals','title':'Uttarakhand government geography: capital roles','url':'https://cm.uk.gov.in/geography/','publisher':'Chief Minister Office Uttarakhand','publishedAt':None,'family':'uk-cmo-geography','kind':'official','summary':'Lists Dehradun as temporary capital and Gairsain as summer capital.','locator':'Geography table rows3–4','limitations':['Role list, not evidence of a project location; Gairsain/Bhararisain represented by an approximate regional navigation anchor.']}]
notes={'chandigarh':'Physically in Chandigarh UT; capitalFor separately records Punjab and Haryana administrative roles. These associations do not place their projects inside Chandigarh.','sri-vijaya-puram':'Formerly Port Blair; label follows the official September2024 renaming.','gairsain':'Gairsain summer-capital region; Bhararisain hosts the assembly. The pin is an approximate regional navigation anchor.','nagpur':'Maharashtra winter legislative-session centre; Mumbai remains the principal capital.','dharamshala':'Himachal Pradesh second/seasonal capital and legislative-session centre.','kargil':'Ladakh administrative centre, included separately from Leh; no assertion that all government functions occur here.','raipur':'Raipur metropolitan navigation anchor; Naya Raipur/Atal Nagar government offices require project-specific location records.','delhi':'National government and NCT navigation context; nationwide policy records are explicitly identified and must not be interpreted as Delhi-only incidents.','shivpuri':'Additional actual project city for a public corporate defence-investment announcement; inclusion is not a finding of misconduct.'}
cities=[]
for id,label,state,lat,lon,roles,caps in rows:
 refs=['radar-coverage:capital-list'] if caps else []
 if id=='sri-vijaya-puram':refs.append('radar-coverage:svpuram')
 if id in ['dehradun','gairsain']:refs.append('radar-coverage:uk-capitals')
 cities.append({'id':id,'label':label,'stateCodes':[state],'capitalFor':caps.split(',') if caps else [],'latitude':lat,'longitude':lon,'role':roles.split(','),'sectors':sectors,'notes':notes.get(id,'Approximate city navigation anchor. Cases require separately sourced geography; planned coverage is not completed research.'),'sourceIds':refs,'coordinateBasis':'Manually curated approximate navigation anchor; two decimal degrees, not facility geocoding.'})
x={'schemaVersion':1,'cutoff':'2026-10-07','cities':cities,'geographySources':sources,'coverageMeaning':'A navigation and acquisition plan covering capitals for all36state/UT jurisdictions, seasonal centres and selected metro/project cities. Case counts are derived from actual research; unresearched is not low risk.','sectorMeaning':'Planned sector checklist per city; does not assert cases have been investigated in every sector.'}
p=Path('research/raw/research-radar/coverage.json');p.write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n')
print(len(cities),'navigation anchors;',len(set(c for x in cities for c in x['capitalFor'])),'capital jurisdictions')
