import test from 'node:test';
import assert from 'node:assert/strict';
import { validateRadar } from './validate.mjs';
import { buildForecastRegistry, scoreForecasts, validateTemporalSplit, validDate } from './forecast.mjs';

// Synthetic schema fixtures exercise rejection boundaries; they are never production research.
function fixture() {
  const source = { id:'radar-test:source', title:'Synthetic audit',url:'https://example.org/audit',publisher:'Fixture',publishedAt:'2026-09-01',retrievedAt:'2026-10-07',family:'fixture-audit',kind:'official',summary:'Fixture only.',locator:'Paragraph 1',limitations:[],access:'full-text' };
  const entity = id => ({id:`radar-test:${id}`,label:id,kind:'institution',role:'Test role',sourceIds:[source.id]});
  const row={id:'radar-test:case',title:'Synthetic institutional outcome',cityIds:['delhi'],stateCodes:['DL'],sectors:['water'],question:'Will the next inspection be published?',summary:'Synthetic test fixture only.',status:'open-question',sourceIds:[source.id],observations:[{text:'An inspection record exists.',sourceIds:[source.id]}],counterevidence:[{text:'The existing record does not show a violation.',sourceIds:[source.id]}],nextRecords:[{record:'Next inspection',holder:'Test institution',purpose:'Resolve outcome'}],entities:[entity('a'),entity('b')],links:[{id:'radar-test:edge',from:'radar-test:a',to:'radar-test:b',kind:'oversight',label:'Inspects',sourceIds:[source.id],status:'documented'}],scenario:{target:'Publication of next inspection report by deadline',horizonDays:90,evaluationAt:'2027-01-05',baseline:'Not estimated',triggers:['New inspection notice'],alternatives:['No new inspection'],falsifiers:['Inspection finds no issue'],probability:null,probabilityReason:'No outcome population',requiredData:['Dated inspection report']},updatedAt:'2026-10-07'};
  return {regions:[{schemaVersion:1,region:'test',cutoff:'2026-10-07',searchLog:[],sources:[source],cases:[row],actors:[]}],coverage:{schemaVersion:1,cutoff:'2026-10-07',cities:[{id:'delhi',label:'Delhi',stateCodes:['DL'],latitude:28.61,longitude:77.21,role:['metro'],sectors:['water'],notes:'Planning centroid, no inferred case location.'}]}};
}
const rowOf = data => data.regions[0].cases[0];
const invalid = (data, pattern) => {const result=validateRadar(data.regions,data.coverage);assert.equal(result.valid,false);assert.ok(result.errors.some(error=>pattern.test(error)),JSON.stringify(result.errors));};
test('Valid synthetic schema and exact future horizon pass',()=>{const data=fixture();assert.deepEqual(validateRadar(data.regions,data.coverage).errors,[]);assert.equal(buildForecastRegistry([rowOf(data)],'2026-10-07')[0].status,'unknown');});
test('Impossible calendar dates are rejected, not normalized',()=>{assert.equal(validDate('2026-02-30'),false);const data=fixture();data.regions[0].sources[0].publishedAt='2026-02-30';invalid(data,/publishedAt/);});
test('A future publication or retrieval cannot masquerade as latest research',()=>{const data=fixture();data.regions[0].sources[0].publishedAt='2026-10-08';invalid(data,/cutoff|publication after retrieval/);});
test('Unsupported claim stage is not promoted from a court source',()=>{const data=fixture();rowOf(data).links[0].kind='allegation';invalid(data,/allegation cannot be promoted/);});
test('Dangling entities and missing edge sources fail exact graph validation',()=>{const data=fixture();rowOf(data).links[0].to='radar-test:unknown';rowOf(data).links[0].sourceIds=['radar-test:missing'];invalid(data,/dangling exact endpoint/);invalid(data,/missing source/);});
test('An unavailable page cannot be sole evidence',()=>{const data=fixture();data.regions[0].sources[0].access='unavailable';data.regions[0].sources[0].limitations=['Could not inspect'];invalid(data,/unavailable records alone/);});
test('Missing counterevidence is rejected',()=>{const data=fixture();rowOf(data).counterevidence=[];invalid(data,/counterevidence/);});
test('Source frequency is never a probability',()=>{const data=fixture();rowOf(data).scenario.probability=0.8;invalid(data,/probability must remain null/);assert.throws(()=>buildForecastRegistry([rowOf(data)],'2026-10-07'),/probability/);});
test('Legacy or lower-case state aliases are not silently mapped',()=>{const data=fixture();rowOf(data).stateCodes=['tg'];invalid(data,/uppercase state code/);});
test('Horizon must match calendar cutoff and target remains future',()=>{const data=fixture();rowOf(data).scenario.horizonDays=89;invalid(data,/calendar interval/);});
test('Counterevidence cannot disappear from the complete case source list',()=>{const data=fixture();const second={...data.regions[0].sources[0],id:'radar-test:second'};data.regions[0].sources.push(second);rowOf(data).counterevidence[0].sourceIds=[second.id];invalid(data,/counterevidence source omitted/);});
test('Article-only link cannot acquire documented official provenance',()=>{const data=fixture();data.regions[0].sources[0].kind='news';invalid(data,/documented status needs/);});

const prediction = (id, probability, outcome) => ({id,targetType:'institutional-outcome',probability,status:'resolved',outcome,predictedAt:'2026-01-01',evaluationAt:'2026-07-01',latestFeatureAt:'2025-12-31',outcomeObservedAt:'2026-07-01',resolvedAt:'2026-07-03',resolutionSourceIds:['test-resolution']});
test('Brier and proper log loss match independently calculable binary examples',()=>{const result=scoreForecasts([prediction('a',0.8,1),prediction('b',0.2,0)],{asOf:'2026-08-01',bins:2});assert.ok(Math.abs(result.brier-0.04)<1e-12);assert.ok(Math.abs(result.logLoss+Math.log(0.8))<1e-12);assert.deepEqual(result.reliability.map(bin=>[bin.count,bin.meanForecast,bin.observedFrequency]),[[1,0.2,0],[1,0.8,1]]);});
test('Unknown and censored cases are counted but never negative outcomes',()=>{const unknown={...prediction('unknown',0.9,1),status:'unknown',outcome:null,resolvedAt:null,outcomeObservedAt:null,resolutionSourceIds:[]};const result=scoreForecasts([unknown,{...unknown,id:'censored',status:'censored'}],{asOf:'2026-08-01'});assert.equal(result.eligible,0);assert.equal(result.brier,null);assert.equal(result.logLoss,null);assert.deepEqual(result.excluded,{unknown:1,censored:1});});
test('Wrong certainty has infinite log loss, not an arbitrary hidden epsilon',()=>{const result=scoreForecasts([prediction('wrong',0,1)],{asOf:'2026-08-01'});assert.equal(result.brier,1);assert.equal(result.logLoss,Infinity);});
test('Outcome observed after evaluation and late-arriving features cannot leak',()=>{assert.throws(()=>scoreForecasts([{...prediction('late',0.5,1),latestFeatureAt:'2026-01-02'}],{asOf:'2026-08-01'}),/temporal leakage/);assert.throws(()=>scoreForecasts([{...prediction('late',0.5,1),outcomeObservedAt:'2026-07-02'}],{asOf:'2026-08-01'}),/timing/);});
test('Absent event cannot resolve negative before observation window ends',()=>{assert.throws(()=>scoreForecasts([{...prediction('early',0.5,0),outcomeObservedAt:'2026-06-01'}],{asOf:'2026-08-01'}),/absence cannot resolve/);});
test('Outcome requires a source and cannot be known before its publication date',()=>{assert.throws(()=>scoreForecasts([{...prediction('no-source',0.5,1),resolutionSourceIds:[]}],{asOf:'2026-08-01'}),/provenance/);assert.throws(()=>scoreForecasts([prediction('late-source',0.5,1)],{asOf:'2026-07-02'}),/timing/);});
test('Forecast target excludes individual guilt and duplicate weighting',()=>{assert.throws(()=>scoreForecasts([{...prediction('person',0.5,1),targetType:'personal-guilt'}],{asOf:'2026-08-01'}),/institutional-outcome/);assert.throws(()=>scoreForecasts([prediction('same',0.5,1),prediction('same',0.5,1)],{asOf:'2026-08-01'}),/duplicate target/);});
test('Temporal split uses document availability and disjoint entity groups',()=>{const split={train:[{id:'train',entityGroup:'A',featureAvailableAt:'2025-01-01',predictedAt:'2025-01-02',outcomeObservedAt:'2025-09-30',outcomeAvailableAt:'2025-10-01'}],evaluation:[{id:'evaluation',entityGroup:'B',predictedAt:'2026-01-01',featureAvailableAt:'2025-12-31',outcomeObservedAt:'2026-07-01',outcomeAvailableAt:'2026-07-03'}],cutoff:'2025-12-31',asOf:'2026-08-01'};assert.equal(validateTemporalSplit(split).valid,true);split.train[0].outcomeAvailableAt='2026-01-01';split.evaluation[0].entityGroup='A';const invalid=validateTemporalSplit(split);assert.equal(invalid.valid,false);assert.ok(invalid.errors.some(error=>error.includes('outcome not available')));assert.ok(invalid.errors.some(error=>error.includes('overlaps training')));});


test('Historical training rows reject features learned after their own prediction/outcome',()=>{
  const split={train:[{id:'train',entityGroup:'A',featureAvailableAt:'2025-11-01',predictedAt:'2025-01-02',outcomeObservedAt:'2025-09-30',outcomeAvailableAt:'2025-10-01'}],evaluation:[{id:'evaluation',entityGroup:'B',predictedAt:'2026-01-01',featureAvailableAt:'2025-12-31',outcomeObservedAt:'2026-07-01',outcomeAvailableAt:'2026-07-03'}],cutoff:'2025-12-31',asOf:'2026-08-01'};
  const result=validateTemporalSplit(split);assert.equal(result.valid,false);assert(result.errors.some(error=>error.includes('historical prediction time')));
});
