import {test} from 'node:test';
import assert from 'node:assert/strict';
import {loadAtlas} from './load.mjs';
import {loadInvestigation} from '../investigation/load.mjs';
const api=await loadAtlas(),{INVESTIGATION_REGISTRY:registry,getInvestigationView,RETAINED_INTERNATIONAL_LENDER_IDS}=await loadInvestigation();
const source={id:'source:s',title:'Original document',url:'https://example.gov.in/source',locator:'Page 2',publishedAt:'2024-01-01',retrievedAt:'2026-10-06'};
const dimensions={domains:['finance'],layers:['funding'],sourceIds:[source.id],limitations:['A commitment is not a cash payment'],route:'/finance',geography:[{scope:'state',stateCodes:['MH'],localityIds:[],sourceIds:[source.id],basis:'project-location',note:'Documented project location'}]};
const node=id=>({...dimensions,id,namespace:'test',label:id,type:'company',resolved:true,identityBasis:`Exact legal identifier ${id}`});
const edge=(id,from,to,patch={})=>({...dimensions,id,namespace:'test',from,to,label:id,kind:'loan',tier:'documented',status:'committed',fromDate:'2024-01-01',toDate:null,dateBasis:'Commitment signature',recordIds:[],responseIds:[],amounts:[{value:10,currency:'INR',unit:'crore',stage:'committed',period:'2024'}],...patch});
const record=(id,patch={})=>({...dimensions,id,namespace:'test',title:id,summary:'Recorded observation',kind:'investigation-case',tier:'documented',status:'reviewed',entityIds:[],relationshipIds:[],fromDate:'2024-01-01',toDate:null,dateBasis:'Recorded date',response:'Read the retained response',amounts:[],...patch});
const fixture=(entities,relationships,records=[])=>({entities,relationships,records,sources:[source],states:[{code:'MH',name:'Maharashtra'}],localities:[],coverage:[],held:[],updatedAt:'2026-10-06'});

test('five-hop directional discovery retains original arrow direction and excludes counter-evidence traversal',()=>{const nodes=['a','b','c','d','e','f','g'].map(node),edges=['a','b','c','d','e'].map((from,i)=>edge(`e${i}`,from,['b','c','d','e','f'][i]));edges.push(edge('response','a','g',{kind:'response'}));const r=fixture(nodes,edges);const outgoing=api.exploreAtlasGraph(r,{rootId:'a',depth:5,direction:'outgoing'});assert.equal(outgoing.totalEntities,6);assert.deepEqual(api.exploreAtlasGraph(r,{rootId:'a',depth:5,direction:'incoming'}).entities.map(row=>row.id),['a']);assert.equal(api.exploreAtlasGraph(r,{rootId:'a',depth:1,direction:'outgoing'}).totalEntities,2);assert.equal(api.exploreAtlasGraph(r,{rootId:'missing',depth:5}).totalRelationships,0);assert.equal(api.findAtlasTrails(r,{fromId:'a',toId:'f',depth:5,direction:'outgoing'}).paths[0].length,5);const reversed=api.findAtlasTrails(r,{fromId:'f',toId:'a',depth:5,direction:'incoming'}).paths[0];assert.ok(reversed.every(step=>step.reversed));assert.equal(reversed[0].relationship.from,'e');});
test('bounded visual graph never caps the evidence ledger or response-closed export',()=>{const nodes=[node('hub'),...Array.from({length:230},(_,i)=>node(`n${i}`))],edges=nodes.slice(1).map(n=>edge(`hub-${n.id}`,'hub',n.id,{responseIds:['denial']})),denial=record('denial',{kind:'response',fromDate:'2026-01-01',response:'Respondent disputes interpretation'}),r=fixture(nodes,edges,[denial]);const result=api.exploreAtlasGraph(r,{rootId:'hub',depth:1,to:'2024-12-31'});assert.equal(result.entities.length,80);assert.equal(result.ledger.length,230);assert.equal(result.totalEntities,231);assert.equal(result.truncated,true);const packet=api.exportAtlasEvidence(r,result.ledger.map(row=>({kind:'relationship',id:row.id})),{to:'2024-12-31'});assert.equal(packet.relationships.length,230);assert.ok(packet.records.some(row=>row.id==='denial'));assert.deepEqual(packet.missingIds,[]);assert.equal(packet.relationships[0].amounts[0].stage,'committed');});
test('date filtering uses only exact known event endpoints, has explicit unknown toggle and rejects invalid dates',()=>{assert.equal(api.atlasDatePass({fromDate:'2010-01-01',toDate:null},api.ATLAS_DATE_RANGE),false);assert.equal(api.atlasDatePass({fromDate:null,toDate:null},api.ATLAS_DATE_RANGE),true);assert.equal(api.atlasDatePass({fromDate:null,toDate:null},{includeUndated:false}),false);assert.equal(api.atlasDatePass({fromDate:'2024-01-01'},{from:'2024-02-30'}),false);assert.equal(api.atlasDatePass({fromDate:'2024-01-01'},{from:'2025-01-01',to:'2024-01-01'}),false);});
test('case feed counts actual record kinds; documentary presence does not promote allegations to findings',()=>{const records=[record('generic',{kind:'relationship-record',tier:'alleged'}),record('claim',{kind:'allegation-record',tier:'alleged'}),record('finding',{kind:'audit-finding',tier:'documented'}),record('response',{kind:'response'}),record('decision',{kind:'judicial-decision'}),record('case')],r=fixture([],[],records),feed=api.getAtlasCaseFeed(r);assert.equal(feed.total,4);assert.deepEqual(feed.counts,{allegation:1,finding:1,proceeding:1,case:1});assert.equal(api.getAtlasCaseFeed(r,{domains:['water']}).total,0);assert.equal(api.getAtlasCaseFeed(r,{stateCode:'ZZ'}).total,0);assert.equal(api.getAtlasCaseFeed(r,{layers:[]}).total,0);});
test('all retained cases export exact endpoints and recursively linked responses with direct and geography source closure',()=>{const cases=registry.records.filter(row=>row.kind==='investigation-case');assert.ok(cases.length>=13);for(const record of cases){const closure=api.getAtlasEvidenceClosure(registry,[{kind:'record',id:record.id}]),sources=new Set(closure.sources.map(row=>row.id)),entities=new Set(closure.entities.map(row=>row.id)),records=new Set(closure.records.map(row=>row.id));assert.deepEqual(closure.missingIds,[]);for(const edge of closure.relationships){assert.ok(entities.has(edge.from)&&entities.has(edge.to));for(const id of edge.responseIds)assert.ok(records.has(id));}for(const row of [...closure.records,...closure.relationships,...closure.entities])for(const id of [...row.sourceIds,...row.geography.flatMap(geo=>geo.sourceIds)])assert.ok(sources.has(id));}assert.deepEqual(api.getAtlasEvidenceClosure(registry,[{kind:'entity',id:'unavailable'}]).missingIds,['unavailable']);});
test('public facility coordinates reject private people, unsourced coordinates and invalid precision',()=>{const r=fixture([{...node('person'),type:'person'}],[]);const errors=api.validateAtlasSites(r,[{id:'site',label:'Private location',entityIds:['person'],recordIds:[],sourceIds:[],lon:200,lat:100,precision:'guessed',stateCode:'MH',kind:'office',coordinateNote:''}]);assert.ok(errors.some(error=>error.includes('people')));assert.ok(errors.some(error=>error.includes('coordinates')));assert.ok(errors.some(error=>error.includes('source')));assert.ok(errors.some(error=>error.includes('precision')));});

test('atlas expansion preserves three source namespaces, policy chronology and reviewed identity bridge provenance',()=>{for(const namespace of api.ATLAS_NAMESPACES){assert.ok(registry.records.some(row=>row.namespace===namespace&&row.kind==='investigation-case'));assert.ok(registry.sources.some(row=>row.namespace===namespace));}const timeline=api.getAtlasPolicyTimeline(registry);assert.ok(timeline.length>=10);for(const record of timeline){assert.equal(record.kind,'policy-change');assert.ok(record.fromDate||record.toDate);assert.ok(api.atlasDatePass(record,api.ATLAS_DATE_RANGE));}const bridges=registry.relationships.filter(row=>row.kind==='identity-crosswalk'&&row.from.startsWith('atlas-'));assert.ok(bridges.length>=4);for(const bridge of bridges){const from=registry.entities.find(row=>row.id===bridge.from),to=registry.entities.find(row=>row.id===bridge.to);assert.ok(from&&to);assert.equal(bridge.tier,'documented');assert.equal(bridge.amounts.length,0);for(const id of [...from.sourceIds,...to.sourceIds])assert.ok(bridge.sourceIds.includes(id));}});
test('verified site filters use its actual state and anchored dated case, never inherited national location',()=>{assert.deepEqual(api.validateAtlasSites(registry,api.ATLAS_SITES),[]);assert.equal(api.getAtlasVisibleSites(registry,{stateCode:'KA'}).length,0);const tamil=api.getAtlasVisibleSites(registry,{stateCode:'TN',domains:['transport']});assert.equal(tamil.length,1);assert.ok(tamil[0].sourceUrl.startsWith('https://ipa.org.in/'));assert.equal(api.getAtlasVisibleSites(registry,{stateCode:'TN',domains:['education']}).length,0);assert.equal(api.getAtlasVisibleSites(registry,{from:'2099-01-01',includeUndated:false}).length,0);});

test('alleged links retain a separate edge denominator, exact tier and explicitly qualified entity association',()=>{const alleged=api.getAtlasAllegedLinks(registry);assert.equal(alleged.total,registry.relationships.filter(row=>row.tier==='alleged').length);assert.ok(alleged.total>50);assert.ok(alleged.entries.every(row=>row.relationship.tier==='alleged'));const r=fixture([node('a'),node('b')],[edge('allegation','a','b',{tier:'alleged',summary:'Disputed loan',geography:[{scope:'unknown',stateCodes:[],localityIds:[],sourceIds:[source.id],basis:'unknown',note:'Location not established'}]})]);const association=api.getAtlasAllegedLinks(r,{stateCode:'MH'});assert.equal(association.total,1);assert.equal(association.entries[0].placement,'entity-association');assert.equal(api.getAtlasAllegedLinks(r,{stateCode:'MH',geographyMode:'coverage'}).total,0);assert.equal(api.getAtlasCaseFeed(r).total,0);assert.equal(api.getAtlasAllegedLinks(r,{tiers:['documented']}).total,0);});

test('an explicitly empty sector selection empties every atlas surface while undefined means all sectors',()=>{const filters={domains:[]};assert.equal(api.getAtlasCaseFeed(registry,filters).total,0);assert.equal(api.getAtlasAllegedLinks(registry,filters).total,0);assert.equal(api.getAtlasPolicyTimeline(registry,filters).length,0);assert.equal(api.getAtlasVisibleSites(registry,filters).length,0);assert.equal(api.exploreAtlasGraph(registry,filters).totalRelationships,0);assert.equal(api.exploreAtlasGraph(registry,filters).totalEntities,0);assert.ok(api.getAtlasCaseFeed(registry,{}).total>0);});

test('foreign country context stays explicit and does not become Indian national or state coverage',()=>{const country={scope:'country',countryCodes:['PH','IN'],stateCodes:[],localityIds:[],sourceIds:[source.id],basis:'country-context',note:'Sourced bilateral country context; no facility coordinate asserted'},r=fixture([node('a'),node('b')],[edge('export','a','b',{geography:[country]})],[record('export-case',{geography:[country]})]);assert.equal(api.getAtlasCaseFeed(r).international,1);assert.equal(api.getAtlasCaseFeed(r).national,0);assert.equal(api.getAtlasCaseFeed(r,{stateCode:'MH'}).total,0);assert.equal(api.exploreAtlasGraph(r,{stateCode:'MH',geographyMode:'coverage'}).ledger.length,0);assert.equal(api.getAtlasCaseFeed(r).entries[0].record.geography[0].countryCodes[0],'PH');});

test('reviewed identity navigation is symmetric while monetary trail arrows retain their original direction',()=>{const r=fixture(['lender','legacy-borrower','reviewed-borrower','owner'].map(node),[edge('loan','lender','legacy-borrower'),edge('identity','reviewed-borrower','legacy-borrower',{kind:'identity-crosswalk',amounts:[]}),edge('owner','reviewed-borrower','owner',{kind:'ownership',amounts:[]})]);const trail=api.findAtlasTrails(r,{fromId:'lender',toId:'owner',depth:3,direction:'outgoing'}).paths[0];assert.deepEqual(trail.map(step=>step.relationship.id),['loan','identity','owner']);assert.equal(trail[1].reversed,false);assert.equal(trail[1].relationship.from,'reviewed-borrower');assert.equal(api.findAtlasTrails(r,{fromId:'owner',toId:'lender',depth:3,direction:'outgoing'}).paths.length,0);});

test('atlas feeds and graph use the shared source-title, endpoint-name and state-association matcher',()=>{for(const filters of [{q:'Adani'},{q:'CAG'},{stateCode:'KA',includeNational:false,geographyMode:'associations'},{stateCode:'TN',includeNational:false,geographyMode:'associations'},{domains:[]}]){const shared=getInvestigationView(filters),expectedCases=shared.records.filter(row=>api.atlasCaseCategory(row)).map(row=>row.id).sort();assert.deepEqual(api.getAtlasCaseFeed(registry,filters).entries.map(row=>row.record.id).sort(),expectedCases,JSON.stringify(filters));assert.deepEqual(api.exploreAtlasGraph(registry,filters).ledger.map(row=>row.id).sort(),shared.relationships.map(row=>row.id).sort(),JSON.stringify(filters));assert.deepEqual(api.getAtlasAllegedLinks(registry,filters).entries.map(row=>row.relationship.id).sort(),shared.relationships.filter(row=>row.tier==='alleged').map(row=>row.id).sort(),JSON.stringify(filters));}const adani=new Set(api.getAtlasCaseFeed(registry,{q:'Adani'}).entries.map(row=>row.record.id));for(const id of ['justice-research:record:record-adicorp-order','justice-research:record:record-milestone-order','deep-corporate:record:mangaluru-airport-concession'])assert.ok(adani.has(id));});

test('financial accounting context remains discoverable without being promoted to a case or allegation',()=>{const context=api.getAtlasFinancialContext(registry,{domains:['international-finance']});assert.equal(context.total,4);assert.equal(api.getAtlasFinancialContext(registry,{domains:[]}).total,0);const ids=new Set(context.entries.map(({record})=>record.id));for(const id of ['ifc-bajaj-private-debt','ida-budget-support','imf-sdr-allocation','imf-india-no-programme-credit'])assert.ok(ids.has(`atlas-international-finance:record:${id}`));for(const {record} of context.entries){assert.equal(api.atlasCaseCategory(record),null);assert.deepEqual(api.getAtlasEvidenceClosure(registry,[{kind:'record',id:record.id}]).missingIds,[]);}const imf=api.getAtlasFinancialContext(registry,{domains:['international-finance'],q:'IMF'});assert.equal(imf.total,2);const noCredit=imf.entries.find(({record})=>record.kind==='institution-financial-position').record;assert.equal(noCredit.relationshipIds.length,0);const graph=api.exploreAtlasGraph(registry,{q:'IMF',domains:['international-finance']});assert.ok(noCredit.entityIds.every(id=>graph.ledgerEntities.some(row=>row.id===id)));});

test('retained international-finance tags follow exact lender IDs without promoting citation tiers or adding flows',()=>{const ids=new Set(RETAINED_INTERNATIONAL_LENDER_IDS.map(id=>`legacy:entity:${id}`)),edges=registry.relationships.filter(row=>row.namespace==='legacy'&&row.domains.includes('international-finance'));assert.equal(edges.length,961);assert.ok(edges.every(edge=>ids.has(edge.from)||ids.has(edge.to)));const nodes=new Set(edges.flatMap(edge=>[edge.from,edge.to]));assert.equal(nodes.size,66);for(const edge of edges){assert.ok(edge.domains.includes('finance'));assert.ok(edge.sourceIds.every(id=>registry.sources.find(row=>row.id===id)?.tier==='reported'));assert.ok(edge.recordIds.every(id=>registry.records.find(row=>row.id===id)?.domains.includes('international-finance')));}assert.equal(edges.filter(row=>row.tier==='analytic').length,20);assert.equal(edges.filter(row=>row.tier==='reported').length,13);});

test('an empty future window suppresses unsupported standalone graph identities while retaining an explicitly selected root',()=>{const filters={from:'2099-01-01',includeUndated:false},graph=api.exploreAtlasGraph(registry,filters),shared=getInvestigationView(filters);assert.equal(shared.records.length,0);assert.equal(graph.totalRelationships,0);assert.equal(graph.totalEntities,0);const rootId=registry.entities[0].id,selected=api.exploreAtlasGraph(registry,{...filters,rootId});assert.deepEqual(selected.ledgerEntities.map(row=>row.id),[rootId]);assert.equal(selected.ledger.length,0);});

test('explicit outcome-record kinds appear in shared proceedings without becoming findings or allegations',()=>{const outcome=record('explicit-outcome',{kind:'outcome-record',tier:'documented'});assert.equal(api.atlasCaseCategory(outcome),'proceeding');const feed=api.getAtlasCaseFeed(registry);for(const id of ['allegations-policy:record:pacl-current-recovery','allegations-policy:record:chapwa-court-outcome'])assert.equal(feed.entries.find(row=>row.record.id===id)?.category,'proceeding');});
