import { useEffect, useId, useMemo, useRef, useState } from 'react';
import type { InvestigationFilters, InvestigationRegistry } from '../../data/investigation';
import { ATLAS_DATE_RANGE, exploreAtlasGraph, exportAtlasEvidence, findAtlasTrails, type AtlasSelection } from '../../data/atlasInvestigation';
import { InvestigationGraph } from './InvestigationGraph';
import { AtlasEvidencePopover } from './AtlasEvidencePopover';
import { investigationRelationshipDate, relationshipDirected, type GraphDirection } from './graphHelpers';
import './atlas-network.css';
export interface AtlasNetworkProps {registry:InvestigationRegistry;evidenceRegistry?:InvestigationRegistry;filters?:InvestigationFilters;selectedEntityId?:string|null;selectedEvidence?:AtlasSelection|null;onSelectionChange?:(selection:AtlasSelection|null)=>void;onEntitySelect?:(id:string)=>void;onRelationshipSelect?:(id:string)=>void;onRecordSelect?:(id:string)=>void;onSourceSelect?:(id:string)=>void}
const EMPTY_FILTERS:InvestigationFilters={};
export function AtlasNetwork({registry,evidenceRegistry=registry,filters=EMPTY_FILTERS,selectedEntityId,selectedEvidence,onSelectionChange,onEntitySelect,onRelationshipSelect,onRecordSelect,onSourceSelect}:AtlasNetworkProps) {
 const searchRef=useRef<HTMLInputElement>(null);
 const uid=useId(),[focus,setFocus]=useState<string|null>(null),[selection,setSelection]=useState<AtlasSelection|null>(null),[depth,setDepth]=useState<1|2|3|4|5>(2),[direction,setDirection]=useState<GraphDirection>('both'),[view,setView]=useState<'graph'|'table'>('graph'),[moneyOnly,setMoneyOnly]=useState(false),[query,setQuery]=useState(''),[dates,setDates]=useState<{from:string;to:string}>({from:'',to:''}),[includeUndated,setIncludeUndated]=useState(true),[target,setTarget]=useState(''),[targetQuery,setTargetQuery]=useState('');
 useEffect(()=>{if(selectedEntityId!==undefined)setFocus(selectedEntityId);},[selectedEntityId]);
 useEffect(()=>{if(selectedEvidence===undefined)return;setSelection(selectedEvidence);if(selectedEvidence?.kind==='entity')setFocus(selectedEvidence.id);},[selectedEvidence?.kind,selectedEvidence?.id,selectedEvidence===null]);
 const selected=focus;
 const targetOptions=useMemo(()=>{const terms=targetQuery.toLowerCase().trim().split(/\s+/u).filter(Boolean);return terms.length?registry.entities.filter(row=>terms.every(term=>`${row.label} ${row.id}`.toLowerCase().includes(term))).slice(0,10):[];},[registry.entities,targetQuery]);
 const activeFilters={...filters,from:filters.from??dates.from,to:filters.to??dates.to,includeUndated:filters.includeUndated??includeUndated};
 const exploration=useMemo(()=>exploreAtlasGraph(registry,{...filters,from:filters.from??dates.from,to:filters.to??dates.to,includeUndated:filters.includeUndated??includeUndated,rootId:selected,depth,direction,moneyOnly}),[registry,filters,dates,includeUndated,selected,depth,direction,moneyOnly]);
 const options=useMemo(()=>{const terms=query.trim().toLowerCase().split(/\s+/u).filter(Boolean);return terms.length?registry.entities.filter(row=>terms.every(term=>`${row.label} ${row.id}`.toLowerCase().includes(term))).slice(0,24):[];},[registry.entities,query]);
 const trail=useMemo(()=>selected&&target?findAtlasTrails(registry,{...filters,from:filters.from??dates.from,to:filters.to??dates.to,includeUndated:filters.includeUndated??includeUndated,fromId:selected,toId:target,depth,direction,moneyOnly}):null,[registry,filters,dates,includeUndated,selected,target,depth,direction,moneyOnly]);
 const trailEdgeIds=trail?.paths.flatMap(path=>path.map(step=>step.relationship.id))??[];
 const selectEntity=(id:string|null)=>{const next=id?{kind:'entity' as const,id}:null;setFocus(id);setSelection(next);setQuery('');if(onSelectionChange)onSelectionChange(next);else if(id)onEntitySelect?.(id);};
 const selectEdge=(id:string|null)=>{const next=id?{kind:'relationship' as const,id}:null;setSelection(next);if(onSelectionChange)onSelectionChange(next);else if(id)onRelationshipSelect?.(id);};
 const selectSource=(id:string)=>{setSelection(null);onSourceSelect?.(id);};
 const selectRecord=(id:string)=>{const next={kind:'record' as const,id};setSelection(next);if(onSelectionChange)onSelectionChange(next);else onRecordSelect?.(id);};
 const exportEvidence=()=>{const packet=exportAtlasEvidence(registry,exploration.ledger.map(row=>({kind:'relationship',id:row.id})),activeFilters);const url=URL.createObjectURL(new Blob([JSON.stringify(packet,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='atlas-network-evidence.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="atlas-network" aria-labelledby={`${uid}-heading`}><header className="atlas-network-header"><div><span className="atlas-eyebrow">Connected public records</span><h2 id={`${uid}-heading`}>Follow the recorded trail</h2><p>{registry.entities.length.toLocaleString()} retained identities · {registry.relationships.length.toLocaleString()} exact relationships across all sectors</p></div><button type="button" onClick={exportEvidence} disabled={!exploration.ledger.length}>Export trail + responses</button></header>
  <div className="atlas-network-settings"><label className="atlas-entity-search">Find an exact identity<input ref={searchRef} type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Company, person, institution or policy" aria-controls={`${uid}-matches`}/></label><label>Hops<select aria-label="Hops" value={depth} onChange={event=>setDepth(Number(event.target.value) as 1|2|3|4|5)}>{[1,2,3,4,5].map(value=><option value={value} key={value}>{value} {value===1?'hop':'hops'}</option>)}</select></label><label>Explore<select aria-label="Explore" value={direction} onChange={event=>setDirection(event.target.value as GraphDirection)}><option value="both">Both directions</option><option value="outgoing">Outgoing arrows</option><option value="incoming">Incoming arrows</option></select></label><label className="atlas-check"><input type="checkbox" checked={moneyOnly} onChange={event=>setMoneyOnly(event.target.checked)}/>Amount-bearing links</label></div>
  {query.trim()&&<div id={`${uid}-matches`} className="atlas-identity-results">{options.map(entity=><button type="button" key={entity.id} onClick={()=>selectEntity(entity.id)}><strong>{entity.label}</strong><small>{entity.type} · {entity.namespace}</small></button>)}{!options.length&&<p>No exact retained identity matches this search.</p>}<small>Search discovers records. Similar names are never joined automatically.</small></div>}
  <div className="atlas-date-controls" aria-label="Network event dates"><label>From<input type="date" min={ATLAS_DATE_RANGE.from} max={ATLAS_DATE_RANGE.to} value={activeFilters.from} onChange={event=>setDates(value=>({...value,from:event.target.value}))} disabled={!!filters.from}/></label><span aria-hidden="true">→</span><label>To<input type="date" min={ATLAS_DATE_RANGE.from} max={ATLAS_DATE_RANGE.to} value={activeFilters.to} onChange={event=>setDates(value=>({...value,to:event.target.value}))} disabled={!!filters.to}/></label><label className="atlas-check"><input type="checkbox" checked={activeFilters.includeUndated} onChange={event=>setIncludeUndated(event.target.checked)} disabled={filters.includeUndated!==undefined}/>Include unknown dates</label>{selected&&<button type="button" onClick={()=>{selectEntity(null);setTarget('');}}>Global overview</button>}</div>
  <p className="atlas-network-method">{exploration.totalEntities.toLocaleString()} identities and {exploration.totalRelationships.toLocaleString()} relationships in this exploration. {exploration.undatedRelationships.toLocaleString()} relationships have unknown dates. {direction==='both'?'Both-direction exploration includes reversed traversal; each arrow keeps its source direction.':direction==='outgoing'?'Follow arrows from the selected entity.':'Follow arrows into the selected entity.'} Amounts retain their own stage, currency and period.</p>
  {selected&&<section className="atlas-trail-builder" aria-label="Trace an exact relationship trail"><label>Trace from {registry.entities.find(row=>row.id===selected)?.label} to<input type="search" value={targetQuery} placeholder="Find destination identity" onChange={event=>{setTargetQuery(event.target.value);setTarget('');}}/></label>{targetOptions.length>0&&<div className="atlas-trail-targets">{targetOptions.map(entity=><button type="button" key={entity.id} onClick={()=>{setTarget(entity.id);setTargetQuery('');}}>{entity.label}<small>{entity.namespace}</small></button>)}</div>}{target&&<p>Destination: <strong>{registry.entities.find(row=>row.id===target)?.label}</strong><button type="button" onClick={()=>setTarget('')}>Clear trail</button></p>}{trail&&<><p className="atlas-network-method">{trail.reason}</p>{trail.paths.map((steps,index)=><ol key={index} className="atlas-trail-steps" aria-label={`Recorded trail ${index+1}`}>{steps.map((step,stepIndex)=><li key={step.relationship.id}><span className="atlas-step-number">{stepIndex+1}</span><div><strong>{registry.entities.find(row=>row.id===step.fromId)?.label} {relationshipDirected(step.relationship.kind)?step.reversed?'←':'→':'↔'} {registry.entities.find(row=>row.id===step.toId)?.label}</strong><button type="button" onClick={()=>selectEdge(step.relationship.id)}>{step.relationship.label}</button><small>{step.relationship.tier} · {investigationRelationshipDate(step.relationship)}{step.reversed?' · traversed against the recorded arrow':''}</small>{step.relationship.amounts.map((amount,i)=><p key={i}>{amount.value.toLocaleString('en-IN')} {amount.currency} {amount.unit} · {amount.stage} · {amount.period}</p>)}{step.relationship.responseIds.length>0&&<button type="button" onClick={()=>selectRecord(step.relationship.responseIds[0])}>Read response / counter-evidence</button>}</div></li>)}</ol>)}</>}</section>}
  <InvestigationGraph entities={exploration.ledgerEntities} relationships={exploration.ledger} sources={registry.sources} records={registry.records} highlightEdgeIds={trailEdgeIds} selectedNode={selected??null} selectedEdge={selection?.kind==='relationship'?selection.id:null} depth={depth} direction={direction} hideDepthControls view={view} onNodeSelect={selectEntity} onEdgeSelect={selectEdge} onDepthChange={setDepth} onViewChange={setView} onSourceSelect={onSourceSelect?selectSource:undefined}/>
  <AtlasEvidencePopover returnFocusRef={searchRef} registry={evidenceRegistry} selection={selection} onClose={()=>{setSelection(null);onSelectionChange?.(null);}} onEntitySelect={selectEntity} onRelationshipSelect={selectEdge} onRecordSelect={selectRecord} onSourceSelect={onSourceSelect?selectSource:undefined}/>
 </section>;
}
