import { useId, useMemo, useState } from 'react';
import type { InvestigationFilters, InvestigationRegistry } from '../../data/investigation';
import { getAtlasCaseFeed, getAtlasAllegedLinks, getAtlasFinancialContext, getAtlasPolicyTimeline, type AtlasCaseCategory } from '../../data/atlasInvestigation';
import { investigationRelationshipDate } from './graphHelpers';
import './atlas-network.css';
export interface AtlasCaseFeedProps {registry:InvestigationRegistry;filters?:InvestigationFilters;onRecordSelect?:(id:string)=>void;onRelationshipSelect?:(id:string)=>void;onEntitySelect?:(id:string)=>void;onSourceSelect?:(id:string)=>void}
const EMPTY_FILTERS:InvestigationFilters={};
const categories:{value:AtlasCaseCategory;label:string}[]=[{value:'case',label:'Reviewed cases'},{value:'allegation',label:'Allegation records'},{value:'finding',label:'Findings'},{value:'proceeding',label:'Proceedings'}];
export function AtlasCaseFeed({registry,filters=EMPTY_FILTERS,onRecordSelect,onRelationshipSelect,onSourceSelect}:AtlasCaseFeedProps) {
 const id=useId(),[category,setCategory]=useState<AtlasCaseCategory|'all'|'alleged-links'|'financial-context'>('all'),[limit,setLimit]=useState(6);
 const feed=useMemo(()=>getAtlasCaseFeed(registry,filters),[registry,filters]);
 const alleged=useMemo(()=>getAtlasAllegedLinks(registry,filters),[registry,filters]);
 const financial=useMemo(()=>getAtlasFinancialContext(registry,filters),[registry,filters]);
 const nodes=useMemo(()=>new Map(registry.entities.map(row=>[row.id,row])),[registry.entities]);
 const entries=category==='financial-context'?financial.entries.map(entry=>({...entry,category:'financial context'})):category==='all'?feed.entries:feed.entries.filter(entry=>entry.category===category),page=entries.slice(0,limit);
 return <section className="atlas-case-feed" aria-labelledby={id}><header><div><span className="atlas-eyebrow">Evidence in this view</span><h2 id={id}>Cases, allegations & findings</h2></div><span className="atlas-record-count">{feed.total.toLocaleString()} records</span></header>
  <div className="atlas-feed-tabs" aria-label="Case record type"><button type="button" aria-pressed={category==='all'} onClick={()=>setCategory('all')}>All records {feed.total}</button>{categories.map(item=><button key={item.value} type="button" aria-pressed={category===item.value} onClick={()=>setCategory(item.value)}>{item.label} <span>{feed.counts[item.value]}</span></button>)}<button type="button" aria-pressed={category==='alleged-links'} onClick={()=>setCategory('alleged-links')}>Alleged links <span>{alleged.total}</span></button>{financial.total>0&&<button type="button" aria-pressed={category==='financial-context'} onClick={()=>setCategory('financial-context')}>Financial context <span>{financial.total}</span></button>}</div>
  <p className="atlas-feed-method">{category==='alleged-links'?alleged.interpretation:category==='financial-context'?financial.interpretation:<>{feed.interpretation} {feed.undated} have unknown event dates. {feed.national} describe Indian national context. {feed.international} include international context.</>}</p>
  {category!=='alleged-links'&&<ol className="atlas-case-list">{page.map(({record,category,placement})=><li key={record.id} data-case-id={record.id}><div className="atlas-case-meta"><span data-tier={record.tier}>{category} · {record.tier}</span><time>{investigationRelationshipDate(record)}</time></div><button type="button" className="atlas-case-title" onClick={()=>onRecordSelect?.(record.id)}>{record.title}<span aria-hidden="true">↗</span></button><p>{record.summary}</p>{placement==='entity-association'&&<p className="atlas-placement-note">Shown through an entity associated with this state; this is not a finding about the location of the case.</p>}<div className="atlas-case-footer"><span>{record.status} {record.statusAsOf&&`· ${record.statusAsOf}`}</span>{record.sourceIds[0]&&<button type="button" onClick={()=>onSourceSelect?.(record.sourceIds[0])}>Source record</button>}</div></li>)}</ol>}
  {category==='alleged-links'&&<ol className="atlas-case-list atlas-alleged-list">{alleged.entries.slice(0,limit).map(({relationship:edge,placement})=><li key={edge.id} data-alleged-link-id={edge.id}><div className="atlas-case-meta"><span data-tier="alleged">Alleged link · {edge.namespace==='legacy'?'inherited citation':'retained assertion'}</span><time>{investigationRelationshipDate(edge)}</time></div><button type="button" className="atlas-case-title" onClick={()=>onRelationshipSelect?.(edge.id)}>{nodes.get(edge.from)?.label} → {nodes.get(edge.to)?.label}<span aria-hidden="true">↗</span></button><p><strong>{edge.label}</strong> {edge.summary}</p>{placement==='entity-association'&&<p className="atlas-placement-note">The selected place is an entity association. The location of the alleged conduct is not established by this placement.</p>}<div className="atlas-case-footer"><span>{edge.status} · {edge.statusAsOf??'Status date unknown'} · {edge.responseIds.length} linked responses</span><button type="button" onClick={()=>onSourceSelect?.(edge.sourceIds[0])}>Source record ({edge.sourceIds.length})</button></div></li>)}</ol>}
  {category==='alleged-links'&&!alleged.total&&<p className="atlas-empty">No retained alleged links match these filters. This does not establish absence of allegations.</p>}
  {category!=='alleged-links'&&!entries.length&&<p className="atlas-empty">No supported records of this type match the selected place, sector and dates. This is a coverage gap, not evidence that no cases exist.</p>}
  {(category==='alleged-links'?alleged.total>limit:entries.length>page.length)&&<button className="atlas-load-more" type="button" onClick={()=>setLimit(value=>value+10)}>Show more · {category==='alleged-links'?Math.min(limit,alleged.total):page.length} of {category==='alleged-links'?alleged.total:entries.length}</button>}
 </section>;
}
export function AtlasPolicyTimeline({registry,filters=EMPTY_FILTERS,onRecordSelect}:AtlasCaseFeedProps) {
 const id=useId(),records=useMemo(()=>getAtlasPolicyTimeline(registry,filters),[registry,filters]);
 return <section className="atlas-policy-timeline" aria-labelledby={id}><header><span className="atlas-eyebrow">6 October 2011 — 6 October 2026</span><h2 id={id}>Policy & ownership timeline</h2><p>Each entry retains the instrument's date, scope and documented consequences.</p></header><ol>{records.map(record=><li key={record.id}><time>{record.fromDate??record.toDate??'Date unknown'}</time><button type="button" onClick={()=>onRecordSelect?.(record.id)}>{record.title}</button><p>{record.summary}</p><small>{record.status} · {record.sourceIds.length} source{record.sourceIds.length===1?'':'s'}</small></li>)}</ol>{!records.length&&<p className="atlas-empty">No retained policy-change record matches this view.</p>}</section>;
}
