import { useEffect, useId, useRef, useState, type RefObject } from 'react';
import type { InvestigationRegistry } from '../../data/investigation';
import { exportAtlasEvidence, getAtlasEvidenceClosure, type AtlasSelection } from '../../data/atlasInvestigation';
import { investigationRelationshipDate } from './graphHelpers';
import './atlas-network.css';
export interface AtlasEvidencePopoverProps {registry:InvestigationRegistry;selection:AtlasSelection|null;onClose:()=>void;onEntitySelect?:(id:string)=>void;onRelationshipSelect?:(id:string)=>void;onRecordSelect?:(id:string)=>void;onSourceSelect?:(id:string)=>void;returnFocusRef?:RefObject<HTMLElement>}
export function AtlasEvidencePopover({registry,selection,onClose,onEntitySelect,onRelationshipSelect,onRecordSelect,onSourceSelect,returnFocusRef}:AtlasEvidencePopoverProps) {
 const titleId=useId(),container=useRef<HTMLElement>(null),[expanded,setExpanded]=useState(false);
 useEffect(()=>{setExpanded(false);if(!selection)return;const previous=document.activeElement as HTMLElement|null;container.current?.focus();return ()=>{if(previous?.isConnected&&previous!==document.body&&previous!==document.documentElement)previous.focus();else returnFocusRef?.current?.focus();};},[selection?.kind,selection?.id]);
 if(!selection)return null;
 const row=selection.kind==='entity'?registry.entities.find(row=>row.id===selection.id):selection.kind==='relationship'?registry.relationships.find(row=>row.id===selection.id):registry.records.find(row=>row.id===selection.id);
 if(!row)return <aside className="atlas-evidence-popover" role="dialog" aria-labelledby={titleId}><button onClick={onClose}>Close</button><h2 id={titleId}>Record unavailable</h2><p>This exact identifier is not retained: {selection.id}</p></aside>;
 const closure=getAtlasEvidenceClosure(registry,[selection]),edge=selection.kind==='relationship'?registry.relationships.find(item=>item.id===row.id):undefined,record=selection.kind==='record'?registry.records.find(item=>item.id===row.id):undefined,entity=selection.kind==='entity'?registry.entities.find(item=>item.id===row.id):undefined;
 const direct=entity?registry.relationships.filter(item=>item.from===entity.id||item.to===entity.id):[];
 const responses=closure.records.filter(item=>closure.relationships.some(edge=>edge.responseIds.includes(item.id)));
 const download=()=>{const data=exportAtlasEvidence(registry,[selection]),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='atlas-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const item=edge??record;
 return <aside ref={container} tabIndex={-1} className={`atlas-evidence-popover${expanded?' is-expanded':''}`} role="dialog" aria-labelledby={titleId} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();onClose();}}} data-selection-id={row.id}>
  <div className="atlas-reader-toolbar"><span>{selection.kind} · {row.namespace}</span><button type="button" aria-expanded={expanded} onClick={()=>setExpanded(value=>!value)}>{expanded?'Compact':'Expand'}</button><button type="button" onClick={onClose} aria-label="Close evidence details">×</button></div>
  <h2 id={titleId}>{'title' in row?row.title:row.label}</h2><p className="atlas-reader-summary">{row.summary}</p>
  {entity&&<><p><strong>Identity basis</strong> {entity.identityBasis}</p><p>{direct.length.toLocaleString()} exact incident relationships in the retained registry.</p></>}
  {item&&<><div className="atlas-evidence-facts"><span>{item.tier}</span><span>{item.status}</span><time>{investigationRelationshipDate(item)}</time></div><p>{item.dateBasis}</p>{item.statusAsOf&&<p>Legal or documentary status as of {item.statusAsOf}.</p>}{item.amounts.map((amount,index)=><p className="atlas-money-stage" key={index}><strong>{amount.value.toLocaleString('en-IN')} {amount.currency} {amount.unit}</strong><span>{amount.stage} · {amount.period}</span></p>)}</>}
  {edge&&<div className="atlas-endpoints"><button type="button" onClick={()=>onEntitySelect?.(edge.from)}>{registry.entities.find(row=>row.id===edge.from)?.label??edge.from}</button><span>→ {edge.label} →</span><button type="button" onClick={()=>onEntitySelect?.(edge.to)}>{registry.entities.find(row=>row.id===edge.to)?.label??edge.to}</button></div>}
  {record&&<p><strong>Response and outcome</strong> {record.response}</p>}
  {responses.length>0&&<section><h3>Responses and counter-evidence</h3>{responses.map(response=><article key={response.id} data-response-id={response.id}><button className="atlas-text-link" type="button" onClick={()=>onRecordSelect?.(response.id)}>{response.title}</button><p>{response.summary}</p><p>{response.response}</p><small>{response.status} · {response.statusAsOf??'Status date unknown'}</small></article>)}</section>}
  <section><h3>Source record{closure.sources.length!==1?'s':''}</h3>{(expanded?closure.sources:closure.sources.slice(0,4)).map(source=><article className="atlas-source-row" key={source.id}>{onSourceSelect?<button type="button" className="atlas-text-link" onClick={()=>onSourceSelect(source.id)}>{source.title}</button>:<a href={source.url} target="_blank" rel="noopener noreferrer">{source.title} ↗</a>}<small>{source.publisher} · {source.publishedAt??'Publication date unknown'}</small><p>{source.locator}</p>{source.limitations.length>0&&<details><summary>Source limitations</summary>{source.limitations.map(text=><p key={text}>{text}</p>)}</details>}<a href={source.url} target="_blank" rel="noopener noreferrer">Open source ↗</a></article>)}{!expanded&&closure.sources.length>4&&<button type="button" onClick={()=>setExpanded(true)}>Show all {closure.sources.length} sources</button>}</section>
  <details open={expanded}><summary>Geography, qualifications and linked evidence</summary>{row.geography.map((geo,index)=><p key={index}><strong>{geo.basis}</strong> {geo.note}</p>)}{row.limitations.map(text=><p key={text}>{text}</p>)}{item?.alternativeExplanations.map(text=><p key={text}><strong>Alternative explanation</strong> {text}</p>)}{item?.falsifier&&<p><strong>Evidence that would change this reading</strong> {item.falsifier}</p>}{(entity?direct:closure.relationships).map(edge=><button type="button" className="atlas-related-edge" key={edge.id} onClick={()=>onRelationshipSelect?.(edge.id)}>{edge.label}<small>{edge.tier} · {investigationRelationshipDate(edge)}</small></button>)}</details>
  <button type="button" className="atlas-export-evidence" onClick={download}>Export evidence + linked responses ({closure.records.length} records)</button><small className="atlas-reader-id">{row.id}</small>
 </aside>;
}
