import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import ts from 'typescript';
import {assemblePublicWorks,classifyBuyer,IDENTITY_CROSSWALK,validateRawResearch} from './assemble.mjs';
import {validatePublicWorks,validateEvidenceManifest} from './validate.mjs';
const data=JSON.parse(readFileSync(new URL('../../src/data/public-works-research.json',import.meta.url),'utf8'));
const source=readFileSync(new URL('../../src/data/publicWorks.ts',import.meta.url),'utf8').replace("import research from './public-works-research.json';",`const research=${JSON.stringify(data)};`);
const compiled=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.ES2020}}).outputText;
const works=await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
const clone=()=>structuredClone(data);

test('source joins, graph endpoints, sector denominators and retained input hashes validate',()=>{assert.deepEqual(validatePublicWorks(data),[]);assert.equal(data.states.length,36);assert.equal(data.coverage.length,9);assert.ok(data.buyers.length>100);});
test('assembly is deterministic and re-derives every emitted field from retained inputs',()=>{assert.deepEqual(assemblePublicWorks(),data);assert.deepEqual(assemblePublicWorks(),assemblePublicWorks());});
test('numeric tampering and input hash changes cannot pass as source-backed metrics',()=>{const broken=clone();broken.buyers[0].singleBidder+=1;broken.dataset.inputs[0].sha256='wrong';const errors=validatePublicWorks(broken);assert.ok(errors.some(error=>error.includes('differs from retained aggregate')));assert.ok(errors.some(error=>error.includes('Input hash mismatch')));});
test('sector lenses classify buyer labels and exclude opaque state codes and ambiguous purpose words',()=>{assert.deepEqual(classifyBuyer('West Bengal / PWD','state'),[]);assert.deepEqual(classifyBuyer('Heavy Water Board','central'),[]);assert.deepEqual(classifyBuyer('Inland Waterways Authority of India,MoS','central'),[]);assert.deepEqual(classifyBuyer('Border Roads Organisation','central').map(row=>row.sector),['roads','military']);assert.deepEqual(classifyBuyer('Union Public Service Commission','central').map(row=>row.sector),['recruitment']);});
test('state navigation keeps labelled national buyer context and rejects unknown state codes',()=>{assert.ok(works.getPublicWorksBuyers({stateCode:'KA',sector:'roads'}).length>0);assert.ok(works.getPublicWorksBuyers({stateCode:'KA'}).every(row=>row.scope==='national'&&row.stateCodes.length===0));assert.deepEqual(works.getPublicWorksSources({stateCode:'IMAGINARY'}),[]);});
test('locality search cannot borrow a buyer name, publisher address or full-text topic',()=>{assert.deepEqual(works.getPublicWorksBuyers({place:'Delhi'}),[]);assert.deepEqual(works.getPublicWorksSources({place:'Imaginary Village 999'}),[]);assert.ok(works.getPublicWorksBuyers({q:'Delhi'}).length>0);assert.ok(works.getPublicWorksDiscovery({place:'Imaginary Village 999',q:'no matching source',sector:'roads'}).length>0);});
test('all local matches belong to selected state and declared locality metadata',()=>{for(const row of data.localities){const matches=works.getPublicWorksSources({place:row.name,stateCode:row.stateCode});assert.ok(matches.every(source=>source.localityIds.some(id=>data.localities.some(place=>place.id===id&&place.stateCode===row.stateCode))));}});
test('source type selection propagates through provenance joins when requested',()=>{assert.ok(works.getPublicWorksBuyers({type:'dataset'}).length>0);assert.deepEqual(works.getPublicWorksBuyers({type:'news'}),[]);assert.ok(works.getPublicWorksSources({type:'dataset'}).every(row=>row.type==='dataset'));});
test('graph identity failures and unsupported locality joins are rejected',()=>{if(!data.entities.length)return;const broken=clone();broken.entities[0].resolved=false;const edge=broken.relationships.find(row=>row.from===broken.entities[0].id||row.to===broken.entities[0].id);if(edge)assert.ok(validatePublicWorks(broken).some(error=>error.includes('unresolved identity')));const orphan=clone();orphan.relationships[0].to='not-real';assert.ok(validatePublicWorks(orphan).some(error=>error.includes('unknown graph endpoint')));});
test('source ledger export retains provenance and guards spreadsheet formulas',()=>{const rows=[{...data.sources[0],title:'=HYPERLINK("https://example.com")',summary:'Line one, line two\nThird line',publishedAt:null}];const csv=works.publicWorksSourcesCsv(rows);assert.match(csv,/publishedAt,period,retrievedAt,retrievalStatus,locator/);assert.match(csv,/"'=HYPERLINK\(""https:\/\/example.com""\)"/);assert.match(csv,/Line one, line two\nThird line/);assert.ok(csv.includes(data.sources[0].url));});
test('legal chronology rejects unknown or invalid dates and distinguishes temporal eligibility from breach',()=>{const rule={effectiveFrom:'2024-06-21',effectiveTo:'2025-12-31'};assert.equal(works.assessRuleDate(rule,'2024-06-20'),'predates-rule');assert.equal(works.assessRuleDate(rule,'2024-06-21'),'within-recorded-period');assert.equal(works.assessRuleDate(rule,'2026-01-01'),'after-rule');assert.equal(works.assessRuleDate({...rule,effectiveFrom:null},'2025-01-01'),'date-unknown');assert.equal(works.assessRuleDate(rule,'2025-02-30'),'date-unknown');assert.equal(works.assessRuleDate(rule,'2025-03'),'date-unknown');});
const a={id:'record-1',contractId:'contract-1',authorityId:'authority-1',locationId:'district-1',assetId:'bridge-1',scopeId:'deck-resurfacing-BOQ-1',periodStart:'2024-01-01',periodEnd:'2024-03-31',stage:'award'};
const b={...a,id:'record-2',contractId:'contract-2',periodStart:'2024-02-01'};
test('exact asset, authority, geography, work scope, stage and overlapping periods produce a review question only',()=>{const result=works.assessRepeatedWork([a,b]);assert.equal(result.comparisons.length,1);assert.equal(result.comparisons[0].status,'review-overlap');assert.match(result.conclusion,/not proof/);});
test('repeat-work gate excludes notices, cancelled tenders, corrigenda and duplicate extracts',()=>{const rows=[a,{...b,stage:'notice'},{...b,id:'cancelled',cancelled:true},{...b,id:'correction',correctsId:a.id},{...b,id:'amendment',stage:'amendment'},a];const result=works.assessRepeatedWork(rows);assert.equal(result.eligible,1);assert.equal(result.comparisons.length,0);assert.deepEqual(result.excluded.map(row=>row.reason),['notice-is-not-work','cancelled','correction-or-amendment','correction-or-amendment','duplicate-extract']);});
test('different lots, contract stages, locations, authorities and non-overlapping maintenance periods do not become repeated-work flags',()=>{for(const patch of [{contractId:a.contractId},{authorityId:'other-authority'},{locationId:'other-district'},{assetId:'bridge-2'},{scopeId:'structural-strengthening'},{stage:'payment'},{periodStart:'2025-01-01',periodEnd:'2025-03-31'}])assert.equal(works.assessRepeatedWork([a,{...b,...patch}]).comparisons.length,0,JSON.stringify(patch));});
test('missing identity keys and invalid calendar dates block comparison without throwing',()=>{for(const patch of [{authorityId:null},{locationId:null},{assetId:null},{scopeId:null},{contractId:null},{periodStart:'2024-02-30'},{periodEnd:'2024-99-31'},{periodStart:'2024-04-01'}]){const result=works.assessRepeatedWork([a,{...b,...patch}]);assert.equal(result.comparisons.length,0);assert.equal(result.excluded.length,1);}});
test('existing recurring-name aggregate retains its actual denominator and cannot become physical repeat-work evidence',()=>{assert.equal(data.dataset.repeatWork.status,'not-assessable');assert.equal(data.dataset.repeatWork.repeatPairCount,7777);assert.equal(data.dataset.repeatWork.pairDenominator,74940);assert.equal(data.dataset.verifiedRows,0);assert.equal(data.dataset.verificationSample,40);assert.equal(data.dataset.rawRows-data.dataset.removedRows,data.dataset.afterDedupRows);});
test('missing source tiers, retrieval metadata and identity statuses fail closed',()=>{
 const broken=clone();delete broken.sources[0].tier;delete broken.sources[0].retrievalStatus;delete broken.entities[0].resolved;broken.sources[0].retrievedAt='2025-02-30';
 const errors=validatePublicWorks(broken);for(const field of ['source tier invalid','retrievalStatus required','resolved status required','retrieval date invalid'])assert.ok(errors.some(error=>error.includes(field)),field);
});
test('malformed reference arrays produce validation errors instead of bypassing or throwing',()=>{for(const patch of [{sourceIds:'one-source'},{sectors:null},{localityIds:{}},{amounts:'₹100 crore'}]){const broken=clone();Object.assign(broken.cases[0],patch);assert.ok(validatePublicWorks(broken).some(error=>/array/.test(error)));}});
test('an allegation cannot borrow an unrelated response from the same actor',()=>{
 const broken=clone();const edge=broken.relationships[0];edge.tier='alleged';
 broken.relationships.push({...edge,id:'test-unrelated-response',kind:'response',from:edge.to,to:edge.from,tier:'documented'});
 assert.ok(validatePublicWorks(broken).some(error=>/explicitly linked visible response/.test(error)));
 broken.relationships.at(-1).respondsTo=edge.id;
 assert.ok(!validatePublicWorks(broken).some(error=>/explicitly linked visible response/.test(error)));
});
test('amount arrays require each amount to retain currency, unit, accounting stage and period',()=>{for(const field of ['currency','unit','stage','period']){const broken=clone();broken.cases[0].amounts=[{value:1,currency:'INR',unit:'crore',stage:'estimate',period:'FY2024'}];delete broken.cases[0].amounts[0][field];assert.ok(validatePublicWorks(broken).some(error=>/amount series requires/.test(error)));}});
test('archived evidence hashes and sizes are verified independently of source metadata',()=>{
 const path='research/raw/cppp/rates.json';const bytes=readFileSync(new URL(`../../${path}`,import.meta.url));const manifest=[{path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')}];
 assert.deepEqual(validateEvidenceManifest(manifest),[]);manifest[0].bytes+=1;assert.ok(validateEvidenceManifest(manifest).some(error=>/hash\/size mismatch/.test(error)));manifest[0].path='research/raw/public-works/missing.pdf';assert.ok(validateEvidenceManifest(manifest).some(error=>/Missing evidence artifact/.test(error)));
});
test('CSV formulas preceded by spaces and control characters are guarded',()=>{for(const title of ['  =SUM(1,2)','\t+1+1','\r@command','   -2+4'])assert.ok(works.publicWorksSourcesCsv([{...data.sources[0],title}]).includes(`"'${title}"`));});

test('network search resolves endpoint labels without using them as geographic evidence',()=>{const edge=data.relationships[0];const endpoint=data.entities.find(row=>row.id===edge.from);assert.ok(works.getPublicWorksNetwork({q:endpoint.label}).edges.some(row=>row.id===edge.id));assert.deepEqual(works.getPublicWorksNetwork({place:endpoint.label}).edges,[]);});

test('only four independently reviewed exact identities are reconciled, without orphaning edges or merging groups',()=>{for(const mapping of IDENTITY_CROSSWALK){assert.ok(data.entities.some(row=>row.mergedIds?.includes(mapping.from)));assert.ok(!data.entities.some(row=>row.id===mapping.from));const target=data.entities.find(row=>row.id===mapping.to);assert.ok(target);assert.ok(target.sourceIds.length>=2);assert.ok(data.relationships.every(edge=>edge.from!==mapping.from&&edge.to!==mapping.from));}if(data.entities.some(row=>row.id==='pwg-irb-group-fy24'))assert.ok(data.entities.some(row=>row.id==='pwg-irb-idl'));});

test('raw geography cannot silently default a local record to national context',()=>{const complete={id:'test-row',sectors:['roads'],scope:'state',stateCodes:['WB'],localityIds:[]};for(const key of ['scope','stateCodes','localityIds']){const row={...complete};delete row[key];assert.ok(validateRawResearch({relationships:[row]}).some(error=>error.includes(key)));}assert.ok(!works.getPublicWorksNetwork({stateCode:'UP',sector:'electricity'}).edges.some(edge=>edge.stateCodes.includes('WB')));assert.ok(!works.getPublicWorksNetwork({stateCode:'KA',sector:'water'}).edges.some(edge=>edge.stateCodes.includes('WB')));assert.ok(!works.getPublicWorksCases({stateCode:'KA',sector:'water'}).some(row=>row.stateCodes.includes('WB')));});
