import json, pathlib, hashlib, re

ROOT=pathlib.Path(__file__).resolve().parent
OUT=ROOT.parent/'procurement.json'
SNAPSHOT='2026-10-06'
RETRIEVED='2026-10-07'
route='/follow-the-money'
data={k:[] for k in ['sources','entities','relationships','records','localities']}
def source(id,title,url,publisher,date,locator,summary,artifacts,tier='documented',limitations=None):
    data['sources'].append(dict(id=id,title=title,url=url,publisher=publisher,publishedAt=date,retrievedAt=RETRIEVED,locator=locator,summary=summary,tier=tier,limitations=(limitations or [])+['Retained evidence: '+', '.join(artifacts)]))
def geo(src,states=None,note=None,basis='project-location'):
    return [dict(scope='multi-state' if states and len(states)>1 else 'state' if states else 'national',stateCodes=states or [],localityIds=[],basis=basis if states else 'national-context',note=note or ('Project geography; not registered office or all activities of the entity.' if states else 'National institution or project-financing context; no local payment allocation inferred.'),sourceIds=src)]
def dims(src,states=None,layers=None,domains=None,limitations=None):
    return dict(sourceIds=src,geography=geo(src,states),layers=layers or ['procurement','funding'],domains=domains or ['public-works','capital','finance'],route=route,limitations=limitations or [])
def entity(id,label,type,src,summary,states=None,canonical=None,identity=None):
    d=dict(id=id,label=label,type=type,resolved=True,identityBasis=identity or 'Exact named legal entity or expressly identified project/facility in cited primary source; no contractor-string fuzzy merge.',summary=summary,**dims(src,states,['organisations']))
    if canonical:d['canonicalId']=canonical
    data['entities'].append(d)
def amount(v,stage,period,currency='INR',unit='crore'):return dict(value=v,currency=currency,unit=unit,stage=stage,period=period)
def edge(id,a,b,kind,label,src,summary,case,states=None,amts=None,start=None,end=None,status='documented-historical-transaction',asof=None,tier='documented',responses=None,alternatives=None,falsifier=None,limitations=None,dateBasis=None,layers=None,domains=None):
    data['relationships'].append(dict(id=id,from_=a,to=b,kind=kind,label=label,tier=tier,status=status,statusAsOf=asof,fromDate=start,toDate=end,dateBasis=dateBasis or ('Exact dates from the cited record.' if start or end else 'Exact event day not established; consult the stated period.'),summary=summary,alternativeExplanations=alternatives or [],falsifier=falsifier,responseIds=responses or [],recordIds=[case],amounts=amts or [],**dims(src,states,layers,domains,limitations)))
    data['relationships'][-1]['from']=data['relationships'][-1].pop('from_')
def record(id,title,summary,kind,src,entities,relationships,period,response,alternatives,falsifier,states=None,amts=None,status='bounded-source-backed-case',asof=None,start=None,end=None,tier='documented',limitations=None,layers=None,domains=None):
    data['records'].append(dict(id=id,title=title,summary=summary,kind=kind,tier=tier,status=status,statusAsOf=asof,fromDate=start,toDate=end,dateBasis='Dates are independently supported event or publication dates; month-only events remain in the period text.',entityIds=entities,relationshipIds=relationships,period=period,response=response,alternativeExplanations=alternatives,falsifier=falsifier,amounts=amts or [],**dims(src,states,layers,domains,limitations)))

source('upeida-awards','UPEIDA: four Ganga Expressway selected bidders and lowest-grant bids','https://upeida.up.gov.in/en/page/ganga-expressway','UPEIDA',None,'Selected-bidders table; GO.2648/77-3-21-90(M)/21 and letters of award dated 16 December 2021','IRB selected for Group I; Adani Enterprises for Groups II–IV. Criterion is lowest public grant, not lowest total project cost.',['source-01.body','source-01.receipt.json'])
source('irb-close','IRB: Group I financial closure','https://www.irb.co.in/home/wp-content/uploads/2022/06/PressRelease_FC-GangaExpresswayBOT_Final_16thJune.2022.pdf','IRB Infrastructure Developers Limited','2022-06-16','pp.1–2, funding mix','₹2,659 crore lender financing, ₹2,133 crore equity/related contribution and ₹1,746 crore VGF for ₹6,538 crore project.',['irb-financial-closure.body','irb-financial-closure.receipt.json'],limitations=['Company disclosure, not bank drawdown ledger. Consortium members not named.'])
source('irb-gic','IRB: equity raise and project-manager consideration','https://www.irb.co.in/home/wp-content/uploads/2022/10/PressRelease_GICinvestmentInGangaExpressway_19thOctober.2022.pdf','IRB Infrastructure Developers Limited','2022-10-19','pp.1–2, equity contributions and EPC/O&M consideration','First equity raise reported complete; separate contractual EPC and lifetime O&M consideration to IRB.',['irb-gic-investment.body','irb-gic-investment.receipt.json'],limitations=['₹5,279 crore EPC and ₹5,180 crore O&M are contractual consideration plus taxes over different periods, not payments already received. GIC affiliate is generic in this release.'])
source('irb-related-party','IRB Trust: MBEL acquisition approval and related-party terms','https://www.irbinfratrust.co.in/home/wp-content/uploads/2024/12/IntimationApprovalforexecutiondefagreementsGangaProjectIRBITsigned.pdf','MMK Toll Road Private Limited, investment manager to IRB Infrastructure Trust','2024-12-14','Annexure I: shareholding, related-party status, consideration','MBEL 51% IRB/49% Anahera; unitholders approved related-party transaction on 6 February 2024; issuer says arm’s length.',['source-04.body','source-04.receipt.json'],limitations=['Arm’s-length language is an issuer assertion. Approval is distinct from closing and independent valuation fairness.'])
source('irb-acquisition-close','IRB Trust: completion of MBEL equity and debenture purchase','https://www.irbinfratrust.co.in/home/wp-content/uploads/2024/12/UpdateonClosingInvestmentintoMBELSecurities.pdf','MMK Toll Road Private Limited, investment manager to IRB Infrastructure Trust','2024-12-27','Single-page closing disclosure','80.4% of equity and 80.4% of debentures purchased for combined consideration ₹1,714.92 crore.',['source-05.body','source-05.receipt.json'],limitations=['No seller-level split or proof of government reimbursement. Count aggregate consideration once.'])
source('cci-mbel','CCI approval: IRB Trust acquisition in Meerut Budaun Expressway Limited','https://www.cci.gov.in/combination/press-release/details/399/0','Competition Commission of India','2024-06-04','Press-release landing page, date and title','Competition regulator approved proposed acquisition.',['source-06.body','source-06.receipt.json'],limitations=['Approval of combination is not certification of price fairness, construction quality or procurement integrity.'])
source('irb-toll','IRB Trust: Ganga Group I toll collection commenced','https://www.irbinfratrust.co.in/home/wp-content/uploads/2026/05/UpdateGangaExpresswayIRBIT.pdf','MMK Toll Road Private Limited, investment manager to IRB Infrastructure Trust','2026-05-17','Single-page disclosure','MBEL commenced toll collection effective 17 May 2026, after provisional certificate/trial operations.',['irb-toll-start.body','irb-toll-start.receipt.json'])
source('irb-ar25','IRB Infrastructure Trust annual report 2024–25','https://www.irbinfratrust.co.in/home/wp-content/uploads/2025/06/IRB-Infra-Trust-AR-2024-25.pdf','IRB Infrastructure Trust',None,'Printed pp.16–17, acquisition and borrowing maturity profile','Confirms acquisition; ₹26,590 million MBEL financing row expressly includes pending disbursement.',['source-07.body','source-07.receipt.json'],limitations=['Do not interpret the maturity-profile amount as fully drawn debt: footnote says including pending disbursement.'])
source('adani-close','Adani Enterprises: Ganga Groups II–IV financing closure filing','https://www.adanienterprises.com/-/media/Project/Enterprises/Investors/Corporate-Announcement/FY-2021-22-Announcements/FY-2022-23-Announcement/454-Ganga-Expressway-Financial-Closure29092022.pdf','Adani Enterprises Limited','2022-09-29','pp.1–3: three SPVs, per-SPV financing and SBI underwriting','Exact concession SPVs, their group affiliation and stage-separated debt/equity/VGF funding. SBI underwrites entire debt requirement.',['source-08.body','source-08.receipt.json'],limitations=['Lender underwriting and company equity commitment are not bank disbursement, public grant release or paid contractor bills. Historical ownership at filing date.'])
source('adani-ar26','Adani Enterprises FY2025–26 directors’ report: project update','https://www.adanienterprises.com/digital-reports/enterprises/2026/pdf/directors-report.pdf','Adani Enterprises Limited',None,'Roads: projects completed, Ganga Expressway inaugurated 29 April 2026','Later issuer update records inauguration of Ganga Expressway.',['adani-2026-directors.body','adani-2026-directors.receipt.json'],limitations=['Inauguration is not final financial reconciliation or completion of every contractual obligation.'])
source('nhsrcl-awards','NHSRCL official awarded-tender register: first displayed 20 rows','https://nhsrcl.in/index.php/en/tenders/awarded-tenders','National High Speed Rail Corporation Limited',None,'Row8 MAHSR - C-4; row16 MAHSR-C-6; first displayed20 rows retained','C4 awarded to Larsen & Toubro with separate INR, JPY and USD components.',['fetch-nhsrcl.json','nhsrcl-register-20rows.json','nhsrcl-awards.receipt.json'],limitations=['Direct original fetch returned HTTP503; retained full Exa-indexed official page text is the content evidence. This page slice is not the complete tender population.'])
source('nhsrcl-c4-sign','NHSRCL: C4 contract agreement signing','https://nhsrcl.in/en/media/press-release/nhsrcl-signs-contract-agreement-countrys-biggest-infrastructure-contract-design','National High Speed Rail Corporation Limited','2020-11-26','Opening paragraphs; tender chronology; contract duration','L&T signed 237km civil package; technical bids23Sep, financial bids19Oct, LOA28Oct2020.',['fetch-nhsrcl.json','source-09.receipt.json'],limitations=['Direct host503; indexed official content retained. Scheduled duration is not completion certification.'])
source('nhsrcl-process','NHSRCL: account of C4 award in35 days','https://www.nhsrcl.in/en/media/blog/nhsrcl-awarded-indias-largest-infrastructure-contract-35-days','National High Speed Rail Corporation Limited',None,'C4 process narrative, over50 engineers and review arrangement','Authority attributes speed to parallel multidisciplinary coordination and consultant support.',['fetch-nhsrcl.json','source-10.receipt.json'],limitations=['Agency account of its own process, not an independent compliance audit. This is independently dated award chronology, not the tender-corpus comparison field.'])
source('nhsrcl-equity','NHSRCL: public ownership and JICA financing terms','https://nhsrcl.in/en/media/press-release/information-nhsrcl','National High Speed Rail Corporation Limited','2019-12-02','Ownership and financing paragraph','Government of India50%, Gujarat25%, Maharashtra25%; described project loan terms.',['fetch-updates.json','nhsrcl-ownership.receipt.json'],limitations=['Authorized capital is not equity paid in. These historical participation ratios are not inferred payment amounts. Direct host503.'])
source('jica-c4','JICA: C4 construction milestone and executing agency','https://www.jica.go.jp/english/overseas/india/information/press/2021/press211125_01.html','Japan International Cooperation Agency','2021-11-25','Second paragraph and final project-funding paragraph','Lender confirms L&T/NHSRCL C4 agreement26Nov2020 and whole-project loan support.',['jica-c4.body','jica-c4.receipt.json'])
source('jica-tranche5','JICA: MAHSR tranche5 signed with Government of India','https://www.jica.go.jp/english/overseas/india/information/press/2023/20231221.html','Japan International Cooperation Agency','2023-12-21','Opening two paragraphs','JPY400bn tranche5; cumulative JPY1,050bn project commitment. NHSRCL executing agency.',['source-11.body','source-11.receipt.json'],limitations=['Commitment, not expenditure; cumulative figure already includes tranche5. Loan is to Government of India for whole project, not direct corporate borrowing by L&T.'])
source('cag-polavaram','CAG Polavaram Report4/2025, ChapterIII','https://cag.gov.in/uploads/download_audit_report/2025/Chapter-III-069aaedf1e98285.20041628.pdf','Comptroller and Auditor General of India','2026-03-06','Paras3.2.2.1–3.2.3, printed pp.57–59; footnotes147–148; associated government replies','Material advance, REC financing, premature equipment procurement and dated government replies.',['fetch-polavaram-ch3-full.json','polavaram-chapter3.receipt.json','cag-chapter3-mirror.receipt.json'],limitations=['Official indexed text retained; direct cag and saiindia PDF requests503. Some other paragraphs have dropped number glyphs; case uses only fully legible figures in selected paragraphs. Audit findings are not criminal judgments; report number2025 differs from publication6Mar2026.'])
source('cag-publication','CAG Andhra Pradesh audit-report listing: Polavaram report','https://cag.gov.in/ag/andhra-pradesh/en/audit-report','Comptroller and Auditor General of India','2026-03-06','Report4of2025 Polavaram entry,6March2026','Establishes publication date independently from report year.',['search-polavaram-publication.json','cag-publication.receipt.json'],limitations=['Date from indexed official listing; direct host503.'])
source('meil-moa','MEIL company memorandum in official EGM notice','https://meil.in/sites/default/files/2025-07/EGM_notice_2025.pdf','Megha Engineering & Infrastructures Limited',None,'Memorandum clauseI legal name and clauseII Telangana registered office','Exact corporate legal name corroborates CAG’s named contractor.',['meil-legal.body','meil-legal.receipt.json'],limitations=['Historic memorandum subscriber names are not treated as current shareholders. No name-only tender-corpus merge.'])
source('polavaram-answer','Lok Sabha question3007: funding for Polavaram PhaseI','https://sansad.in/getFile/lsapps/loksabhaquestions/annex/188/AU3007_dETnz9.pdf','Ministry of Jal Shakti','2026-08-06','Answer(a)–(d), especially(c)','Central PhaseI grant excludes powerhouse; powerhouse cost borne by Andhra Pradesh. Main-dam/LA/R&R milestone targetJune2027.',['polavaram-answer-2026.body','polavaram-answer-2026.receipt.json'],limitations=['Does not adjudicate or settle CAG’s separate material-advance/equipment findings. Grant releases to project are not traced to MEIL bills.'])
source('zojila-notice','CPPP original notice2020_NHIDC_564017_1','https://eprocure.gov.in/eprocure/app?component=%24DirectLink&page=FrontEndViewTender&service=direct&sp=STApYhUmN%2FisSihquRdmDRw%3D%3D','Central Public Procurement Portal',None,'TenderID2020_NHIDC_564017_1; reference NHIDCL/JnK-Ladakh/ Zojila/NH-01/2020','Original notice fields accessible, estimate₹4,429.83crore; exact corpus-ID query returns0.',['source-14.body','source-14.receipt.json','zojila-exact-query.json'],limitations=['Notice estimate is not award/payment. Zero exact-ID corpus hits does not establish absence of the contract.'])
source('nhidcl-zojila','NHIDCL current project-status register: Zojila','https://www.nhidcl.com/en/current-status/Jammu-Kashmir','National Highways & Infrastructure Development Corporation Limited',None,'Zojila row, award25August2020, contractor MEIL, schedule columns','Authority names MEIL for exact Zojila project and records ongoing status.',['source-13.body','source-13.receipt.json'],limitations=['Website current-status table is mutable and not a payment ledger. Financial-cost/current-schedule cells need header-aware reconciliation before interpreting variations.'])

entity('upeida','Uttar Pradesh Expressways Industrial Development Authority','authority',['upeida-awards'],'State procuring authority for four Ganga groups.',['UP'])
entity('irb','IRB Infrastructure Developers Limited','company',['irb-related-party','irb-close'],'Listed sponsor and project manager; exact legal issuer, CIN L65910MH1998PLC115967 retained on issuer site.')
entity('mbel','Meerut Budaun Expressway Limited','company',['irb-related-party'],'Ganga GroupI project company; incorporated5January2022. Earlier financial-close disclosure names private-limited form. Exact continuous project identity established by issuer acquisition disclosure.',['UP'])
entity('irbit','IRB Infrastructure Trust','trust',['irb-related-party','irb-acquisition-close'],'Private InvIT acquiring MBEL securities; distinct from IRB InvIT Fund, the public InvIT.')
entity('anahera','Anahera Investment Pte. Ltd.','company',['irb-related-party'],'Named49% MBEL shareholder before acquisition; expressly described as GIC affiliate. Do not merge with other GIC affiliates.')
entity('gic','GIC Private Limited','organisation',['irb-gic','irb-related-party'],'Singapore reserves investment manager; affiliate relationship does not mean the parent directly paid every project contribution.')
entity('mbel-loan','Ganga Group I disclosed project-finance facility','loan-facility',['irb-close'],'₹2,659crore financing package. Consortium members not individually resolved.',['UP'])
entity('cci','Competition Commission of India','regulator',['cci-mbel'],'Competition authority; approval scope limited to the proposed combination.')
entity('ael','Adani Enterprises Limited','company',['adani-close'],'Listed issuer ADANIENT/BSE512599. Historical parent of three named Ganga SPVs.',canonical='co:adani-enterprises',identity='Primary exchange filing BSE512599/NSEADANIENT exactly matches companies-by-state.json adani-enterprises; identity-only bridge.')
entity('sbi','State Bank of India','bank',['adani-close'],'Named senior-debt underwriter for three Ganga SPVs; amount source is borrower’s exchange filing.')
for id,label in [('bhrpl','Budaun Hardoi Road Private Limited'),('hurpl','Hardoi Unnao Road Private Limited'),('uprpl','Unnao Prayagraj Road Private Limited')]:entity(id,label,'company',['adani-close'],'Project-specific wholly owned AEL subsidiary at29September2022; separate legal concession company.',['UP'])
entity('lnt','Larsen & Toubro Limited','company',['nhsrcl-c4-sign','nhsrcl-awards','jica-c4'],'Legal C4 contractor; L&T Construction is its construction business, not a separately inferred contractor.',canonical='co:larsen-toubro',identity='Exact legal name in authority agreement and lender report matches roster Larsen & Toubro Limited; no merge with other L&T group companies.')
entity('nhsrcl','National High Speed Rail Corporation Limited','company',['nhsrcl-c4-sign','nhsrcl-equity'],'Public project SPV and C4 contracting authority.')
entity('jica','Japan International Cooperation Agency','lender',['jica-tranche5'],'Official development lender to Government of India for MAHSR.')
entity('goi','Government of India','government',['jica-tranche5','nhsrcl-equity'],'Sovereign borrower and NHSRCL central shareholder through Ministry of Railways.')
entity('gujarat','Government of Gujarat','government',['nhsrcl-equity'],'25% NHSRCL equity participation stated2December2019.')
entity('maharashtra','Government of Maharashtra','government',['nhsrcl-equity'],'25% NHSRCL equity participation stated2December2019.')
entity('c4','MAHSR C4 civil and building package','contract',['nhsrcl-awards','nhsrcl-c4-sign'],'Exact tender ref MAHSR - C-4, Zaroli–Vadodara237km.',['GJ'])
entity('mahsr','Mumbai–Ahmedabad High Speed Rail project','project',['jica-tranche5','jica-c4'],'Whole508km project, not synonymous with packageC4.',['GJ','MH'])
entity('apgenco','Andhra Pradesh Power Generation Corporation Limited','company',['cag-polavaram'],'PHEP contracting borrower. Separate from WRD irrigation financing.',['AP'])
entity('rec','REC Limited (Rural Electrification Corporation)','lender',['cag-polavaram'],'Named project term lender in CAG para3.2.3.')
entity('meil','Megha Engineering & Infrastructures Limited','company',['cag-polavaram','meil-moa'],'Exact second PHEP contractor in CAG footnotes147–148, corroborated legal name by company memorandum.')
entity('phep','Polavaram Hydro Electric Project','project',['cag-polavaram','polavaram-answer'],'960MW powerhouse financed by Andhra Pradesh; excludes central irrigation-grant allocation.',['AP'])
entity('cag','Comptroller and Auditor General of India','auditor',['cag-polavaram','cag-publication'],'Named public auditor; conclusions remain attributed audit observations.')
entity('andhra','Government of Andhra Pradesh','government',['cag-polavaram','polavaram-answer'],'Respondent to CAG and responsible for powerhouse financing.',['AP'])
entity('nhidcl','National Highways & Infrastructure Development Corporation Limited','authority',['zojila-notice','nhidcl-zojila'],'Zojila EPC procuring authority.')

case='irb-ganga-capital-recycling';resp='irb-response-and-outcome'
edge('irb-selected','upeida','irb','award','Selected Group I bidder: lowest grant',['upeida-awards'],'UPEIDA selected IRB with₹1,746crore grant bid; LOA16December2021.',case,['UP'],[amount(1746,'selected viability-gap grant bid; not payment','LOA16December2021')],start='2021-12-16',asof='2021-12-16',responses=[resp])
edge('mbel-concession','upeida','mbel','concession','Ganga Group I concession vehicle',['irb-related-party','irb-close'],'Exact129.7km Meerut–Budaun DBFOT concession;30years with possible6-year traffic-linked extension.',case,['UP'],asof='2024-12-14',responses=[resp])
edge('mbel-debt','mbel-loan','mbel','loan','₹2,659 crore project financing tied up',['irb-close'],'Finance commitment from unspecified consortium. 2025annual-report maturity row includes pending disbursement, so no full-drawdown inference.',case,['UP'],[amount(2659,'project debt financing tied up; drawdown unverified','16June2022')],start='2022-06-16',asof='2022-06-16',limitations=['Borrower named; individual lenders not resolved.'])
edge('irb-owns-mbel','irb','mbel','ownership','51% before securities transfer',['irb-related-party'],'Sponsor holds51% at14December2024, before closing; historical shareholding is not presented as current.',case,['UP'],asof='2024-12-14',responses=[resp])
edge('anahera-owns-mbel','anahera','mbel','ownership','49% before securities transfer',['irb-related-party'],'Named GICaffiliate holds49% at14December2024.',case,['UP'],asof='2024-12-14',responses=[resp])
edge('gic-affiliate','gic','anahera','affiliate','Expressly identified GIC affiliate',['irb-related-party'],'Anahera is expressly named as a GICaffiliate. No unsupported ultimate-ownership percentage is supplied.',case,asof='2024-12-14')
edge('mbel-epc-irb','mbel','irb','contracted','EPC project-manager consideration',['irb-gic'],'IRB says it will receive₹5,279crore plus taxes for EPC during construction. Contractual stream, not paid amount.',case,['UP'],[amount(5279,'contractual EPC consideration plus applicable taxes; receipt unverified','construction period; disclosure19October2022')],start='2022-10-19',asof='2022-10-19',responses=[resp])
edge('mbel-om-irb','mbel','irb','contracted','O&M consideration over concession',['irb-gic'],'Separate₹5,180crore plus taxes over concession; cannot be added to project capex as current expenditure.',case,['UP'],[amount(5180,'contractual O&M consideration plus applicable taxes; receipt unverified','concession period; disclosure19October2022')],start='2022-10-19',asof='2022-10-19',responses=[resp])
edge('irbit-buys-mbel','irbit','mbel','acquisition','80.4% equity and debentures acquired',['irb-acquisition-close','irb-related-party'],'Closing27December2024:₹1,714.92crore combined consideration for80.4% equity and80.4%NCD. Seller allocation between IRB and Anahera is not disclosed in this notice.',case,['UP'],[amount(1714.92,'closed aggregate securities acquisition consideration; equity+debentures counted once','27December2024')],start='2024-12-27',asof='2024-12-27',responses=[resp],limitations=['Not a public construction payment or a new award.'])
edge('cci-approves-mbel','cci','irbit','approval','Combination approved4June2024',['cci-mbel'],'Regulatory approval is recorded before closing; no finding on alleged procurement wrongdoing follows.',case,start='2024-06-04',asof='2024-06-04',layers=['legal','organisations'])
irb_edges=[r['id'] for r in data['relationships'] if r['recordIds']==[case]]
record(resp,'IRB: approval, issuer explanation and later operating status','Issuer calls related-party acquisition arm’s length and ordinary-course; CCI approved combination4June2024. Acquisition closed27December2024. MBEL commenced tolling17May2026. None of these facts establishes price fairness or a completed final account.','response',['irb-related-party','cci-mbel','irb-acquisition-close','irb-toll'],['irb','mbel','irbit','anahera','cci'],irb_edges,'6February2024 unitholder approval;4June2024CCI;27December2024closing;17May2026toll start','Issuer explanation retained; no corruption allegation is advanced by this ownership/finance trail.',['Capital recycling and project-risk sharing can explain a related-party InvIT transfer.'],'Inspect independent valuation, approved transaction agreements, consent conditions and seller bank receipts to test price and consideration allocation.',['UP'],status='dated-regulatory-and-commercial-outcomes',asof='2026-05-17',start='2024-06-04',end='2026-05-17')
record(case,'IRB Ganga: public concession, private equity and a related-party exit','A₹1,746crore lowest-grant award led to MBEL’s₹6,538crore financing plan. IRB retained EPC and O&M roles while GICaffiliate Anahera held49%. InDecember2024IRB Infrastructure Trust acquired80.4%of equity anddebentures for₹1,714.92crore combined consideration. This is a documented capital-recycling chain, not proof of a political favour.','investigation-case',['upeida-awards','irb-close','irb-gic','irb-related-party','irb-acquisition-close','cci-mbel','irb-toll','irb-ar25'],['upeida','irb','mbel','mbel-loan','anahera','gic','irbit','cci'],irb_edges,'Award16December2021;financial close16June2022;equity/EPCdisclosure19October2022;transfer27December2024;tolling17May2026','Read linked response: regulatory approval and issuer arm’s-length assertion are distinct; acquisition closed and tolling commenced. No public bill/payment ledger or seller-level consideration split was retrieved.',['An InvIT can recycle sponsor capital and spread construction/toll risks through disclosed approvals.','Foreign investment or related-party status alone does not establish undue influence.'],'Reconcile contract modifications, VGF releases, lender drawdowns, independent valuation, seller receipts and related-party EPC invoices; evidence of unfair valuation or undisclosed payments could change the assessment.',['UP'],[amount(1746,'selected VGF grant; release unverified','2021award'),amount(2659,'debt financing tied up','2022financial close'),amount(2133,'equity and related infusion commitment','2022financial close'),amount(1714.92,'closed combined equity-and-debenture acquisition consideration','27December2024')],asof='2026-05-17',start='2021-12-16',end='2026-05-17',limitations=['All four amounts measure different flows/stages; no combined spending total.','₹533.20crore completed first equity raise in2022is a component of financing, not additional project cost.','IRB annual-report debt figure includes pending disbursement.','Private IRB Infrastructure Trust and public IRB InvIT Fund remain separate.'])

case='adani-ganga-financing';resp='adani-ganga-response'
for spv,group,debt,equity,grant in [('bhrpl','II',3433,2289,1720),('hurpl','III',3295,2197,2177),('uprpl','IV',3510,2341,2099)]:
    edge(spv+'-concession','upeida',spv,'concession','Group'+group+' concession and VGF',['upeida-awards','adani-close'],'Selected parent AEL’s Group'+group+' concession implemented through this exact SPV. VGF is a funding commitment, not verified release.',case,['UP'],[amount(grant,'concession VGF funding commitment; release unverified','29September2022filing')],asof='2022-09-29',responses=[resp])
    edge(spv+'-ownership','ael',spv,'ownership','Wholly owned at financial close',['adani-close'],'AEL identifies exact SPV as wholly owned in29September2022filing; do not extrapolate ownership indefinitely.',case,['UP'],asof='2022-09-29')
    edge(spv+'-debt','sbi',spv,'loan','SBI-underwritten senior debt',['adani-close'],'Per-SPV senior debt tied up. Filing states SBI underwrites whole₹10,238crore debt requirement across all threeSPVs.',case,['UP'],[amount(debt,'senior debt tied up/underwritten; drawdown unverified','29September2022')],start='2022-09-29',asof='2022-09-29',responses=[resp])
    edge(spv+'-equity','ael',spv,'investment','Equity contribution committed',['adani-close'],'Company will contribute this amount; commitment is not proof of a bank credit or EPC bill payment.',case,['UP'],[amount(equity,'equity contribution commitment; infusion unverified','29September2022')],start='2022-09-29',asof='2022-09-29',responses=[resp])
adani_edges=[r['id'] for r in data['relationships'] if r['recordIds']==[case]]
record(resp,'Adani Ganga: procurement criterion and subsequent inauguration','UPEIDA says the selected bidders quoted the lowest grants; the2022filing explains30-year concessions with traffic-linked extension. AEL’sFY2025–26directors’report records inauguration29April2026. No claim of unlawful selection is supported by these documents.','response',['upeida-awards','adani-close','adani-ar26'],['upeida','ael','bhrpl','hurpl','uprpl','sbi'],adani_edges,'16December2021selection;29September2022financing;29April2026inauguration','Borrower says SBI financing supports development; later inauguration does not reconcile drawdowns, grants or final EPC accounts.',['A public bank can finance a competitively selected concession under ordinary project-finance terms.'],'Retrieve final lender sanctions, escrow drawdowns, VGF-release orders and independent-engineer completion certificates.',['UP'],status='financing-disclosed-later-inauguration-recorded',asof='2026-04-29',start='2021-12-16',end='2026-04-29')
record(case,'Adani Ganga: three concessions, three borrowers and SBI’s debt commitment','GroupsII–IV are held by Budaun Hardoi, Hardoi Unnao and Unnao Prayagraj Road companies. The29September2022exchange filing disaggregates₹10,238crore senior debt,₹6,826crore company equity and₹5,996croreVGF. UPEIDA independently confirms group-specific lowest-grant selection; the lender identity comes from the borrower filing.','investigation-case',['upeida-awards','adani-close','adani-ar26'],['upeida','ael','sbi','bhrpl','hurpl','uprpl'],adani_edges,'Award16December2021;financing29September2022;inauguration29April2026','Linked response preserves lowest-grant criterion and2026inauguration; no direct bank disbursement, EPC recipient or current loan balance is established.',['Standard concession financing can legitimately combine public grants, commercial debt and equity.','SBI’s name in a borrower filing is not independent confirmation of every drawdown or of preferential treatment.'],'Match signed concessions and loan sanctions to eachSPV’s audited accounts, escrow drawdowns, EPC invoices and VGF-release orders; test changes against approved terms.',['UP'],[amount(10238,'aggregate senior-debt underwriting; components onSPVedges','29September2022'),amount(6826,'aggregate equity commitment; components onSPVedges','29September2022'),amount(5996,'aggregate VGF commitment; components onSPVedges','29September2022')],asof='2026-04-29',start='2021-12-16',end='2026-04-29',limitations=['Aggregate amounts repeat the threeSPVcomponents and must not be added again.','₹23,060crore funding-plan arithmetic is not an actual government payment or measured project outturn.','Parent-shareholding snapshot2022; no current ultimate ownership inferred.'])

case='lnt-c4-jica-finance';resp='lnt-c4-response'
edge('c4-award','nhsrcl','lnt','award','C4 multi-currency contract',['nhsrcl-awards','nhsrcl-c4-sign'],'Official award register retains INR21239,95,62,767 plusJPY878,236,238 plusUSD495,520,952; contract signed26November2020. NoFXconversion applied.',case,['GJ'],[amount(21239.9562767,'contract INR component; not payment','C4award','INR','crore'),amount(878.236238,'contract JPY component; not payment','C4award','JPY','million'),amount(495.520952,'contract USD component; not payment','C4award','USD','million')],start='2020-11-26',asof='2020-11-26',responses=[resp])
edge('lnt-delivers-c4','lnt','c4','implements','Contractor for exact C4package',['nhsrcl-c4-sign','jica-c4'],'C4scope237km Zaroli–Vadodara and4stations; exact project relation independently supported by lender and buyer.',case,['GJ'],start='2020-11-26')
edge('c4-part-mahsr','c4','mahsr','project-component','C4 is one MAHSR package',['jica-c4'],'237km is about47%of508km project alignment, not47%of all project expenditure.',case,['GJ','MH'],start='2021-11-25',limitations=['Physical alignment share is not financial allocation.'])
edge('jica-goi-loan','jica','goi','loan','Sovereign MAHSR loan commitment',['jica-tranche5'],'Tranche5JPY400billion signed21December2023; cumulative commitmentJPY1,050billion includes this tranche.',case,['GJ','MH'],[amount(400,'signed tranche5loan commitment; already within cumulative1050','21December2023','JPY','billion')],start='2023-12-21',asof='2023-12-21',responses=[resp])
edge('goi-nhsrcl-equity','goi','nhsrcl','ownership','50% equity participation via Railways',['nhsrcl-equity'],'Historical2December2019statement identifies Government of India through Ministry of Railways50%participation; no paid-in amount inferred.',case,asof='2019-12-02',start='2019-12-02')
edge('gujarat-nhsrcl-equity','gujarat','nhsrcl','ownership','25% equity participation',['nhsrcl-equity'],'Historical equity participation, not state payment.',case,asof='2019-12-02',start='2019-12-02')
edge('maharashtra-nhsrcl-equity','maharashtra','nhsrcl','ownership','25% equity participation',['nhsrcl-equity'],'Historical equity participation, not state payment.',case,asof='2019-12-02',start='2019-12-02')
edge('nhsrcl-executes-mahsr','nhsrcl','mahsr','implements','Executing agency of JICA-funded project',['jica-tranche5'],'Loan recipient is sovereign Government of India; NHSRCL is executing agency contracting works.',case,['GJ','MH'],asof='2023-12-21')
lnt_edges=[r['id'] for r in data['relationships'] if r['recordIds']==[case]]
record(resp,'C4: the authority’s fast-award explanation and funding boundary','NHSRCL records technical bids23September2020, financial bids19October, LOA28October and agreement26November. Its process account cites more than50engineers, daily coordination and Japanese consultant support. This official35-day account is separate from the unreliable dataset comparison-date field. JICA confirms project financing, not a direct loan to L&T.','response',['nhsrcl-c4-sign','nhsrcl-process','jica-c4','jica-tranche5'],['nhsrcl','lnt','jica','goi','c4'],lnt_edges,'2020awardprocess;2021lenderconfirmation;2023tranche5','Agency explanation is retained as its account, not an independent evaluation audit; no adverse C4adjudication is established.',['Parallel technical work can produce a faster award without misconduct.','Different currencies and package scopes explain why rounded rupee headlines cannot serve as exact payment totals.'],'Obtain signedC4price schedules, JICA procurement no-objection/evaluation documents, amendments, disbursement applications and final payment certificates.',['GJ'],status='award-and-financing-verified-payments-unresolved',asof='2023-12-21',start='2020-09-23',end='2023-12-21')
record(case,'L&T C4: a three-currency award inside a sovereign-funded railway','The officialC4award contains₹21,239.9562767crore,JPY878.236238million andUSD495.520952million. NHSRCL is thebuyer and publicSPV; JICA’s cumulativeJPY1,050billion commitment by21December2023is toGovernment ofIndia for thewholeMAHSRproject. The chain separates packagecontract, public ownership, executingagency and sovereign finance.','investigation-case',['nhsrcl-awards','nhsrcl-c4-sign','nhsrcl-equity','nhsrcl-process','jica-c4','jica-tranche5'],['lnt','nhsrcl','c4','mahsr','goi','jica','gujarat','maharashtra'],lnt_edges,'2December2019ownershipstatement;26November2020C4agreement;21December2023latestloantrancheretained','Linked response preserves official process explanation. No package-specific loan drawdown or final L&T payment has been reconciled.',['ODA project loans commonly fund multiple contracts through a sovereign borrower and executingSPV.','The rounded₹24,985crore press headline depends oncurrencyconversion; thiscase uses thethreecontractcomponents.'],'Join eachC4paymentcertificate andFXclause to JICAdisbursementapplications andNHSRCLaccounts; absent those, do not attribute thewholeprojectloan toL&T.',['GJ','MH'],[amount(21239.9562767,'C4contract INRcomponent','2020award','INR','crore'),amount(878.236238,'C4contract JPYcomponent','2020award','JPY','million'),amount(495.520952,'C4contract USDcomponent','2020award','USD','million'),amount(1050,'wholeMAHSRcumulativeJICAcommitment; includestranche5','asof21December2023','JPY','billion')],asof='2023-12-21',start='2019-12-02',end='2023-12-21',limitations=['No cross-currency sum and no whole-project-loan allocation toC4.','NHSRCLoriginalserver503; exactindexedofficialregisterretained.','No overallprojectcompletion claim; laterpackageworksarenot inferredfromconstructionduration.'])

case='meil-polavaram-working-capital';resp='meil-polavaram-response'
edge('apgenco-phep','apgenco','phep','implements','Powerhouse implementing borrower',['cag-polavaram','polavaram-answer'],'Power component is financed separately from central irrigation grant, reaffirmed6August2026.',case,['AP'],asof='2026-08-06',responses=[resp],domains=['energy','public-works','finance'])
edge('rec-apgenco-loan','rec','apgenco','loan','₹3,965.11crore project term loan at11%',['cag-polavaram'],'CAGpara3.2.3records APGENCO obtained termloan₹3,965.11crore at11%for debtportionofPHEPcost₹4,956.39crore. Loanamount isnot anadditional contractorpayment.',case,['AP'],[amount(3965.11,'project termloan obtained; drawdownschedule not retained','CAGpara3.2.3historicalPHEPfinancing')],asof='2026-03-06',responses=[resp],domains=['energy','finance'])
edge('apgenco-meil-contract','apgenco','meil','award','PHEPelectromechanicalcontract',['cag-polavaram'],'CAGpara3.2.3identifies March2021agreement, contractprice₹2,810.88crore;fn148namesMEIL. Thiscomponent differsfromthe2019combinedheadworks/powerhousebid.',case,['AP'],[amount(2810.88,'electromechanicalcontractprice; notpaidamount','agreementMarch2021')],asof='2026-03-06',responses=[resp],dateBasis='March2021only; exactsigningdaynotretained.',domains=['energy','public-works'])
edge('apgenco-meil-advance','apgenco','meil','payment','₹30.86crore materialadvances paid',['cag-polavaram'],'CAGpara3.2.2.1records₹30.86crore paidDecember2021–October2022forsteelafterNovember2021amendment. Governmentdisputesadvancecharacterisation; CAGestimates₹1.10croreinterestloss.',case,['AP'],[amount(30.86,'materialadvancepaymentsasrecordedbyaudit','December2021–October2022')],asof='2026-03-06',responses=[resp],alternatives=['Government says Board-approved split-price schedule permitted payment when steel reachedsite.'],falsifier='Board-approvedpricebreakup,originalandamendedclauses,steelreceiptandincorporationrecordsandacceptedPACsettlementcouldresolvethecharacterisation.',domains=['energy','finance','public-works'])
edge('cag-material-finding','cag','apgenco','audit-finding','Audit: interest-free materialadvancefavouredcontractor',['cag-polavaram'],'CAGconcludespaymentshouldbeafterfinishedworkandcalculates₹1.10croreforegoneinterestDecember2021–November2022. Attributedauditfinding, notcriminalverdict.',case,['AP'],[amount(1.10,'auditor-estimatedforegoneinterest; not principal loss','December2021–November2022')],asof='2026-03-06',responses=[resp],layers=['legal','review','funding'],domains=['energy','finance'],limitations=['₹1.10crore interest cannot be added to₹30.86crore as stolenfunds.'])
edge('cag-equipment-finding','cag','apgenco','audit-finding','Audit:₹41.26crore early equipmentprocurement',['cag-polavaram'],'CAGpara3.2.3records₹41.26croreequipmentprocuredJune2022–June2023andlyingidle28–428daysbeyondallowed6months;₹1.90croreadditionalinterestestimatedtoFebruary2024. GovernmentcitesdesignchangesandearlyBHELequipment.',case,['AP'],[amount(41.26,'equipmentprocurementvaluedescribedbyaudit; notallprojectspending','June2022–June2023'),amount(1.90,'auditestimateofadditionalfinancinginterest','asofFebruary2024')],asof='2026-03-06',responses=[resp],layers=['legal','review','funding'],domains=['energy','finance'],limitations=['No separate BHELcontract/paymentedge: governmentmentiondoesnotestablishspecificsubcontractamounts.','No sumwithmaterialadvancesbecausepotentialoverlaprequiresinvoice-levelreconciliation.'])
meil_edges=[r['id'] for r in data['relationships'] if r['recordIds']==[case]]
record(resp,'Polavaram: government’s payment defence and current financing boundary','GovernmentrepliesAugust/November2024saysteelpaymentsfollowedBoard-approvedsplitpricesandreceiptatsite;clauseswereinsertedatcontractorrequestformobilisingfunds. CAGrejectsthisasaninterest-freeadvanceforunfinishedwork. OnE&M,governmentcitesdesignchangesandearlyBHELsupply;CAGsaysprocurementshouldfollowinstallationneed. Parliamenton6August2026reaffirmspowerhousecostisAndhraPradesh’s,withcentralPhaseIgrantscoveringirrigation/LA/R&R.','response',['cag-polavaram','polavaram-answer'],['andhra','apgenco','meil','rec','phep','cag'],meil_edges,'GovernmentrepliesAugustandNovember2024;reportpublished6March2026;parliament6August2026','No later accepted audit settlement, recovery order or criminal adjudication of these specific material/equipment findings was retrieved. The2026answerdoesnotsettlethem.',['Supply-stagepaymentscanlegitimatelyfinanceworkwhenexpresslyauthorised;thecontesthereiswhetherpost-awardamendmentandfinished-workrulesallowedthem.','Designchangescanexplainmisaligneddelivery,butdonotbythemselvesdisprovefinancingcost.'],'RetrieveBoardminutes,AmendmentNo2,originalschedule,steelandE&Minvoices,installationdates,loaninterestledgerandpost-auditPACactiontakenreports.',['AP'],status='audit-findings-contested-response-retained-no-later-settlement-established',asof='2026-08-06',end='2026-08-06',domains=['energy','finance','public-works','justice'])
record(case,'MEIL Polavaram: contractor advances inside an interest-bearing public loan','CAGlinksMEIL’s₹2,810.88croreE&McontracttoAPGENCO’sREC-financedpowerhouse. Itrecords₹30.86croresteeladvancesafteracontractamendmentand₹1.10croreforegoneinterest;separately₹41.26croreprematureequipmentprocurementwith₹1.90crorefinancinginterest. Governmentconteststheadvancecharacterisationandexplainsearlyequipmentbydesignchanges.','investigation-case',['cag-polavaram','cag-publication','meil-moa','polavaram-answer'],['meil','apgenco','rec','phep','cag','andhra'],meil_edges,'March2021E&Magreement;November2021amendment;paymentsDecember2021–October2022;equipmentJune2022–June2023;interesttoFebruary2024;replies2024;publication2026','Linked response preserves government’sauthorised-stage-paymentdefenceandCAG’srejoinder. Latestparliamentaryanswerkeepspowerhousefundingseparatefromcentralirrigationgrants;itdoesnotresolvetheauditdispute.',['Board-approvedmaterialpaymentscouldhaveacommercialcash-flowjustification;theauditquestioniscompliancewithpost-awardtermsandinteresttreatment.','Delayanddesignrevisioncanexplainidlecomponents;theyarenotautomaticallyevidenceofdiversion.'],'Reconstructeachinvoice’ssupply,inspection,installation,paymentandloan-interestdatesandcheckthelegalauthorityforAmendmentNo2;alateracceptedreconciliationoradjudicationcouldnarroworreversethefinding.',['AP'],[amount(3965.11,'APGENCOprojecttermloanobtainedfromREC','historicalPHEPfinancing'),amount(2810.88,'MEILE&Mcontractprice','March2021'),amount(30.86,'audit-recordedmaterialadvancespaid','December2021–October2022'),amount(1.10,'audit-estimatedforegoneinterestonmaterialadvances','December2021–November2022'),amount(41.26,'separateearlyE&Mprocurementvaluedescribedbyaudit','June2022–June2023'),amount(1.90,'audit-estimatedadditionalinterestonearlyequipment','asofFebruary2024')],asof='2026-08-06',end='2026-08-06',domains=['energy','finance','public-works','justice'],limitations=['Audit, not criminal adjudication. No politicalquid-pro-quoinferenceandnoelectoral-bondpaymentjoinedtoawards.','Loan,contract,advance,equipmentandinterestareseparatestageswithpossibleoverlap;donotsum.','Report4of2025waspublished6March2026;mostfinancialeventsandresponsesaremucholder.','Officialindexedextractusedafteroriginalhost503;exactparalocatorsandfailurereceiptsretained.'])

# Entire displayed official register is retained as a finite queue, including negative/direction controls.
rows=json.loads((ROOT/'nhsrcl-register-20rows.json').read_text())['rows']
for r in rows:
    if r['tenderRef']=='MAHSR - C-4':continue
    i='nhsrcl-queue-'+str(r['sourceRow']).zfill(2)
    discharged=r['contractorLabel']=='Tender Discharged'
    auction='Auction' in r['title']
    status='discharged-no-award-control' if discharged else 'revenue-direction-review' if auction else 'awarded-label-identity-and-payment-unresolved'
    summary=('Original authority row: '+r['title']+' Counterparty field: '+r['contractorLabel']+'. Amount as written: '+(r['amountLexeme'] or 'not populated')+'. ')
    summary+=('This is a discharged tender and supplies no awarded supplier.' if discharged else 'Cutting/disposal auction may generate authority revenue; do not assume government pays the named buyer.' if auction else 'Exact public tender reference is established; legal registration, parent chain, contract amendments and actual payment remain unresolved.')
    record(i,r['tenderRef']+' — '+('discharged control' if discharged else r['contractorLabel']),summary,'discovery-lead',['nhsrcl-awards'],['nhsrcl'],[],'Authority register row; award date not populated in retained table','No bidder-specific allegation advanced. No response requested or inferred.',['A supplier label may denote aconsortiumortradingname; exactlegalidentitymustprecedecorporateorpoliticaljoins.'],'Retrieve original signedaward/contract usingexactreference, establishCIN/consortiummembersandpaymentdirection,thenlinkbank/bill/completionrecords.',status=status,asof=SNAPSHOT,tier='analytic',limitations=['One of20displayedrows,notanationalorNHSRCLcensus.','Noawardamountparsedintopaymentormergedwiththeprojectloan.'])
record('zojila-exact-id-lead','Zojila: original notice recovered; corpus linkage remains unproved','TheoriginalCPPPnotice2020_NHIDC_564017_1andreferenceNHIDCL/JnK-Ladakh/ Zojila/NH-01/2020areaccessible. NHIDCL’sprojectregisterseparatelynamesMEILandaward25August2020. ExactID/referencequeryagainstuser-suppliedsnapshotreturned0rows;thisisacoveragegap,notproofnoaward.','discovery-lead',['zojila-notice','nhidcl-zojila'],['nhidcl','meil'],[],'NoticeJune2020;authorityawarddate25August2020;snapshot26June2026','No allegation advanced; varying newsbidfiguresandcurrentprojectcostneedoriginalLOA/contractreconciliation.',['Thedatabasecapturecanomitavalidawardorformatreferencess differently.','Revisedprojectcostmayincludescope,landorotheritemsabsentfromanEPCbid.'],'Obtain signedLOAandEPCagreementforexactnotice,verifyCINandprice/corrigenda,thenjoinmilestonecertificatesandpaidbills.',status='exact-primary-notice-verified-award-payment-link-unresolved',asof=SNAPSHOT,tier='analytic',limitations=['No₹4,429.83crnoticeestimateorcurrentprojectcostiscategorisedaspayment.','UTgeographyisnotassignedfromambiguouslegacyJKstatecodes.'])

# Carry over explicit unresolved follow-ups, with prior evidence named, not relabelled new findings.
carry=[('roads-research.json',['rw-case-dwarka','rw-case-cherkkala','rw-case-meachi']),('services-research.json',['svc-overlapping-manpower','svc-duplicate-connections','svc-water-single-bids','svc-water-retendering']),('state-research.json',['state-case-ts-vehicle-loan'])]
for filename,ids in carry:
    p=ROOT.parents[1]/'public-works'/filename
    old=json.loads(p.read_text());sm={s['id']:s for s in old['sources']}
    for c in old['cases']:
        if c['id'] not in ids:continue
        sidlist=[]
        for sid in c['sourceIds']:
            nid='prior-'+sid;sidlist.append(nid)
            if any(s['id']==nid for s in data['sources']):continue
            s=sm[sid]
            data['sources'].append(dict(id=nid,title=s['title'],url=s['url'],publisher=s.get('publisher','See primary citation'),publishedAt=s.get('publishedAt'),retrievedAt=s.get('retrievedAt'),locator=s.get('locator','See prior register'),summary=s.get('summary','Retained prior source'),tier=s.get('tier','documented'),limitations=s.get('limitations',[])+['Reused existing evidence from research/raw/public-works/'+filename+'; not a fresh discovery or fresh primary retrieval.']))
        record('carry-'+c['id'],'Unresolved extension: '+c['title'],'Prior corpus finding: '+c['summary']+' New work required: connect exactcontractandcompanyidentitiestothepayment/recovery/completionchain;nosuchjoinisinferredhere.','discovery-lead',sidlist,[],[],c.get('period','Historical audit period'),c.get('response','See retained prior response'),c.get('alternativeExplanations',[]),c.get('falsifier','Retrieveexactcontracts,paymentsandrecoveryoutcomes.'),c.get('stateCodes',[]),status='prior-finding-open-identity-and-payment-follow-up',tier='analytic',limitations=['Carriedforwardleadfromexistingcorpus;notcountedasnewlydiscoveredirregularity.'],domains=['public-works'])

# Human-readable prose: preserve conventional spaces at boundaries in compact authoring text.
replacements={
'crore':' crore','₹ ':'₹','%of':'% of','%before':'% before','%participation':'% participation',
'Government ofIndia':'Government of India','GovernmentofIndia':'Government of India','toGovernment':'to Government',
'wholeMAHSR':'whole MAHSR','wholeproject':'whole project','C4award':'C4 award','C4contract':'C4 contract','C4agreement':'C4 agreement','C4package':'C4 package','C4scope':'C4 scope','C4price':'C4 price','C4payment':'C4 payment','C4adjudication':'C4 adjudication',
}
def clean(v):
    if isinstance(v,list):return [clean(i) for i in v]
    if isinstance(v,dict):return {k:clean(x) if k not in ['id','from','to','sourceIds','entityIds','relationshipIds','recordIds','responseIds','canonicalId','url','route','currency','unit','kind','type','status','domains','layers'] else x for k,x in v.items()}
    if isinstance(v,str):
        for a,b in replacements.items():v=v.replace(a,b)
        v=re.sub(r'(?<=[a-zA-Z])(?=\d)|(?<=\d)(?=[a-zA-Z])',' ',v)
        v=re.sub(r'\s{2,}',' ',v)
    return v
# Do not rewrite exact identifiers/dates. A prose-only pass is applied below only to display text.
textkeys={'label','title','summary','period','response','dateBasis','identityBasis','stage','note','locator','falsifier'}
def prose(v,k=None):
    if isinstance(v,list):return [prose(x,k) for x in v]
    if isinstance(v,dict):return {kk:prose(x,kk) for kk,x in v.items()}
    return clean(v) if isinstance(v,str) and (k in textkeys or k in {'limitations','alternativeExplanations'}) else v
data=prose(data)
# Final editorial pass keeps source identifiers untouched and all display prose legible.
overrides=json.loads((ROOT/'editorial_overrides.json').read_text())
for group in data.values():
    for row in group:
        if row['id'] in overrides: row.update(overrides[row['id']])
        if row['id'].startswith('nhsrcl-queue-'):
            row['falsifier']='Retrieve the original signed award or contract using the exact reference; establish legal registration, consortium membership and payment direction, then link bill, bank and completion records.'
            row['alternativeExplanations']=['A supplier label may denote a consortium or trading name. Establish exact legal identity before corporate or political joins.']
            row['limitations']=['One of 20 displayed rows, not a national or NHSRCL census.','No award amount is parsed into payment or merged with the project loan.']
        if row['id'].startswith('carry-'):
            row['summary']=row['summary'].split(' New work required:')[0]+' New work required: connect exact contract and company identities to the payment, recovery and completion chain; no such join is inferred here.'
            row['limitations']=['Carried-forward lead from the existing corpus; not counted as a newly discovered irregularity.']
fixes={
 'GICaffiliate':'GIC affiliate','InDecember':'In December','anddebentures':'and debentures','directors’report':'directors’ report','AEL’sFY':'AEL’s FY',
 'GroupsII':'Groups II','GroupIII':'Group III','GroupII':'Group II','GroupIV':'Group IV','threeSPVs':'three SPVs','threeSPVcomponents':'three SPV components','onSPVedges':'on SPV edges','eachSPV':'each SPV','C 4':'C4','B 15':'B15',
 'plusJPY':'plus JPY','plusUSD':'plus USD','NoFXconversion':'No FX conversion','commitmentJPY':'commitment JPY','GICaffiliate':'GIC affiliate','awardprocess':'award process','lenderconfirmation':'lender confirmation','signedC4':'signed C4','wholeMAHSRcumulativeJICAcommitment':'whole MAHSR cumulative JICA commitment','includestranche':'includes tranche','asof':'as of ',
 'CAGpara':'CAG paragraph','Ganga groups':'Ganga groups','GroupI':'Group I','projectfinance':'project finance','Report4of':'Report 4 of ','Polavaram report':'Polavaram report','p.16':'p. 16','SPVs':'SPVs','proposedcombination':'proposed combination',
 'PHEPfinancing':'PHEP financing','50engineers':'50 engineers','wholeMAHSR':'whole MAHSR','MAHSRcumulative':'MAHSR cumulative','JICAcommitment':'JICA commitment','unitholderapproval':'unitholder approval','LOAand':'LOA and',
}
def polish(v,k=None):
    if isinstance(v,dict):return {kk:polish(x,kk) for kk,x in v.items()}
    if isinstance(v,list):return [polish(x,k) for x in v]
    if not isinstance(v,str) or k not in textkeys|{'limitations','alternativeExplanations'}:return v
    for a,b in fixes.items():v=v.replace(a,b)
    v=re.sub(r'(?<=\S)(?=₹)',' ',v)
    v=re.sub(r'(?<=[a-z])(?=[A-Z])',' ',v)
    v=re.sub(r'([A-Z]{2,})([a-z]{2,})',r'\1 \2',v)
    v=re.sub(r'(?<=[%;])(?=[A-Za-z0-9])',' ',v)
    v=re.sub(r'(?<=[a-zA-Z]);(?=\S)','; ',v)
    v=re.sub(r'(?<=,)(?=[A-Za-z])',' ',v)
    v=v.replace('Inv IT','InvIT').replace('Jn K-Ladakh','JnK-Ladakh').replace('L 65910 MH 1998 PLC 115967','L65910MH1998PLC115967')
    return re.sub(r'\s{2,}',' ',v)
data=polish(data)
OUT.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
print({k:len(v) for k,v in data.items()})
