"""Build compact, source-backed corpus audit cards from retained executed results."""
import hashlib,json,pathlib,sys
ROOT=pathlib.Path(__file__).resolve().parent;REPO=ROOT.parents[2]
read=lambda name:json.loads((ROOT/name).read_text())
a=read('analysis.json');f=read('followup.json');s=read('closing-field-semantics.json');v=read('linkage-v2.json')
base='https://github.com/occult-kranti/india-corporate-intelligence/blob/codex/education-funding-intelligence/'
source_specs=[
 ('origin','Original tender corpus publication','https://tender.sarthaksidhant.com/','Sarthak Sidhant','2026-06-26','Published database schemas and full SQLite SHA-256 values; public R2 mirror','reported'),
 ('hashes','Verified original SQLite download receipts',base+'research/raw/tender-portal-audit/evidence/','ICIP source audit',None,'aoc_tenders.db.download-receipt.json and tenders_vps.db.download-receipt.json; full SHA-256, bytes and ZIP CRC verified','analytic'),
 ('analysis','Executed source grain, joins and deduplication audit',base+'research/raw/tender-portal-audit/analysis.json','ICIP source audit',None,'Exact SQL, query rows and sourceHashes in analysis.json; normalization recipe in derivation-manifest.json','analytic'),
 ('followup','Strict lexical, chronology and status controls',base+'research/raw/tender-portal-audit/followup.json','ICIP source audit',None,'Exact query IDs, SQL and bounded populations; followup.py does not mutate originals','analytic'),
 ('semantics','Award closing-field semantics in exact listing-only pairs',base+'research/raw/tender-portal-audit/closing-field-semantics.json','ICIP source audit',None,'field_equality, by_buyer, by_year; semantic_probe.py','analytic'),
 ('linkage','Separate detail-reference-fallback linkage audit',base+'research/raw/tender-portal-audit/linkage-v2.json','ICIP source audit',None,'reference_agreement, fallback_join_cardinality, closing_field_semantics; independently versioned linkage_v2.py','analytic'),
 ('numeric','Independent raw amount lexeme review',base+'docs/tender-investigation/amount-lexemes.json','Independent ICIP data reviewer',None,'central_nonplain_amounts; original amount strings only; no contact or winner data','analytic'),
 ('notebook','Inspectable source-quality audit notebook',base+'research/raw/tender-portal-audit/audit.ipynb','ICIP source audit',None,'Retained input hashes, exact executed SQL, denominators and optional read-only rerun cells','analytic'),
]
sources=[{'id':id,'title':title,'url':url,'publisher':publisher,'publishedAt':published,'retrievedAt':'2026-10-06','locator':locator,'summary':title,'tier':tier,'limitations':['This documents the scrape or an analysis of it; it does not independently verify every original procurement event.']} for id,title,url,publisher,published,locator,tier in source_specs]
findings=[];records=[]
def add(id,title,summary,metrics,queryIds,period,alternatives,falsifier,limits,support):
 sourceIds=list(dict.fromkeys(['origin','hashes',*support,'notebook']))
 findings.append({'id':id,'recordId':'procurement-audit:record:'+id,'title':title,'summary':summary,'scope':'Corpus-level source audit; not a finding about a selected buyer.','sourceIds':['procurement-audit:source:'+x for x in sourceIds],'queryIds':queryIds,'metrics':metrics})
 metric_text=' '.join(f"{m['label']}: {m['value']:,} {m['unit']}"+(f"; denominator {m['denominator']:,} {m['denominatorLabel']}" if 'denominator' in m else '')+'.' for m in metrics)
 records.append({'id':id,'title':title,'summary':summary+' '+metric_text,'kind':'procurement-source-audit','tier':'analytic','status':'source-quality-finding','statusAsOf':'2026-10-06','fromDate':'2026-06-16','toDate':'2026-06-24','dateBasis':'Dates describe source capture, not every underlying procurement event. This quality review was performed 6 October 2026.','period':period,'entityIds':[],'relationshipIds':[],'response':'No allegation is made against a contractor or buyer; original-record verification and disclosure gaps remain explicit.','alternativeExplanations':alternatives,'falsifier':falsifier,'amounts':[],'domains':['public-works','procurement'],'layers':['procurement','review'],'geography':[{'scope':'national','stateCodes':[],'localityIds':[],'basis':'national-context','note':'Corpus-wide collection context; no asset, supplier or delivery geography is inferred.','sourceIds':sourceIds}],'route':'/tenders?section=national&iw_record=procurement-audit%3Arecord%3A'+id,'sourceIds':sourceIds,'limitations':limits+['Query locators: '+', '.join(queryIds),'Original databases remain outside the repository. Full input SHA-256 values: '+json.dumps(a['sourceHashes'],sort_keys=True)]})
def m(label,value,unit,denominator=None,denominatorLabel=None):return {'label':label,'value':value,'unit':unit,**({'denominator':denominator,'denominatorLabel':denominatorLabel} if denominator is not None else {})}
add('corpus-grain','Four source tables do not mean sixteen million distinct tenders','The two publisher-hash-verified databases contain listing and detail rows for two different stages. Joining each detail to its own listing does not create another procurement event.',[m('Award listings',4921960,'rows'),m('Notice listings',3952191,'rows'),m('All four raw tables',16593375,'rows'),m('Orphan test detail',1,'row',3178485,'raw notice detail rows')],['analysis.source_counts','analysis.detail_integrity'],'Source captures 16–24 June 2026; historical dates extend beyond the intended period',['Listing/detail storage duplication is normal relational design.','The extra notice-detail row is a known test record, not an additional tender.'],'Close by reconciling primary listing/detail keys and retaining distinct stage grains.',['The website’s displayed grand total differs from its table counts; no distinct-tender count is derived by adding tables.'],['analysis'])
add('state-notice-coverage','State notices cover a recent active slice','State notices are a small and mostly future-closing portion of this snapshot, while state awards form most award rows. Missing notice/award links cannot be interpreted as failed tenders.',[m('State notices',41825,'rows',3952191,'all notice listings'),m('State awards',2916702,'rows',4921960,'all award listings'),m('State notices closing after capture',39104,'rows',41825,'state notice listings')],['analysis.portal_population','analysis.notice_status','followup.window_status_cohorts'],'State notice publications 2022–June 2026; all collected as active on 16 June 2026',['Active notices normally have deadlines after capture.','Collector coverage and portal archival availability can explain unmatched historical awards.'],'Acquire dated archived state notices with declared portal-year coverage before comparing outcome rates.',['No state performance ranking or national procurement coverage rate follows.'],['analysis','followup'])
j=a['queries']['join_id_only']['rows'][0]
add('unsafe-tender-id-join','A tender-ID-only join explodes into candidate pairs','Tender identifiers include reused buckets and generic values. A direct notice/award join on tender_id would multiply rows rather than discover that many contracts.',[m('Candidate pairs',j['candidate_pair_rows'],'pairs'),m('Shared exact ID keys',j['shared_keys'],'keys'),m('Pairs from generic ID 1',2579823328,'pairs',j['candidate_pair_rows'],'candidate pair rows')],['analysis.join_id_only','analysis.largest_ambiguous_keys'],'Whole retained notice/award snapshots',['Generic IDs and organisation/year buckets are not globally unique contract identifiers.','Multiple versions and lots can legitimately share a public identifier.'],'Require portal, authority, reference, lot and version evidence; audit join cardinality before creating relationships.',['No many-to-many join is materialized or published as a money trail.'],['analysis'])
j2=v['queries']['fallback_join_cardinality']['rows'][0]
add('strict-linkage-limits','Contextual keys still need version and date checks','Listing-only portal+buyer+tenderID+reference keys yield 1,714 unique pairs. A separately declared within-stage detail-reference fallback raises unique candidate pairs to 17,704; these are candidate links, not independently confirmed contracts.',[m('Listing-only shared keys',2625,'keys'),m('Listing-only unique pairs',1714,'pairs',2625,'shared listing-only keys'),m('Fallback unique pairs',j2['one_to_one_keys'],'pairs',j2['shared_keys'],'shared fallback keys'),m('Nonblank listing/detail reference conflicts',118342,'award rows',4921960,'raw award listings')],['analysis.join_portal_buyer_id_reference','followup.join_field_missingness','linkage.reference_agreement','linkage.fallback_join_cardinality'],'Historical retained snapshots; exact raw authority labels preserved',['Award listing references are often absent but present in linked detail records.','Nonblank reference disagreements or amendments can leave identity/version unresolved despite a unique key.'],'Resolve nonblank conflicts and inspect original tender IDs, references, lots and dated amendments before approving a link.',['The fallback uses the same internal_id within awards; no supplier-name or fuzzy buyer join occurs.','The two variants overlap and must not be added together.'],['analysis','followup','linkage'])
add('closing-field-semantics','The award closing label needs source verification','In a narrow exact listing-only subset, 1,709 of 1,714 award closing timestamps equal notice publication, and none equals notice closing. That subset is all central, dated 2013–2018 and dominated by Neyveli Lignite. The larger fallback variant separately finds 15,816 publication matches among 17,704 unique pairs.',[m('Publication matches in listing-only subset',1709,'pairs',1714,'unique listing-only pairs'),m('Notice-closing timestamp matches',0,'pairs',1714,'unique listing-only pairs'),m('Publication matches in fallback variant',15816,'pairs',17704,'unique fallback pairs')],['semantics.field_equality','semantics.by_buyer','semantics.by_year','linkage.closing_field_semantics'],'Listing-only notices 2 December 2013–31 December 2018; fallback is a separate historical population',['A collector field mapping or source-column interpretation may explain the equality.','Reference/version inconsistencies can affect candidate pair semantics.'],'Read original portal headers and dated notice/award documents for exact identifiers; validate field meaning before evaluation-speed analysis.',['These are selected matched subsets, not representative samples of 4.92 million awards.','Historical ≤2-day calculations are preserved as recorded dataset-date gaps, not evaluation speed or evidence of impropriety.'],['semantics','linkage'])
add('planned-bid-windows','Separate scheduled windows from past-deadline observations','The state snapshot contains 46 listed windows shorter than 72 hours, but 36 of those deadlines were still in the future at capture. The remaining 10 occur among 2,721 notices whose scheduled closing was at or before capture.',[m('Short windows in future-closing state notices',36,'rows',39104,'future-closing state notice rows'),m('Short windows at/before capture',10,'rows',2721,'state notices closed by scheduled date')],['followup.window_status_cohorts'],'As-observed publication and scheduled closing at 16 June 2026 capture',['Limited procurement and temporary service arrangements can lawfully use different procedures.','Extensions and corrigenda may change the operative submission period.'],'Retrieve original notice, applicable procedure and all amendments; verify the actual submission period and procurement scope.',['Listed publication-to-closing duration is not automatically the legally required bid period.','No source-wide legal violation rate is calculated.'],['followup'])
add('scoped-deduplication','Buyer and portal scope change the deduplication grain','The historical dedup key omits portal and buyer. Adding those fields raises the number of groups by 385; adding reference as well raises it by 1,351. The small overall difference still matters for exact record identity.',[m('Historical groups',3385233,'groups'),m('Additional portal/buyer-scoped groups',385,'groups',3385233,'historical groups'),m('Cross-portal keys',22,'keys',3385233,'historical keys'),m('Cross-buyer keys',310,'keys',3385233,'historical keys')],['analysis.legacy_dedup_key_collisions','analysis.scoped_dedup_counts'],'Whole retained award snapshot',['Different authority labels can denote one body or different subunits.','Generic tender IDs can collide across portals and buyers.'],'Review scoped identifiers and compare sensitivity without silently replacing the historical count.',['This is a dataset grouping limitation, not evidence of repeated completed work or duplicate payment.'],['analysis'])
add('payload-and-chronology','Conflicting versions and impossible dates need quarantine','Some historical dedup groups carry different raw amount, bid-count or closing values. Separately, 748 award timestamps fall after the 26 June 2026 publication cutoff. Neither conflict establishes which version or event date is correct.',[m('Raw amount-variant groups',1757,'groups',3385233,'historical dedup groups'),m('Raw bid-count-variant groups',928,'groups',3385233,'historical dedup groups'),m('Post-publication award dates',748,'rows',4921960,'raw award listings')],['followup.payload_variants_raw_null_inclusive','analysis.award_date_quality','followup.timezone_aware_caution'],'Source capture 18–24 June 2026; publication cutoff 26 June 2026',['Null/non-null variants can reflect incomplete detail extraction or later updates.','Erroneous date entry, field interpretation or timezone ambiguity can create chronology conflicts.'],'Retain all versions and identify the authoritative dated record; compare same-day timezone-sensitive observations separately.',['Null-versus-present differences are counted explicitly.','A future scheduled notice closing is normal and is not included as a misconduct finding.'],['analysis','followup'])
add('numeric-lexeme-safety','Scientific notation must not be stripped into another number','Fourteen central notice EMD values and one fee use scientific notation. The third-party converter and initial audit extraction rule remove nonnumeric characters: 1e17 becomes 117. Original SQLite strings are intact; strict parsing quarantines these lexemes.',[m('Scientific-notation EMD strings',14,'values',3136659,'central notice detail EMD fields'),m('Scientific-notation fee strings',1,'value',3136659,'central notice detail fee fields'),m('Nonblank award amounts with compatible decimal form',4463564,'values',4463564,'nonblank award amount strings')],['numeric.central_nonplain_amounts','followup.award_numeric_lexical_quality','followup.notice_emd_fee_lexical_quality'],'Original June 2026 notice snapshot; conversion rule review 6 October 2026',['Huge exponent lexemes can themselves be data-entry or extraction artifacts.','Rupee-prefixed state amounts are normal formatting and should not be classified as malformed solely for containing a currency symbol.'],'Use a grammar-aware parser, preserve raw strings and quarantine exponent/unsupported formats; verify unusually large amounts in original documents.',['This defect affects notice EMD/fee transformation, not altered SQLite originals or a demonstrated defect in HF award monetary values.','EMD and tender fees are not estimated contract values or payment evidence.'],['numeric','followup'])
paths=['analysis.json','followup.json','closing-field-semantics.json','linkage-v2.json','derivation-manifest.json','strict_parse.py','audit.ipynb','evidence/aoc_tenders.db.download-receipt.json','evidence/tenders_vps.db.download-receipt.json','../../../docs/tender-investigation/amount-lexemes.json']
compact={'status':{'state':'complete','asOf':'2026-10-06','scope':'Corpus-level source and linkage audit; findings do not describe an individual buyer.','recordCount':len(records),'limitations':['Derived from publisher-hash-verified scraped records; source correctness remains separately verifiable.','Candidate links, nominal award values and short windows do not establish payment, delivery or wrongdoing.']},'findings':findings,'slice':{'sources':sources,'entities':[],'relationships':[],'records':records,'localities':[]},'inputHashes':{name:hashlib.sha256((ROOT/name).read_bytes()).hexdigest() for name in paths}}
output=REPO/'src/data/procurement-audit.json'
serialized=json.dumps(compact,indent=2)+'\n'
if '--check' in sys.argv:
 if not output.exists() or output.read_text()!=serialized:raise SystemExit('Stale procurement-audit.json: rerun build_cards.py after reviewing input changes')
 print('Compact audit matches reviewed inputs and producer')
else:
 output.write_text(serialized);print('Generated',len(records),'audit records and',len(sources),'sources')
