"""Additional strict-field and chronology controls. Read-only derived/source DBs.
Neither permissive extraction nor a unique key alone certifies a procurement link.
"""
import datetime,hashlib,json,pathlib,sqlite3,time,duckdb
ROOT=pathlib.Path(__file__).resolve().parent;CACHE=pathlib.Path('/workspace/research-cache/tender-20260626')
c=duckdb.connect(str(CACHE/'audit.duckdb'),read_only=True);c.execute("SET memory_limit='1100MB';SET threads=2;SET temp_directory='/workspace/research-cache/tender-20260626/followup-tmp'")
result={'asOf':'2026-10-06','inputAnalysisSHA256':hashlib.sha256((ROOT/'analysis.json').read_bytes()).hexdigest(),'sourceHashes':json.loads((ROOT/'analysis.json').read_text())['sourceHashes'],'queries':{}}
def run(name,sql):
 start=time.time();q=c.execute(sql);rows=[dict(zip([d[0] for d in q.description],row)) for row in q.fetchall()];result['queries'][name]={'sql':sql,'rows':rows,'seconds':round(time.time()-start,3)};(ROOT/'followup.json').write_text(json.dumps(result,indent=2,default=str));print(name,round(time.time()-start,2),json.dumps(rows,default=str)[:2000],flush=True);return rows
integer="regexp_full_match(trim(bids_raw),'[0-9]+')"
money=r"regexp_full_match(trim(value_raw),'(?i)(?:(?:INR|Rs\.?|₹)\s*)?(?:[0-9]+|[0-9]{1,3}(?:,[0-9]{3})+|[0-9]{1,2}(?:,[0-9]{2})*,[0-9]{3})(?:\.[0-9]+)?')"
run('award_numeric_lexical_quality',f"SELECT count(*) AS rows,count(*) FILTER(WHERE nullif(trim(bids_raw),'') IS NOT NULL) AS nonblank_bid_counts,count(*) FILTER(WHERE {integer}) AS strict_unsigned_integer_forms,count(*) FILTER(WHERE {integer} AND try_cast(trim(bids_raw) AS INTEGER) BETWEEN 1 AND 1000) AS strict_eligible_bid_counts,count(*) FILTER(WHERE bids IS NOT NULL AND NOT coalesce({integer},false)) AS numeric_extraction_without_integer_form,count(*) FILTER(WHERE value_amount IS NOT NULL) AS extracted_amounts,count(*) FILTER(WHERE {money}) AS strict_grouped_numeric_forms,count(*) FILTER(WHERE value_amount IS NOT NULL AND NOT coalesce({money},false)) AS numeric_extraction_without_money_form FROM awards")
run('notice_emd_fee_lexical_quality',"SELECT portal,count(*) AS listings,count(*) FILTER(WHERE regexp_full_match(trim(emd_raw),'[0-9]+(?:\\.[0-9]+)?')) AS unsigned_decimal_emd,count(*) FILTER(WHERE regexp_full_match(trim(fee_raw),'[0-9]+(?:\\.[0-9]+)?')) AS unsigned_decimal_fee,count(*) FILTER(WHERE emd_amount=0) AS zero_emd,count(*) FILTER(WHERE fee_amount=0) AS zero_fee FROM notices GROUP BY portal")
run('timezone_aware_caution',"SELECT portal,count(*) FILTER(WHERE aoc_at>scraped_at AND aoc_at<=scraped_at+INTERVAL '24 hour') AS after_scrape_within_24h,count(*) FILTER(WHERE aoc_at>scraped_at+INTERVAL '24 hour') AS after_scrape_over_24h,count(*) FILTER(WHERE aoc_at>scraped_at+INTERVAL '7 day') AS after_scrape_over_7d FROM awards GROUP BY portal")
run('join_field_missingness',"SELECT 'awards' AS grain,portal,count(*) AS rows,count(*) FILTER(WHERE nullif(trim(tender_id),'') IS NULL) AS missing_tender_id,count(*) FILTER(WHERE nullif(trim(buyer),'') IS NULL) AS missing_buyer,count(*) FILTER(WHERE nullif(trim(reference),'') IS NULL) AS missing_reference FROM awards GROUP BY portal UNION ALL SELECT 'notices',portal,count(*),count(*) FILTER(WHERE nullif(trim(tender_id),'') IS NULL),count(*) FILTER(WHERE nullif(trim(buyer),'') IS NULL),count(*) FILTER(WHERE nullif(trim(reference),'') IS NULL) FROM notices GROUP BY portal")
run('window_status_cohorts',"SELECT portal,status,closing_at>listing_scraped_at AS scheduled_to_close_after_scrape,count(*) AS listings,median(date_diff('minute',published_at,closing_at)/1440.0) AS median_scheduled_window_days,count(*) FILTER(WHERE date_diff('minute',published_at,closing_at)<72*60) AS scheduled_window_under_72h,count(*) FILTER(WHERE nullif(trim(corrigendum_url),'') IS NOT NULL) AS with_corrigendum_link FROM notices WHERE published_at<=closing_at AND published_at<=listing_scraped_at AND year(published_at)>=2011 GROUP BY ALL ORDER BY ALL")
run('payload_variants_raw_null_inclusive',"WITH k AS(SELECT tender_id,bidder_norm,aoc_at,count(*) AS rows,count(DISTINCT struct_pack(v:=portal)) AS portals,count(DISTINCT struct_pack(v:=buyer)) AS buyers,count(DISTINCT struct_pack(v:=reference)) AS refs,count(DISTINCT struct_pack(v:=value_raw)) AS raw_values,count(DISTINCT struct_pack(v:=bids_raw)) AS raw_bids FROM awards GROUP BY ALL) SELECT count(*) AS old_key_groups,count(*) FILTER(WHERE buyers>1) AS buyer_variants_including_null,count(*) FILTER(WHERE refs>1) AS reference_variants_including_null,count(*) FILTER(WHERE raw_values>1) AS raw_amount_variants_including_null,count(*) FILTER(WHERE raw_bids>1) AS raw_bid_variants_including_null FROM k")
# Only nonempty exact contextual keys. Duplicate award versions remain visible.
key_cte="""WITH nk AS(SELECT portal,buyer,tender_id,reference,count(*) AS n FROM notices WHERE nullif(trim(tender_id),'') IS NOT NULL AND nullif(trim(buyer),'') IS NOT NULL AND nullif(trim(reference),'') IS NOT NULL GROUP BY ALL),ak AS(SELECT portal,buyer,tender_id,reference,count(*) AS n FROM awards WHERE nullif(trim(tender_id),'') IS NOT NULL AND nullif(trim(buyer),'') IS NOT NULL AND nullif(trim(reference),'') IS NOT NULL GROUP BY ALL),matched AS(SELECT n.*,a.internal_id AS award_internal_id,a.aoc_at,a.closing_at AS award_closing,a.scraped_at AS award_scraped,a.bids_raw,a.value_raw,a.value_amount,a.document_url AS award_document_url,ak.n AS award_versions FROM notices n JOIN nk USING(portal,buyer,tender_id,reference) JOIN awards a USING(portal,buyer,tender_id,reference) JOIN ak USING(portal,buyer,tender_id,reference) WHERE nk.n=1 AND ak.n=1) """
run('unique_key_temporal_compatibility',key_cte+"SELECT count(*) AS one_to_one_pairs,count(*) FILTER(WHERE aoc_at<published_at) AS aoc_before_notice,count(*) FILTER(WHERE aoc_at<award_closing) AS aoc_before_award_close,count(*) FILTER(WHERE award_closing IS DISTINCT FROM closing_at) AS closing_mismatch,count(*) FILTER(WHERE aoc_at>award_scraped+INTERVAL '24 hour') AS aoc_over_24h_after_scrape,count(*) FILTER(WHERE nullif(trim(corrigendum_url),'') IS NOT NULL) AS corrigendum_link,count(*) FILTER(WHERE published_at<=closing_at AND closing_at<=aoc_at AND aoc_at<=award_scraped AND closing_at=award_closing AND year(published_at)>=2011) AS temporal_compatible_pairs FROM matched")
# Finite discovery pool; legal sufficiency and scope are checked in original documents, not inferred here.
eligibility=f"published_at>=TIMESTAMP '2021-06-16' AND published_at<=closing_at AND closing_at<=aoc_at AND aoc_at<=award_scraped AND closing_at=award_closing AND {integer} AND try_cast(trim(bids_raw) AS INTEGER) BETWEEN 1 AND 1000 AND {money} AND value_amount BETWEEN 100000 AND 10000000000"
run('case_discovery_denominator',key_cte+f"SELECT count(*) AS eligible_pairs,count(*) FILTER(WHERE try_cast(bids_raw AS INTEGER)=1 AND date_diff('minute',published_at,closing_at)<72*60) AS short_window_single_bid,count(*) FILTER(WHERE try_cast(bids_raw AS INTEGER)>1 AND date_diff('minute',published_at,closing_at)>=7*24*60) AS longer_window_multiple_bid FROM matched WHERE {eligibility}")
rows=run('candidate_discovery_pool',key_cte+f"SELECT internal_id AS notice_internal_id,award_internal_id,portal,buyer,tender_id,reference,title,status,tender_category,tender_type,product_category,published_at,closing_at,aoc_at,award_scraped,bids_raw,value_raw,value_amount,date_diff('minute',published_at,closing_at)/60.0 AS listed_window_hours,nullif(trim(corrigendum_url),'') IS NOT NULL AS corrigendum_link,document_url AS notice_document_url,award_document_url FROM matched WHERE {eligibility} ORDER BY CASE WHEN try_cast(bids_raw AS INTEGER)=1 AND date_diff('minute',published_at,closing_at)<72*60 THEN 0 ELSE 1 END,listed_window_hours,tender_id LIMIT 40")
# Only requested public procurement fields; personal names/contact addresses are not fetched.
for row in rows:
 for db,table,idkey,cols,prefix in [('tenders_vps.db','tenders','notice_internal_id',['e_published_date','bid_submission_closing_date','detail_url'],'notice_'),('aoc_tenders.db','aoc_tenders','award_internal_id',['aoc_date','closing_date','detail_url'],'award_')]:
  s=sqlite3.connect(f'file:{CACHE}/{db}?mode=ro&immutable=1',uri=True);raw=s.execute(f"SELECT {','.join(cols)} FROM {table} WHERE internal_id=?",(row[idkey],)).fetchone();s.close();row.update({prefix+key:value for key,value in zip(cols,raw)})
(ROOT/'candidate-pool.json').write_text(json.dumps({'status':'discovery-only-not-allegations','selectionSQL':result['queries']['candidate_discovery_pool']['sql'],'sourceHashes':result['sourceHashes'],'rows':rows},indent=2,default=str))
c.close()
