"""Transparent within-stage detail-reference fallback and field-semantics audit.
New versioned derivative; no stale parsed cache is reused or originals modified.
"""
import datetime,hashlib,json,pathlib,time,duckdb,sqlite3
ROOT=pathlib.Path(__file__).resolve().parent;CACHE=pathlib.Path('/workspace/research-cache/tender-20260626')
c=duckdb.connect(str(CACHE/'linkage-v2.duckdb'));c.execute("SET memory_limit='1100MB';SET threads=2;SET preserve_insertion_order=false;SET temp_directory='/workspace/research-cache/tender-20260626/linkage-tmp'");c.execute('LOAD sqlite')
c.execute(f"ATTACH '{CACHE}/audit.duckdb' AS audit (READ_ONLY)");c.execute(f"ATTACH '{CACHE}/aoc_tenders.db' AS raw_a (TYPE sqlite, READ_ONLY)");c.execute(f"ATTACH '{CACHE}/tenders_vps.db' AS raw_t (TYPE sqlite, READ_ONLY)")
result={'asOf':'2026-10-06','sourceHashes':json.loads((ROOT/'analysis.json').read_text())['sourceHashes'],'derivationVersion':'linkage-v2-detail-reference-fallback','scriptSHA256':hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest(),'queries':{}}
def run(name,sql,fetch=True):
 start=time.time();q=c.execute(sql);rows=[dict(zip([d[0] for d in q.description],row)) for row in q.fetchall()] if fetch else None;result['queries'][name]={'sql':sql,'rows':rows,'seconds':round(time.time()-start,3)};(ROOT/'linkage-v2.json').write_text(json.dumps(result,indent=2,default=str));print(name,round(time.time()-start,2),json.dumps(rows,default=str)[:1500],flush=True);return rows
run('build_reference_fallback',r'''CREATE OR REPLACE TABLE award_reference AS SELECT internal_id,json_extract_string(try_cast(details_json AS JSON),'$."Tender Ref. No."') AS detail_reference FROM raw_a.aoc_details''',False)
run('reference_agreement',"SELECT count(*) AS award_rows,count(*) FILTER(WHERE nullif(trim(a.reference),'') IS NULL) AS listing_ref_missing,count(*) FILTER(WHERE nullif(trim(a.reference),'') IS NULL AND nullif(trim(d.detail_reference),'') IS NOT NULL) AS filled_from_same_internal_id,count(*) FILTER(WHERE nullif(trim(a.reference),'') IS NOT NULL AND nullif(trim(d.detail_reference),'') IS NOT NULL AND trim(a.reference)<>trim(d.detail_reference)) AS nonblank_ref_conflicts FROM audit.awards a LEFT JOIN award_reference d USING(internal_id)")
run('build_scoped_keys',"CREATE OR REPLACE TABLE award_keys AS SELECT a.internal_id,a.portal,a.buyer,a.tender_id,coalesce(nullif(trim(a.reference),''),nullif(trim(d.detail_reference),'')) AS reference_key FROM audit.awards a LEFT JOIN award_reference d USING(internal_id)",False)
run('build_unique_pairs',"CREATE OR REPLACE TABLE unique_pairs AS WITH n AS(SELECT internal_id,portal,buyer,tender_id,trim(reference) AS reference_key,count(*) OVER(PARTITION BY portal,buyer,tender_id,trim(reference)) AS k FROM audit.notices WHERE nullif(trim(reference),'') IS NOT NULL AND nullif(trim(buyer),'') IS NOT NULL AND nullif(trim(tender_id),'') IS NOT NULL),a AS(SELECT *,count(*) OVER(PARTITION BY portal,buyer,tender_id,reference_key) AS k FROM award_keys WHERE reference_key IS NOT NULL AND nullif(trim(buyer),'') IS NOT NULL AND nullif(trim(tender_id),'') IS NOT NULL) SELECT n.internal_id AS notice_internal_id,a.internal_id AS award_internal_id FROM n JOIN a USING(portal,buyer,tender_id,reference_key) WHERE n.k=1 AND a.k=1",False)
run('fallback_join_cardinality',"WITH n AS(SELECT portal,buyer,tender_id,trim(reference) AS reference_key,count(*) AS n FROM audit.notices WHERE nullif(trim(reference),'') IS NOT NULL AND nullif(trim(buyer),'') IS NOT NULL AND nullif(trim(tender_id),'') IS NOT NULL GROUP BY ALL),a AS(SELECT portal,buyer,tender_id,reference_key,count(*) AS n FROM award_keys WHERE reference_key IS NOT NULL AND nullif(trim(buyer),'') IS NOT NULL AND nullif(trim(tender_id),'') IS NOT NULL GROUP BY ALL) SELECT count(*) AS shared_keys,sum(n.n::HUGEINT*a.n) AS candidate_pairs,count(*) FILTER(WHERE n.n=1 AND a.n=1) AS one_to_one_keys,count(*) FILTER(WHERE n.n>1 AND a.n>1) AS many_to_many_keys FROM n JOIN a USING(portal,buyer,tender_id,reference_key)")
joined='FROM unique_pairs p JOIN audit.notices n ON n.internal_id=p.notice_internal_id JOIN audit.awards a ON a.internal_id=p.award_internal_id'
run('closing_field_semantics',"SELECT count(*) AS unique_pairs,count(*) FILTER(WHERE a.closing_at=n.published_at) AS award_closing_equals_notice_publication,count(*) FILTER(WHERE a.closing_at=n.closing_at) AS award_closing_equals_notice_closing,count(*) FILTER(WHERE a.closing_at::DATE=n.closing_at::DATE) AS same_closing_day,count(*) FILTER(WHERE a.closing_at::TIME=TIME '00:00:00') AS award_closing_midnight,count(*) FILTER(WHERE n.closing_at>a.aoc_at) AS award_before_notice_closing "+joined)
run('closing_semantics_by_buyer',"SELECT n.portal,n.buyer,count(*) AS unique_pairs,count(*) FILTER(WHERE a.closing_at=n.published_at) AS close_equals_published,count(*) FILTER(WHERE a.closing_at=n.closing_at) AS close_equals_close "+joined+" GROUP BY ALL ORDER BY unique_pairs DESC,n.portal,n.buyer LIMIT 20")
base="n.published_at>=TIMESTAMP '2021-06-16' AND n.published_at<=n.closing_at AND n.closing_at<=a.aoc_at AND a.aoc_at<=a.scraped_at AND regexp_full_match(n.tender_id,'[0-9]{4}_[A-Za-z][A-Za-z0-9]*_[0-9]+_[0-9]+') AND regexp_full_match(trim(a.bids_raw),'[0-9]+') AND try_cast(trim(a.bids_raw) AS INTEGER) BETWEEN 1 AND 1000 AND regexp_full_match(trim(a.value_raw),'[0-9]+(?:\\.[0-9]+)?') AND a.value_amount BETWEEN 100000 AND 10000000000"
run('candidate_eligibility_by_closing_semantics',"SELECT count(*) AS exact_key_chronology_eligible,count(*) FILTER(WHERE a.closing_at=n.closing_at) AS closing_timestamp_confirmed,count(*) FILTER(WHERE a.closing_at=n.published_at) AS award_closing_is_notice_publication,count(*) FILTER(WHERE cast(a.bids_raw AS INTEGER)=1 AND date_diff('minute',n.published_at,n.closing_at)<72*60) AS short_window_single_bid "+joined+" WHERE "+base)
columns="n.internal_id AS notice_internal_id,a.internal_id AS award_internal_id,n.portal,n.buyer,n.tender_id,k.reference_key AS reference,n.title,n.tender_category,n.product_category,n.tender_type,n.status,n.published_at,n.closing_at AS notice_closing,a.closing_at AS award_closing,a.aoc_at,a.bids_raw,a.value_raw,a.value_amount,date_diff('minute',n.published_at,n.closing_at)/60.0 AS listed_window_hours,nullif(trim(n.corrigendum_url),'') IS NOT NULL AS corrigendum_link,n.document_url AS notice_document_url,a.document_url AS award_document_url"
rows=run('bounded_field_semantics_leads',"SELECT "+columns+' '+joined+" JOIN award_keys k ON k.internal_id=a.internal_id WHERE "+base+" ORDER BY CASE WHEN cast(a.bids_raw AS INTEGER)=1 AND date_diff('minute',n.published_at,n.closing_at)<72*60 THEN 0 ELSE 1 END,listed_window_hours,n.tender_id LIMIT 12")
for row in rows:
 for db,table,idkey,cols,prefix in [('tenders_vps.db','tenders','notice_internal_id',['e_published_date','bid_submission_closing_date','detail_url'],'notice_'),('aoc_tenders.db','aoc_tenders','award_internal_id',['aoc_date','closing_date','detail_url'],'award_')]:
  s=sqlite3.connect(f'file:{CACHE}/{db}?mode=ro&immutable=1',uri=True);raw=s.execute(f"SELECT {','.join(cols)} FROM {table} WHERE internal_id=?",(row[idkey],)).fetchone();s.close();row.update({prefix+key:value for key,value in zip(cols,raw)})
(ROOT/'field-semantics-leads.json').write_text(json.dumps({'status':'discovery only; award closing semantics unresolved where publication matches','sourceHashes':result['sourceHashes'],'selectionSQL':result['queries']['bounded_field_semantics_leads']['sql'],'rows':rows},indent=2,default=str));c.close()
