#!/usr/bin/env node
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import {chromium} from 'playwright';
import {loadInvestigation} from '../investigation/load.mjs';
const result=await build({stdin:{contents:"export * from './src/data/metroSpending';",resolveDir:fileURLToPath(new URL('../..',import.meta.url)),loader:'ts'},bundle:true,platform:'node',format:'cjs',write:false,logLevel:'silent',target:'node24'});
const module={exports:{}};new Function('module','exports',result.outputFiles[0].text)(module,module.exports);
const {getMetroSpendingView,metroPlacement,METRO_CITY_LABELS,METRO_TOPIC_LABELS}=module.exports,{INVESTIGATION_REGISTRY:registry}=await loadInvestigation();
const dist=resolve(process.env.INVESTIGATION_DIST??'dist'),out=resolve(process.env.METRO_ARTIFACTS??'/tmp/metro-spending-browser');mkdirSync(out,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.woff2':'font/woff2'};
let server,base=process.env.INVESTIGATION_BASE_URL;
if(!base){server=createServer((req,res)=>{const file=resolve(dist,`.${new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname}`);if(!file.startsWith(`${dist}/`))return res.writeHead(403).end();try{res.writeHead(200,{'content-type':mime[extname(file)]??'application/octet-stream'}).end(readFileSync(file));}catch{res.writeHead(404).end();}});await new Promise(done=>server.listen(0,'127.0.0.1',done));base=`http://127.0.0.1:${server.address().port}`;}
base=base.replace(/\/$/u,'');
const binary=process.env.PLAYWRIGHT_CHROMIUM_PATH??'/usr/bin/chromium',browser=await chromium.launch(existsSync(binary)?{executablePath:binary}:{});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce',acceptDownloads:true}),errors=[],checks=[];
page.on('pageerror',error=>errors.push(error.message));page.setDefaultTimeout(30000);
const check=(value,label)=>{assert.ok(value,label);checks.push(label);};
const open=async(query='')=>{
 await page.goto(`${base}/#/allegations${query?'?'+query:''}`,{waitUntil:'domcontentloaded'});await page.locator('[data-allegations-page]').waitFor();
 // A hash-only navigation does not replace the document. Await its committed controls.
 const params=new URLSearchParams(query),city=Object.hasOwn(METRO_CITY_LABELS,params.get('al_city'))?params.get('al_city'):'all',topic=Object.hasOwn(METRO_TOPIC_LABELS,params.get('al_topic'))?params.get('al_topic'):'all';
 await page.waitForFunction(({cityLabel,topic,context,national,state})=>document.querySelector('.al-city-switch button[aria-pressed=true]')?.textContent===cityLabel&&document.querySelector('.al-topic-select select')?.value===topic&&document.querySelector('.al-context-trigger')?.getAttribute('aria-expanded')===String(context)&&document.querySelectorAll('.al-context-switches input')[0]?.checked===national&&document.querySelectorAll('.al-context-switches input')[1]?.checked===state,{cityLabel:METRO_CITY_LABELS[city],topic,context:params.get('al_context')==='1',national:params.get('al_national')!=='0',state:params.get('al_state_context')==='1'});
};
const param=async(key,value)=>page.waitForFunction(({key,value})=>(new URLSearchParams(location.hash.split('?')[1]??'').get(key))===value,{key,value});
const count=async(value,label)=>{await page.waitForFunction(value=>Number(document.querySelector('.al-scope-line strong')?.textContent.replaceAll(',',''))===value,value);check(true,label);};
const checkboxState=async(name,checked)=>page.waitForFunction(({name,checked})=>[...document.querySelectorAll('.al-context-switches label')].some(label=>label.textContent.trim()===name&&label.querySelector('input')?.checked===checked),{name,checked});
const toggleCheckbox=async(name,checked)=>{const input=page.getByRole('checkbox',{name,exact:true});if(await input.isChecked()!==checked)await input.click();await checkboxState(name,checked);};
const popup=page.locator('.atlas-evidence-popover'),context=page.getByRole('complementary',{name:'Budgets and contracts context'});
const overflow=async(label)=>check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${label}: no horizontal page overflow`);
try{
 const all=getMetroSpendingView(registry);check(all.contextRecords.length>0,'Metro review integrates real ordinary budget or procurement records');
 check(all.entries.some(row=>metroPlacement(registry,(row.record??row.relationship).geography).cities.includes('delhi')),'Source-backed Delhi entries available');
 check(all.entries.some(row=>metroPlacement(registry,(row.record??row.relationship).geography).cities.includes('mumbai')),'Source-backed Mumbai entries available');
 await open();await count(all.entries.length,'Default All reviewed preserves the complete new claim population');
 check(await page.getByRole('group',{name:'City focus'}).getByRole('button',{name:'All reviewed',exact:true}).getAttribute('aria-pressed')==='true','Default city focus remains All reviewed');check(await page.getByRole('checkbox',{name:'Include state context',exact:true}).isDisabled(),'All reviewed already contains statewide context');
 await page.getByRole('group',{name:'City focus'}).getByRole('button',{name:'Delhi',exact:true}).click();await param('al_city','delhi');await count(getMetroSpendingView(registry,{}, {city:'delhi'}).entries.length,'Delhi exact-locality and national-context count matches the data selector');
 await toggleCheckbox('Include national context',false);await param('al_national','0');await count(getMetroSpendingView(registry,{}, {city:'delhi',includeNational:false}).entries.length,'National-only context can be excluded from Delhi view');
 await toggleCheckbox('Include state context',true);await param('al_state_context','1');await count(getMetroSpendingView(registry,{}, {city:'delhi',includeNational:false,includeStateContext:true}).entries.length,'Optional state context includes relevant DL records without inferring city allocation');
 await page.reload();await page.locator('[data-allegations-page]').waitFor();check(await page.getByRole('checkbox',{name:'Include state context',exact:true}).isChecked(),'State-context URL survives reload independently of national scope');
 await page.goBack();await param('al_state_context',null);await checkboxState('Include state context',false);check(!await page.getByRole('checkbox',{name:'Include state context',exact:true}).isChecked(),'Browser Back restores strict city-only scope');
 await page.getByRole('group',{name:'City focus'}).getByRole('button',{name:'Mumbai',exact:true}).click();await param('al_city','mumbai');await count(getMetroSpendingView(registry,{}, {city:'mumbai',includeNational:false}).entries.length,'Mumbai view excludes statewide Maharashtra and unplaced claims');
 await page.goBack();await param('al_city','delhi');await checkboxState('Include national context',false);check(!await page.getByRole('checkbox',{name:'Include national context'}).isChecked(),'Browser Back restores independent national-context choice');
 await page.goForward();await param('al_city','mumbai');await page.reload();await page.locator('[data-allegations-page]').waitFor();check(await page.getByRole('group',{name:'City focus'}).getByRole('button',{name:'Mumbai',exact:true}).getAttribute('aria-pressed')==='true','Reload preserves city URL state');
 await toggleCheckbox('Include national context',true);await page.getByRole('combobox',{name:'Spending topic'}).selectOption('defence');await param('al_topic','defence');await count(getMetroSpendingView(registry,{}, {city:'mumbai',topic:'defence'}).entries.length,'Defence topic uses the reviewed defence namespace');
 await open('al_city=both&al_context=1');await context.waitFor();check((await context.textContent()).includes('separate from the claims count'),'Ordinary financial context is explicitly separate from allegations');
 const first=context.locator('[data-metro-context]').first();await first.waitFor();const recordId=await first.getAttribute('data-metro-context');const original=registry.records.find(row=>row.id===recordId);check(!all.entries.some(row=>row.id===recordId),'Ordinary selected record is absent from the allegation entry population');
 await context.getByRole('searchbox',{name:'Search budgets and contracts'}).fill('no-context-match-444');await context.getByRole('button',{name:'Search',exact:true}).click();await param('al_cq','no-context-match-444');await page.getByRole('heading',{name:'No matching financial context'}).waitFor();check(await context.locator('[data-metro-context]').count()===0,'Context search has an honest empty state');
 await page.reload();await context.waitFor();check(await context.getByRole('searchbox',{name:'Search budgets and contracts'}).inputValue()==='no-context-match-444','Context search survives reload');
 await context.getByRole('searchbox',{name:'Search budgets and contracts'}).fill('');await context.getByRole('button',{name:'Search',exact:true}).click();await param('al_cq',null);await first.waitFor();await first.click();await popup.waitFor();check(await popup.getAttribute('data-selection-id')===recordId,'Ordinary context opens its exact existing evidence reader');check((await popup.textContent()).includes(original.response),'Financial context retains the original response or limitation');check(await page.getByRole('dialog').count()===1,'Context does not open a competing reader');
 await popup.getByRole('button',{name:'Close evidence details'}).click();await page.locator('.al-view-switch').getByRole('button',{name:'Network',exact:true}).click();await param('al_view','network');check(new URLSearchParams(new URL(page.url()).hash.split('?')[1]).get('al_city')==='both','Network mode preserves city scope');await page.locator('.al-view-switch').getByRole('button',{name:'Map',exact:true}).click();await param('al_view',null);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export allegations evidence and responses',exact:true}).click();const packet=JSON.parse(readFileSync(await(await download).path(),'utf8'));check(packet.metroScope.city==='both'&&packet.metroScope.contextRecordIds.includes(recordId),'View export records the city scope and ordinary-context seed IDs');check(packet.missingIds.length===0,'View export remains source-closed');check(packet.records.some(row=>row.id===recordId),'Ordinary context is included in the evidence packet');
 await open('al_city=mumbai&al_state=DL');await page.getByRole('group',{name:'City focus'}).getByRole('button',{name:'Mumbai',exact:true}).click();await param('al_state',null);check(true,'Explicit city choice clears a conflicting state filter');
 await open('al_city=bad-value&al_topic=bad-value');check(await page.getByRole('group',{name:'City focus'}).getByRole('button',{name:'All reviewed',exact:true}).getAttribute('aria-pressed')==='true','Invalid city URL value falls back to All reviewed');check(await page.getByRole('combobox',{name:'Spending topic'}).inputValue()==='all','Invalid topic URL value falls back to All topics');
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});await open('al_city=both&al_context=1');await context.waitFor();if(width<=767){await page.waitForFunction(()=>{const panel=document.getElementById('al-context-index');if(!panel)return false;const controls=[panel.querySelector('h2'),panel.querySelector('input[type=search]')];return controls.every(control=>{if(!control)return false;const box=control.getBoundingClientRect();return box.top>=0&&box.bottom<=innerHeight&&box.left>=0&&box.right<=innerWidth;});});check(true,`${width}px opening budgets makes the context heading and search visible`);}await overflow(`${width}px context`);await page.screenshot({path:resolve(out,`metro-context-${width}.png`)});await open(`al_city=both&al_selection=${encodeURIComponent(`record:${recordId}`)}`);await popup.waitFor();await overflow(`${width}px reader`);const box=await popup.boundingBox();check(box.x>=0&&box.x+box.width<=width+1&&box.y>=0&&box.y+box.height<=1001,`${width}px context reader remains within the viewport`);}
 check(errors.length===0,`No runtime exceptions (${errors.length})`);writeFileSync(resolve(out,'acceptance.json'),JSON.stringify({base,checks,errors},null,2)+'\n');console.log(`Metro spending browser: ${checks.length} checks passed; ${out}`);
}finally{await browser.close();if(server)await new Promise(done=>server.close(done));}
