import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight } from 'lucide-react';
import analysis from '../../research/funding-investigations/analysis-ui.json';
import { FUNDING_CASES } from '../data/fundingInvestigations';

const repository = 'https://github.com/occult-kranti/india-corporate-intelligence/blob/codex/education-funding-intelligence';

export default function FundingSearches() {
  const [queryId, setQueryId] = useState(analysis.queries[0].id);
  const [identityQuery, setIdentityQuery] = useState('');
  const query = analysis.queries.find(row => row.id === queryId)!;
  const identities = analysis.identityCandidates.filter(row => row.labelKey.includes(identityQuery.toLowerCase().trim()));
  return <section className="fi-wide-section" data-fi-analysis="">
    <header><h2>Search across the whole record</h2><p>Thirteen fixed research questions were run across {analysis.counts.sources.toLocaleString()} source entries, {analysis.counts.entities.toLocaleString()} entity records and {analysis.counts.edges.toLocaleString()} retained relationships. These counts include inherited material, duplicates and unreviewed candidates.</p><p>These are lexical search results and exact-edge navigation exercises. The school, health and border searches include off-topic results; the later NDTV correction was absent from the first five source results. Rankings do not measure the truth or likelihood of a claim.</p></header>
    <label className="fi-atlas-select">Research question<select aria-label="Cross-sector research question" value={queryId} onChange={event => setQueryId(event.target.value)}>{analysis.queries.map(row => <option key={row.id} value={row.id}>{row.sector} · {row.id.split(':').slice(-1)[0].replace(/-/g, ' ')}</option>)}</select></label>
    <section className="fi-search-results" aria-label="Cross-sector search candidates"><h3>{query.question}</h3><p className="fi-section-note">{query.positiveScores.toLocaleString()} of {query.candidateCount.toLocaleString()} candidate records have a nonzero lexical score. Five leading source candidates are shown below; every zero and off-topic result is retained in the downloadable research output. Original source inspection is required before use.</p>{query.topSources.map((row, index) => <article key={row.id}>
      <span className="fi-case-number">{String(index + 1).padStart(2, '0')}</span><div><span className="fi-status">{row.corpusOrigin === 'funding-stream' ? 'Current research source' : 'Inherited source · not newly re-read'}</span><h4>{row.label}</h4><p>{row.source.publisher} · {row.source.publishedAt ?? 'Publication date not established'}</p><a href={row.source.url} target="_blank" rel="noreferrer">Inspect original source<ArrowUpRight size={13} aria-hidden="true" /></a><details><summary>Relevance score and source boundary</summary><p>BM25: {row.bm25.toFixed(3)}. This score measures word overlap, not reliability, causation or wrongdoing.</p><p>{'locator' in row.source ? row.source.locator : 'No retained locator.'}</p>{row.source.limitations.map((text, i) => <p key={i}>{text}</p>)}</details></div>
    </article>)}</section>
    <details className="fi-search-related"><summary>Leading source, entity and case candidates</summary>{query.topCandidates.map(row => {
      const item = FUNDING_CASES.find(item => item.id === row.id);
      return <p key={row.id}>{item ? <Link to={`/funding-investigations?fi_case=${encodeURIComponent(item.id)}`}>{row.label}</Link> : row.label}<small> · {row.kind} · unjudged relevance candidate</small></p>;
    })}</details>
    <section className="fi-coverage-track"><h3>Recorded paths, with their stopping points</h3><p>These six navigation exercises preserve the original direction, stage and source of each relationship. Traversing an arrow backwards does not reverse a payment. None introduces a new connection.</p><div className="fi-coverage-list">{analysis.pathDemonstrations.map(row => {
      const item = FUNDING_CASES.find(item => item.entityIds.includes(row.startEntityId));
      return <article key={row.id}><div><h4>{row.id.replace(/-/g, ' ')}</h4><span className="fi-status">{row.contextEdgesExplicitlyEnabled ? 'Documentary context explicitly included' : 'Context-only edges excluded'}</span></div><div><p>{row.pathCount} retained paths · {row.sourceCount} source entries · {row.acquisitionQuestionCount} next-record questions.</p>{item && <Link to={`/funding-investigations?fi_case=${encodeURIComponent(item.id)}&fi_view=network`}>Inspect the research network</Link>}<p>{row.truncated ? 'Output hit its path limit.' : 'This bounded traversal did not hit its path limit.'} This is not proof of a complete network.</p></div></article>;
    })}</div></section>
    <section className="fi-coverage-track"><h3>Identity review queue</h3><p>{analysis.identityCandidates.length} repeated labels occur across namespaces. They remain separate identities. A matching name alone cannot establish the same legal entity, beneficiary or person.</p><label className="fi-identity-filter">Filter repeated names<input type="search" aria-label="Filter identity review queue" value={identityQuery} onChange={event => setIdentityQuery(event.target.value)} placeholder="Institution or company name" /></label><p className="fi-section-note">{identities.length} matching name groups · no automatic identity links approved</p>{identities.map(row => <details key={row.labelKey} className="fi-identity-candidate"><summary>{row.entities[0].label} · {row.entities.length} separate records{row.involvesNewStream ? ' · includes current research' : ''}</summary><p>{row.reason}</p>{row.entities.map(entity => <article key={entity.entityId}><h4>{entity.label}</h4><p>{entity.identityBasis}</p><small>{entity.entityId}</small><div>{entity.sourceURLs.map(url => <a key={url} href={url} target="_blank" rel="noreferrer">{new URL(url).hostname}<ArrowUpRight size={12} aria-hidden="true" /></a>)}</div></article>)}</details>)}</section>
    <section className="fi-coverage-track"><h3>Reproduce and challenge the search</h3><p>{analysis.sourceFamilies.exactURLDuplicateGroups} exact-URL groups recur in the corpus. Repetition across pages is not independent corroboration. A reused budget URL can also serve different documents over time; inspect retained captures and dates.</p><p>The repository retains every ranking, source metadata and exact path in a lossless compressed JSON artifact, with checksums and the fixed query list. It contains no pooled cash total or estimated guilt probabilities.</p><div className="fi-analysis-links"><a href={`${repository}/research/funding-investigations/analysis-review.md`} target="_blank" rel="noreferrer">Read the retrieval review</a><a href={`${repository}/${analysis.rawRankingsPath}`} target="_blank" rel="noreferrer">Full rankings and paths (.json.gz)</a><a href={`${repository}/scripts/funding-investigations/trace.py`} target="_blank" rel="noreferrer">Reproducible analysis tool</a></div></section>
  </section>;
}
