"""Curated case assembly. Monetary stages deliberately remain separate."""
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parent
OUT=ROOT.parent/'corporate.json'
D={'snapshot':'2026-10-07','sources':[],'entities':[],'relationships':[],'records':[],'localities':[]}
ROUTE='/follow-the-money'
manifest=json.loads((ROOT/'manifest.json').read_text())
receipts={r['sourceId']:r for r in manifest['receipts']}
def source(id,title,publisher,date,locator,summary,tier='documented',limitations=[]):
 r=receipts[id]
 D['sources'].append(dict(id=id,title=title,url=r['url'],publisher=publisher,publishedAt=date,retrievedAt='2026-10-07',locator=locator,summary=summary,tier=tier,limitations=limitations+[f"Retained original/extract SHA-256 receipt: research/raw/deep-investigation/corporate-evidence/manifest.json ({id})."]))
def geo(ids,states=[],note='National company, sale or policy context; no state-level spending allocation inferred.',basis='national-context'):
 return [dict(scope='multi-state' if len(states)>1 else 'state' if states else 'national',stateCodes=states,localityIds=[],basis=basis,note=note,sourceIds=ids)]
def dim(ids,domains,layers,states=[],note=None):
 return dict(sourceIds=ids,domains=domains,layers=layers,geography=geo(ids,states,note or ('Documented asset/project location; neither headquarters nor inferred expenditure.' if states else 'National company, sale or policy context; no state-level spending allocation inferred.'),'project-location' if states else 'national-context'),route=ROUTE,limitations=[])
def entity(id,label,type,ids,domains,identity,summary,family='capital',states=[],canonical=None):
 r=dict(id=id,label=label,type=type,family=family,resolved=True,identityBasis=identity,summary=summary,**dim(ids,domains,['legal'] if family=='enforce' else ['organisations'],states));
 if canonical:r['canonicalId']=canonical
 D['entities'].append(r)
def amount(v,stage,period,unit='crore',currency='INR'):return dict(value=v,currency=currency,unit=unit,stage=stage,period=period)
def edge(id,a,b,label,summary,ids,domains,layers,kind='contracted',tier='documented',status='documented',date=None,end=None,asof=None,amounts=[],states=[],limits=[],alternatives=[],falsifier=None,responses=[],records=[]):
 D['relationships'].append(dict(id=id,**{'from':a,'to':b},kind=kind,label=label,tier=tier,status=status,statusAsOf=asof or date,fromDate=date,toDate=end,dateBasis='Exact event or financial-position date from the cited record.' if date else 'Historical period is stated in the summary; an exact day is not inferred.',summary=summary,alternativeExplanations=alternatives,falsifier=falsifier,responseIds=responses,recordIds=records,amounts=amounts,**{**dim(ids,domains,layers,states),'limitations':limits}))
def record(id,title,summary,ids,entities,edges,domains,layers,date,asof,period,response,alternatives,falsifier,amounts=[],states=[],kind='investigation-case',tier='documented',status='source-bounded',end=None,limits=[]):
 D['records'].append(dict(id=id,title=title,summary=summary,kind=kind,tier=tier,status=status,statusAsOf=asof,fromDate=date,toDate=end,dateBasis='Dates delimit documented events; statusAsOf is the latest supporting source date, not a claim of continuous current legal status.',entityIds=entities,relationshipIds=edges,period=period,response=response,alternativeExplanations=alternatives,falsifier=falsifier,amounts=amounts,**{**dim(ids,domains,layers,states),'limitations':limits}))

source('air-india-award','Air India winning bid, rival and retained public assets','Ministry of Finance / PIB','2021-10-08','PRID1762146; opening paragraph and bid comparison','Winning EV ₹18,000cr; rival ₹15,100cr; reserve ₹12,906cr; excluded non-core assets valued ₹14,718cr. Describes debt resizing and release of public guarantees before closing.')
source('air-india-close','Air India strategic disinvestment completed','Ministry of Finance / PIB','2022-01-27','PRID1792950; first two paragraphs','Government received ₹2,700cr; ₹15,300cr debt remained in sold airlines; shares transferred to Talace, wholly owned by Tata Sons.')
source('air-budget-2022','Civil Aviation Demand 8, Budget 2022–23','Government of India, Union Budget','2022-02-01','PDF pp1–2, printed pp30–31, line19.01–19.03; Revised2021–22 column','AIAHL equity revised estimate ₹62,057cr split between guaranteed debt, SLB lease borrowings and other past dues.',limitations=['A revised estimate is not actual expenditure.'])
source('air-budget-actual-2023','Civil Aviation Demand 8, Budget 2023–24: actual debt-cleanup funding','Government of India, Union Budget','2023-02-01','PDF p2, line21.01–21.03, Actual2021–22 column','Actual AIAHL equity ₹62,365.40cr, including ₹13,754.40cr for past dues/liabilities, compared with prior RE ₹13,446cr.',limitations=['Budget actual is central-government equity expenditure, not a beneficiary-wise creditor receipt ledger.'])
source('airports-receipts-2022','AAI six-airport upfront and concession receipts','Ministry of Civil Aviation / PIB','2022-12-12','PRID1882715, airport table and paragraph beginning Further','Mangaluru upfront receipt ₹221.88cr; concession fees ₹710.88cr for all six airports through October2022.',limitations=['The six-airport concession receipt must not be assigned to Mangaluru. Snapshot is October2022.'])
source('mangaluru-concession','AAI–Adani Mangaluru concession signed 14 February 2020','Ministry of Civil Aviation, original executed agreement','2020-02-14','Original PDF pp5–6 (parties/CIN/award),27 (Article3),108–110 (Article27); retained original-page excerpt','Named concessionaire CIN U63030GJ2019PLC110062; AEL selected bidder; 50-year concession from COD; domestic fee ₹115 and international twice domestic with revision rules.',limitations=['Original PDF has imperfect OCR; cited pages are retained for visual review. Full original 74MB retained in workspace cache; repository holds complete extract and nine-page excerpt. Fee is the original formula, not a current tariff or an asset-sale price.'])
source('ael-report-2026','Adani Enterprises integrated annual report FY2025–26','Adani Enterprises, NSE archive',None,'Original PDF pp266–269 (standalone note50, printed524–531);280 (CIN list);288–289 (consolidated shareholding printed568–571)','PKCL74%AEL; Mangaluru51%AEL49%AAHL; AAHL100%AEL. Note50 discloses services, loans, receivables and parent lending.',limitations=['Company statutory financial disclosure. Related-party income/receivables are not proof of state cash reaching the parent, of arm’s-length value, or of wrongful extraction. Full original in workspace cache; complete extract and eight-spread excerpt retained.'])
source('coal-block-allotments','Ministry of Coal tranche-wise allotments','Ministry of Coal',None,'Allotment section; Parsa East & Kanta Basan row, allotment31-03-2015','The block in Chhattisgarh is allotted to Rajasthan Rajya Vidyut Utpadan Nigam Ltd for power, rather than conveyed to its private MDO.',limitations=['Fetched May2023-path allocation table; no claim this is a current complete national register.'])
source('pekb-guarantee-2016','PEKB: government direction to invoke performance bank guarantee','Ministry of Coal','2016-05-03','Letter paragraph2–3 and bank-guarantee calculation annexure','Directs invocation of ₹16.48452cr from RRVUNL’s performance bank guarantee for prior-allocation delays.',limitations=['Direction to invoke is not a bank debit receipt or proof of final collection. Subsequent appeal/recovery record not retrieved.'])
source('parsa-sc-2019','Parsa Kente Collieries v RRVUNL, Civil Appeal9023/2018','Supreme Court of India','2019-05-27','Paras2–2.2,11.1–11.3,12; original PDF pp2–5,21–27','Records tender acceptance12-May2006, LoI23-Oct2006 and CMDA16-Jul2008. Restores escalation award; confirms rejection of ₹78cr fixed-cost award and escrow claim.',limitations=['Judgment reports ₹837/MT at para2.2 and ₹895/MT at para11.1; do not resolve discrepancy by inventing a single tariff. It is separate from the 2025 road-transport case.'])
source('parsa-transport-2025','Adani-led firm charged Rajasthan PSU over ₹1,400cr: court finding and stay','Scroll; Shreegireesh Jalihal','2025-11-24','Sections on July5 judgment, July18 High Court stay and final response paragraph','Reports road-cost reimbursement dispute, over₹1,400cr paid, ₹50lakh fine, audit direction and stay; reporters sought both firms’ response.','reported',['Original 2025 trial judgment and High Court order not retrieved; source’s court description is reported, not independently authenticated. Later appellate status not verified.'])
source('hzl-sc-2021','National Confederation of Officers Associations v Union of India','Supreme Court of India','2021-11-18','Writ Petition229/2014, paras7–11,37–44,57–61; PDF pp6–10,30–36,55–62','History of nationalised HZL, ₹445cr26% sale to SOVL, later64.92% holding; permits residual public-stake sale and orders a regular CBI case.',limitations=['Investigation direction and prima-facie grounds are not a conviction or a proved loss. The ruling does not invalidate the completed strategic sale.'])
source('hzl-government-response-2022','DIPAM disputes CBI premises in HZL sale inquiry','ThePrint; Apoorva Mandhani','2022-02-10','Account of withdrawn recall application; BNP adviser and valuer-selection explanations','Government said contemporaneous records contradicted several CBI premises; withdrawal allowed pursuit of review.','reported',['Court application itself not retrieved; attribute explanations to DIPAM as reported.'])
source('hzl-fir-2022','Government tells Supreme Court CBI registered HZL case','Financial Express','2022-04-30','Opening paragraphs reporting29-April2022 hearing','Solicitor General reportedly stated FIR registered and status report to follow.','reported',['No primary FIR, charge-sheet, closure report or later merits judgment retrieved. Does not establish current2026 investigation status.'])
source('vedanta-proposal-2023','Vedanta Q3FY23: proposed zinc sale to Hindustan Zinc','Vedanta Limited','2023-01-27','PDF p1, Strategic initiative to unlock shareholder value; company CIN in header','Proposed cash consideration US$2,981million, including US$562million milestone-linked deferred consideration; company says transaction would unlock value for both firms.','self-reported',['Corporate rationale is the company’s position; proposed consideration is not a paid transfer.'])
source('hzl-objection-2023','Government opposes HZL related-party zinc purchase; HZL response','The Hindu','2023-02-20','Article quoting17-February Mines Ministry letter and20-February HZL reply','Government recorded dissent and urged cashless alternatives; HZL said shareholder approval required and notice not issued.','reported',['Original BSE filing download returned HTTP403; retained source is reporting of that filing, not a primary copy.'])
source('hzl-target-2023','HZL proposed acquisition structure and government objection','The New Indian Express','2023-02-21','Opening five paragraphs','Names Mauritius THL Zinc Ltd, wholly owned by THL Zinc Ventures Ltd, itself wholly owned by Vedanta Limited.','reported',['No Mauritius registry identifier retrieved. Identity is bounded to the named transaction; no similarly named entities are merged.'])
source('hzl-lapse-2023','HZL US$2.98bn proposal reported lapsed','Reuters via Business Standard','2023-05-02','Full article; government-source status and final response paragraph','Two unnamed government sources said shareholder approval window lapsed; Reuters reported no immediate company or government email response.','reported',['Lapse is reported from unnamed government sources, not an independently fetched board withdrawal. No completed2023 acquisition is established.'])

AIR=['capital','finance','debt-relief','governance'];AP=['capital','public-works','finance'];COAL=['energy','capital','finance','governance'];ZINC=['energy','capital','finance','governance']
entity('goi','Government of India','government',['air-india-award','hzl-sc-2021'],AIR,'Named seller/shareholder in PIB closing release and Supreme Court judgment.','Public seller of Air India and historical shareholder in Hindustan Zinc.','state')
entity('air-india','Air India Limited','company',['air-india-close'],AIR,'Exact company named in the government’s closing announcement; transaction identity limited to27-Jan2022.','Airline whose100% government equity transferred to Talace; transaction also included AIXL and50%AISATS.')
entity('talace','Talace Private Limited','company',['air-india-close'],AIR,'Exact strategic-partner legal name and wholly-owned parent expressly named in PIB. No guessed CIN.','Buyer that paid government ₹2,700cr cash for Air India transaction.')
entity('tata-sons','Tata Sons Private Limited','company',['air-india-close'],AIR,'Named legal parent of Talace in government closing announcement.','Wholly owned Talace at the sale-closing date.')
entity('aiahl','Air India Asset Holding Limited','company',['air-india-award','air-budget-actual-2023'],AIR,'Exact government holding vehicle named in award release and line21 of Demand8.','Retained excluded non-core assets and received public equity for historical airline obligations.','state')
entity('ajay-singh-consortium','Consortium led by Ajay Singh (Air India bidder)','consortium',['air-india-award'],AIR,'Transaction-specific bidder description; not merged with SpiceJet Limited.','The other financial bidder offered ₹15,100cr enterprise value.')
entity('aai','Airports Authority of India','authority',['mangaluru-concession','airports-receipts-2022'],AP,'Statutory authority named as contracting party in executed concession.','Public airport authority granting operating rights and receiving concession payments.','state')
entity('mangaluru-airport','Mangaluru International Airport (public airport asset)','asset',['mangaluru-concession'],AP,'Named airport/site in contract; asset distinct from concessionaire legal company.','AAI asset under50-year operations, management and development concession.',family='state',states=['KA'])
entity('mangaluru-spv','Mangaluru International Airport Limited','company',['mangaluru-concession','ael-report-2026'],AP,'CIN U63030GJ2019PLC110062 appears under Adani Mangaluru International Airport Limited in2020 contract and current name in FY26 report PDFp280. Exact CIN establishes continuity; rename date not inferred.','Concession SPV held51% directly by AEL and49% by AAHL at31-Mar2026.',states=['KA'])
entity('ael','Adani Enterprises Limited','company',['ael-report-2026','parsa-sc-2019'],COAL+['public-works'],'NSE ADANIENT annual-report issuer, retained canonical co:adani-enterprises; named bidder and service counterparty in original court record.','Listed parent; airport investment and coal-mining-service counterparty.',canonical='co:adani-enterprises')
entity('aahl','Adani Airport Holdings Limited','company',['ael-report-2026'],AP,'Full legal name in consolidated shareholding schedule;100% directly owned by AEL. No registry-mirror CIN needed.','Airport holding company and49% direct shareholder in Mangaluru at31-Mar2026.')
entity('six-airport-concessions','Six AAI concessions in the2018–19 round','asset-set',['airports-receipts-2022'],AP,'Explicitly enumerated Ahmedabad, Jaipur, Lucknow, Guwahati, Mangaluru, Thiruvananthapuram; cohort is not a legal person.','Receipt denominator for all-six monthly concession fees.','state')
entity('coal-ministry','Ministry of Coal','ministry',['coal-block-allotments','pekb-guarantee-2016'],COAL,'Named allotment authority and bank-guarantee-direction issuer.','Allots public coal rights and directs performance-guarantee enforcement.','state')
entity('rrvunl','Rajasthan Rajya Vidyut Utpadan Nigam Limited','company',['coal-block-allotments','parsa-sc-2019'],COAL,'Same exact state utility named in original allotment table and court cause title; original block row anchors identity.','Public allottee and contracting purchaser of coal; joint-venture counterparty to AEL.','state')
entity('pekb','Parsa East & Kanta Basan coal block','asset',['coal-block-allotments'],COAL,'Exact block name plus Chhattisgarh and31-Mar2015 allotment identify the asset; distinct from separate Parsa/Kente Extension blocks.','Coal right allotted to RRVUNL, with mining services supplied through PKCL.',family='state',states=['CG'])
entity('pkcl','Parsa Kente Collieries Limited','company',['parsa-sc-2019','ael-report-2026'],COAL,'CIN U10200RJ2007PLC025173 in original FY26 reportPDFp280; same exact legal entity in Supreme Court cause title and canonical energy:parsa-kente-collieries.','Joint-venture coal contractor,74% held by AEL at31-Mar2026; state utility remains allottee.',states=['CG'],canonical='energy:parsa-kente-collieries')
entity('supreme-court','Supreme Court of India','court',['parsa-sc-2019','hzl-sc-2021'],COAL+['justice'],'Original signed judgments identify court, cause titles, case numbers and dates.','Adjudicated PKCL arbitration and directed HZL sale investigation.','enforce')
entity('hzl','Hindustan Zinc Limited','company',['hzl-sc-2021','hzl-target-2023'],ZINC,'Exact nationalised company and sale subject in WritPetition229/2014; same exact listed company named in2023 proposal reporting.','Former government company; government was minority shareholder during2023 related-party proposal.',states=['RJ'])
entity('sovl','Sterlite Opportunities & Ventures Limited','company',['hzl-sc-2021'],ZINC,'Exact strategic partner named in original Supreme Court judgment. Kept distinct from later Vedanta Limited; unreviewed merger continuity not asserted.','Acquired26% government stake in2002 and reached64.92% after open offer and call option.')
entity('vedanta','Vedanta Limited','company',['vedanta-proposal-2023','hzl-target-2023'],ZINC,'Original corporate release gives CIN L13209MH1965PLC291394; not confused with Vedanta Resources parent.','Proposed seller of zinc-international business; HZL controlling shareholder in2023.')
entity('thl-ventures','THL Zinc Ventures Limited (Mauritius)','company',['hzl-target-2023'],ZINC,'Full legal name,jurisdiction and transaction-specific parent relation in opened reporting; registry identifier not retrieved.','Reported wholly owned Vedanta subsidiary and owner of proposed target THL Zinc.')
entity('thl-zinc','THL Zinc Limited (Mauritius)','company',['hzl-target-2023'],ZINC,'Full legal name,jurisdiction and exact2023 proposed acquisition in opened source; no address-only match.','Proposed overseas-zinc holding-company target; acquisition completion not established.')
entity('mines-ministry','Ministry of Mines','ministry',['hzl-objection-2023'],ZINC,'Named author of17-Feb2023 shareholder objection letter as reported by The Hindu.','Government minority-shareholder representative opposing proposed cash deal.','state')
entity('cbi','Central Bureau of Investigation','agency',['hzl-sc-2021'],ZINC+['justice'],'Original judgment paras60–61 names CBI and directs regular case.','Agency directed to investigate2002 HZL sale; no conviction inferred.','enforce')

# AIR INDIA: sale consideration, debt in the acquired companies and retained public obligations are different perimeters.
aircase=['air-india-talace']
edge('talace-owner','tata-sons','talace','100% legal ownership at closing','PIB identifies Talace as wholly owned by Tata Sons.',['air-india-close'],AIR,['organisations'],kind='owns',date='2022-01-27',records=aircase)
edge('air-shares-transfer','goi','talace','100% Air India shares transferred','Government transferred100% Air India shares, including100%AIXL and50%AISATS interests, on27-Jan2022.',['air-india-close'],AIR,['organisations'],kind='disinvestment',date='2022-01-27',records=aircase)
edge('talace-controls-air','talace','air-india','Acquired Air India equity','Sale-specific control as of closing; later mergers/investors not inferred.',['air-india-close'],AIR,['organisations'],kind='owns',date='2022-01-27',records=aircase)
edge('air-sale-cash','talace','goi','₹2,700cr cash received by public seller','Closing receipt, distinct from₹18,000cr winning enterprise value.',['air-india-award','air-india-close'],AIR,['funding'],kind='payment',date='2022-01-27',amounts=[amount(2700,'cash consideration received by government','2022-01-27'),amount(18000,'winning enterprise-value bid; includes retained debt','2021-10-08')],records=aircase)
edge('air-retained-debt','talace','air-india','₹15,300cr debt remained in acquired airlines','PIB says₹15,300cr debt retained in Air India and AIXL. This is debt in the sold businesses, not cash government received or debt retained by government.',['air-india-close'],AIR,['funding'],kind='acquisition-debt',date='2022-01-27',amounts=[amount(15300,'debt retained within sold Air India/AIXL perimeter','2022-01-27')],records=aircase)
edge('air-public-assets','air-india','aiahl','Excluded non-core assets remain public','Award announcement excludes land/buildings and other non-core assets valued₹14,718cr; government holding vehicle is designated recipient. No realised disposal receipt is claimed.',['air-india-award'],AIR,['organisations','funding'],kind='retained-assets',date='2021-10-08',amounts=[amount(14718,'announced value of excluded non-core assets; not sale proceeds','2021-10-08')],records=aircase)
edge('aiahl-public-equity','goi','aiahl','Actual FY22 public equity ₹62,365.40cr','Budget2023–24 actual column updates prior RE₹62,057cr. Components actual₹36,254cr guaranteed borrowings,₹12,357cr SLB lease borrowings,₹13,754.40cr past dues. This funds historical obligations of the public airline and is not a lender waiver to Talace.',['air-budget-2022','air-budget-actual-2023'],AIR,['funding'],kind='equity-infusion',date='2021-04-01',end='2022-03-31',asof='2023-02-01',amounts=[amount(62365.4,'actual central-government equity expenditure to AIAHL','FY2021–22'),amount(62057,'revised estimate for equity infusion; superseded by actual','FY2021–22')],records=aircase,limits=['₹62,365.40cr is not a calculated net taxpayer loss; asset proceeds, avoided future losses and creditor recoveries require separate evidence.'])
edge('air-rival-bid','ajay-singh-consortium','air-india','Other bid ₹15,100cr EV','Two financial bids from seven EOIs; five disqualified under requirements. Rival was a consortium led by Ajay Singh, not automatically SpiceJet as legal bidder.',['air-india-award'],AIR,['procurement'],kind='bid',date='2021-10-08',amounts=[amount(15100,'unsuccessful enterprise-value bid','2021-10-08'),amount(12906,'reserve enterprise value','2021-10-08')],records=aircase)
record('air-india-talace','Air India: follow the sale cash, acquired debt and public cleanup separately','Tata Sons→Talace acquired the public airline. The government actually received₹2,700cr;₹15,300cr debt stayed inside the acquired airlines. Excluded non-core assets valued₹14,718cr went to the public holding perimeter. The later Union Budget reports₹62,365.40cr actual FY22 equity to AIAHL—₹308.40cr above the prior₹62,057cr estimate, driven by the past-dues component. These are different ledgers, not quantities to net into an unsupported “giveaway”.',['air-india-award','air-india-close','air-budget-2022','air-budget-actual-2023'],['goi','tata-sons','talace','air-india','aiahl','ajay-singh-consortium'],[e['id'] for e in D['relationships'] if e['recordIds']==aircase],AIR,['organisations','funding','procurement','policy','review'],'2021-10-08','2023-02-01','Award8-Oct2021; closing27-Jan2022; actual FY2021–22 expenditure published1-Feb2023','Government says excessive losses/debt required an EV bidding model to improve competition, two bids exceeded reserve, and guarantees were to be released before closing. The record contains no adjudicated corruption finding.',['A loss-making airline may require balance-sheet cleanup to obtain competitive bids; historical creditor repayment is not automatically a benefit created for the buyer.','₹14,718cr is asset valuation, not monetisation revenue, and cannot be subtracted as if realised.','Actual expenditure differs from the prior estimate; the difference is a normal reconciliation question until creditor-level evidence explains it.'],'Obtain AIAHL audited ledger and creditor settlements, SPA schedules, independent valuation and realised asset-sale receipts; these could establish which liabilities/assets transferred and test any claimed net public cost.',amounts=[amount(2700,'sale cash actually received','2022-01-27'),amount(15300,'debt retained in acquired airlines','2022-01-27'),amount(62365.4,'actual government equity infusion into AIAHL','FY2021–22'),amount(62057,'prior revised estimate; not an additional payment','FY2021–22')],status='sale-completed; public-expenditure-reconciled-to-budget-actual',end='2023-02-01',limits=['No buyer-specific loan write-off or waiver is established. No post2022 ownership continuity is assumed.','Budget expenditure to AIAHL does not establish the date or amount of every creditor payment.'])

# AIRPORT: legal-company identity and direct ownership correct the earlier effective-parent shortcut.
apcase=['mangaluru-airport-concession']
edge('aai-mangaluru-right','aai','mangaluru-spv','50-year operations concession','Executed14-Feb2020 agreement names Adani Mangaluru International Airport Ltd as concessionaire and AEL selected bidder; grants50years from COD.',['mangaluru-concession'],AP,['procurement','services'],kind='concession',date='2020-02-14',states=['KA'],records=apcase)
edge('mangaluru-operation','mangaluru-spv','mangaluru-airport','Operates and develops airport under concession','Contractual operating/development right over named airport; not a freehold sale of the airport land.',['mangaluru-concession'],AP,['services'],kind='operates',date='2020-02-14',states=['KA'],records=apcase)
edge('ael-aahl','ael','aahl','100% direct shareholding','Consolidated FY26 schedule row73 states100% by AEL.',['ael-report-2026'],AP,['organisations'],kind='owns',date='2026-03-31',records=apcase)
edge('ael-mangaluru-direct','ael','mangaluru-spv','51% direct shareholding','Consolidated FY26 schedule row78; the other49% is held by AAHL.',['ael-report-2026'],AP,['organisations'],kind='owns',date='2026-03-31',states=['KA'],records=apcase)
edge('aahl-mangaluru-direct','aahl','mangaluru-spv','49% direct shareholding','AEL also owns100%AAHL, so effective group control differs from the direct51/49 legal split.',['ael-report-2026'],AP,['organisations'],kind='owns',date='2026-03-31',states=['KA'],records=apcase)
edge('mangaluru-upfront','mangaluru-spv','aai','₹221.88cr upfront receipt','Government reply identifies Mangaluru upfront payment toward capital work in progress and regulated asset base; not total50-year concession value.',['airports-receipts-2022'],AP,['funding'],kind='payment',asof='2022-12-12',amounts=[amount(221.88,'upfront capital-work/regulated-asset reimbursement received','handover; reported12-Dec2022')],states=['KA'],records=apcase)
edge('six-airports-fees','six-airport-concessions','aai','₹710.88cr received across all six','Concession-fee aggregate throughOctober2022. Cohort includes Ahmedabad, Jaipur, Lucknow, Guwahati, Mangaluru, Thiruvananthapuram. No allocation to one SPV.',['airports-receipts-2022'],AP,['funding'],kind='aggregate-receipt',asof='2022-12-12',amounts=[amount(710.88,'all-six concession-fee receipts; not Mangaluru-only','throughOctober2022')],records=apcase)
edge('ael-aahl-finance','ael','aahl','Parent loans support airport holding platform','Standalone note50 shows₹11,200.27cr non-current loans and₹7,796.50cr current loans receivable fromAAHL at31-Mar2026, plus₹851.43crFY26 interest income. None is identified as a loan solely funding Mangaluru.',['ael-report-2026'],AP,['funding'],kind='loan',date='2026-03-31',amounts=[amount(11200.27,'closing parent non-current loan receivable','2026-03-31'),amount(7796.5,'closing parent current loan receivable','2026-03-31'),amount(851.43,'parent interest income recognised; not principal or cash proof','FY2025–26')],records=apcase)
record('mangaluru-airport-concession','Mangaluru: public airport→concession SPV→direct owners→parent finance','The executed agreement connects AAI’s airport to CINU63030GJ2019PLC110062. That CIN also identifies the later Mangaluru International Airport Limited. FY26 filings show51%AEL and49%AAHL direct ownership, withAAHL100%AEL: a correction to the earlier100%-AAHL shortcut. AAI reports₹221.88cr Mangaluru upfront capital reimbursement. The₹710.88cr concession-fee figure belongs to all six airports. Parent loan stocks finance the airport holding platform, without a site-level use-of-funds trace.',['mangaluru-concession','airports-receipts-2022','ael-report-2026'],['aai','mangaluru-airport','mangaluru-spv','ael','aahl','six-airport-concessions'],[e['id'] for e in D['relationships'] if e['recordIds']==apcase],AP,['organisations','procurement','funding','services','review'],'2020-02-14','2026-03-31','Concession signed14-Feb2020; receipts throughOct2022; ownership/loan balances31-Mar2026','Government says AEL was highest bidder for all six under open competition. Article27 bases original monthly fees on both embarking and disembarking traffic:₹115 domestic, twice domestic for international, with revisions. Article27.1.2 excludes concession fee from aeronautical cost pass-through.',['One corporate group can win multiple assets by bidding highest under common rules; six-of-six is a cohort result, not alone proof of rigging.','51%direct plus49%through a wholly owned company gives effective group control, but does not meanAAHL directly owns100%.','Loan stocks at the holding platform do not show which airport received the cash.'],'Concession amendments, current SPV register, AAI airport-level monthly receipts and lender drawdown/use-of-funds schedules could falsify the ownership, fee or financing path; bid evaluation records would test competitive-treatment concerns.',amounts=[amount(221.88,'Mangaluru upfront payment received by AAI','reported12-Dec2022'),amount(710.88,'all-six concession fees received; different perimeter','throughOctober2022'),amount(115,'original domestic per-passenger bid fee; subject to revision','contract14-Feb2020',unit='rupees per passenger')],states=['KA'],end='2026-03-31',status='executed-concession; dated-ownership-and-finance-disclosed',limits=['A50-year term starts atCOD, not necessarily signing; no invented expiry date.','Concession fees are not total contract value, private profit or an airline ticket charge.','No wrongdoing allegation is asserted solely from concentration; bid-file concerns remain untested.'])

# COAL: state right remains public; service and finance flows are at separate legal/accounting stages.
ccase=['parsa-kente-coal-contract']
edge('pekb-allotment','coal-ministry','rrvunl','PEKB allotted31-Mar2015','Official allocation table assigns Parsa East &Kanta Basan, Chhattisgarh, toRRVUNL underCMSP allotment route.',['coal-block-allotments'],COAL,['policy','organisations'],kind='allotment',date='2015-03-31',states=['CG'],records=ccase)
edge('rrvunl-pekb','rrvunl','pekb','Public allottee of coal right','The coal right is with the utility; private service ownership does not transfer the block toAEL.',['coal-block-allotments'],COAL,['organisations'],kind='holds-right',date='2015-03-31',states=['CG'],records=ccase)
edge('rrvunl-pkcl-cmda','rrvunl','pkcl','Coal Mining and Delivery Agreement','SupremeCourt para2 recordsAELbid acceptance12-May2006,LoI23-Oct2006, formation ofJVPKCL and CMDA16-Jul2008 betweenRRVUNL andPKCL.',['parsa-sc-2019'],COAL,['procurement'],kind='contracted',date='2008-07-16',states=['CG','RJ'],records=ccase)
edge('pkcl-ael-services-contract','pkcl','ael','Coal Mining Service Agreement','SupremeCourt para2 expressly records the service agreement betweenPKCL andAEL, adding the contractual leg beyond ownership.',['parsa-sc-2019'],COAL,['procurement'],kind='contracted',asof='2019-05-27',states=['CG'],records=ccase)
edge('ael-pkcl-owner','ael','pkcl','74% direct equity at31-Mar2026','Original consolidated shareholding row8 identifies74%byAEL; balance26%not independently inferred from subtraction. The JV origin withRRVUNL is established separately bycourt.',['ael-report-2026','parsa-sc-2019'],COAL,['organisations'],kind='owns',date='2026-03-31',records=ccase)
edge('pkcl-ael-services-money','pkcl','ael','₹2,032.50crFY26 services recognised','AEL standalone note50 records services rendered toPKCL including reimbursements₹2,032.50cr versus₹1,999.14cr prior year. ClosingPKCL trade receivable₹648.11cr is a balance, not additional revenue.',['ael-report-2026'],COAL,['funding'],kind='related-party-services',date='2025-04-01',end='2026-03-31',asof='2026-03-31',amounts=[amount(2032.5,'parent services income incl reimbursements; accrual disclosure','FY2025–26'),amount(648.11,'closing parent trade receivable fromPKCL; stock','2026-03-31')],records=ccase,limits=['This does not establish matching government cash payments or arm’s-length pricing.'])
edge('pkcl-ael-loan-return','pkcl','ael','₹2,127.14cr loans received back inFY26','Standalone note50 item21 separately discloses loans received back fromPKCL. Principal turnover is not profit or services income; originating lending and all cash sources must be reconciled before interpreting net extraction.',['ael-report-2026'],COAL,['funding'],kind='loan-repayment',date='2025-04-01',end='2026-03-31',asof='2026-03-31',amounts=[amount(2127.14,'related-party loan principal received back; gross turnover','FY2025–26')],records=ccase)
edge('pekb-guarantee-direction','coal-ministry','rrvunl','₹16.48452cr guarantee invocation directed','3-May2016 letter directsCCOto invoke this amount fromRRVUNL performanceBGfor delays in earlier allocation. It is not a penalty paid byPKCL/AEL or an established collected receipt.',['pekb-guarantee-2016'],COAL,['legal','funding'],kind='guarantee-invocation-direction',date='2016-05-03',amounts=[amount(16.48452,'performance-guarantee invocation directed; execution unverified','2016-05-03')],states=['CG','RJ'],records=ccase)
edge('pkcl-sc-outcome','supreme-court','pkcl','Escalation restored; fixed-cost/escrow claims rejected','27-May2019 appeal partly allowed. Court treated escalation as plausible contract interpretation, but upheld rejection of₹78cr fixed-cost award because CA certificate did not demonstrate loss and utility lifted more than fixed quantity. It also rejected return of mine-closure escrow.',['parsa-sc-2019'],COAL+['justice'],['legal','funding'],kind='adjudicates',date='2019-05-27',status='appeal-partly-allowed',amounts=[amount(78,'arbitral fixed-cost award set aside; not final payout','2019-05-27')],responses=['parsa-2019-outcome'],records=ccase)
record('parsa-2019-outcome','PKCL2019 arbitration: read the split result','The SupremeCourt restored price escalation but confirmed rejection of fixed-cost and escrow claims. It did not find every claim improper or approve every claim. Source itself prints two different escalated tariffs, so no tariff-based total is calculated.',['parsa-sc-2019'],['pkcl','rrvunl','supreme-court'],['pkcl-sc-outcome'],COAL+['justice'],['legal','review'],'2019-05-27','2019-05-27','CivilAppeal9023/2018, decided27-May2019','PKCL argued contract interpretation entitled it to escalation after clearance delays; utility argued commencement changed. Court accepted one plausible arbitrator interpretation but rejected unsupported fixed costs and return of mine-closure security.',['Contract interpretation can produce a lawful price increase.','Rejection of a claim is not a finding of criminal fraud.'],'Any later review or execution order changing the decree would update this result.',kind='response',status='partly-allowed-final-judgment',limits=['Separate from2025 road-transport litigation.'])
record('parsa-transport-status','PKCL2025 road-charge case: adverse finding reported, directions stayed','Scroll reports5-Jul2025 Jaipur court found over₹1,400cr road charges recovered despite a rail-siding obligation, and imposed₹50lakh fine plus audit direction. It also reports18-Jul2025 HighCourt stay. The suit concerned interest on delayed reimbursements, not a final₹1,400cr recovery award.',['parsa-transport-2025'],['pkcl','rrvunl'],[],COAL+['justice'],['legal','funding','review'],'2025-07-05','2025-11-24','Reported2025 road-transport case; appellate status verified only throughsource24-Nov2025','PKCL appealed and obtained an interim stay as reported. Scroll said it emailedAELandRRVUNL and would update if they responded. No original appellate order or later merits disposition is held.',['An interim stay suspends directions without resolving merits.','The₹1,400cr figure describes reimbursed costs; it is not established net loss or final ordered recovery.'],'Obtain certified trial judgment, RajasthanHighCourt18-Jul2025 stay and subsequent docket orders; those would authenticate/narrow or reverse the reported finding.',amounts=[amount(0.5,'trial-court fine reported; stayed, payment unverified','2025-07-05')],kind='response',tier='reported',status='adverse-trial-finding-reported; directions-stayed',limits=['Over₹1,400cr remains approximate narrative, not encoded as exact1400. No inference about unrelated judicial transfers or political pressure.'])
record('parsa-kente-coal-contract','PEKB: public coal right→state utility→private-majorityJV→parent services and loan returns','Ministry records keep the coal right withRRVUNL. The2008delivery agreement connects it toPKCL, and the SupremeCourt records a separatePKCL–AELmining-services agreement. FY26parent disclosures identify₹2,032.50cr services recognised,₹648.11cr receivable and₹2,127.14cr loans returned. A2016government order also puts₹16.48452cr performance-guarantee exposure on the public allottee. These are traceable financial/contractual legs, with no claim they are all the same cash.',['coal-block-allotments','pekb-guarantee-2016','parsa-sc-2019','ael-report-2026','parsa-transport-2025'],['coal-ministry','rrvunl','pekb','pkcl','ael','supreme-court'],[e['id'] for e in D['relationships'] if e['recordIds']==ccase],COAL+['justice'],['organisations','procurement','funding','legal','review'],'2006-05-12','2026-03-31','Tender2006, CMDA2008; allotment2015; guarantee direction2016; appeal2019; separate reported2025case; FY26accounts','2019SupremeCourt partly favouredPKCL on price escalation while rejecting fixed-cost/escrow claims. Separate2025road-cost adverse directions were reportedly stayed. Neither ruling authenticates every later service invoice.',['A public utility may outsource capital-intensive mining while retaining coal rights; private-majorityMDOis not itself illegal.','Services and loan repayments can reflect legitimate operation and funding; standalone related-party flows eliminate on group consolidation.','The state guarantee is its allottee obligation; no source assigns its burden toAEL.'],'ReconcileRRVUNL mine-wise invoice/payment ledger,PKCL audited accounts, CMDA/CMSA amendments, parent loan origin/returns and guarantee-bank debit records. Evidence of unperformed billing or non-market pricing would materially strengthen the concern; matched delivery and lawful pricing would weaken it.',amounts=[amount(2032.5,'AELservices recognised fromPKCL; not verified state cash','FY2025–26'),amount(2127.14,'loan principal returned toAEL; separate financing flow','FY2025–26'),amount(648.11,'AELclosing trade receivable fromPKCL','2026-03-31'),amount(16.48452,'public-allottee guarantee invocation directed; not confirmed collection','2016-05-03')],states=['CG','RJ'],end='2026-03-31',status='documented-contract-and-accounting-chain; litigation-scopes-separated',limits=['No block ownership is assigned toAEL. The full bidder register and contract price schedule are not held; no rigging claim.','Related-party service accrual and loan turnover cannot be added as parent profit or public loss.','2025reported court finding remains qualified by stay and unknown later disposition.'])

# HINDUSTAN ZINC: historic privatisation plus a proposed, contested, uncompleted related-party cash route.
zcase=['hindustan-zinc-related-party']
edge('hzl-strategic-sale','goi','sovl','26%HZLequity sold for about₹445cr','Court describes sale of109,858,294shares at₹40.51, approximately₹445cr. Government holding fell from75.92%to49.92%, ending government-company status.',['hzl-sc-2021'],ZINC,['organisations','funding'],kind='disinvestment',date='2002-04-04',amounts=[amount(445,'approximate26%equity strategic-sale consideration','2002')],records=zcase,limits=['Court narrative also refers to27-Mar2002SPA;4-April is agreement date inpara7, not an invented cash settlement date.'])
edge('sovl-hzl-holding','sovl','hzl','64.92%after open offer and call option','Court records26%strategic stake,20%public open offer and18.92%call-option acquisition inNov2003. The20%open-offer shares were not all sold by government.',['hzl-sc-2021'],ZINC,['organisations'],kind='owns',asof='2021-11-18',records=zcase,limits=['Exact Nov2003day not inferred. No amount for call-option cash is fabricated.'])
edge('vedanta-hzl-2023','vedanta','hzl','Controlling HZLshareholder in2023','Opened2023reporting identifiesVedanta as about64.9%shareholder and government29.54%minority shareholder. HistoricalSOVL and currentVedanta remain distinct legal nodes.',['hzl-lapse-2023','hzl-target-2023'],ZINC,['organisations'],kind='owns',tier='reported',date='2023-05-02',records=zcase)
edge('vedanta-thl-ventures','vedanta','thl-ventures','Reported wholly owned subsidiary','Transaction reporting identifiesTHLZincVentures as direct wholly ownedVedanta subsidiary.',['hzl-target-2023'],ZINC,['organisations'],kind='owns',tier='reported',date='2023-02-21',records=zcase)
edge('thl-ventures-target','thl-ventures','thl-zinc','Reported wholly owned target company','THLZincLtdMauritius is reported wholly owned byTHLZincVentures. Registry identifiers not retrieved; identity bounded tothis transaction.',['hzl-target-2023'],ZINC,['organisations'],kind='owns',tier='reported',date='2023-02-21',records=zcase)
edge('hzl-proposed-acquisition','hzl','thl-zinc','Proposed related-party acquisition; completion not established','Vedanta release announces proposedUS$2,981m cash sale includingUS$562m deferred/milestone-linked consideration. Government minority-shareholder opposition and reported lapse prevent treating it as paid money.',['vedanta-proposal-2023','hzl-target-2023','hzl-lapse-2023'],ZINC,['funding','organisations'],kind='proposed-acquisition',tier='reported',date='2023-01-19',asof='2023-05-02',status='proposal-reported-lapsed; no-completion-evidence',amounts=[amount(2981,'announced proposed cash consideration; not paid','2023proposal',unit='million',currency='USD'),amount(562,'deferred component included within2981; not additional','2023proposal',unit='million',currency='USD')],responses=['hzl-response-status'],records=zcase)
edge('mines-hzl-objection','mines-ministry','hzl','Minority shareholder opposes cash purchase','17-Feb2023letter reportedly reiteratesdissent, urges cashless alternatives and threatens legal options; not an adjudicated fraud finding.',['hzl-objection-2023'],ZINC,['legal','review'],kind='response',tier='reported',date='2023-02-17',responses=['hzl-response-status'],records=zcase)
edge('hzl-cbi-order','supreme-court','cbi','CBI regular case ordered for2002sale','18-Nov2021judgment permits residualstake sale whilefinding sufficientmaterial forregularCBIcase into2002disinvestment. Inquiry direction does not reverse sale or convictbuyer.',['hzl-sc-2021'],ZINC+['justice'],['legal'],kind='adjudicates',date='2021-11-18',status='investigation-directed; merits-unresolved',responses=['hzl-response-status'],records=zcase)
record('hzl-response-status','HZL: government challenge, corporate rationale and procedural limits','The2021Court allowed residualpublic-stake sale and orderedinvestigation of2002sale. DIPAM laterdisputedCBIpremises asreported; by29-Apr2022government reportedlysaidFIRregistered. For thedistinct2023related-party proposal,Vedanta calledit value-accretive,HZLsaidshareholderapprovalrequired,governmentdissented,andReutersreportedlapse.',['hzl-sc-2021','hzl-government-response-2022','hzl-fir-2022','vedanta-proposal-2023','hzl-objection-2023','hzl-lapse-2023'],['hzl','sovl','vedanta','mines-ministry','cbi','supreme-court'],['hzl-cbi-order','mines-hzl-objection','hzl-proposed-acquisition'],ZINC+['justice'],['legal','review'],'2021-11-18','2023-05-02','Court2021; reportedgovernmentchallenge/FIR2022; separateproposalstatus2023','DIPAMsaidBNPadviserappointmentandvaluerselectionwerebeingmischaracterised; Vedantasaidthe2023dealwouldcreateaglobalzincleader. HZLsaidno shareholdermeetingnoticehadbeenissuedasof20-Feb2023. Theseareattributedresponses,notacceptedfindings.',['RegistrationofanFIRisnotaconviction; permissionforsharedivestmentisnotanexonerationofeveryhistoricaldecision.','Arelated-partyacquisitioncanhavelegitimatesynergies; pricingandminority-shareholderprotectionrequirespecificvaluationevidence.'],'PrimaryFIR/closure/charge-sheetandlaterSupremeCourtorderswouldupdatethehistoricalinquiry; a2023approval/closingfilingwoulddisprovetheclaimthattheheldrecordestablishesonlyaproposal.',kind='response',tier='reported',status='historical-status-only; later-primary-disposition-not-held',limits=['No laterinvestigationclosureorconvictionclaimed. Originalgovernment2023letterdownloadHTTP403recordedinmanifest.'])
record('hindustan-zinc-related-party','Hindustan Zinc: privatisation, retained state stake and a blocked cash proposal','Thegovernment’s26%sale toSOVLforabout₹445crmadeHZLaprivatecompanyin2002;laterpublicopenofferandcalloptionbuilt64.92%control. In2023Vedanta’sproposedUS$2,981mrelated-partyasset sale wouldhaveusedHZLcash,whilegovernmentremainedaminorityshareholderandopposedthecashstructure. Theproposalwasreportedlylapsed,soitdoesnotenterapaymentledger. Separately,theSupremeCourtorderedinvestigationof2002saleprocesswhileallowingresidualgovernmentstake sale.',['hzl-sc-2021','hzl-government-response-2022','hzl-fir-2022','vedanta-proposal-2023','hzl-objection-2023','hzl-target-2023','hzl-lapse-2023'],['goi','hzl','sovl','vedanta','thl-ventures','thl-zinc','mines-ministry','cbi','supreme-court'],[e['id'] for e in D['relationships'] if e['recordIds']==zcase],ZINC+['justice'],['organisations','funding','legal','policy','review'],'2002-04-04','2023-05-02','2002–03privatisation;2021courtorder;2022reportedFIR;2023proposedrelated-partycashsale','CourtorderedCBIcase,butnotconvictionorassetreversal. DIPAMdisputedfactualpremisesinreportedrecallapplication. Vedantadescribedthe2023dealasshareholdervaluecreation;HZLsaidthatshareholderapprovalwasrequired. Reutersreportedlapsefromgovernment sources,withnoimmediateresponsereceived.',['Residualgovernmentownershipcanprovideaminority-shareholdercheckafterprivatisation.','Acommercialassetpurchasemayrestructureagroupwithoutillicitpurpose;counterpartyvaluation,minorityapprovalandactualsettlementdetermineitsmerits.','HistoricSOVLownershipandVedanta’s2023holdingareseparatelysourcedsnapshots;corporatemergercontinuityisnotprovedbynameassociation.'],'Fetchsalevaluation/bidfiles,CBIcaseoutcome,full2023valuationandminority-votingrecord,andclosing/withdrawalfilings. Acompletedcashsettlementwouldchangetheproposal-onlystatus; avalidvaluationandapprovalrecordcouldweakenpricingconcerns.',amounts=[amount(445,'approximateconsiderationfor26%governmentstake','2002'),amount(2981,'proposedrelated-partycashconsideration; notsettled','2023proposal',unit='million',currency='USD'),amount(562,'includeddeferredcomponent; do notadd','2023proposal',unit='million',currency='USD')],states=['RJ'],tier='reported',end='2023-05-02',status='privatisation-documented; proposal-lapsed-reported; investigation-outcome-unverified',limits=['No2026currentownership/inquirystatusisinferredfrom2023sources.','NoUS$2,981mpaymentedgeorquantifiedpubliclossisasserted. Allegedvaluationdefectsarecourt-recordedinquirygrounds,notprovenmisconduct.'])

# Reviewed prose overrides keep the case file readable without altering identifiers.
byrecord={r['id']:r for r in D['records']}
byrecord['hzl-response-status'].update(
 summary='The 2021 Court allowed the residual public-stake sale and ordered investigation of the 2002 sale. DIPAM later disputed CBI premises, according to reporting. At the 29 April 2022 hearing, the government reportedly said an FIR had been registered. For the distinct 2023 related-party proposal, Vedanta claimed value creation, HZL said shareholder approval was required, the government dissented, and Reuters subsequently reported that the proposal had lapsed.',
 response='DIPAM said BNP adviser appointment and valuer selection had been mischaracterised. Vedanta said the 2023 deal would create a global zinc leader. HZL said no shareholder-meeting notice had been issued as of 20 February 2023. These are attributed responses, not accepted findings.',
 alternativeExplanations=['Registration of an FIR is not a conviction; permission for share divestment does not exonerate every historical decision.','A related-party acquisition can have legitimate synergies; its pricing and minority-shareholder protection require specific valuation evidence.'],
 falsifier='A primary FIR, closure report, charge-sheet or later Supreme Court order would update the historical inquiry. A 2023 approval and closing filing would establish whether the proposed acquisition ever became a completed transaction.',
 limitations=['No later investigation closure or conviction is claimed. The original 2023 government-letter download returned HTTP 403, recorded in the manifest.'])
byrecord['hindustan-zinc-related-party'].update(
 summary='The government’s 26% sale to SOVL for about ₹445 crore ended HZL’s government-company status in 2002. A public open offer and call option later built a 64.92% holding. In 2023, Vedanta’s proposed US$2,981 million related-party asset sale would have used HZL cash while the government remained a minority shareholder and opposed the cash structure. The proposal reportedly lapsed, so it does not enter a payment ledger. Separately, the Supreme Court ordered investigation of the 2002 sale process while allowing the residual government-stake sale.',
 period='2002–03 privatisation; 2021 court order; 2022 reported FIR; 2023 proposed related-party cash sale',
 response='The Court ordered a CBI case; it did not convict anyone or reverse the asset sale. DIPAM disputed factual premises in a reported recall application. Vedanta described the 2023 deal as creating shareholder value; HZL said shareholder approval was required. Reuters reported lapse from government sources and received no immediate response to its requests for comment.',
 alternativeExplanations=['Residual government ownership can provide a minority-shareholder check after privatisation.','A commercial asset purchase may restructure a group without illicit purpose; valuation, minority approval and actual settlement determine its merits.','Historic SOVL ownership and Vedanta’s 2023 holding are separately sourced snapshots; corporate merger continuity is not proved by name association.'],
 falsifier='Obtain the sale valuation and bid files, CBI case outcome, full 2023 valuation and minority-voting record, and closing or withdrawal filings. A completed cash settlement would change the proposal-only status; a valid valuation and approval record could weaken pricing concerns.',
 limitations=['No current 2026 ownership or inquiry status is inferred from 2023 sources.','No US$2,981 million payment or quantified public loss is asserted. Alleged valuation defects are court-recorded grounds for investigation, not proven misconduct.'])
for a in byrecord['hindustan-zinc-related-party']['amounts']:
 if a['value']==445:a['stage']='approximate consideration for 26% government stake'
 elif a['value']==2981:a['stage']='proposed related-party cash consideration; not settled'
 else:a['stage']='deferred component included in total; do not add'
public_fields={'title','label','summary','response','alternativeExplanations','falsifier','limitations','identityBasis','period','stage','locator','dateBasis','note'}
tokens=['RRVUNL','PKCL','AEL','AAHL','AIAHL','HZL','SOVL','CBI','DIPAM','CMDA','CMSA','PEKB','THL','NSE','AIXL','AISATS','COD','MDO','CIN','LoI','PDF','FIR','SPA','AAI','AERA','SEBI','CCO']
def readable(s):
 protected={}
 def hold(match):
  key='zzidentity'+chr(97+len(protected))+'zz';protected[key]=match.group();return key
 s=re.sub(r'[LU][0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}|SpiceJet',hold,s)
 for token in tokens:
  s=re.sub(r'(?<=[a-z0-9])('+re.escape(token)+r')',r' \1',s)
  s=re.sub(r'('+re.escape(token)+r')(?=[A-Za-z0-9])',r'\1 ',s)
 s=re.sub(r'(?<=[a-z])(?=[A-Z][a-z])',' ',s)
 s=re.sub(r'(?<=[a-z])(?=\d)',' ',s)
 s=re.sub(r'(?<=\d)(?=[A-Za-z])',' ',s)
 s=re.sub(r'(?<=[A-Za-z])(?=₹)',' ',s)
 s=re.sub(r'(?<=%)(?=[A-Za-z])',' ',s)
 s=re.sub(r'(?<=[A-Za-z]),(?=[A-Za-z])',', ',s)
 s=re.sub(r';(?=\S)','; ',s)
 for a,b in {'SupremeCourt':'Supreme Court','HighCourt':'High Court','asof':'as of','bycourt':'by court','bidderegister':'bidder register','residualstake':'residual stake','governmentstake':'government stake','cashstructure':'cash structure','shareholderapprovalrequired':'shareholder approval required','value-accretive,HZL':'value-accretive, HZL','byAEL':'by AEL','caseinto':'case into','laterdisputed':'later disputed','directionswere':'directions were','appellateorder':'appellate order','court-recordedinquirygrounds':'court-recorded inquiry grounds','statedates':'state dates','notproved':'not proved','notheld':'not held','afterclearance':'after clearance','thatshareholder':'that shareholder','separatelysourced':'separately sourced','afterprivatisation':'after privatisation','shareholdingrow':'shareholding row','publicopenoffer':'public open offer','call-optionacquisition':'call-option acquisition','governmentreply':'government reply','governmentminority-shareholder':'government minority-shareholder','samecash':'same cash','reportedlystayed':'reportedly stayed','contractand':'contract and','loansreturned':'loans returned','governmentorder':'government order','stateservice':'state service','courtjudgment':'court judgment','courtorder':'court order','sourceitself':'source itself','fullbidder':'full bidder','Courtorders':'Court orders','Governmentshareholder':'Government shareholder','company’sposition':'company’s position','notaccepted':'not accepted','novation':'novation'}.items():s=s.replace(a,b)
 for a,b in {'crFY':'cr FY','&Kanta':'& Kanta','underCMSP':'under CMSP','ofJVPKCL':'of JV PKCL','performanceBGfor':'performance bank guarantee for','tothis':'to this','proposedUS$':'proposed US$','includingUS$':'including US$','reiteratesdissent':'reiterates dissent','whilefinding':'while finding','sufficientmaterial':'sufficient material','forregular':'for a regular','convictbuyer':'convict the buyer','A2016':'A 2016','asof':'as of','FY26parent':'FY26 parent','claimunder':'claim under'}.items():s=s.replace(a,b)
 s=re.sub(r',(?=[₹A-Za-z])',', ',s)
 s=s.replace('traffic:₹','traffic: ₹')
 for key,value in protected.items():s=s.replace(key,value)
 return re.sub(r' +',' ',s).strip()
def polish(obj,key=None):
 if isinstance(obj,dict):return {k:polish(v,k) for k,v in obj.items()}
 if isinstance(obj,list):return [polish(v,key) for v in obj]
 if isinstance(obj,str) and key in public_fields:return readable(obj)
 return obj
D=polish(D)
for row in D['relationships']:
 if row['id']=='hzl-proposed-acquisition':
  row['label']='Proposed acquisition target; no completed payment'
  row['summary']='The arrow identifies THL Zinc as the proposed acquisition target, not a cash recipient. Vedanta announced US$2,981 million consideration including US$562 million deferred and milestone-linked consideration. Reporting identifies THL Zinc Ventures as the target’s shareholder. Government opposition and reported lapse mean no completed sale payment is established.'
  row['limitations']=['This relationship denotes the proposed target/control transaction, not a money transfer to THL Zinc. No cash-recipient payment edge or completed settlement is asserted.']
for row in D['records']:
 if row['id']=='parsa-transport-status':row['period']='Reported 2025 road-transport case; appellate status verified only through the source dated 24 November 2025'
 elif row['id']=='parsa-kente-coal-contract':row['title']='PEKB: public coal right → state utility → private-majority JV → parent services and loan returns'
 elif row['id']=='hzl-response-status':row['period']='Court order in 2021; reported government challenge and FIR in 2022; separate proposal status in 2023'
D['methodology']=['Four purposively selected developed corporate/energy/resource cases, not representative prevalence estimates.','Existing energy/capital/company/resource corpus mined first; exact legal identifiers rechecked where primary documents became available.','Accounting stage, financial perimeter and source date retained on every amount; no aggregate combines sale EV, government equity, fees, loans, income, receivables or proposed consideration.','Ownership snapshots are not backdated to the original award; direct and effective holdings distinguished.','Investigation, interim stay, rejected claim and final conviction are different statuses. Source publication is not evidence of current unresolved proceedings.','Public-source investigation only; no shared-address matching, inferred personal guilt or unnamed allegations upgraded into facts.']
OUT.write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
print({k:len(D[k]) for k in ['sources','entities','relationships','records']})
