"""Three attributed institutional allegation networks with attached responses.

No skills, inferred ownership or same-name joins. Run from any directory.
"""
import json,pathlib
B=pathlib.Path(__file__).resolve().parent
D={'sources':[],'entities':[],'relationships':[],'records':[],'localities':[]}
ROUTE='/allegations'
CONFIG={
 'lifeline':(['health','disaster-relief','public-funds','justice'],['MH']),
 'scholarship':(['education','welfare','ngo','public-funds','justice'],['UK','UP']),
 'srmf':(['ngo','justice'],['UP','MP','CG']),
}
def geo(case,src):
 states=CONFIG[case][1]
 return [dict(scope='state' if len(states)==1 else 'multi-state',stateCodes=states,localityIds=[],basis='state-association',note='States expressly associated with the public programme or property investigation; not a private address, exact asset pin, or allocation of every payment to every state.',sourceIds=src)]
def dims(case,src,layers):return dict(domains=CONFIG[case][0],layers=layers,geography=geo(case,src),route=ROUTE,sourceIds=src,limitations=[])
def source(i,title,url,publisher,date,locator,summary,tier,limits):
 D['sources'].append(dict(id=i,title=title,url=url,publisher=publisher,publishedAt=date,retrievedAt='2026-10-07',locator=locator,summary=summary,tier=tier,limitations=limits))
def entity(i,label,typ,case,src,summary,basis,limits=[]):
 r=dict(id=i,label=label,type=typ,resolved=True,identityBasis=basis,summary=summary,**dims(case,src,['people' if typ=='person' else 'organisations']));r['limitations']=limits;D['entities'].append(r)
def amt(v,u,stage,period):return dict(value=v,currency='INR',unit=u,stage=stage,period=period)
def edge(i,a,b,kind,label,summary,case,src,tier='alleged',date=None,amounts=[],responses=[],limits=[],event=False):
 r=dict(id=i,**{'from':a,'to':b},kind=kind,label=label,summary=summary,tier=tier,status='attributed-allegation' if tier=='alleged' else 'dated-source-record',statusAsOf=date,fromDate=date if event else None,toDate=date if event else None,dateBasis='Exact procedural event date.' if event else 'Status/source date only; underlying programme period is stated in the summary and amount. No one-day role, continuing custody or present guilt is inferred.',alternativeExplanations=['Read the attached response and procedural limits; an enforcement claim, business role or temporary asset restraint does not establish criminal guilt.'],falsifier='Corrected original records, a merits judgment, reconciled payment ledger or proof of different legal identity would require revising or withdrawing this edge.',responseIds=responses,recordIds=[case+'-case'],amounts=amounts,**dims(case,src,['legal'] if kind in ['enforcement-action','court-relief','investigation-direction'] else ['people'] if kind=='role' else ['funding','organisations']));r['limitations']=limits;D['relationships'].append(r)
def record(i,title,summary,case,src,ents,rels,tier,kind,date,response,limits,amounts=[]):
 D['records'].append(dict(id=i,title=title,summary=summary,kind=kind,tier=tier,status='pending-or-procedural-not-final-guilt' if tier=='alleged' else 'response-or-bounded-outcome',statusAsOf=date,fromDate=None,toDate=None,dateBasis='Latest retained source/procedural status, not an assertion that no later proceeding exists. Underlying conduct windows are stated separately.',entityIds=ents,relationshipIds=rels,period={'lifeline':'2020–2022 procurement and payment allegations; 2023–2025 responses and bail','scholarship':'FY2011–12 to FY2016–17 cohort; 15 June 2026 attachment statement','srmf':'2025–2026 disputed Noida transfer and 2026 proceedings; 2010/early2011 origins are historical context'}[case],response=response,alternativeExplanations={'lifeline':['Genuine pandemic staffing services and bed-occupancy billing can explain part of the payments; the bail court questioned the Dean-specific theory and proof.'],'scholarship':['Legitimate scholarships, administrative errors or contested eligibility could explain some records; no court merits determination for this named cohort is retained.'],'srmf':['Competing management claims or a purchaser acting on apparently valid documents are alternatives requiring investigation; buyer status alone does not show knowledge of forgery.']}[case],falsifier='The case must be revised on a contrary merits judgment, authenticated underlying deed/authority, reconciled eligibility and bank records, or corrected identity. Missing response records are not admissions.',amounts=amounts,**{**dims(case,src,['funding','legal','organisations']), 'limitations':limits}))

source('lifeline-bisure-court-2025','Bombay High Court: Dr Kishore Bisure bail, 2025:BHC-AS:6860','https://rawlaw.in/wp-content/uploads/2025/02/BB2-1.pdf','Bombay High Court judgment reproduced by RawLaw','2025-02-12','BA4055/2024; §§3–12 prosecution account, §§13–14 parties, §§20–22 merits-at-bail discussion, final order','Court text records alleged BMC receipts and intermediary firms, the Dean’s defence, weaknesses in the kickback/billing theory, and conditional bail.','reported',['Full public court document retrieved from a legal mirror, not the court host; mirror-only assertions stay reported or alleged. Bail observations are prima facie, not acquittal.'])
source('lifeline-bail-report-2025','Patkar granted bail after custody and trial delay','https://www.thehindu.com/news/cities/mumbai/jumbo-covid-19-centres-scam-bombay-high-court-grants-bail-to-sanjay-rauts-alleged-aide-sujit-patkar/article69819130.ece','The Hindu','2025-07-17','Report of 16 July 2025 Bombay High Court order; custody, parity and trial-stage paragraphs','Reports Patkar’s conditional bail, parity with unarrested co-accused and charges not yet framed at that time.','reported',['Underlying Patkar order not retrieved from court host. The article contains an inconsistent amount/unit string; it is not used for financial values. Commercial body is retained only in local cache.'])
source('lifeline-bmc-response-2023','BMC response: manpower payments and denial of inflated headline claim','https://www.freepressjournal.in/mumbai/mumbai-covid-centre-scam-bmc-commissioner-iqbal-singh-chahal-says-allegation-of-100-crore-is-baseless','Free Press Journal, reproducing BMC response','2023-01-21','Numbered BMC statement points2–5','BMC says due process was followed and INR33.13crore paid for manpower, split INR3.36crore NSCI and INR29.77crore Dahisar; it disputes the political INR100crore claim.','reported',['Original BMC release not separately retrieved. This reported total is not reconciled with the prosecution’s different receipt total. Commercial body is external-cache only.'])
source('lifeline-patkar-court-2025','Bombay High Court: Patkar bail, 2025:BHC-AS:29188','https://indiankanoon.org/doc/25256776/','Bombay High Court judgment transcribed by Indian Kanoon','2025-07-16','BA3/2025; §6 invoice/penalty/TDS figures, §§15–21 and28–35 defence, §§39–54 parity and conditional bail','Judgment transcription distinguishes invoiced, sanctioned and net-credit amounts, records Patkar’s denial of personal forgery/recordkeeping, and grants bail on custody, delay and parity grounds.','reported',['Direct retrieval returned403; indexed legal transcription retained separately, not court-host original. Private address/account fields excluded from public artifact. Source net-credit figure differs by two paise from subtraction of printed sanctioned amount and TDS; no silent repair.'])
source('scholarship-ed-www-2026','ED: Haridwar scholarship cohort and sixth provisional attachment','https://www.enforcementdirectorate.gov.in/media/press-release-documents/4a44cdde-c3be-430d-b877-1b2a2815c0b2_PR%20in%20SC%20ST%20scam-1562026%201.pdf','Directorate of Enforcement','2026-06-15','pp1–2: disbursement paragraphs, category table and deduplication footnote, named societies, PAO status','Agency alleges false scholarship records and fund diversion involving three named colleges and societies; states full disbursements, alleged proceeds and temporary asset attachment separately.','documented',['Documented as an authentic agency allegation and announced attachment, not a court finding of fraud. Table counts2,895unique students; prose calls them claims. No rate against6,208claims is inferred. FY2011–12 overlaps the atlas start; no pre/post6October2011 split is supplied.'])
source('srmf-ed-2026','ED: alleged SRMF impersonation, sale and asset freezing','https://enforcementdirectorate.gov.in/media/press-release-documents/58486e21-6f04-4a3f-9349-a897355bc398_PRESS%20RELEASE-%20Search-Arrest-15-05-2026.pdf','Directorate of Enforcement','2026-05-15','pp1–2: registered society, alleged lookalike entity, buyer director and freezing paragraphs','Agency alleges forged authority and sale/resale of society property, reports two arrests/remand and freezing of named buyer/director assets.','documented',['Authentic official allegation and procedural statement; not proof of knowing participation or conviction. No exact sale consideration or frozen-asset value is supplied.'])
source('srmf-sc-original-2026','Shrikant Ojha v State of UP, 2026 INSC482','https://www.sci.gov.in/sci-get-pdf/?diary_no=92502026&from=latest_judgements_order&order_date=2026-05-12&type=j','Supreme Court of India','2026-05-12','§§3–10 identity and disputed transfer; §§16–20 SIT, respondent2 protection and merits reservation','Court orders investigation/SIT into disputed society land transactions, removes bar on filing police report and protects one identified respondent until stated conditions end.','documented',['Original official-host judgment retrieved; full normalized text matches the separately retained legal mirror. The court expressly reserves merits and does not convict any party. Historical2010/early2011 context is not newly dated conduct.'])

L=['lifeline-bisure-court-2025'];S=['scholarship-ed-www-2026'];T=['srmf-ed-2026'];J=['srmf-sc-original-2026']
entity('lh-bmc','Municipal Corporation of Greater Mumbai (BMC)','public-body','lifeline',L+['lifeline-bmc-response-2023'],'Public purchaser of staffing services for two Covid centres.','Court text and BMC response identify MCGM/BMC as the same named municipal buyer; no external canonical merge.')
entity('lh-firm','Lifeline Hospital Management Services','partnership','lifeline',L,'Named contracting partnership in the court-recorded prosecution case.','BA4055/2024 §§4–9 identify partnership and its partners; not merged with similarly named hospitals or assumed a limited company.')
for i,label in [('lh-patkar','Sujit Mukund Patkar'),('lh-gupta','Dr Hemant Ramsharan Gupta'),('lh-shah','Sanjay Madanlal Shah'),('lh-salunke','Raju Nandkumar Salunke')]:
 entity(i,label,'person','lifeline',L,'Named partner in the Lifeline court record; individual criminal liability remains contested.','Full named party/partner in BA4055/2024 §§4 and13.1; record-scoped identity, no political or common-name merge.')
entity('lh-ms','M.S. Consultancy (court-record firm)','firm','lifeline',L,'Service-provider firm alleged by prosecution to have received diverted funds.','Exact business name and proprietor Ravikant Singh in §7; no CIN or broader-company identity inferred.')
entity('lh-elegant','Elegant Multiservices (court-record firm)','firm','lifeline',L,'Second service-provider firm in the prosecution account.','Exact business name and proprietor Sanjay Parab in §7; no same-name business merge.')
entity('lh-ravikant','Ravikant Singh (M.S. Consultancy)','person','lifeline',L,'Named proprietor in the court-recorded allegation.','Role-qualified identity in §7 only; not joined to other people named Ravikant Singh.')
entity('lh-parab','Sanjay Parab (Elegant Multiservices)','person','lifeline',L,'Named proprietor in the court-recorded allegation.','Role-qualified identity in §7 only; not joined by common name.')
entity('lh-bisure','Dr Kishore Bisure','person','lifeline',L,'Former Dahisar centre Dean; obtained conditional bail with substantial prima-facie reservations about the case against him.','Named applicant BA4055/2024, neutral citation2025:BHC-AS:6860; not every centre administrator.')
entity('lh-ed','Directorate of Enforcement — Lifeline proceeding','agency','lifeline',L,'Prosecution authority; its allegations are distinct from the court’s conclusions.','ED respondent and ECIR/MBZO-1/63/2022 in the retained judgment; proceeding-scoped node.')
entity('lh-hc','Bombay High Court — Lifeline bail proceedings','court','lifeline',L+['lifeline-bail-report-2025'],'Court issuing separate Bisure and Patkar bail relief.','Named court, judge and case citation in public judgment; no external canonical bridge from mirror-only evidence.')

entity('sc-social','Social Welfare Department, Uttarakhand','department','scholarship',S,'Named source of post-matric scholarship funds.','Exact department named in ED15June2026 release; no allegation that all departmental officers participated.')
entity('sc-dswo','District Social Welfare Officer, Haridwar (office)','office','scholarship',S,'Office said to have processed6,208 claims in this cohort.','Institutional office specified by ED; no officer’s personal identity or personal bank account inferred.')
entity('sc-institutions','Accounts of three named scholarship institutions (ED cohort)','cohort','scholarship',S,'Aggregate recipient-account cohort for the INR19.74crore direct-credit figure.','Explicit bounded cohort: Motherhood Institute, RIMS and Mahaveer Institute in this release; not all Indian colleges.')
entity('sc-students','Student-name accounts in the ED scholarship cohort','cohort','scholarship',S,'Aggregate accounts credited INR8.24crore, some allegedly controlled by management/staff.','Defined account cohort in ED release; no student names, bank numbers or individual allegations are published.')
for i,label,summary in [
 ('sc-new-tuples','New Tuples Education Society','Named society operating Mahaveer Institute of Technology, Meerut.'),
 ('sc-motherhood-soc','Motherhood Institute of Management & Technology Society','Named society operating Motherhood Institute, Roorkee.'),
 ('sc-modern-soc','Modern Institute of Management & Technology Society','Named society operating RIMS, Haridwar.'),
 ('sc-mahaveer','Mahaveer Institute of Technology, Meerut','Named institution in the2026 ED cohort, Uttar Pradesh.'),
 ('sc-motherhood','Motherhood Institute of Management & Technology, Roorkee','Named institution in the2026 ED cohort, Uttarakhand.'),
 ('sc-rims','Roorkee Institute of Management Sciences/Medical Sciences (RIMS)','Institution named with this dual wording in the ED release, Haridwar.')]:
 entity(i,label,'society' if i.endswith('soc') or i=='sc-new-tuples' else 'institution','scholarship',S,summary,'Exact name and operating institution paired by ED15June2026. No registration number, university-wide identity or same-name entity is inferred.')
entity('sc-manika','Manika Sharma (ED scholarship case identity)','person','scholarship',S,'Person whom ED alleges controlled the relevant institutions and scholarship receipts.','Identity confined to named person in this ED release and its specific cohort; no link to same-name school directors, faculty, students or other professionals.')
entity('sc-ed','Directorate of Enforcement — Haridwar scholarship proceeding','agency','scholarship',S,'Agency alleging diversion and announcing sixth provisional attachment.','ED Dehradun Sub Zonal Office and15June2026 release; five earlier complaints are case-wide, not individually attributed to every listed entity.')
entity('sc-assets','Assets in sixth scholarship provisional attachment','asset-cohort','scholarship',S,'FD account, land and institutional buildings valued by ED at approximately INR13.83crore.','Exact bounded aggregate in release; no individual asset owner or map coordinate inferred.')

entity('sr-society','Spiritual Regeneration Movement Foundation of India — S/2366/1963','society','srmf',T+J,'Registered charitable society whose property transfers and competing management claims are disputed.','Registration S/2366/1963 in ED release and S-2366of1963 in SupremeCourt text independently identify same society; separate from alleged lookalike arrangement.')
entity('sr-mohan','G. Ram Chandra Mohan (SRMF proceeding)','person','srmf',T+J,'Person ED alleges falsely claimed society authority and created a lookalike entity/account arrangement.','ED spacing and court G.RamChandramohan tied to same registration, named co-accused and Noida transaction; no unrelated common-name merge.')
entity('sr-akash','Akash Malviya (SRMF proceeding)','person','srmf',T+J,'Person ED alleges executed disputed sale deeds using claimed executive-member authority.','Same named person, registered society and Noida FIR642/2025 in court and ED source.')
entity('sr-lookalike','Alleged lookalike SRMF entity/account arrangement','mechanism','srmf',T,'Agency-described mechanism using a similar society name, disputed PAN and account.','This is a defined alleged mechanism, not a second legally verified incorporated society; no PAN or private account details published.')
entity('sr-buyer','Singhvahini Infra Projects Private Limited (SRMF buyer)','company','srmf',T+J,'Named buyer in disputed transfer; ED alleges director knowledge and further resale.','Court spelling Singhvahini Infraprojects and ED Infra Projects tied by named directors and identical SRMF/Noida sale; no CIN or unrelated issuer bridge.')
entity('sr-pradeep','Pradeep Singh (Singhvahini director)','person','srmf',T+J,'Buyer director whom ED alleges knowingly participated; allegation remains unadjudicated.','ED Pradeep and court Pradip identify same named buyer director in same transaction, distinct from respondent2Raghvendra.')
entity('sr-raghvendra','Raghvendra Pratap Singh (respondent2)','person','srmf',J,'Buyer-company director who sought FIR quashing and received specific temporary protection.','SupremeCourt §§8,10 and18 identify respondent2 and distinguish him from co-director Pradip Singh; no blanket protection for all accused.')
entity('sr-land','SRMF land in disputed Noida sale, FIR642/2025','property','srmf',T+J,'Property transfer at issue; registry title, authority and downstream interests require investigation.','Specific transaction in FIR642/2025,20December2025 and named purchaser. No exact parcel coordinates or sale-price figure retained.')
entity('sr-ed','Directorate of Enforcement — SRMF proceeding','agency','srmf',T,'Agency reports arrests, remand and freezing under PMLA.','ECIR dated7May2026 and press release15May2026 define this proceeding; custody is not asserted beyond that date.')
entity('sr-sc','Supreme Court — Shrikant Ojha appeal','court','srmf',J,'Orders SIT and police investigation while reserving merits and protecting a specific respondent.','2026INSC482; SLP(Crl)3123/2026; source is the original official Supreme Court judgment; no external canonical bridge is added.')

LR=['lifeline-bisure-response','lifeline-bmc-response','lifeline-patkar-status'];SR=['scholarship-response-gap'];TR=['srmf-court-response','srmf-status-gap']
edge('lh-contract','lh-bmc','lh-firm','contract','BMC staffing contract; procurement validity disputed','Court text records Lifeline staffing arrangements for Dahisar and NSCI-Worli Covid centres. Prosecution alleges fabricated eligibility documents; BMC says due process and rate negotiations were followed.','lifeline',L+['lifeline-bmc-response-2023'],'reported','2025-02-12',responses=LR)
edge('lh-receipts-alleged','lh-bmc','lh-firm','alleged-payment','Prosecution: INR324,486,784.90 received','Bisure judgment §9 recounts prosecution allegation that false invoices were cleared and this total received. This is alleged gross contract receipt, not a proved loss, kickback or net diverted amount.','lifeline',L,date='2025-02-12',amounts=[amt(324486784.9,'rupee','prosecution-alleged gross contract receipts; not proven loss','2020–2022 programme; court recounts on12February2025')],responses=LR)
edge('lh-receipts-response','lh-bmc','lh-firm','reported-payment','BMC response: INR33.13crore paid','BMC’s reported statement says INR3.36crore for NSCI and INR29.77crore for Dahisar manpower, INR33.13crore total. This overlaps the prosecution receipt figure; do not add the two or derive loss from their difference.','lifeline',['lifeline-bmc-response-2023'],'reported','2023-01-21',amounts=[amt(33.13,'crore','BMC-reported staffing payment total; unreconciled with prosecution scope','Statement21January2023')],responses=LR)
for ident in ['lh-patkar','lh-gupta','lh-shah','lh-salunke']:
 edge(ident+'-partner',ident,'lh-firm','role','Named partnership role; guilt not inferred','Court identifies this person as a partner. Partner status is distinct from proof of directing a false invoice or personally receiving alleged proceeds.','lifeline',L,'reported','2025-02-12',responses=LR)
for ident,target in [('lh-to-ms','lh-ms'),('lh-to-elegant','lh-elegant')]:
 edge(ident,'lh-firm',target,'alleged-diversion','Prosecution alleges diversion to service-provider firm','Judgment §7 recounts alleged transfers of public receipts to this named firm, said to have been created at partners’ instance. No firm-specific amount or independently opened bank ledger is supplied.','lifeline',L,date='2025-02-12',responses=LR)
edge('lh-ravikant-role','lh-ravikant','lh-ms','role','Named proprietor in prosecution account','§7 describes M.S. Consultancy as Ravikant Singh’s firm; business identity does not alone establish criminal knowledge.','lifeline',L,'reported','2025-02-12',responses=LR)
edge('lh-parab-role','lh-parab','lh-elegant','role','Named proprietor in prosecution account','§7 describes Elegant Multiservices as Sanjay Parab’s firm; no amount assigned to him individually.','lifeline',L,'reported','2025-02-12',responses=LR)
edge('lh-dean-allegation','lh-ed','lh-bisure','allegation','ED allegation: bill approvals and kickbacks','Court records alleged false-bill approvals and claimed cash/in-kind benefits. At bail it found the INR21.6lakh allegation prima facie unsubstantiated, noted multi-person invoice review and bed-occupancy billing, and reported no recovery from him. The amount is not represented as a proven payment.','lifeline',L,date='2025-02-12',responses=LR)
edge('lh-bisure-bail','lh-hc','lh-bisure','court-relief','Conditional bail; prima-facie weaknesses recorded','12February2025 court order grants bail; it questions Dean-specific duty, proof and arrest procedure. The partnership deed and alleged fund routing remain matters for trial.','lifeline',L,'reported','2025-02-12',responses=LR,event=True)
edge('lh-patkar-bail','lh-hc','lh-patkar','court-relief','Conditional bail on16July2025','Reporting attributes bail to prolonged custody, trial delay and parity. This is not dismissal of the prosecution or acquittal; no final trial outcome was located in the follow-up search.','lifeline',['lifeline-bail-report-2025'],'reported','2025-07-16',responses=LR,event=True)

edge('sc-process','sc-social','sc-dswo','administration','DSWO processed6,208 cohort claims','ED states that DSWO Haridwar processed6,208 scholarship claims resulting in approximately INR27.98crore disbursed. The office is a processing endpoint, not an identified personal bank recipient.','scholarship',S,'reported','2026-06-15',responses=SR,limits=['The full disbursement cohort is not identical to the alleged false-claim subset.'])
edge('sc-direct-credits','sc-social','sc-institutions','reported-payment','ED: INR19.74crore direct institution credits','Agency states this aggregate direct-credit amount out of approximately INR27.98crore total. It does not allocate all disbursements by individual institution or declare every payment fraudulent.','scholarship',S,'reported','2026-06-15',amounts=[amt(19.74,'crore','ED-reported aggregate direct disbursements; not all alleged proceeds','FY2011–12 to FY2016–17; start-year cutoff split unavailable')],responses=SR)
edge('sc-student-credits','sc-social','sc-students','reported-payment','ED: INR8.24crore student-name credits','Agency reports credits to student-name accounts; some are alleged to have been controlled by college staff. INR19.74crore plus INR8.24crore equals the source’s rounded INR27.98crore cohort total.','scholarship',S,'reported','2026-06-15',amounts=[amt(8.24,'crore','ED-reported student-name account disbursements; not beneficiary net benefit','FY2011–12 to FY2016–17; start-year cutoff split unavailable')],responses=SR)
edge('sc-return-routing','sc-students','sc-institutions','alleged-diversion','ED alleges return transfers and cash withdrawals','ED alleges management/staff controlled some student-name accounts and routed credited funds back to institutions or withdrew cash. No exact amount for this leg, fraction of INR8.24crore or destination for every withdrawal is established.','scholarship',S,date='2026-06-15',responses=SR)
for society,college,money in [('sc-new-tuples','sc-mahaveer',2.44),('sc-motherhood-soc','sc-motherhood',3.95),('sc-modern-soc','sc-rims',7.44)]:
 edge(society+'-operates',society,college,'operates','ED identifies operating society','Agency explicitly pairs this society with the named institution. This is a source-scoped operating identity, not a wider corporate group or university merge.','scholarship',S,'reported','2026-06-15',responses=SR)
 edge(college+'-cohort',college,'sc-institutions','cohort-membership','Included in named institution-account cohort','Named member of the three-institution cohort; the group’s direct-credit total is not assigned individually through this link.','scholarship',S,'reported','2026-06-15',responses=SR)
 edge(society+'-proceeds','sc-ed',society,'alleged-proceeds','ED attributes approximately INR'+str(money)+'crore proceeds','ED assigns this approximate alleged-proceeds component to the society. It is an agency quantification, not a fresh transfer from ED, restitution or final judicial forfeiture.','scholarship',S,date='2026-06-15',amounts=[amt(money,'crore','agency-attributed alleged proceeds component; not cash transfer or final forfeiture','FY2011–12 to FY2016–17; quantified15June2026')],responses=SR)
edge('sc-manika-control','sc-manika','sc-institutions','alleged-control','ED alleges control of receipt and diversion','ED alleges this record-scoped person managed the relevant institutions and receipt/use of funds. No ownership percentage, personal receipt amount or unrelated identity bridge is inferred.','scholarship',S,date='2026-06-15',responses=SR)
edge('sc-attachment','sc-ed','sc-assets','enforcement-action','Sixth provisional attachment: approximately INR13.83crore','Official release announces temporary PMLA attachment of FD, land and buildings valued approximately INR13.83crore. This restrains assets and is not money recovered or a criminal conviction. Five earlier prosecution complaints are stated case-wide, not against every named person here.','scholarship',S,'documented','2026-06-15',amounts=[amt(13.83,'crore','provisional attachment valuation; not recovered cash or additional alleged proceeds','Announcement15June2026')],responses=SR,event=True)

edge('sr-mohan-authority','sr-mohan','sr-society','alleged-impersonation','ED: disputed claim to treasurer authority','ED alleges Mohan falsely presented himself as treasurer, beginning in2010. The origin is historical context; no legitimate officer role is encoded. SupremeCourt notes rival office-bearer lists and pending management litigation.','srmf',T+J,date='2026-05-15',responses=TR)
edge('sr-akash-authority','sr-akash','sr-society','alleged-impersonation','ED: disputed executive-member authority','ED alleges Malviya used purported executive-member status to execute forged-authority sales. A claim of authority is not mapped as a verified officer appointment.','srmf',T,date='2026-05-15',responses=TR)
edge('sr-lookalike-control','sr-mohan','sr-lookalike','alleged-intermediation','ED alleges lookalike-name account mechanism','Agency alleges creation of a similarly named entity, disputed PAN and account for proceeds routing. No account number, exact receipt amount or independently verified legal entity is published.','srmf',T,date='2026-05-15',responses=TR)
edge('sr-property-context','sr-society','sr-land','disputed-property','Society property at issue in Noida proceeding','Court and ED identify the society’s property as the subject of disputed sale. §9 clarifies the society holds freehold land, correcting the Court’s initial government-lease assumption. Authority and individual liability remain under investigation; no public grant, government lease or valid seller authority is inferred.','srmf',T+J,'reported','2026-05-15',responses=TR)
edge('sr-land-sale','sr-land','sr-buyer','alleged-transfer','Alleged forged-authority sale to named buyer','FIR642/2025 and ED release allege transfer to Singhvahini through disputed seller authority. ED also alleges subsequent resale of portions, but unnamed downstream purchasers are not drawn as resolved entities. Exact consideration and proceeds allocation are not in the admitted originals.','srmf',T+J,date='2026-05-15',responses=TR)
edge('sr-pradeep-role','sr-pradeep','sr-buyer','role','Named director; knowledge separately alleged','Both sources identify the director. ED’s allegation that he knew the sellers lacked authority is separate from ordinary directorship and remains unadjudicated.','srmf',T+J,'reported','2026-05-15',responses=TR)
edge('sr-buyer-knowledge','sr-ed','sr-pradeep','allegation','ED alleges knowing participation and resale','ED asserts director knowledge of defective authority and further alienation. Neither the original deeds nor a final court finding on his knowledge was retrieved. Do not infer knowledge merely because he was a purchaser/director.','srmf',T,date='2026-05-15',responses=TR)
edge('sr-raghvendra-role','sr-raghvendra','sr-buyer','role','Buyer co-director; quashing petitioner','Court identifies respondent2 as co-director, distinct from Pradip Singh. He sought FIR quashing and received conditional non-coercion protection while investigation proceeds.','srmf',J,'reported','2026-05-12',responses=TR)
edge('sr-freeze','sr-ed','sr-buyer','enforcement-action','ED announces freezing of buyer/director assets','ED reports Section17(1A) freezing of bank accounts, FDs, lockers and vehicles belonging to named buyer and director. No aggregate value is supplied; freeze is not recovery, confiscation or guilt.','srmf',T,'documented','2026-05-15',responses=TR,event=True)
for target in ['sr-mohan','sr-akash']:
 edge(target+'-arrest','sr-ed',target,'enforcement-action','ED reports arrest and remand in May2026','Official release reports arrest after14–15May searches and remand to ED custody. No continuing detention beyond the reported event or current absence of bail is inferred.','srmf',T,'documented','2026-05-15',responses=TR,event=True)
edge('sr-sit','sr-sc','sr-land','investigation-direction','SIT ordered; merits expressly reserved','12May2026 judgment removes the restriction on filing police report and orders a ChiefSecretary-supervised UP SIT with Registrar of Societies, report within three months. No completed SIT report was located; the deadline is not proof of completion.','srmf',J,'documented','2026-05-12',responses=TR,event=True)
edge('sr-protection','sr-sc','sr-raghvendra','court-relief','Specific conditional non-coercion protection','§18 protects respondent2 Raghvendra Pratap Singh until SIT report and police investigation completion, subject to cooperation. This is not blanket protection for Mohan, Malviya or every buyer director. §19 reserves merits.','srmf',J,'documented','2026-05-12',responses=TR,event=True)

edge('lh-net-credit','lh-bmc','lh-firm','alleged-payment','Prosecution transcription: INR318,471,635.72 net credit','Patkar judgment §6 reports INR327,633,861.50 invoiced, INR3,147,076.60 penalty, INR324,486,784.90 sanctioned before INR6,015,149.20 TDS, and net credit of INR318,471,635.72. The printed subtraction yields INR318,471,635.70, a two-paise source discrepancy. These are overlapping stages, not additional transfers or proved loss; no account identifier is published.','lifeline',['lifeline-patkar-court-2025'],date='2025-07-16',amounts=[amt(318471635.72,'rupee','prosecution-reported net bank credit in court transcription; two-paise internal discrepancy','16September2020 to24June2022; recounted16July2025')],responses=LR,limits=['No bank ledger or official court-host original independently verifies the transcribed net-credit amount.'])

def caseids(case):return [e['id'] for e in D['entities'] if set(e['domains'])==set(CONFIG[case][0])]
def relids(case):return [e['id'] for e in D['relationships'] if e['recordIds']==[case+'-case']]
record('lifeline-case','Lifeline: BMC staffing receipts → alleged intermediary diversion → bail responses','Prosecution alleged false staffing records and routed BMC payments through Lifeline to M.S. Consultancy and Elegant Multiservices. The court-recorded alleged gross receipt is INR324,486,784.90; BMC separately reported INR33.13crore paid for manpower. Those totals overlap and are unreconciled. The February2025 Bisure bail order questions the Dean-specific kickback and billing theory; Patkar obtained bail in July2025. No final guilt or loss finding is supplied.','lifeline',L+['lifeline-bmc-response-2023','lifeline-bail-report-2025'],caseids('lifeline'),relids('lifeline'),'alleged','investigation-case','2025-07-16','BMC denies improper procurement and says payment followed services. Bisure argued limited tenure, shared invoice checks and bed-occupancy billing; the court recorded substantial prima-facie weaknesses. Patkar’s later bail rests on custody, delay and parity, not acquittal.',['No political-friendship or party edge is inferred from newspaper descriptions.','Mirror-only court sourcing remains reported; all prosecution conduct claims are expressly alleged.','Do not treat gross receipts, claimed kickbacks, asset restraints or historical headline estimates as additive loss.','Latest retained specific outcome is16July2025 bail; a later trial disposition was not found in the bounded search.'])
record('lifeline-bisure-response','Bisure response and court’s prima-facie reservations','The bail court notes no identified requirement that the Dean physically verify every staffing count, multiple review stages, and billing based on bed occupancy. It finds the claimed INR21.6lakh benefit prima facie unsubstantiated and reports no recovery from him; partnership-deed validity and routing remain trial questions.','lifeline',L,['lh-bisure','lh-firm','lh-ed','lh-hc'],['lh-dean-allegation','lh-bisure-bail'],'reported','response','2025-02-12','Defence and judicial reservations are set out in §§13,20–22; the order grants conditional bail.',['Bail observations are not final acquittal or a ruling that every Lifeline invoice was valid.'])
record('lifeline-bmc-response','BMC denies procurement wrongdoing and supplies its payment total','BMC’s reported21January2023 response says Lifeline supplied manpower after due process and rate negotiation, and bills were paid after services. Its INR33.13crore total comprises INR3.36crore NSCI and INR29.77crore Dahisar. The response disputes a political INR100crore allegation; that figure is not treated as proved loss.','lifeline',['lifeline-bmc-response-2023'],['lh-bmc','lh-firm'],['lh-contract','lh-receipts-response'],'reported','response','2023-01-21','Municipal response is retained as attributed counter-evidence, not independent clearance by a court.',['No reconciliation explaining the difference from court-recorded prosecution receipts is available.'])
record('lifeline-patkar-status','Patkar bail: custody, trial delay and parity','The Hindu reports that the HighCourt granted Patkar conditional bail16July2025, considering nearly two years’ custody, trial not yet commenced and parity with a co-accused. This changes custody status without deciding the laundering charge.','lifeline',['lifeline-bail-report-2025'],['lh-patkar','lh-gupta','lh-hc'],['lh-patkar-bail'],'reported','response','2025-07-16','Reported judicial relief and trial-stage limits attached to every Lifeline edge.',['No final trial verdict or later custody change was located.'])
record('scholarship-case','Haridwar scholarships: named societies, account routing and provisional attachment','ED’s15June2026 release traces post-matric scholarship funds through DSWO processing to three named institutions and student-name accounts. Approximately INR27.98crore total disbursements comprise INR19.74crore direct institution credits and INR8.24crore student-name credits. ED alleges INR138,353,060 in the adverse table and approximately INR13.83crore in proceeds/attached assets. The table deduplicates2,895students; it is not a comparable claim denominator for6,208claims.','scholarship',S,caseids('scholarship'),relids('scholarship'),'alleged','investigation-case','2026-06-15','No specifically attributable management response, merits judgment or order confirming this sixth attachment was located in the public search. That gap is not an admission. ED says investigation continues; its five earlier complaints are case-wide, not proof that each newly named actor was charged.',['This is a named three-institution cohort, not a statewide or national fraud estimate.','FY2011–12 overlaps the6October2011 cutoff; no datewise split supports assigning the entire cohort to the window.','Approximate society components2.44+3.95+7.44crore and the attachment valuation describe overlapping proceeds; no cross-stage sum.','INR138,353,060 is the exact table total; INR13.83crore is rounded. The exact figure is not silently substituted for attachment valuation.'])
record('scholarship-response-gap','Scholarship status: agency allegation, no retrieved merits adjudication','The official record announces a sixth provisional attachment and continuing investigation. It does not identify a final court determination for this cohort or publish defendants’ replies. Searches for the named societies and management did not locate a specific response or later merits order; unrelated same-name people are excluded.','scholarship',S,['sc-ed','sc-assets','sc-manika','sc-new-tuples','sc-motherhood-soc','sc-modern-soc'],relids('scholarship'),'reported','response','2026-06-15','Response unavailable in retrieved corpus, not refusal to respond. Authentic enrollment/eligibility records and consented account-operation evidence could rebut or narrow ED’s theory.',['No adverse inference from the response gap; no conclusion that every credited student account was management-controlled.'])
record('srmf-case','SRMF: disputed authority → society-land sale → buyer freeze and SIT','ED alleges that purported society officers used forged authority and a lookalike entity/account arrangement to sell SRMF property to Singhvahini. It separately alleges knowledge and resale by a buyer director. The SupremeCourt’s12May2026 judgment orders investigation while reserving merits and protecting one specific respondent; ED reports two other persons’ arrests and buyer/director asset freezing15May. Exact sale consideration, proceeds split and frozen value are not in the admitted originals.','srmf',T+J,caseids('srmf'),relids('srmf'),'alleged','investigation-case','2026-05-15','The court records competing management lists and pending litigation; respondent2 sought FIR quashing. It preserves conditional non-coercion for Raghvendra Pratap Singh and directs independent investigation without a merits opinion. No specific public denial by the ED-arrested persons or completed SIT report was retrieved.',['ED’s allegation of buyer knowledge is not inferred from ordinary purchaser/director status.','The original registered society and alleged lookalike mechanism are separate nodes; no fake-entity registration is invented.','Court §9 confirms freehold society land, not government leasehold; no public-grant funding is inferred.','No national spiritual organisation or unrelated trust is joined through the founder’s name.','Historical2010 and early2011 allegations are labelled context; current graph status is the2025–2026 transfer/proceeding.'])
record('srmf-court-response','SRMF court boundary: rival management, investigation and individual protection','The Court notes rival office-bearer lists and pending DelhiHighCourt proceedings. It sets aside the bar on filing a police report, orders an SIT, and preserves conditional non-coercion only for respondent2 Raghvendra Pratap Singh. The Court expressly does not decide merits.','srmf',J,['sr-society','sr-raghvendra','sr-buyer','sr-sc'],['sr-sit','sr-protection','sr-raghvendra-role'],'documented','response','2026-05-12','FIR quashing was sought; the order permits investigation and gives bounded procedural protection. It is neither an acquittal nor a finding that every buyer knowingly joined forgery.',['Do not apply protection for respondent2 to different people arrested by ED three days later.'])
record('srmf-status-gap','SRMF latest retained status and missing follow-up','ED’s15May2026 statement reports arrests/remand and asset freezing; it says further investigation continues. The earlier court-directed three-month SIT deadline is not evidence a report was filed. Follow-up search did not locate the report, a later merits judgment or specific response from the ED-arrested persons.','srmf',T+J,['sr-ed','sr-mohan','sr-akash','sr-pradeep','sr-buyer'],['sr-freeze','sr-mohan-arrest','sr-akash-arrest'],'reported','response','2026-05-15','Status is bounded to retrieved documents; no continuing incarceration, absence of defence or completed confiscation is asserted.',['No private residence pins, bank numbers or unrelated personal information is reproduced.'])

# Whitespace repair is prose-only and does not modify identity or reference keys.
import re
def tidy(t):
 t=re.sub(r'(?<=[a-z])(?=[A-Z][a-z])',' ',t)
 t=re.sub(r'\b(INR|USD|PHP)(?=\d)',r'\1 ',t)
 t=re.sub(r'(?<=[A-Za-z])(?=\d)',' ',t)
 t=re.sub(r'(?<=\d)(?=[A-Za-z])',' ',t)
 t=re.sub(r'(?<=[a-z])(?=\d)',' ',t)
 return t.replace('PMLA','PMLA').replace('2025:BHC-AS:6860','2025:BHC-AS:6860')
for group in ['sources','entities','relationships','records']:
 for row in D[group]:
  if row.get('id') in ['lifeline-bail-report-2025','lifeline-bmc-response-2023']:
   row['limitations']=[x.replace('Commercial body is retained only in local cache.','Commercial body is not retained; authored summary and retrieval hashes only.').replace('Commercial body is external-cache only.','Commercial body is not retained; authored summary and retrieval hashes only.') for x in row['limitations']]
  if row.get('id') in ['lifeline-case','lifeline-patkar-status','lh-patkar-bail','lh-receipts-alleged']:
   row['sourceIds']=list(dict.fromkeys(row['sourceIds']+['lifeline-patkar-court-2025']))
  if row.get('id')=='lh-receipts-alleged':
   row['label']='Prosecution: INR324,486,784.90 sanctioned before TDS'
   row['summary']='Bisure §9 and Patkar §6 recount INR324,486,784.90 sanctioned for payment. The later transcription distinguishes this gross amount from TDS and net account credit. It is not a proved loss, kickback or net diverted amount.'
   row['amounts'][0]['stage']='prosecution-alleged sanctioned gross payment before TDS; not net bank credit or proved loss'
  if row.get('id')=='lifeline-patkar-status':
   row['summary']+=' In the court transcription Patkar denies personally forging documents or managing daily attendance/financial records. The court acknowledges prima-facie implications if the prosecution account is taken at face value, but grants conditional bail.'
   row['response']+=' Defence submissions and court qualifications appear in BA3/2025 §§15–21,28–35 and39–54; mirror-only text remains reported.'
  if row.get('id')=='lifeline-case':
   row['summary']=row['summary'].replace('alleged gross receipt is INR324,486,784.90','alleged sanctioned gross amount before TDS is INR324,486,784.90')
   row['limitations'].append('Patkar court transcription separately reports INR318,471,635.72 net credit; this has a two-paise internal subtraction discrepancy and is not added to gross receipts.')
  for key in ['title','label','summary','identityBasis','locator','response','dateBasis','period','falsifier']:
   if isinstance(row.get(key),str):row[key]=tidy(row[key])
  for key in ['limitations','alternativeExplanations']:
   if key in row:row[key]=[tidy(x) for x in row[key]]
  for a in row.get('amounts',[]):a['stage']=tidy(a['stage']);a['period']=tidy(a['period'])
(B.parent/'institutions.json').write_text(json.dumps(D,indent=2,ensure_ascii=False)+'\n')
print({k:len(v) for k,v in D.items()})
