#!/usr/bin/env python3
"""Reproduce the manually reviewed policy slice. No generated inference or inferred joins."""
import json,pathlib,re
R=pathlib.Path(__file__).resolve().parents[4]
OUT=R/'research/raw/atlas-expansion/policy.json'
D={'sources':[],'entities':[],'relationships':[],'records':[],'localities':[]}
def source(id,title,publisher,date,locator,summary,tier='documented',limitations=None,url=None):
 receipt=pathlib.Path(__file__).parent/(id+'.receipt.json')
 if url is None:url=json.load(open(receipt))['url']
 D['sources'].append(dict(id=id,title=title,url=url,publisher=publisher,publishedAt=date,retrievedAt='2026-10-07',locator=locator,summary=summary,tier=tier,limitations=(limitations or [])+[f'Archive: research/raw/atlas-expansion/policy-evidence/{id}.receipt.json; original bytes and extracted text are distinct artifacts.']))
def geo(src,state=None,local=None,note=None):
 return [{'scope':'city' if local else ('state' if state else 'national'),'stateCodes':[state] if state else [],'localityIds':[local] if local else [],'basis':'project-location' if state else 'national-context','note':note or ('Dated project location; no statewide spending inferred.' if state else 'National legal or institutional context; no allocation to every state inferred.'),'sourceIds':src}]
def dims(src,domain,route,layers=None,g=None,limitations=None):
 return dict(sourceIds=src,domains=domain,layers=layers or ['policy','legal'],route=route,geography=g or geo(src),limitations=limitations or [])
def entity(id,label,type,src,domain,route,summary,basis=None,canonical=None,g=None):
 x=dict(id=id,label=label,type=type,resolved=True,identityBasis=basis or 'Exact institution or instrument named in the cited primary document.',summary=summary,**dims(src,domain,route,['organisations','policy','legal'],g))
 if canonical:x['canonicalId']=canonical
 D['entities'].append(x)
def amount(value,unit,stage,period,currency='INR'):return dict(value=value,currency=currency,unit=unit,stage=stage,period=period)
def edge(id,a,b,label,kind,date,src,domain,route,summary,records=None,responses=None,amounts=None,tier='documented',status=None,g=None,limits=None,end=None):
 D['relationships'].append(dict(id=id,from_=a,to=b,kind=kind,label=label,tier=tier,status=status or 'documented dated relationship',statusAsOf=date,fromDate=date,toDate=end or date,dateBasis='Dated legal, contract or disclosure event; an instantaneous event is not an ongoing ownership assertion.',summary=summary,alternativeExplanations=['A lawful policy, contract or financing relationship does not by itself establish preferential treatment or wrongdoing.'],falsifier='A corrected original instrument identifying a different legal party, date, scope or financial stage would require amendment of this relationship.',responseIds=responses or [],recordIds=records or [],amounts=amounts or [],**dims(src,domain,route,['policy','organisations','funding','legal'],g,limits)))
 D['relationships'][-1]['from']=D['relationships'][-1].pop('from_')
def record(id,title,summary,kind,date,src,entities,edges,domain,route,response,alternatives,falsifier,amounts=None,tier='documented',status='documented historical event',asof=None,end=None,g=None,limits=None,period=None):
 D['records'].append(dict(id=id,title=title,summary=summary,kind=kind,tier=tier,status=status,statusAsOf=asof or date,fromDate=date,toDate=end or date,dateBasis='Event/commencement date is distinct from publication, retrieval and later outcome dates; see period.',entityIds=entities,relationshipIds=edges,period=period or date,response=response,alternativeExplanations=alternatives,falsifier=falsifier,amounts=amounts or [],**dims(src,domain,route,['policy','legal','funding','review'],g,limits)))

# Primary originals, named secondary analyses and original issuer statements.
source('finance-act-2017-court','Finance Act 2017, Act 7 of 2017','Gazette of India; official Tripura High Court archive','2017-03-31','PDF pp1,44–45,52; sections11,135–137,154','Section154 removed Companies Act182 profit cap and party-specific company disclosure; associated provisions enabled electoral bonds.',['documented'][0],['Historical enacted version; specified electoral-funding provisions were struck down in February2024.'])
source('bonds-judgment-2024','Association for Democratic Reforms v Union of India, 2024 INSC113','Supreme Court of India','2024-02-15','Majority opinion paragraphs2–25,211–220; PDF pp149–152 conclusion','Constitution Bench struck down electoral-bond anonymity and unlimited corporate funding; ordered issuance stopped and SBI disclosures.',['documented'][0],['This judgment does not establish that any particular donation purchased a government favour; later implementation deadlines are separate.'])
source('ibc-original-2016','Insolvency and Bankruptcy Code2016, Act31','Gazette of India / IBBI','2016-05-28','Sections1,7,21,30–31,53,60; original Gazette','Creditor-initiated corporate resolution, creditor voting and binding adjudicated plans.',['documented'][0],['Original enactment is historical, not a consolidated2026 statement. Commencement was provision-specific under section1(3).'])
source('ibc29a-2018','IBC amendment, Act8 of2018; deemed commencement23November2017','Gazette of India / IBBI','2018-01-19','PDF pp1–4; sections1(2),5–7 inserting29A and related restrictions','Resolution-applicant disqualifications and connected-person test, with specified cure/exception provisions.',['documented'][0],['Gazette heading says Amendment Act2017 while section1 calls it2018; identify unambiguously as Act8of2018, assented18January2018, effective23November2017. Later amendments are not reproduced.'])
source('coal-act-2015','Coal Mines (Special Provisions) Act2015, Act11','Gazette of India / Ministry of Coal','2015-03-30','Sections1(3),4–8,27; ScheduleI','Auction/allotment, vesting and statutory tribunal framework for cancelled-block reallocations.',['documented'][0],['Deemed commencement21October2014; not a complete current consolidation.'])
source('mineral-laws-2020','Mineral Laws (Amendment) Act2020, Act2','Gazette of India / Ministry of Coal','2020-03-13','PDF pp1–6; sections1,3,10–11','Amended MMDR and CMSP to permit coal mining for own consumption, sale or other prescribed purposes and remove former end-use restriction.',['documented'][0],['Section1(3) self-repeals amending Act after60days without prejudice to amendments; this does not mean the inserted changes vanished. Deemed commencement10January2020.'])
source('coal-methodology-2025-annex2020','Commercial coal auction methodology:2020 order and2021/2022/2025 amendments','Ministry of Coal','2025-04-23','AnnexureI order28May2020 paragraphs2.1.2–2.1.7;2025 covering order','Final2020 methodology uses revenue-share bids payable to states, 4%floor and unrestricted sale/utilisation; later underground-only concessions are separately dated.',['documented'][0],['Do not use January2020 discussion-paper terms;2025 underground2%floor/upfront waiver applies prospectively to specified future tranches, not automatically to Radhikapur.'])
source('mmdr-consolidated-2021','MMDR Act1957 consolidated through28March2021','Ministry of Mines text hosted by Maharashtra Directorate of Geology and Mining','2021-03-28','Sections8(5),8A(7A),8B; Sixth Schedule and amendment footnotes','2021 changes permit specified captive-mine sale up to50% after end-use requirements, subject to extra payments, and transfer statutory clearances.',['documented'][0],['Official consolidated historical text; original amendment Gazette endpoint returned503 and is retained separately. This is not the current2026 consolidated Act.'])
source('ports-act-2021','Major Port Authorities Act2021, Act1','Gazette of India / Cochin Port Authority','2021-02-18','Sections1(3),24,27,54,58','Port boards may contract; prospective PPP tariff setting under market conditions, subject to law and rules.',['documented'][0],['Assent17February2021 differs from publication18February and commencement3November2021. Listed major ports scope does not automatically include corporate Kamarajar Port.'])
source('ports-commencement-2021','S.O.4504(E), Major Port Authorities Act commencement','Ministry of Ports, Shipping and Waterways','2021-10-29','PDF p3 Gazette; forwarding letter2November2021','Appoints3November2021 as commencement of the2021 Act.')
source('ports-tariff-2021','Tariff Guidelines2021 for future PPP concessionaires','Ministry of Ports, Shipping and Waterways','2021-12-21','PDF pp1–5; applicability1.2–1.3,2.1–2.5','Prospective market tariff setting, published ceiling rates and continuing contractual royalty conditions.',['documented'][0],['Not proof that an older PPP concession migrated; exact concession dates and tariff regime must be read.'])
source('airports-policy','Rajya Sabha answer on six-airport PPP design','Ministry of Civil Aviation / PIB','2023-03-27','PRID1911136; three eligibility/bid changes and11December2018 PPPAC discussion','No prior airport experience, no cap on airports bid, per-passenger fee rather than revenue share;50year concessions awarded2020–21.',['documented'][0],['Official retrospective policy explanation, not the signed2018 PPPAC minutes or airport-specific payment ledger.'])
source('green-open-access-2022','Electricity Green Energy Open Access Rules2022, GSR418(E)','Ministry of Power Gazette','2022-06-06','Rules2,4–9; four-page English Gazette excerpt','100kW entry threshold,15day access decision, green procurement and banking/charge framework.',['documented'][0],['Historical rules were later challenged and struck down by Karnataka HC; do not present this text as an uncontested nationwide current entitlement.'])
source('karnataka-openaccess-analysis','Forgetting the Basics: Analysis of Rulings on Renewable Energy Banking','Prayas Energy Group','2025-05-25','Karnataka section; footnotes33–35; information compiled30April2025','Reports20December2024 judgment striking GEOA rules/regulations, Union appeal WA154/2025 and KERC final2025 replacement regulations.','reported',['Independent specialist analysis, not primary court order. Official KERC final-PDF retrieval failed503; appeal outcome after this report not verified.'])
source('procurement-2020','Public Procurement (Preference to Make in India) revised order2020','DPIIT','2020-09-16','No.P45021/2/2017-PP(BE-II); paragraphs2,3,3A,5,9,10','ClassI/ClassII local-content rules and price-matching preference alter eligible bidders and quantity allocation.',['documented'][0],['Cover dated15September but says revised order16September2020 effective immediately. Historical version; subsequent revisions require tender-date version checks.'])
source('defence-dap-2020','Defence Acquisition Procedure2020 (retained official11November2021 version)','Department of Defence Production','2021-11-11','ChapterI paragraphs8–14,21; offsets provisions','Indian-IDDM50% indigenous content and no offsets in ab-initio single-vendor cases including IGA/FMS.',['documented'][0],['Retained691page official version includes updates; not every2021 clause is asserted as present at original launch.'])
source('dap-commencement','Defence Acquisition Procedure2020 launch','Ministry of Defence / PIB','2020-09-28','PRID1659746; commencement and indigenous-content table','Government states DAP2020 applicable1October2020 and compares indigenous-content thresholds.')
source('fcra-judgment-2022','Noel Harper v Union of India, WPC566/2021 and connected matters','Supreme Court of India','2022-04-08','Paragraphs1,5,58–87; finalp132','Court records2020 FCRA changes and upholds sections7,12(1A),12A,17, reading down identification to permit Indian passport.',['documented'][0],['Section8 administrative-expense change is reproduced as legislative context; conclusion expressly lists the challenged provisions. No NGO-specific diversion or adverse finding follows from foreign funding.'])
source('tata-bhushan-approval-2018','Approval of Tata Steel resolution plan for Bhushan Steel','Tata Steel exchange disclosure','2018-05-15','PDF pp1–2; NCLT approval and payment/ownership structures','Issuer records NCLT approval, Bamnipal72.65%subscription and proposed creditor settlement.','self-reported',['Original issuer disclosure; approvals and outcomes cross-checked with2022 NCLAT order.'])
source('tata-bhushan-close-2018','Acquisition of Bhushan Steel Limited','Tata Steel exchange disclosure','2018-05-18','PDF p2; acquisition, finance, dues and control paragraphs','Bamnipal completed72.65%acquisition; equity158.89crore, intercompanyloan34973.69crore, bridge16500crore; FCsettlement35200crore being undertaken.','self-reported',['Do not turn being-undertaken settlement or12month OC promise into verified cash receipts. Components overlap and must not be summed.'])
source('bhushan-share-order-2022','Neeraj Singal & another v Tata Steel, CA(AT)(Ins)988/2021','NCLAT Principal Bench / IBBI','2022-03-07','Paragraphs2,8,24–29; pp2–4,25–29','SBI initiated CIRP;2018 approval implemented;2021 SC appeal withdrawn; NCLAT dismissed promoter-share appeal requiring sale at₹2per share.',['documented'][0],['This is Bhushan Steel/Tata Steel BSL, not Bhushan Power & Steel/JSW. It does not decide all criminal or tax matters of former promoters. Latest independently read disposition of this specific share dispute is7March2022.'])
source('bhushan-merger-2021','Effective date of Bamnipal and Tata Steel BSL amalgamation into Tata Steel','Tata Steel exchange disclosure','2021-11-11','One-page letter; effective date and ROC filing','Reports NCLT-sanctioned amalgamation became effective11November2021.','self-reported',['Historical ownership entities cease to be shown as currently separate operating subsidiaries solely on the2018 acquisition.'])
source('coal-auction-winners-2020','Notice declaring successful bidders, CMSP11th/MMDR1st tranche','Ministry of Coal / Nominated Authority',None,'Table row4; comparator rows2,5; final CMDPA sentence','Radhikapur West auction2November2020 won by Vedanta Limited/bidder68522 at21% revenue share.',['documented'][0],['PDF has no printed publication date. Auction date, declaration date and agreement date are distinct.'])
source('coal-allocations-2023','Allocation of coal blocks, tranche-wise','Ministry of Coal',None,'Radhikapur West row15','Official table records Odisha, Vedanta Ltd, auction/sale-of-coal, allocation3March2021 and6MTPA.',['documented'][0],['Historical May2023-hosted allocation snapshot; no production or state cash receipts established.'])
source('vedanta-judgment-2025-pdf','Vedanta v Nominated Authority, WPC10686/2025','Delhi High Court','2025-12-02','Paragraph2;paragraphs16–22; pp74–76; PBG1637622BG0000209','Original judgment records CMDPA11January2021, vesting3March2021,₹292355117.68 appropriation order, party positions and alternative-remedy disposition.',['documented'][0],['Court expressly expresses no merits opinion. Interim PBG status quo was time-limited; a later appeal/tribunal record is necessary.'])
source('vedanta-appeal-2026-mirror','Vedanta/Coal Ministry cross-appeals LPA83 and84/2026','Delhi High Court judgment, third-party PDF mirror','2026-04-10','Paragraphs7–18,42–55; pp14–17 conclusion','Both appeals concerning SCN-III termination-notice/ST31 proceedings were dismissed; territorial/forum objection upheld and limited status-quo protection pending that stay application left intact. PBG/ST28 is a separate proceeding.','reported',['Full signed-looking court PDF read from third-party mirror; official pronouncement list corroborates case/date but not reasons. No final tribunal, subsequent appeal, cash appropriation or termination verified through6October2026.','Paragraph3 says Act2025, an apparent typographical error; primary2025 judgment and statute establish CMSP2015.'])
source('vedanta-appeal-pronouncement-2026','Pronouncement list, LPA83/2026 and84/2026','Delhi High Court','2026-04-10','PDF p1; items1–2','Official court list corroborates cross-appeal numbers, parties and10April2026 pronouncement.',['documented'][0],['Cause/announcement list does not establish substantive disposition; reasons retained separately from mirror.'])
source('vedanta-operations-2025','FY2024–25 aluminium operational review','Vedanta Limited',None,'Captive coal / coal-security section','Radhikapur West6MTPA was planned to commission FY2025–26; separates plans from actual production.','self-reported',['Issuer outlook is not actual commissioning, public royalties paid or legal clearance.'])
source('port-concession-2022','V.O.Chidambaranar–TICTPL concession agreement announcement','Ministry of Ports / PIB','2022-09-04','PRID1856626; agreement date, berth9, cost and DBFOT paragraphs','Names exact parties,3September2022 agreement and₹434.17crore estimated concessionaire development.',['documented'][0],['Announcement, not full executed concession; estimated investment is not a treasury transfer.'])
source('tict-care-2024','Tuticorin International Container Terminal Private Limited rating rationale','CARE Ratings','2024-09-05','PDF pp1–4; concession and royalty paragraphs; Annexure1','Reports exact parent,30year concession from6April2023,₹1900.44/TEU royalty,₹1annual licence, rated bank facilities and repayment covenants.','reported',['Original rating publication, but contract/ownership assertions are the agency’s account, not the executed agreement or audited shareholder register.','₹482.41crore long-term and₹35crore short-term rated facilities are not proved drawdowns. Concession end date appears5/6April2053 in different passages, so do not resolve that one-day discrepancy by assumption.','2024 proposed demerger is not treated as a completed2026 ownership change.'])
source('port-inauguration-2024','Inauguration of Tuticorin International Container Terminal','Ministry of Ports / PIB','2024-09-16','PRID2055412; inauguration, vessel and investment paragraphs','Government records terminal inauguration and maiden vessel, investment over₹434crore and6lakhTEU capacity.',['documented'][0],['Official completion/operating announcement; no audited final cost or port royalty receipt ledger. One repeated paragraph erroneously says6TEUs; repeated main paragraphs specify6lakh, consistent with2022 release.'])
source('port-ipa-location','V.O.Chidambaranar Port Authority public profile','Indian Ports Association',None,'Port details table: latitude, longitude, city and Barathi Nagar address','Explicit public authority location8.75637793296619N78.1790887243492E, TuticorinTamilNadu.',['documented'][0],['Profile locates public port-authority premises; it does not locate berth9 or a specific container crane. Public locality/campus marker only.'])
old=json.load(open(R/'research/raw/investigation/finance-research.json'))
s=next(x for x in old['sources'] if x['id']=='ibbi-named');D['sources'].append({k:s[k] for k in ['id','title','url','publisher','publishedAt','retrievedAt','locator','summary','tier','limitations']});D['sources'][-1]['limitations']+=['Reused original research/raw/investigation/evidence/finance/ibbi-resolutions.pdf, page2 row25; hashes in reused-evidence-manifest.json.']

G=['governance','capital','public-records']; F=['debt-relief','finance','public-finance']; C=['energy','capital','public-funds']; P=['transport','public-works','capital','public-funds']
entity('parliament','Parliament of India','legislature',['finance-act-2017-court','ibc-original-2016'],G,'/political','Enacted the cited statutes; no transaction recipient inferred.')
entity('finance-ministry','Ministry of Finance, Government of India','ministry',['bonds-judgment-2024'],G,'/political','Department of Economic Affairs notified Electoral Bond Scheme2018.')
entity('supreme-court','Supreme Court of India','court',['bonds-judgment-2024','fcra-judgment-2022'],['justice','governance'],'/justice','Constitutional adjudication; the outcome of each distinct case is separately retained.')
entity('sbi','State Bank of India','public-bank',['bhushan-share-order-2022','bonds-judgment-2024'],F,'/debt','CIRP applicant in Bhushan and designated electoral-bond bank; these are separate roles.')
entity('eci','Election Commission of India','constitutional-authority',['bonds-judgment-2024'],G,'/political','Court-directed publication recipient of electoral-bond information.')
entity('nclt','National Company Law Tribunal, Principal Bench, New Delhi','tribunal',['bhushan-share-order-2022'],F,'/debt','Adjudicating authority for cited Bhushan Steel plan; IBBI does not approve the plan.')
entity('ibbi','Insolvency and Bankruptcy Board of India','regulator',['ibbi-named','ibc-original-2016'],F,'/debt','Regulates insolvency ecosystem and publishes RP-reported outcomes.','Exact regulator statutory name and retained official publisher.',canonical='finance-research:entity:ibbi')
entity('nominated-authority','Nominated Authority, Ministry of Coal','authority',['coal-auction-winners-2020','vedanta-judgment-2025-pdf'],C,'/energy','Named statutory allocation and CMDPA enforcement authority; not an inferred minister-person link.')
entity('mines-ministry','Ministry of Mines','ministry',['mmdr-consolidated-2021'],C,'/resources','Publishes mineral-lease statute; state granting authorities retain specified roles.')
entity('ports-ministry','Ministry of Ports, Shipping and Waterways','ministry',['ports-tariff-2021'],P,'/public-works','Issues tariff rules; port board is actual concession party.')
entity('aai','Airports Authority of India','authority',['airports-policy'],P,'/public-works','Awarding authority for six specified airport concessions.')
entity('power-ministry','Ministry of Power','ministry',['green-open-access-2022'],['energy','governance'],'/energy','Issued2022 rules under Electricity Act; later Karnataka vires challenge is separately reported.')
entity('dpiit','DPIIT','department',['procurement-2020'],['public-works','capital','governance'],'/procurement','Issued local-content procurement order under GFR153(iii).')
entity('defence-ministry','Ministry of Defence','ministry',['dap-commencement','defence-dap-2020'],['security','public-funds'],'/security','Capital defence acquisition procedure issuing authority.')
entity('home-ministry','Ministry of Home Affairs','ministry',['fcra-judgment-2022'],['ngo','governance'],'/ngo','Administers foreign-contribution regime; foreign receipt does not imply misconduct.')

policies=[
('finance2017','Finance Act2017: removal of corporate donation cap and party disclosure','2017-03-31',['finance-act-2017-court','bonds-judgment-2024'],['parliament','finance-ministry'],G,'/political','Section154 omitted Companies Act182(1)’s7.5%three-year average-profit cap and replaced party-specific disclosure with a total amount; related amendments enabled electoral bonds. This is the enacted2017 change, subsequently held unconstitutional in specified parts on15February2024.','Union defended formal banking channels, donor privacy and reducing black money; the Court found less restrictive alternatives and Article14/19 violations.','Compare board approval, profits, corporate filing and matched bank instrument for the applicable period; amount/date overlap alone cannot establish quid pro quo.',['Court ruling concerns legal design, not an automatic finding against every donor.'],'2017 statute; specified funding provisions struck down2024'),
('bonds2024','Electoral bonds2024: disclosure remedy and cessation of issuance','2024-02-15',['bonds-judgment-2024'],['supreme-court','sbi','eci'],G,'/political','2024 INSC113 invalidated the scheme and specified secrecy/unlimited-funding amendments; SBI was directed to stop issuing bonds and disclose purchase/encashment information from12April2019 for ECI publication.','The Court balanced donor informational privacy against voters’ right to know; later production orders and serial-number joins must be read separately.','Use exact instrument identity and denomination to match purchaser and encashment; preserve unmatched rows and exclude assumptions of illegal exchange.',['A disclosed lawful contribution is not itself a public-fund disbursement.'],'struck-down scheme; disclosure directions'),
('ibc2016','IBC2016: creditor process, binding plan and recovery accounting','2016-05-28',['ibc-original-2016','bhushan-share-order-2022','ibbi-named'],['parliament','ibbi','nclt'],F,'/debt','The2016 Code created a creditor-initiated resolution mechanism: section7 admission, creditor committee, section30 plan and section31 approval. Bhushan shows SBI’s application reaching an approved transfer to a new owner. Enactment date is not universal commencement.','Creditor recovery must be compared with liquidation and operating value; debt claims, approved plan-realizable value and verified cash receipts differ. An IBC plan is not the same legal event as an accounting write-off or government loan waiver.','Reconcile plan, creditor-wise distribution and bank cash ledger, preserving claim classes and dates; do not subtract a buyer’s equity cheque from total claims to compute public loss.',['Distress and going-concern value can explain compromise; former owners can lose control.'],'historical enactment; specific plan implemented'),
('ibc29a','Section29A: eligibility checks before acquiring distressed assets','2017-11-23',['ibc29a-2018'],['parliament','ibbi'],F,'/debt','Act8of2018, deemed effective23November2017, inserted disqualifications including wilful default, specified NPA/control relationships and connected persons, plus a defined overdue-payment cure. Liquidation sales received a linked restriction.','This is a dated legal version; later statutory exceptions and amendments must be checked for the bid date. No named bidder is declared ineligible from a shared surname or address.','Verify applicant/connected-person ownership, dates of NPA classification, cure evidence and RP/CoC determination from actual bid documents.',['Eligibility criteria can protect creditors while narrowing a distressed auction’s bidder pool.'],'enacted with retrospective commencement'),
('coal2020','Commercial coal2020: end-use liberalisation and revenue-share auction','2020-01-10',['mineral-laws-2020','coal-act-2015','coal-methodology-2025-annex2020','coal-auction-winners-2020'],['parliament','nominated-authority'],C,'/energy','Act2of2020 broadened coal eligibility/end uses, effective10January2020; the final28May2020 methodology used ascending revenue-share bids payable to states and permitted own use, sale and related-party sales. Radhikapur’s actual21%award is a specific implementation.','The government methodology seeks production and competition; the public audit check is benchmark revenue, production and milestones. January2020 discussion-paper terms were not adopted as final.','Test declared volumes/grade/value against National Coal Index/actual-price methodology and royalty statements; require actual receipts before claiming fiscal gain.',['An open statutory auction is a common mechanism; the published winner table includes different corporate bidders.'],'enacted amendment plus final auction order'),
('mmdr2021','MMDR2021: captive sale permission and transferred clearances','2021-03-28',['mmdr-consolidated-2021'],['parliament','mines-ministry'],C,'/resources','Sections8(5)/8A(7A) permit specified captive mines to sell up to50%of annual output after meeting linked end-use needs, subject to SixthSchedule additional payments. Section8B changes the transfer of statutory clearances. Tariff-bid/UMPP coal exception remains material.','These are permissions with conditions, not proof that any operator sold mineral or remitted money. Historic mine-specific lease and latest implementing rules are needed.','Compare permitted end use, annual production, sale invoices, additional-payment receipt and transfer conditions; apply explicit statutory exclusions before counting beneficiaries.',['Selling genuine surplus may improve utilisation without diverting linked-plant supply.'],'historical enacted amendment'),
('ports2021','Major ports2021: market tariffs with concession royalties intact','2021-11-03',['ports-act-2021','ports-commencement-2021','ports-tariff-2021'],['ports-ministry'],P,'/public-works','The Act commenced3November2021;21December guidelines apply prospectively to future PPP agreements. Concessionaires may publish market-based ceiling tariffs, subject to law, while contract royalties and other conditions continue. TICTPL’s2022concession fits the dated scope.','Existing concessions are a separate comparison class. The retained Act lists covered major ports; corporate Kamarajar/Ennore was not automatically joined.','Inspect concession date/regime, published scale of rates, invoices, minimum throughput and royalty ledger; tariff autonomy alone does not establish a giveaway.',['Market pricing can improve competition and responsiveness while preserving landlord payments.'],'commenced Act; prospective tariff guidelines'),
('airports2018','Six-airport PPP design: experience, concentration and fee basis','2018-12-11',['airports-policy'],['aai'],P,'/public-works','The government’s2023parliamentary explanation identifies the2018PPPAC process: no prior airport experience, no cap on airports bid, and per-passenger fee rather than revenue-sharing. Six airports were awarded50year concessions in2020–21. This was procurement design, not a new Act.','Government states the changes sought competition/flexibility and technical/financial capacity was evaluated; demand uncertainty explained not estimating total50year project cost upfront.','Compare eligible/qualified bidders and per-passenger fee bids with demand, termination and revenue ledgers; do not equate concession tenure with a permanent asset sale.',['Opening eligibility can broaden competition even if one bidder ultimately wins multiple airports.'],'retrospectively documented procurement-policy design'),
('green2022','Green open access2022: industrial purchasing routes and later court challenge','2022-06-06',['green-open-access-2022','karnataka-openaccess-analysis'],['power-ministry'],['energy','public-finance'],'/energy','GSR418(E) introduced100kWgreen-access eligibility,15day processing and developer/distribution-licensee procurement routes. Karnataka HC struck down central/state GEOA measures on20December2024, according to retained specialist reporting; KERC replaced its regulations in2025 and a Union appeal was reported.','Prayas records WritAppeal154/2025 admitted and listed23June2025, based on information compiled30April2025. No later appeal disposition was verified here; this card does not assert an uncontested nationwide current entitlement.','Use the operative state regulation, dated court orders, PPA, wheeling/banking agreement and billing-period charges before quantifying a corporate benefit or distribution-company burden.',['The dispute concerns allocation of regulatory power and banking costs; renewable procurement itself is not evidence of impropriety.'],'historical rules; Karnataka invalidation/appeal reported'),
('procurement2020','Local-content procurement2020: eligibility and L1 matching','2020-09-16',['procurement-2020'],['dpiit'],['public-works','capital','public-funds'],'/procurement','Revised Make-in-India order distinguishes ClassI/ClassII suppliers using local content (normally50%/20%) and gives specified ClassI price-matching/quantity preference within20%margin. It changes allocation rules; it does not authorize charging20%more automatically.','Order’s declared aim is domestic production and employment. Historical2020version only; category-specific nodal rules and later revisions must be checked for each tender.','Recompute local content from import values and auditor certification; compare awarded quantity, eligible class and matched L1 price, with exceptions retained.',['A compliant preference may lawfully favour domestic value added; imports or an Indian brand alone do not determine supplier class.'],'historical revised executive order'),
('dap2020','DAP2020: indigenous-content categories and offset exclusions','2020-10-01',['dap-commencement','defence-dap-2020'],['defence-ministry'],['security','capital','public-funds'],'/security','DAP2020 applies from1October2020. Official retained2021version requires50%indigenous content for Indian-IDDM and excludes offsets in ab-initio single-vendor cases including IGA/FMS. A defence purchase and an offset obligation are separate instruments.','Government launch explains higher indigenous content and domestic capability goals; the retained manual includes later updates, so the exact RFP/date governs.','Identify acquisition category/AoN/RFP, base contract price excluding tax, imported content and applicable offset exception before labelling absent offsets a breach.',['Government-to-government or strategic procurement may lawfully use an offset exception.'],'adopted procedure; retained updated version identified'),
('fcra2020','FCRA2020: designated receipt bank, transfer ban and administrative cap','2020-09-29',['fcra-judgment-2022'],['home-ministry','sbi','supreme-court'],['ngo','governance','finance'],'/ngo','The amendment commenced29September2020: foreign contribution must first enter designated SBI NewDelhi account; onward transfer to another person is barred and administrative-expense limit changed50%to20%. NoelHarper2022upheld challenged provisions, permitting Indian passports under section12A.','Union argued traceability and beneficiary use; petitioners argued operational burdens and fundamental-rights infringement. Court’s conclusion upholds sections7,12(1A),12A,17; expense-cap discussion is context.','Reconcile donor remittance, designated FCRA account, recipient’s utilisation accounts and FC4/audited returns. Distinguish internal account transfers and vendor payments from prohibited grants to another person using actual legal records.',['Lawful foreign funding and an SBI account create neither a public subsidy nor proof of diversion.'],'enacted2020; challenged provisions upheld2022')]
for id,title,date,src,agencies,domain,route,summary,response,test,alts,status in policies:
 entity(id+'-instrument',title,'legal-instrument',src,domain,route,summary)
 rel=id+'-implementation';authority=agencies[0]
 edge(rel,authority,id+'-instrument','Dated enactment, adjudication or implementation framework','legal-framework',date,src,domain,route,summary,records=[id],responses=['green-litigation'] if id=='green2022' else [])
 record(id,title,summary,'policy-change',date,src,agencies+[id+'-instrument'],[rel],domain,route,response,alts,test,status=status,asof='2025-04-30' if id=='green2022' else date,limits=['Curated policy history, not a complete consolidation or a causal finding about an unnamed beneficiary.','Public-interest audit test: '+test])

record('green-litigation','GEOA: later Karnataka judgment and incomplete appeal endpoint','Retained Prayas analysis reports2024HC invalidation,2025replacement regulations and admitted Union appeal WA154/2025. Official final-KERC PDF returned503 and indexed fetch failed. Later disposition is unverified.','response','2024-12-20',['karnataka-openaccess-analysis','green-open-access-2022'],['power-ministry','green2022-instrument'],[],['energy','justice'],'/energy','Both generator access and distribution-company costs require hearing; this entry makes the legal-status gap visible.',['A later appellate stay or reversal may alter operative scope.'],'Obtain official WA154/2025 orders after30April2025 and current consolidated state regulations.',tier='reported',asof='2025-04-30',status='primary outcome and later appeal endpoint incomplete')

# CASE1: new-owner resolution finance, not a waiver to former owners.
entity('bhushan-steel','Bhushan Steel Limited / Tata Steel BSL Limited','company',['ibbi-named','bhushan-merger-2021'],F,'/debt','Historical debtor subsequently renamed and amalgamated; distinct from Bhushan Power & Steel.','IBBI row25 gives CIN L74899DL1983PLC014942; issuer expressly names formerBhushanSteel.',canonical='finance-research:entity:bhushan-steel')
entity('tata-steel','Tata Steel Limited','company',['tata-bhushan-close-2018','bhushan-share-order-2022'],F+['capital'],'/debt','Resolution sponsor and eventual amalgamated successor.','Original exchange disclosure gives CIN L27100MH1907PLC000260; NCLAT names the same legal respondent.')
entity('bamnipal','Bamnipal Steel Limited','company',['tata-bhushan-close-2018','bhushan-merger-2021'],F+['capital'],'/debt','Wholly owned acquisition subsidiary in2018; issuer reports2021amalgamation.','Exact acquisition subsidiary expressly identified in original Tata exchange disclosure.')
entity('bhushan-fc','Bhushan Steel financial creditors (plan cohort)','creditor-cohort',['ibbi-named','tata-bhushan-close-2018'],F,'/debt','Plan-defined creditor cohort; not a single bank or wholly public-sector exposure.','Defined creditor class in plan reporting; no unnamed bank allocation inferred.')
br=['bhushan-policy-resolution'];rr=['bhushan-response']
edge('ibc-bhushan','ibc2016-instrument','nclt','Provides corporate-resolution adjudication framework','statutory-framework','2016-05-28',['ibc-original-2016'],F,'/debt','Sections7/30/31/60 supply the adjudication route used by theBhushan plan.',br,rr)
edge('sbi-bhushan-cirp','sbi','bhushan-steel','Initiated CIRP through creditor application','creditor-application','2017-07-26',['bhushan-share-order-2022','ibbi-named'],F,'/debt','NCLAT paragraph2 records SBI application; IBBI row25 supplies CIRP commencement date. No SBI-only recovery amount inferred.',br,rr)
edge('nclt-bhushan-plan','nclt','bhushan-steel','Approved Tata resolution plan','plan-approval','2018-05-15',['bhushan-share-order-2022','tata-bhushan-approval-2018'],F,'/debt','Approval binds parties subject to the documented appeal history.',br,rr)
edge('tata-bamnipal','tata-steel','bamnipal','Wholly owned acquisition vehicle in2018','ownership','2018-05-18',['tata-bhushan-close-2018'],F+['capital'],'/debt','Issuer expressly states wholly ownedBNPL; no current subsidiary status after2021amalgamation inferred.',br,rr,tier='self-reported')
edge('bamnipal-bhushan','bamnipal','bhushan-steel','Acquired72.65%and funded equity/inter-company loan','acquisition-finance','2018-05-18',['tata-bhushan-close-2018'],F+['capital'],'/debt','Equity₹158.89crore and inter-corporate loan₹34973.69crore funded control transfer;₹16500crore external bridge financed BNPL and is not another public payout.',br,rr,[amount(158.89,'crore','issuer-reported equity subscription','2018-05-18'),amount(34973.69,'crore','issuer-reported inter-corporate loan','2018-05-18')],tier='self-reported')
edge('bamnipal-fc','bamnipal','bhushan-fc','Paid reported debt-novation consideration','creditor-settlement','2018-05-18',['tata-bhushan-close-2018'],F,'/debt','Issuer explicitly attributes ₹100 crore paid for novation of remaining debt to BNPL. The wider ₹35,200 crore settlement is a plan-level statement, without direct payer assigned here.',br,rr,[amount(100,'crore','issuer-reported BNPL debt-novation consideration; do not add to aggregate plan measures','2018-05-18')],tier='self-reported')
record('bhushan-response','Bhushan: former-owner challenge, binding plan and2021merger','NCLAT dismissed the promoter-share appeal on7March2022 and upheld sale at₹2per share under the approved structure. Its judgment records the prior Supreme Court challenge dismissed as withdrawn22February2021. Tata reportsBNPL/TSBSL merger effective11November2021.','response','2022-03-07',['bhushan-share-order-2022','bhushan-merger-2021'],['tata-steel','bamnipal','bhushan-steel'],[],F,'/debt','Former promoters argued they could retain reclassified public shares; Tata argued transfer was integral to the approved plan. NCLAT rejected the former-promoter position. No new contact was attempted.',['A new-owner recovery plan differs from cancellation of debt for the former promoter.'],'A later order in this same share-transfer dispute or corrected merger filing would change this dated status.',status='latest retained specific share-dispute order; broader disputes outside scope',limits=['Do not import2025–26 BhushanPower&Steel/JSW outcomes into this distinct debtor.'])
record('bhushan-policy-resolution','Bhushan Steel: IBC→SBI/NCLT→Bamnipal→creditor settlement','SBI-initiated CIRP led to15May2018plan approval and18May72.65%acquisition byTata’sBamnipal. Issuer financing separated₹158.89crore equity,₹34973.69crore inter-company loan and₹16500crore external bridge. The35200crore creditor settlement was then being undertaken; IBBI later reports35571crore FC-realizable against56022.06crore FCclaims.','investigation-case','2018-05-18',['ibc-original-2016','bhushan-share-order-2022','tata-bhushan-close-2018','ibbi-named','bhushan-merger-2021'],['ibc2016-instrument','nclt','sbi','ibbi','tata-steel','bamnipal','bhushan-steel','bhushan-fc'],['ibc-bhushan','sbi-bhushan-cirp','nclt-bhushan-plan','tata-bamnipal','bamnipal-bhushan','bamnipal-fc'],F+['capital'],'/debt','Response card retains promoter objections and rejection, previousSCwithdrawal, and issuer2021merger. Recovery statistics are plan-realizable, not independently verified cash.',['Liquidation value₹14541crore is a relevant counterfactual; claim haircut alone is not a payment to buyer or former owner.','₹35200crore2018settlement statement and₹35571crore2022FC-realizable measure differ in date/stage and need plan-ledger reconciliation.'],'The approved distribution schedule and creditor-wise dated cash receipts would validate/revise realized recovery and public-bank allocation.',[amount(35200,'crore','issuer-reported aggregate financial-creditor settlement being undertaken; direct payer not assigned','2018-05-18'),amount(56022.06,'crore','IBBI admitted financial-creditor claims','2022-09-30 historical snapshot'),amount(35571,'crore','IBBI FC plan-realizable; not NPV or verified cash','2022-09-30 historical snapshot'),amount(14541,'crore','IBBI estimated liquidation value','2022-09-30 historical snapshot'),amount(16500,'crore','issuer-reported external acquisition bridge loan; lender not established here','2018-05-18')],asof='2022-03-07',status='acquisition/merger documented; creditor cash reconciliation incomplete',limits=['New edges extend the retained historical IBBI row; no named individual is claimed to have received a loan waiver.','Accounting units overlap. Never sum financing sources, financing uses and creditor claims.'],period='CIRP26July2017; approval15May2018; acquisition18May2018; merger11November2021; share appeal7March2022; IBBIsnapshot30September2022')

# CASE2: a commercial-coal instrument and contested enforcement, with current outcome boundary.
cg=geo(['coal-allocations-2023','vedanta-judgment-2025-pdf'],'OD',None,'Radhikapur(West)coal mine, Angul district, Odisha, named in court and ministry records; no inferred boundary coordinates.')
entity('vedanta-limited','Vedanta Limited','company',['coal-auction-winners-2020','vedanta-judgment-2025-pdf'],C,'/energy','Exact auction bidder/petitioner, not aggregatedVedanta/BALCO group.','Official bidder68522 and exact plaintiff name in original court judgment.',g=cg)
entity('radhikapur-west','Radhikapur(West)coal mine','public-resource',['coal-allocations-2023','vedanta-judgment-2025-pdf'],C,'/energy','Odisha commercial coal block, allocated3March2021; production status not inferred from allocation.',g=cg)
entity('radhikapur-cmdpa','Radhikapur(West)CMDPA dated11January2021','concession-instrument',['vedanta-judgment-2025-pdf'],C,'/energy','President of India–Vedanta Coal Mine Development and Production Agreement; enforcement clauses10/25/26 andScheduleD.',g=cg)
cr=['radhikapur-policy-enforcement'];cp=['radhikapur-response']
edge('coal-framework-authority','coal2020-instrument','nominated-authority','Commercial auction framework implemented by statutory authority','implements-framework','2020-06-18',['vedanta-judgment-2025-pdf','coal-methodology-2025-annex2020'],C,'/energy','11thtranche tender issued18June2020 for commercial sale underCMSP2015 as amended.',cr,cp,g=cg)
edge('coal-award-vedanta','nominated-authority','vedanta-limited','Awarded Radhikapur at21%revenue-share bid','auction-award','2020-12-28',['coal-auction-winners-2020','vedanta-judgment-2025-pdf'],C,'/energy','Auction2November; successful declaration28December2020 per court.21%is contractual share, not21%of a measured treasury receipt.',cr,cp,g=cg)
edge('coal-cmdpa','nominated-authority','radhikapur-cmdpa','Executed commercial mine development instrument','concession-contract','2021-01-11',['vedanta-judgment-2025-pdf'],C,'/energy','Court identifies agreement between PresidentofIndia andVedanta and efficiency milestones.',cr,cp,g=cg)
edge('coal-vesting','radhikapur-cmdpa','vedanta-limited','Vested rights in RadhikapurWest','resource-vesting','2021-03-03',['vedanta-judgment-2025-pdf','coal-allocations-2023'],C,'/energy','Vesting underCMSP is a development/right instrument; environmental and forest obligations continue.',cr,cp,g=cg)
edge('coal-mine-right','vedanta-limited','radhikapur-west','Named allottee of commercial coal block','allotment','2021-03-03',['coal-allocations-2023'],C,'/energy','Official allocation table lists sale-of-coal category and6MTPAcapacity; no actual production or payment inferred.',cr,cp,g=cg)
edge('coal-pbg-order','nominated-authority','vedanta-limited','Ordered disputed performance-guarantee appropriation','enforcement-order','2025-07-21',['vedanta-judgment-2025-pdf'],C+['justice'],'/energy','Appropriation orderNA104/8/2020-NA directed₹292355117.68 fromPBG for disputed milestone noncompliance; later proceedings prevent treating order as final cash recovery.',cr,cp,[amount(292355117.68,'rupees','appropriation ordered and disputed; not verified received','2025-07-21')],status='disputed order; later procedural protection retained',g=cg)
record('radhikapur-response','Radhikapur: disputed clearances, alternative remedy and2026cross-appeals','Vedanta cited changed mine boundaries, forest/compensatory-afforestation issues and force majeure. Ministry disputed delay justification. On 2 December 2025 Delhi HC referred the PBG dispute to the CMSP Tribunal and reserved merits. The reported 10 April 2026 cross-appeals instead concerned ST31/2025 and SCN-III proposing termination; both were dismissed with limited protection on that separate track.','response','2026-04-10',['vedanta-judgment-2025-pdf','vedanta-appeal-2026-mirror','vedanta-appeal-pronouncement-2026'],['vedanta-limited','nominated-authority','radhikapur-cmdpa'],[],C+['justice'],'/energy','The original 2025 PBG order continued status quo for ten days or until the tribunal was approached, whichever earlier. The 2026 mirror reports a December 2025 LPA759/2025 extension pending the ST28/2025 stay application; its final outcome remains unverified. April 2026 protection concerns termination notice SCN-III/ST31/2025, not a final determination of PBG recovery. No company contact was attempted; public pleadings supply its position.',['Government enforcement is evidence of a contested contract administration process, not proof of completed cancellation or an improper award.'],'Official2026judgment and laterTalcherTribunal/OrissaHighCourt/SCorders, plus bank debit/state credit confirmation, would settle remaining status.',tier='reported',status='latest found outcome10April2026; final tribunal and cash endpoint unknown',g=cg,limits=['Official2026pronouncement list validates parties/case/date only; substantive2026reasoning remains mirror-reported.'])
record('radhikapur-policy-enforcement','RadhikapurWest: commercial coal rule→Vedanta CMDPA→disputed guarantee','The2020commercial framework led toVedantaLimited’s21%revenue-share bid,11January2021CMDPA and3March2021vesting forRadhikapurWest. The21July2025order directed₹29,23,55,117.68PBGappropriation for a missed milestone; the original 2025 judgment reserved merits. The separate termination-notice appeals in April 2026 left limited protection pending ST31/2025 stay adjudication. Final PBG recovery in ST28/2025 remains unverified.','investigation-case','2021-01-11',['mineral-laws-2020','coal-methodology-2025-annex2020','coal-auction-winners-2020','coal-allocations-2023','vedanta-judgment-2025-pdf','vedanta-appeal-2026-mirror','vedanta-appeal-pronouncement-2026','vedanta-operations-2025'],['coal2020-instrument','nominated-authority','vedanta-limited','radhikapur-cmdpa','radhikapur-west'],['coal-framework-authority','coal-award-vedanta','coal-cmdpa','coal-vesting','coal-mine-right','coal-pbg-order'],C+['justice'],'/energy','Response card retains Vedanta’s force-majeure and boundary case, the Ministry position, and separate PBG/ST28 and termination-notice/ST31 outcomes. No bank encashment, state-revenue receipt or final termination is asserted.',['Same published tranche includesHindalco/Chakla14.25%andJMS/Urtan10.5%; rates differ with resources and cost, so21%alone is not a favour signal.','FY25issuer commissioning plan is an expectation, not completed production.'],'Obtain completeCMDPA, actual revenue-share statements and receipts, PBGdebit/credit evidence and finaltribunal/appellate order; withdraw any contrary cash/termination inference.',[amount(292355117.68,'rupees','contested performance-guarantee appropriation order, not cash recovered','2025-07-21')],asof='2026-04-10',status='specific award documented; enforcement contested; later outcome partly reported',g=cg,limits=['No donor/political favour edge is inferred from timing or group identity.','Current legal review found April2026outcome; no later final disposition verified through6October2026.'],period='Framework2020; bid2November2020; declaration28December2020; CMDPA11January2021; vesting3March2021; appropriation21July2025; HC2December2025; latest found appeal10April2026')

# CASE3: publicly owned port -> exact private concessionaire -> distinct recurring charge and finance.
pg=geo(['port-concession-2022','port-inauguration-2024'],'TN','thoothukudi','Berth9project atV.O.ChidambaranarPort,Thoothukudi,TamilNadu; public authority marker is not berth location.')
D['localities'].append(dict(id='thoothukudi',name='Thoothukudi',stateCode='TN',kind='city',aliases=['Tuticorin'],districtName='Thoothukudi'))
entity('voc-port','V.O.Chidambaranar Port Authority','public-port-authority',['port-concession-2022','ports-act-2021','port-ipa-location'],P,'/public-works','Public port board and concession landlord forberth9.',g=pg)
entity('tictpl','Tuticorin International Container Terminal Private Limited','company',['port-concession-2022','tict-care-2024'],P,'/public-works','Exact2022concession counterparty; do not substitute group parent or nearbyPSASical.','Exact legal name independently named by official concession announcement and originalCARErationale.',g=pg)
entity('jmbaxi-pl','J M Baxi Ports and Logistics Private Limited','company',['tict-care-2024'],P,'/public-works','CARE-reported direct parent asofSeptember2024; later proposed demerger not treated as completed.','Full legal parent name specified inCARErationale; no current2026ownership assertion.',g=pg)
entity('tict-concession','TICTPL berth9DBFOT concession dated3September2022','concession-instrument',['port-concession-2022','tict-care-2024'],P,'/public-works','Specific public-asset concession; execution date differs fromCARE-reported6April2023award/start date.',g=pg)
pr=['tict-policy-concession'];ps=['tict-response']
edge('port-law-board','ports2021-instrument','voc-port','Provides board/concession and prospective tariff framework','statutory-framework','2021-11-03',['ports-act-2021','ports-commencement-2021','ports-tariff-2021'],P,'/public-works','Act explicitly includes V.O. Chidambaranar; guideline applies to future concessions.',pr,ps,g=pg)
edge('voc-tict-concession','voc-port','tict-concession','Signed berth9conversion concession','concession-award','2022-09-03',['port-concession-2022'],P,'/public-works','Official DBFOT announcement estimates ₹434.17 crore concessionaire development and 600,000 TEU capacity; no public cash grant.',pr,ps,[amount(434.17,'crore','estimated concessionaire project-development cost','2022-09-03 announcement')],g=pg)
edge('tict-concession-spv','tict-concession','tictpl','Names private development/operation counterparty','contract-party','2022-09-03',['port-concession-2022'],P,'/public-works','The exact SPV undertakes DBFOT conversion of berth 9.',pr,ps,g=pg)
edge('jmbaxi-tict','jmbaxi-pl','tictpl','Reported wholly owned subsidiary at2024snapshot','ownership','2024-09-05',['tict-care-2024'],P,'/public-works','CARE identifies the direct parent and sponsor-support undertaking; planned parent demerger requires later completion proof.',pr,ps,tier='reported',g=pg)
edge('tict-royalty-port','tictpl','voc-port','Contractual royalty perTEU and annual licence fee','royalty-obligation','2024-09-05',['tict-care-2024'],P,'/public-works','CARE reports ₹1,900.44 per TEU, WPI escalation, minimum throughput and ₹1 annual licence fee; ₹1 is not the total consideration.',pr,ps,[amount(1900.44,'rupees per TEU','reported contractual royalty rate before subsequent WPI escalation; not aggregate paid','2024-09-05'),amount(1,'rupees per year','reported annual licence fee; excludes royalty and other obligations','2024-09-05')],tier='reported',g=pg)
edge('voc-tict-operation','voc-port','tictpl','Government announced inauguration and maiden vessel','operational-milestone','2024-09-16',['port-inauguration-2024'],P,'/public-works','Official inauguration records commencement; this is not an audited royalty receipt.',pr,ps,g=pg)
record('tict-response','TICTPL: commercial rationale, minimum throughput and financial-stage limits','Government describes added capacity and lower logistics costs. CARE identifies minimum throughput, royalty, competition, DSCR 1.50 and cash restrictions; its 2024 parent demerger was pending. Government recorded inauguration on 16 September 2024.','response','2024-09-16',['port-inauguration-2024','tict-care-2024'],['voc-port','tictpl','jmbaxi-pl'],[],P,'/public-works','No adverse court proceeding against this concession was verified; no alleged wrongdoing or fabricated denial is introduced. CARE’s risk and obligation record and the government rationale supply counter-evidence. No outreach was attempted.',['Prospective tariff autonomy coexists with royalty and traffic risk; the ₹1 annual licence alone is a misleading valuation.','PSA Sical berth 7 and its litigation are separate and cannot be assigned to TICTPL berth 9.'],'Executed or amended concession, audited royalty receipts and later ownership completion filings would change financial and status inferences.',tier='reported',status='operational announcement verified; latest finance/ownership source September 2024',g=pg)
record('tict-policy-concession','Tuticorin berth 9: new port law → public board → TICTPL → royalty','The 2021 major-port framework applies to the 3 September 2022 VOC–TICTPL DBFOT concession. Government estimated ₹434.17 crore private development; CARE later reports ₹1,900.44 per TEU royalty plus ₹1 annual licence, a 30-year term from 6 April 2023 and ₹482.41 crore long-term / ₹35 crore short-term rated facilities. Terminal inaugurated 16 September 2024.','investigation-case','2022-09-03',['ports-act-2021','ports-commencement-2021','ports-tariff-2021','port-concession-2022','tict-care-2024','port-inauguration-2024','port-ipa-location'],['ports2021-instrument','voc-port','tict-concession','tictpl','jmbaxi-pl'],['port-law-board','voc-tict-concession','tict-concession-spv','jmbaxi-tict','tict-royalty-port','voc-tict-operation'],P,'/public-works','Response card retains government rationale, minimum throughput and debt safeguards. CARE’s royalty and ownership details are reported; full signed concession and actual public royalty receipts remain unobtained.',['Estimated project cost, rated bank limits and royalty rates are incompatible accounting units; differences do not establish a cost overrun or cash transfer.','Old port concessions and specific new SPVs are controls against misapplying prospective 2021 law.'],'Obtain the full concession, post-opening tariffs, volume/royalty statements, port credit entries and latest SPV shareholding before quantifying public receipts or current ownership.',[amount(434.17,'crore','official estimated concessionaire project cost; not state grant','2022-09-03'),amount(482.41,'crore','CARE-rated long-term bank facilities; not verified drawdown','2024-09-05'),amount(35,'crore','CARE-rated short-term bank facilities; not verified drawdown','2024-09-05'),amount(1900.44,'rupees per TEU','reported contractual royalty rate; not total concession value','2024-09-05')],asof='2024-09-16',status='inauguration verified; royalty payments and later ownership not verified',g=pg,limits=['Direct ownership and financial terms retained at the 2024 snapshot; do not treat the pending demerger as completed.','Official port marker describes public authority location, not berth 9 coordinates.'],period='Act commenced 3 November 2021; guidelines 21 December 2021; agreement signed 3 September 2022; CARE start 6 April 2023; rating 5 September 2024; inauguration 16 September 2024')

# Normalize only human-facing text; identifiers, dates and URLs remain exact.
human_keys={'title','label','publisher','locator','summary','identityBasis','status','dateBasis','period','response','falsifier','note','stage','unit'}
human_arrays={'limitations','alternativeExplanations'}
def prose(s):
 ids=re.findall(r'\b[UL][0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}\b',s)
 for i,ident in enumerate(ids):s=s.replace(ident,'protectedidentifier'+chr(97+i))
 s=re.sub(r'([a-z])([A-Z])',r'\1 \2',s)
 s=re.sub(r'([A-Za-z])([0-9])',r'\1 \2',s)
 s=re.sub(r'([0-9])([A-Za-z])',r'\1 \2',s)
 s=re.sub(r'(?<=[;])(?=[A-Za-z0-9₹])',' ',s)
 s=re.sub(r'(?<=[,])(?=[A-Za-z₹])',' ',s)
 s=re.sub(r'(?<=%)(?=[A-Za-z])',' ',s)
 s=re.sub(r'\b(29|8|7|12) ([A-Z])\b',r'\1\2',s)
 s=s.replace('L 1','L1').replace('k Wgreen','kW green').replace('k W','kW')
 for a,b in {'FCclaims':'FC claims','SCwithdrawal':'SC withdrawal','CMSPTribunal':'CMSP Tribunal','PBGappropriation':'PBG appropriation','WPIescalation':'WPI escalation','FY 25':'FY25','₹ 1':'₹1'}.items():s=s.replace(a,b)
 s=re.sub(r'(?<=[a-z])(?=₹)',' ',s)
 for a,b in {'forberth':'for berth','asof':'as of','CA RE':'CARE','CARErationale':'CARE rationale','PSASical':'PSA Sical','Presidentof':'President of','MTPAcapacity':'MTPA capacity','FCsettlement':'FC settlement','intercompanyloan':'inter-company loan','11 thtranche':'11th tranche','11 th':'11th','1 st':'1st','court.21%':'court. 21%','Radhikapur(West)coal':'Radhikapur (West) coal','Radhikapur(West)CMDPA':'Radhikapur (West) CMDPA','(1 A)':'(1A)','parent,30':'parent, 30','parties,3':'parties, 3','eligibility,15':'eligibility, 15','threshold,15':'threshold, 15','previous SCwithdrawal':'previous SC withdrawal'}.items():s=s.replace(a,b)
 for i,ident in enumerate(ids):s=s.replace('protectedidentifier'+chr(97+i),ident)
 return s
def clean(value,key=''):
 if isinstance(value,dict):return {k:clean(v,k) for k,v in value.items()}
 if isinstance(value,list):return [prose(v) if key in human_arrays and isinstance(v,str) else clean(v) for v in value]
 return prose(value) if isinstance(value,str) and key in human_keys else value
D=clean(D)
OUT.write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
print({k:len(v) for k,v in D.items()})
