"""Build the reviewed institutional slice. Run from any directory; no inferred edges."""
import json, pathlib
B=pathlib.Path(__file__).resolve().parent
OUT=B.parent/'institutions.json'
S={'sources':[],'entities':[],'relationships':[],'records':[],'localities':[]}

def source(id,title,publisher,date,locator,summary,tier='documented',limitations=(),url=None):
    if url is None: url=json.loads((B/(id+'-receipt.json')).read_text())['url']
    S['sources'].append(dict(id=id,title=title,url=url,publisher=publisher,publishedAt=date,retrievedAt='2026-10-07',locator=locator,summary=summary,tier=tier,limitations=list(limitations)))

source('ael-warrant-2022','AEL: VCPL exercises RRPR warrants and announces NDTV open offer','Adani Enterprises Limited; stock-exchange disclosure','2022-08-23','pp1–4, warrant exercise and annexure cost/consideration','Identifies AEL → AMNL → VCPL ownership; 1,990,000 RRPR warrants for INR19,900,000; proposed acquisition of up to26% NDTV.',['documented'][0],['The exercise notice and offer are dated stages, not proof that the maximum offer was fully accepted.'])
source('ndtv-warrant-2022','NDTV: founders respond to warrant exercise notice','New Delhi Television Limited; stock-exchange disclosure','2022-08-23','p1, statement and attached public announcement','Records the INR1.99 crore notice-stage deposit and founders’ lack-of-consent response.',limitations=['Original URL returned HTTP403; opened indexed original PDF text is retained in indexed-fetch.json.'])
source('ndtv-response-2022','NDTV: RRPR instructs bankers to return warrant deposit','New Delhi Television Limited; stock-exchange disclosure','2022-08-24','p1, items1–4','Founders say SEBI clearance is needed and RRPR instructed return of INR1,99,00,000.',limitations=['Original URL returned HTTP403; opened indexed original PDF text retained. An instruction to return is not a verified bank refund.'])
source('ael-price-2022','AEL: completed acquisition of 27.26% NDTV from Roys','Adani Enterprises Limited; stock-exchange disclosure','2022-12-30','pp1–3, annexure b,f,g,h,i,j','RRPR acquired27.26% at INR342.65 per share; block deal completed December30, exchange settlement formalities noted; legal CIN of NDTV stated.',limitations=['Cash consideration price is not an independently reconciled seller bank receipt.'])
source('ndtv-completion-2022','NDTV: ownership, direct holdings and founder resignations','New Delhi Television Limited; stock-exchange disclosure','2022-12-30','pp1–3, items2–3 and revised shareholding table','Records1,75,77,676 shares acquired from the two named founders; RRPR56.45%, VCPL8.27% and founders5% combined.',limitations=['Original URL returned HTTP403; opened indexed original PDF text and indexed discovery table are retained. Percentages are the issuer’s rounded December2022 figures.'])
source('ael-response-2022-original','AMG Media Networks statement on NDTV transition','Adani Enterprises Limited / AMG Media Networks','2022-12-30','Media release pp2–3','Acquirer says AMNL controlled64.71% through subsidiaries and describes investment in the newsroom and a friendly transition.',tier='self-reported',limitations=['Company strategy and description of the transition are attributed statements, not an independent editorial-independence assessment.'])
source('ndtv-annual-2026','NDTV annual report FY2025–26 and audited standalone financial statements','New Delhi Television Limited; NSE filing','2026-05-29','PDF42/printed78–79 rights issue; PDF51/printed96–97 legal outcomes; PDF105/printed204–205 cash flow; PDF115/printed224–225 share capital; printed244 related parties','Rights issue proceeds INR3,964.98 million; RRPR67,473,129 shares59.80% and VCPL10,402,138 shares9.22% in standalone note14; legal closure and continuing SEBI matter distinguished.',limitations=['Original14MB PDF kept in /workspace/.cache/atlas-institutions with SHA256 receipt; fulltext, exact page excerpts and shareholding PNG tracked.','Standalone note14 and promoter aggregate69.02% are used. Consolidated note14 prints VCPL9.21% in one table despite the same10,402,138 shares; standalone table and consolidated promoter table print9.22%. No silent averaging.','Legal case status is the issuer’s May2026 disclosure; underlying2025 orders were not independently retrieved.'])
source('padma-sc-2020','Supreme Court: Sri Marthanda Varma v State of Kerala','Supreme Court of India','2020-07-13','CA2732/2020; §§109–116, especially116(e)–(g)','Upholds shebaitship succession, establishes committee management and directs25-year audit and preservation of temple assets.',limitations=['Historical disputes and pre-2011 legislation are context; an audit direction is not a final quantified misappropriation finding.'])
source('padma-sc-2021','Supreme Court: Temple Trust audit clarification','Supreme Court of India; judgment reproduced by AdvocateKhoj','2021-09-22','MA1465/2021 and MA2280–2281/2020; §1 committee reports, §2 trust response, §§6–10 ruling','Audit includes SPSTT; excludes no trust from audit; court leaves request for independent legal status to competent factual determination.',limitations=['Retained HTML is a legal mirror of the court text, not a court-hosted original. Publisher headnote is excluded from claim reasoning.','Assertions in quoted committee and trust submissions remain attributed; no audit completion or recovery is inferred.'])
source('padma-latest-2022','Supreme Court extends temple and trusts special-audit deadline','The Hindu','2022-07-18','Report of July18 order extending completion toAugust31,2022','Reports a further audit deadline and requirement to file a compliance report.',tier='reported',limitations=['Underlying extension order and completed special-audit report not retrieved. Targeted later-outcome search through2026 did not locate a final publicly accessible report; this is a corpus gap, not proof audit never occurred.'])
source('ipi-kpmg-2020','KPMG forensic review of IPI transactions involving Epstein-linked entities','KPMG LLP, publicly released by International Peace Institute','2020-12-18','Printed pp2–3 limitations/summary; pp5–6 methods; p7 donation table; pp8–9 reimbursement and negative findings','Five donations USD650,000 and one airfare reimbursement USD14,158.88 identified in scoped financial review; no IPI payments to Epstein or56 listed entities identified.',limitations=['Consulting/advisory engagement, expressly not an audit/attestation or assurance opinion. Relied on IPI-provided information; public-record entity affiliations not independently verified.','Review covers2010-01-01 through2020-10-31. The earliest retained donation is check2011-10-11 / ledger2011-10-13, within atlas window.','The report bears a client-confidential header but was voluntarily published in full by IPI. No nonpublic IRS ScheduleB or bank records were accessed by this project.'])
source('ipi-review-2020','IPI publishes forensic and probity reviews; explains remedial policy','International Peace Institute','2020-12-22','Board statement, review findings and redonation instruction','IPI reports resignation, commissioning of reviews and direction to donate equivalent funds to programmes supporting survivors.',tier='self-reported',limitations=['Board pledge/direction is not proof that equivalent donations were subsequently paid. Headline statement rounds airfare toUSD14,158; underlying KPMG reportUSD14,158.88 controls.'])
source('ipi-probity-2020','IPI probity review: conflicts, donor policy and legal boundaries','Perlman & Perlman legal review, published by IPI','2020-12-22','Questions1–3 and concluding policy changes','Counsel found no identified legal prohibition on receiving donations or evidence of personal benefit to Epstein; criticises undisclosed personal loan judgment.',limitations=['Commissioned legal review is not a criminal acquittal or exhaustive investigation. The report’s assumptions and limited scope are preserved.'])
source('ipi-puri-role-2016','IPI final report identifies Hardeep Singh Puri’s ICM role','International Peace Institute','2016-09-15','Opening paragraphs: September2014 launch, chair and secretary-general','Identifies former Indian diplomat Puri as secretary-general of IPI’s Independent Commission on Multilateralism.',limitations=['Institutional role does not establish control of donor funds, salary funding source or receipt of Epstein-related funds. Exact role end-date is not asserted.'])
source('epstein-pitch-mirror','Published copy of DOJ release EFTA00688056–57: India internet pitch','Public document transcription; original locator U.S. Department of Justice','2014-11-13','EFTA00688056 and EFTA00688057, email dated2014-11-13','Puri pitches Indian internet opportunities to Epstein and Reid Hoffman. This is correspondence proposing engagement, not a payment instrument.',tier='reported',limitations=['DOJ file URL returned age-verification HTML; that failure is retained and no original PDF retrieval is claimed. Opened transcription corroborated by linked reporting in The Indian Express and The News Minute.','The email’s third-party investment figures and forecasts are not treated as verified transactions by Epstein, Puri or Hoffman. No victim-identifying information is reproduced in structured data.'])
source('epstein-ie-report','DOJ emails: Puri’s India economic pitch and interactions','The Indian Express','2026-02-12','November13,2014 pitch and earlier introduction paragraphs','Reports published email exchanges; distinguishes the retired diplomat’s business pitch from later ministerial office.',tier='reported',limitations=['Reporting and the opened public transcription support correspondence only. No bank transfer, completed investment or criminal participation by Puri is established.'])
source('epstein-reuters-response','Puri acknowledges meetings and denies connection to wrongdoing','Reuters','2026-02-11','Opening paragraphs and Puri response','Reports Puri saying he met Epstein three or four times through IPI and had no connection to wrongdoing or crimes.',tier='reported',limitations=['Reuters direct URL returned HTTP401; opened indexed Reuters text retained. His explanation is a response, not independently adjudicated fact.'])
source('norway-reuters-2026','Norway hearings and separate police probes after Epstein disclosures','Reuters, republished by ThePrint','2026-09-30','Paragraphs concerning Roed-Larsen and denial; external commission','Reports ongoing Norwegian investigations, Roed-Larsen’s denial of wrongdoing and separate parliamentary inquiry.',tier='reported',limitations=['Police investigation is not conviction. This Norwegian follow-up is not a finding against Puri, IPI’s Indian work or an Indian recipient. It does not change the scoped2020 review into a global exoneration.'])

def geo(src,which='national'):
    if which=='temple':return [dict(scope='city',stateCodes=['KL'],localityIds=['thiruvananthapuram'],basis='institution-location',note='Public temple in Thiruvananthapuram; no privately owned property parcel or residence is pinned.',sourceIds=src)]
    if which=='delhi':return [dict(scope='state',stateCodes=['DL'],localityIds=[],basis='headquarters',note='Issuer registered-office association in the cited filing, not the location of every newsroom, subscriber or transaction.',sourceIds=src)]
    if which=='foreign':return [dict(scope='unknown',stateCodes=[],localityIds=[],basis='unknown',note='Foreign institution or person; no India money-transfer destination or private address is inferred.',sourceIds=src)]
    return [dict(scope='national',stateCodes=[],localityIds=[],basis='national-context',note='India public-interest context; no project-level delivery, payment destination or residence is established.',sourceIds=src)]
def dims(src,dom,lay,where='national'):
    return dict(domains=dom,layers=lay,geography=geo(src,where),route='/follow-the-money',sourceIds=src,limitations=[])
def ent(id,label,type,src,dom,summary,identity,where='national',canonical=None):
    x=dict(id=id,label=label,type=type,resolved=True,identityBasis=identity,summary=summary,**dims(src,dom,['people' if type=='person' else 'organisations'],where))
    if canonical:x['canonicalId']=canonical
    S['entities'].append(x)
def amount(value,currency,unit,stage,period):return dict(value=value,currency=currency,unit=unit,stage=stage,period=period)
def edge(id,fr,to,kind,label,summary,src,dom,case,date,end=None,tier='documented',response=(),amounts=(),where='national',alternatives=(),falsifier='A superseding original instrument or reconciled ledger contradicting this stated relationship would require correction.',status='source-retained'):
    S['relationships'].append(dict(id=id,fromDate=date,toDate=end or date,**{'from':fr,'to':to},kind=kind,label=label,summary=summary,tier=tier,status=status,statusAsOf=end or date,dateBasis='Exact dated source or transaction dates; no open-ended continuity inferred.',alternativeExplanations=list(alternatives),falsifier=falsifier,responseIds=list(response),recordIds=[case],amounts=list(amounts),**dims(src,dom,['funding'] if amounts else ['people'] if kind=='role' else ['legal'] if 'audit' in kind else ['organisations'],where)))
def rec(id,title,summary,src,dom,entities,rels,date,end,response,alternatives,falsifier,kind='investigation-case',tier='documented',status='reviewed-with-stated-gaps',amounts=(),where='national',limitations=()):
    x=dict(id=id,title=title,summary=summary,kind=kind,tier=tier,status=status,statusAsOf=end,fromDate=date,toDate=end,dateBasis='Dated source and event window; earlier context and historical accounting period are labelled separately.',entityIds=entities,relationshipIds=rels,period=date+' to '+end,response=response,alternativeExplanations=alternatives,falsifier=falsifier,amounts=list(amounts),**dims(src,dom,['funding','legal','organisations'],where));x['limitations']=list(limitations);S['records'].append(x)

M=['media','capital'];T=['ngo','justice'];I=['ngo','public-records']
ent('ndtv','New Delhi Television Limited','company',['ael-price-2022','ndtv-annual-2026'],M,'Listed issuer and recipient of2025 rights-issue proceeds.','CIN L92111DL1988PLC033099 explicitly in AEL filing; issuer report and NSE symbolNDTV.','delhi', 'co:ndtv')
ent('ael','Adani Enterprises Limited','company',['ael-warrant-2022'],M,'Listed ultimate corporate parent in the documented media holding chain.','CIN L51100GJ1993PLC019067 in signed exchange disclosure; exact legacy entity.','national','co:adani-enterprises')
ent('amnl','AMG Media Networks Limited','company',['ael-warrant-2022'],M,'AEL wholly owned media subsidiary named in the warrant disclosure.','Exact legal subsidiary explicitly identified in AEL filing.')
ent('vcpl','Vishvapradhan Commercial Private Limited','company',['ael-warrant-2022','ndtv-annual-2026'],M,'Warrant holder, AMNL subsidiary and direct NDTV shareholder.','Exact legal name in warrant instrument and issuer related-party note.')
ent('rrpr','RRPR Holding Private Limited','company',['ael-price-2022','ndtv-annual-2026'],M,'NDTV holding company, distinct from NDTV issuer and the founder sellers.','Exact legal company in transaction filings and audited note14.')
ent('roy-sellers','Prannoy Roy and Radhika Roy — specified seller pair','cohort',['ndtv-completion-2022'],M,'Precisely the two founders selling the27.26% block in2022; not a family or wider promoter cohort.','The filing identifies Prannoy Roy DIN00025576 and Radhika Roy DIN00025625 and their separate share counts.')
ent('rights-subscribers','NDTV2025 rights-issue subscribers — complete issuance cohort','cohort',['ndtv-annual-2026'],M,'Aggregate source cohort for48,353,450 fully paid rights shares, not a single beneficial owner.','Exact issuer issuance population in directors’ report and audited cash-flow statement; individual remitters not resolved.')
ent('temple','Sree Padmanabhaswamy Temple','institution',['padma-sc-2020'],T,'Public temple whose management and accounts are subject to Supreme Court directions.','Named institution in CA2732/2020; separate from the specifically named Trust.','temple')
ent('spstt','Sree Padmanabha Swamy Temple Trust (SPSTT)','trust',['padma-sc-2021'],T,'Named trust with rental income and specified religious/maintenance objects; legal independence question reserved.','MA1465/2021 identifies applicant and deed No66/1965; identity does not settle ownership of disputed assets.','temple')
ent('temple-admin','Temple Administrative Committee','public-body',['padma-sc-2020','padma-sc-2021'],T,'Court-directed management committee reporting liquidity constraints and appointing the special auditor.','Exact committee constituted under the2020 Supreme Court directions, distinguished from Advisory Committee.','temple')
ent('temple-auditor','M/s Sridhar & Co. — appointed temple special auditor','organisation',['padma-sc-2021'],T,'Firm named in the October27,2020 joint committee resolution.','Identity scoped to named Thiruvananthapuram chartered-accountant appointment in court text; no merger with similarly named firms.','temple')
ent('supreme-court','Supreme Court of India','court',['padma-sc-2020'],T,'Court issuing management and special-audit directions.','Original Supreme Court-hosted CA2732/2020 judgment.','national','sc')
ent('ipi','International Peace Institute (IPI)','ngo',['ipi-kpmg-2020','ipi-puri-role-2016'],I,'New York nonprofit receiving the reviewed donations and running ICM.','Named KPMG client and official IPI project publisher; no Indian FCRA registration or India recipient is assumed.','foreign')
ent('enhanced-education','Enhanced Education — donor identified in IPI review','foundation',['ipi-kpmg-2020'],I,'Named donor ofUSD125,000 and separate airfare reimbursement.','KPMG donor table and underlying check/ledger review identify the entity; no name-only registry join.','foreign')
ent('gratitude-america','Gratitude America, LTD — donor identified in IPI review','foundation',['ipi-kpmg-2020'],I,'Named donor of four gifts totalingUSD525,000.','KPMG donor table identifies LTD despite inconsistent GL descriptions; no unreviewed alias or beneficial-ownership assertion.','foreign')
ent('kpmg','KPMG LLP — IPI forensic-review engagement','organisation',['ipi-kpmg-2020'],I,'Independent consulting reviewer commissioned through IPI counsel; not a court or criminal investigator.','Engagement letter background names KPMG LLP and public report footer identifies Delaware LLP.','foreign')
ent('epstein','Jeffrey Epstein','person',['ipi-kpmg-2020','epstein-ie-report'],I,'Financier linked by the scoped review to named donor foundations and by published correspondence to the India pitch.','Specific subject of IPI commissioned review and public DOJ-record reporting; not resolved from an address or common-name match.','foreign')
ent('puri','Hardeep Singh Puri','person',['ipi-puri-role-2016','epstein-reuters-response'],I+['governance'],'Former Indian diplomat and ICM secretary-general; correspondence predates ministerial service.','Official IPI2016 report identifies Indian diplomat and role; Reuters2026 identifies same former2009–2013 UN ambassador and subsequent minister.')
ent('icm','Independent Commission on Multilateralism (ICM)','programme',['ipi-puri-role-2016'],I,'Two-year IPI project launched September2014.','Official IPI final-report release identifies project, institution and secretary-general.','foreign')
ent('hoffman','Reid Hoffman','person',['epstein-ie-report','epstein-pitch-mirror'],I+['capital'],'LinkedIn co-founder addressed in the2014 India investment pitch.','Reporting explicitly identifies LinkedIn co-founder and same named addressee in EFTA00688056; no payment asserted.','foreign')
S['localities'].append(dict(id='thiruvananthapuram',name='Thiruvananthapuram',stateCode='KL',kind='city',aliases=['Trivandrum'],districtName='Thiruvananthapuram'))

ND='ndtv-control-financing';PD='padmanabhaswamy-trust-audit';IP='ipi-donations-india-boundary'
nr=['ndtv-founder-response','ndtv-current-outcome'];tr=['temple-trust-response','temple-later-outcome'];ir=['ipi-review-boundaries','puri-response','norway-later-status']
edge('ael-amnl','ael','amnl','ownership','AEL owns AMNL100%','AEL filing identifies AMNL as its wholly owned subsidiary.',['ael-warrant-2022'],M,ND,'2022-08-23',response=nr)
edge('amnl-vcpl','amnl','vcpl','ownership','AMNL owns VCPL100%','The same filing explicitly places VCPL beneath AMNL.',['ael-warrant-2022'],M,ND,'2022-08-23',response=nr)
edge('vcpl-rrpr-warrant','vcpl','rrpr','warrant-exercise','Warrant exercise: INR1.99 crore for99.5% RRPR','August23 notice exercised1,990,000 warrants atINR10 each. RRPR’s next-day return instruction is separately retained; this is not a final bank-balance claim. The originating2009–10 loans are pre-window historical context.',['ael-warrant-2022','ndtv-warrant-2022','ndtv-response-2022'],M,ND,'2022-08-23',response=nr,amounts=[amount(1.99,'INR','crore','warrant-exercise deposit disclosed; next-day return instructed','2022-08-23')],status='exercise-notice-with-response')
edge('vcpl-ndtv-offer','vcpl','ndtv','open-offer','Offer up to26% atINR294/share','An announced maximum under SAST2011; not26% completed acquisition. December filing gives VCPL’s resulting direct holding as8.27%.',['ael-warrant-2022','ael-price-2022'],M,ND,'2022-08-23',response=nr,amounts=[amount(294,'INR','per share','open-offer price; maximum26% offer not full acceptance','2022-08-23')],status='announced-offer-not-full-acceptance')
edge('rrpr-roy-purchase','rrpr','roy-sellers','share-purchase','Completed founder block:27.26% atINR342.65/share','AEL reports December30 block deal completed with exchange settlement formalities outstanding; NDTV identifies17,577,676 transferred shares. Consideration flows to selling shareholders, not new capital to NDTV.',['ael-price-2022','ndtv-completion-2022'],M,ND,'2022-12-30',response=nr,amounts=[amount(342.65,'INR','per share','cash consideration price in completed block-deal disclosure','2022-12-30')])
edge('rrpr-ndtv-2026','rrpr','ndtv','shareholding','RRPR holds59.80% atMarch31,2026','Standalone note14 records67,473,129 shares; this is direct shareholding, separate from parent control.',['ndtv-annual-2026'],M,ND,'2026-03-31',response=nr)
edge('vcpl-ndtv-2026','vcpl','ndtv','shareholding','VCPL holds9.22% atMarch31,2026','Standalone note14 records10,402,138 shares. Combined reported promoter stake is69.02%. A consolidated table’s9.21% discrepancy is disclosed in source limitations.',['ndtv-annual-2026'],M,ND,'2026-03-31',response=nr)
edge('rights-proceeds','rights-subscribers','ndtv','equity-subscription','Rights-issue proceeds INR3,964.98 million','Audited standalone cashflow reports issue proceeds; directors’ report records48,353,450 shares atINR82 allottedOctober9,2025. This is issuer financing, distinct from2022 seller consideration; individual subscriber cash contributions are not resolved.',['ndtv-annual-2026'],M,ND,'2025-10-09',end='2026-03-31',response=nr,amounts=[amount(3964.98,'INR','million','proceeds from issue of equity shares; audited standalone cash-flow','FY2025–26')])

edge('court-temple-audit','supreme-court','temple','audit-direction','Court directs25-year special audit','2020 judgment116(g) directs audit by a reputed chartered-accountant firm and preservation of movable/immovable properties. Audit period1989–90 to2013–14 contains historical context outside atlas window.',['padma-sc-2020','padma-sc-2021'],T,PD,'2020-07-13',response=tr,where='temple')
edge('court-trust-audit','supreme-court','spstt','audit-direction','SPSTT included in audit; independence reserved','2021§6 rejects exclusion from audit. Section7 expressly refrains from deciding the separate plea on independent legal status.',['padma-sc-2021'],T,PD,'2021-09-22',response=tr,where='temple')
edge('admin-auditor','temple-admin','temple-auditor','audit-appointment','Joint committees appoint Sridhar & Co.','Quoted resolution datedOctober27,2020 appoints the firm for temple, SPSTT and allied-trust special audit; no claim that work was completed.',['padma-sc-2021'],T,PD,'2020-10-27',response=tr,where='temple')
edge('trust-temple-purpose','spstt','temple','restricted-purpose','Trust says rental income funds upkeep and specified offerings','Trust application§2 describes rental income and spending on buildings, administration, offerings and objects. The committee challenges whether income use is adequately established; source supplies no reconciled payment amount.',['padma-sc-2021'],T,PD,'2021-09-22',tier='self-reported',response=tr,where='temple',alternatives=['Property upkeep and ritual obligations may legitimately absorb rental receipts; financial stress duringCOVID restrictions does not by itself show diversion.'],falsifier='Trust deed, audited rent ledger and recipient vouchers reconciling expenditure would resolve the competing accounts.')

edge('epstein-enhanced-affiliation','epstein','enhanced-education','identified-affiliation','Epstein affiliation identified by KPMG','KPMG’s public-record entity search identifies Epstein as founder; affiliations were not independently verified by the reviewer. This is not a newly verified beneficial-ownership register.',['ipi-kpmg-2020'],I,IP,'2020-12-18',tier='reported',response=ir,where='foreign')
edge('epstein-gratitude-affiliation','epstein','gratitude-america','identified-affiliation','Epstein affiliation identified by KPMG','KPMG donor table and scope identify Gratitude America as an Epstein-affiliated foundation; no common-address inference is used.',['ipi-kpmg-2020'],I,IP,'2020-12-18',tier='reported',response=ir,where='foreign')
edge('enhanced-ipi-donation','enhanced-education','ipi','donation','USD125,000 donation recorded','CheckOctober11,2011; IPI GL October13,2011. KPMG classified this as a donation and found no donor restriction instructions, despite a fellowship GL description.',['ipi-kpmg-2020'],I,IP,'2011-10-11',end='2011-10-13',response=ir,where='foreign',amounts=[amount(125000,'USD','dollars','donation received and recorded in IPI ledger; KPMG review','check2011-10-11 / GL2011-10-13')])
edge('gratitude-ipi-donations','gratitude-america','ipi','donation','Four donations totalingUSD525,000','KPMG table: USD150,000 checkMay8/GLMay11,2017; USD125,000 checkJune12/GLJune28,2017; USD100,000 checkNovember1/GLNovember7,2017; USD150,000 check/GL April5,2019. Four gifts, not an extra amount on top of theUSD650,000 total.',['ipi-kpmg-2020'],I,IP,'2017-05-08',end='2019-04-05',response=ir,where='foreign',amounts=[amount(525000,'USD','dollars','four donations received and recorded in IPI ledger; KPMG review','2017-05-08 to2019-04-05')])
edge('enhanced-ipi-airfare','enhanced-education','ipi','reimbursement','Separate USD14,158.88 airfare reimbursement','CheckMarch28,2014; GL April17,2014 reimburses Lawrence Summers airfare advanced by IPI. It is not a sixth donation, a payment to Puri or an Indian project.',['ipi-kpmg-2020'],I,IP,'2014-03-28',end='2014-04-17',response=ir,where='foreign',amounts=[amount(14158.88,'USD','dollars','reimbursement of airfare advanced by IPI','check2014-03-28 / GL2014-04-17')])
edge('ipi-review-commission','ipi','kpmg','review-commission','IPI counsel commissions forensic review','KPMG retainedNovember13,2020 through IPI counsel; report datedDecember18. A consulting engagement, not a criminal adjudication or assurance audit.',['ipi-kpmg-2020'],I,IP,'2020-11-13',end='2020-12-18',response=ir,where='foreign')
edge('ipi-icm','ipi','icm','programme','IPI conducts ICM project','Official September2016 final report identifies ICM as a two-year IPI project launchedSeptember2014. No allocation of Epstein-related donations to this programme is established.',['ipi-puri-role-2016'],I,IP,'2016-09-15',response=ir,where='foreign')
edge('puri-icm-role','puri','icm','role','Puri identified as ICM secretary-general','Official final report names the former Indian diplomat as secretary-general at theSeptember2014 launch; exact employment end and salary source are not inferred.',['ipi-puri-role-2016'],I+['governance'],IP,'2016-09-15',response=ir)
edge('puri-epstein-pitch','puri','epstein','correspondence','2014 India internet-opportunity correspondence','Published EFTA00688056–57 transcription and reporting establish aNovember13,2014 business pitch, not a contract, actual investment or connection to Epstein’s crimes. Puri’s2026 denial accompanies the edge.',['epstein-pitch-mirror','epstein-ie-report','epstein-reuters-response'],I+['governance'],IP,'2014-11-13',tier='reported',response=ir,alternatives=['Ordinary economic advocacy and professional networking explain a business pitch without a financial transfer or criminal involvement.'],falsifier='Original authenticated message contradicting the transcription would defeat this correspondence account; bank records or executed investment instruments would be needed to establish any additional money relationship.')
edge('puri-hoffman-pitch','puri','hoffman','investment-proposal','Pitch to LinkedIn co-founder; no executed investment shown','The same email addresses Reid Hoffman and urges an India visit. Quoted SoftBank or Snapdeal figures are background examples, not Epstein/Hoffman/Puri investments.',['epstein-pitch-mirror','epstein-ie-report'],I+['capital'],IP,'2014-11-13',tier='reported',response=ir,alternatives=['The message can be read as an economic-development pitch without any deal being accepted.'])

ndrels=[r['id'] for r in S['relationships'] if r['recordIds']==[ND]];pdrels=[r['id'] for r in S['relationships'] if r['recordIds']==[PD]];iprels=[r['id'] for r in S['relationships'] if r['recordIds']==[IP]]
rec(ND,'NDTV: warrants → founder share purchase → new issuer capital','A2022 warrant conversion and shareholder purchases transferred control; the later2025 rights issue raised new capital for NDTV. INR1.99 crore exercise deposit, INR294/share open offer, INR342.65/share founder block and INR3,964.98 million issuer proceeds are separate stages. March2026 standalone holdings are RRPR59.80% and VCPL9.22%, not the2022 group64.71% snapshot.',['ael-warrant-2022','ndtv-warrant-2022','ndtv-response-2022','ael-price-2022','ndtv-completion-2022','ael-response-2022-original','ndtv-annual-2026'],M,['ndtv','ael','amnl','vcpl','rrpr','roy-sellers','rights-subscribers'],ndrels,'2022-08-23','2026-05-29','Founders objected to surprise exercise and instructed deposit return inAugust2022. Acquirer later described a friendly transition and newsroom investment. The2026 issuer report distinguishes the2025 criminal-case closure/ECIR quashing from continuing SEBI proceedings.',['Exercise of pre-existing contractual rights and a later negotiated founder sale explain the ownership path without proving political direction or editorial interference.','Rights capital may finance expansion, debt reduction and ordinary operations; filings do not establish a quid pro quo.'],'Contradictory definitive allotment/settlement instruments or corrected audited cashflows would falsify the stages; a political quid-pro-quo requires separate sourced decision/payment evidence.',limitations=['2009–10 originating loan terms are historical context outside2011-10-06 start.','No public-loss, political-payment or editorial-control allegation is inferred from ownership concentration.','Issuer legal-outcome disclosure is attributed; no judicial outcome is independently upgraded from company narrative.'])
rec('ndtv-founder-response','Founders’ dated objection and return instruction','August23 disclosure says exercise was without prior input or consent. August24 disclosure says SEBI approval was needed and RRPR had instructed bankers to returnINR1,99,00,000; bank execution of that instruction is not established.',['ndtv-warrant-2022','ndtv-response-2022'],M,['ndtv','rrpr','roy-sellers','vcpl'],['vcpl-rrpr-warrant'],'2022-08-23','2022-08-24','The objection predates the later completed sale.',['A contractual conversion dispute can coexist with a later negotiated transaction.'],'A bank confirmation would settle whether the return instruction was executed.',kind='response',tier='self-reported',status='dated-founder-response')
rec('ndtv-current-outcome','Latest retained capital and legal-outcome disclosure','FY2025–26 report records the rights issue and current direct holdings. It saysCBI closure was acceptedJanuary23,2025 and Delhi High Court quashed the relatedECIR August18,2025 with liberty to revive if closure is set aside; it separately describesSEBI matters pending.',['ndtv-annual-2026','ael-response-2022-original'],M,['ndtv','rrpr','vcpl'],ndrels,'2022-12-30','2026-05-29','Acquirer says transition was friendly and investment would strengthen news operations; report supplies latest retained factual financial snapshot.',['Criminal closure of one loan matter does not dispose of every securities-disclosure proceeding.'],'The actual2025 court orders or a newer final securities judgment may refine or supersede issuer wording.',kind='response',tier='self-reported',status='issuer-disclosure-with-procedural-limits')
rec(PD,'Padmanabhaswamy: rental-income objects → special-audit scope dispute','The court required a25-year audit of the temple and SPSTT, rejected the trust’s exclusion request and reserved its independent-status plea. Trust rental income and religious/maintenance obligations are described in submissions; no reconciled disbursement total or proved diversion is established. The latest retrieved continuation is theJuly2022 audit-deadline extension.',['padma-sc-2020','padma-sc-2021','padma-latest-2022'],T,['temple','spstt','temple-admin','temple-auditor','supreme-court'],pdrels,'2014-04-15','2022-07-18','SPSTT says it is a separate public trust funded by its own rental property and already audited for2008–14; committee says use of income for the temple was not adequately established. Court ordered audit, not a quantified guilt finding.',['COVID closure reduced temple offerings while wages and ritual costs continued.','Legitimate building upkeep and specified ritual expenditure may explain trust use of rental income.'],'The completed special audit, trust deed, rent ledger, property-title records and payment vouchers would test both competing accounts.',where='temple',limitations=['Accounting period1989–90 to2013–14 is historical scope, not25 years of new wrongdoing.','Neither court order establishes criminal guilt, a stolen-treasure valuation or a specific donor-to-private-beneficiary payment.','Targeted search through2026 did not retrieve the final special-audit report; absence from this corpus is not proof it never existed.'])
rec('temple-trust-response','SPSTT’s separate-property and prior-audit response','InMA1465/2021 the trust says income is chiefly rents spent on building upkeep, administration and offerings; it denies that prior reports established temple property was transferred to it and cites a completed earlier special audit. The court rejected audit exclusion but reserved independent status.',['padma-sc-2021'],T,['spstt','temple','supreme-court'],pdrels,'2021-09-22','2021-09-22','Trust position is quoted in§2; findings are limited to§§6–10.',['Prior audits could overlap the new scope without making additional review unlawful.'],'Obtain original trust deed and final special-audit annexures to reconcile property and income ownership.',kind='response',tier='self-reported',where='temple',status='trust-submissions-and-limited-ruling')
rec('temple-later-outcome','Audit deadline extended in2022; completion evidence remains missing','July18,2022 reporting says Supreme Court extended completion toAugust31,2022 and required a compliance report, following an earlier extension. No final report was located in the targeted later-outcome search.',['padma-latest-2022'],T,['temple','spstt','supreme-court'],['court-temple-audit','court-trust-audit'],'2022-07-18','2022-07-18','Extension granted at committees’ request in the interest of justice.',['An audit may have been completed or filed without an accessible public copy.'],'A dated final report or court compliance order closes the stated retrieval gap.',kind='response',tier='reported',where='temple',status='latest-retrieved-order-report-not-current-completion-claim')
rec(IP,'IPI donations and India correspondence: money received, pass-through unproved','KPMG identifiedUSD650,000 in five donations toIPI from two Epstein-affiliated foundations and a separateUSD14,158.88 airfare reimbursement. IPI’s2016 report identifies Puri’sICM role; released-record reporting supports a2014 India internet pitch toEpstein andHoffman. These are separate donation, employment/project-role and correspondence facts. No allocation of those donations toPuri,ICM,an Indian recipient or a completed Indian investment is established.',['ipi-kpmg-2020','ipi-review-2020','ipi-probity-2020','ipi-puri-role-2016','epstein-pitch-mirror','epstein-ie-report','epstein-reuters-response','norway-reuters-2026'],I+['governance'],['ipi','enhanced-education','gratitude-america','kpmg','epstein','puri','icm','hoffman'],iprels,'2011-10-11','2026-09-30','KPMG found noIPI payments toEpstein/listed entities and noIPI payments related toRoed-Larsen’s personal loan in its scoped review. Puri denies involvement in wrongdoing and describes economic advocacy. September2026 Reuters reports separate Norwegian probes and denials, not findings against Puri.',['Ordinary donor fundraising and economic networking can explain these institutional and correspondence links without a pass-through,quid pro quo or criminal participation.','KPMG’s negative findings are bounded by its2010–2020 consulting scope and supplied records; they are not a universal exoneration.'],'A reconciled recipient ledger, executed investment instrument or court finding tracing these specific funds to an Indian recipient would change the financial gap; a verified original message contradicting the transcription would change the correspondence claim.',limitations=['USD650,000 is the sum ofUSD125,000 andUSD525,000 gifts, not an additional payment. Reimbursement is separately classified.','No victims,private residences or personal account details are structured or mapped.','DOJ age-gate response retained as failure to obtainPDF; public transcription and reputable reporting retain reported tier.','No state-specific India receipt orFCRA breach is alleged.'])
rec('ipi-review-boundaries','Counter-evidence: scoped review found noIPI→Epstein payments','KPMG’s consulting review found no payments toEpstein or56 listed entities and noIPI transactions related toRoed-Larsen’s personal loan. It found no donor restriction instructions. IPI directed equivalent donations to survivor-support programmes; completed redonation payment was not verified.',['ipi-kpmg-2020','ipi-review-2020','ipi-probity-2020'],I,['ipi','kpmg','enhanced-education','gratitude-america','epstein'],['enhanced-ipi-donation','gratitude-ipi-donations','enhanced-ipi-airfare','ipi-review-commission'],'2020-12-18','2020-12-22','Probity counsel found no identified legal bar or evidence of personal benefit toEpstein; criticised judgment and sought stronger conflicts/donor rules.',['A legitimate donation can create reputational/conflict concerns without proving misappropriation.'],'A contradictory bank ledger or regulator/court finding would supersede the bounded review; recipient receipts are required to verify redonation.',kind='response',where='foreign',status='scoped-review-no-global-exoneration')
rec('puri-response','Puri: meetings acknowledged; wrongdoing denied','ReutersFebruary11,2026 reports Puri acknowledging three or four meetings throughIPI and denying any connection to wrongdoing or crimes. His2014 internet-market pitch is not proof of an executed investment or of participation inEpstein’s criminal acts.',['epstein-reuters-response','epstein-ie-report','ipi-puri-role-2016'],I+['governance'],['puri','epstein','ipi','icm','hoffman'],['puri-epstein-pitch','puri-hoffman-pitch','puri-icm-role'],'2026-02-11','2026-02-12','Puri says the interactions concerned economic opportunities and hisIPI/ICM work.',['Professional networking and a proposed visit need not result in a contract or money transfer.'],'A specific authenticated transaction or judicial finding is needed for any stronger financial/criminal claim.',kind='response',tier='reported',status='denial-and-admitted-contact')
rec('norway-later-status','Separate Norwegian investigations remain unresolved','ReutersSeptember30,2026 reports Norwegian parliamentary hearings and police corruption investigations involving formerIPI headTerje Roed-Larsen and others,who deny wrongdoing. This is retained to prevent the2020 review being shown as the last word. No finding againstPuri or Indian recipients follows.',['norway-reuters-2026'],I,['ipi','epstein'],['ipi-review-commission'],'2026-09-30','2026-09-30','Roed-Larsen has apologised for the relationship and denies wrongdoing; the reported inquiry is not a conviction.',['Later inquiry may examine records or personal conduct beyond the2020IPI financial-review scope.'],'A final prosecutorial/court disposition or official inquiry report would update this provisional status.',kind='response',tier='reported',where='foreign',status='ongoing-investigations-reported-no-verdict')

# Independent source challenge: include the later equalising-consideration notice.
source('ndtv-equalisation-2023','VCPL notice: equalising payment for accepted NDTV open-offer shares','New Delhi Television Limited; attached VCPL public notice','2023-01-03','Cover filing and attached Regulation8(10) public notice, paragraphs2–5','VCPL says initial consideration on5,330,792 accepted shares completedDecember15,2022; promises an additionalINR48.65/share byFebruary28,2023 to match the founders’INR342.65/share price.',limitations=['Original URL returnedHTTP403; opened indexed original-file OCR retained in ndtv-equalisation-indexed.json. Repeated paragraph5 corroborates amount/deadline despite imperfect OCR.','This notice is a payment commitment; actual additional-payment settlement or shareholder bank receipts were not independently retrieved.'])
ent('open-offer-sellers','NDTV2022 accepted open-offer shareholders — seller cohort','cohort',['ndtv-equalisation-2023'],M,'Exactly the holders of5,330,792 accepted shares; distinct from founders and2025 rights subscribers.','The public notice paragraph2 defines Accepted Public Shareholders and the accepted-share count.')
edge('vcpl-equalising-payment','vcpl','open-offer-sellers','additional-consideration-commitment','INR48.65/share equalising payment announced','January3,2023 notice invokesSAST8(10), promisingINR48.65 additional consideration for accepted shares byFebruary28,2023. INR294 plusINR48.65 equals the founders’INR342.65 price. No bank-confirmed completion of the additional payment is claimed.',['ndtv-equalisation-2023'],M,ND,'2023-01-03',response=['ndtv-price-equalisation'],amounts=[amount(48.65,'INR','per share','additional-consideration commitment, not independently verified settlement','notice2023-01-03; due2023-02-28')],status='announced-equalising-payment')
rec('ndtv-price-equalisation','Later notice equalises the open-offer and founder prices','VCPL’sJanuary2023 notice states initial consideration was completedDecember15,2022 and promisesINR48.65 more per accepted share, bringingINR294 toINR342.65. The initial-price difference must not be presented as an enduring preferential payout.',['ndtv-equalisation-2023'],M,['vcpl','open-offer-sellers','ndtv','roy-sellers'],['vcpl-ndtv-offer','rrpr-roy-purchase','vcpl-equalising-payment'],'2023-01-03','2023-01-03','The filing appliesSAST8(10) following theDecember30 founder transaction; promised deadlineFebruary28,2023.',['A later higher-priced acquisition can trigger statutory equalising consideration.'],'Registrar settlement confirmation or recipient receipts would determine whether the announced additional consideration was paid.',kind='response',status='payment-commitment-settlement-unverified')
for r in S['relationships']:
    if ND in r['recordIds'] and r['id']!='vcpl-equalising-payment':r['responseIds'].append('ndtv-price-equalisation')
    if r['id']=='vcpl-ndtv-offer':
        r['sourceIds'].append('ndtv-equalisation-2023')
        r['summary']+=' January2023 notice promisesINR48.65/share additional consideration underSAST8(10), equalising the price; completion of this extra payment is not independently verified.'
    if r['id'] in ['epstein-enhanced-affiliation','epstein-gratitude-affiliation','puri-icm-role','ipi-icm']:
        r['fromDate']=None;r['toDate']=None
        r['dateBasis']='Status-as-of is source publication, not a one-day role or posthumous action. Source describes earlier affiliation/September2014 launch; the ICM source describes a September2014 launch and two-year project; exact tenure/event boundaries are not inferred.'
    if r['id'] in ['court-trust-audit','admin-auditor']:r['tier']='reported'
for r in S['records']:
    if r['id']==ND:
        r['sourceIds'].append('ndtv-equalisation-2023');r['entityIds'].append('open-offer-sellers');r['relationshipIds'].append('vcpl-equalising-payment')
        r['summary']+=' A January2023 notice promisesINR48.65/share extra to accepted open-offer sellers to equalise their initial price with the founder price; this is a commitment, not independently verified final settlement.'
        r['response']+=' VCPL subsequently announced theSAST8(10) equalising payment.'
    if r['id']=='puri-response':r['statusAsOf']='2026-02-11';r['toDate']='2026-02-11';r['period']='2026-02-11'
    if r['id']==PD:r['tier']='reported'
for s in S['sources']:
    if s['id']=='padma-sc-2021':s['tier']='reported';s['limitations'].append('Mirror-only2021 assertions and edges retain reported tier; the directly retrieved2020 court judgment remains documented.')
    if s['id']=='ndtv-completion-2022':s['limitations'][0]='Original URL returnedHTTP403; full relevant ownership table and founderDINs read through indexed original-file fetch and retained in ndtv-completion-indexed-excerpt.json. Unrelated later annexures/contact details omitted.'

# Normalize prose spacing introduced by compact authoring without altering identifiers or URLs.
import re
def readable(v):
    if isinstance(v,list):return [readable(x) for x in v]
    if isinstance(v,dict):return {k:(x if k in {'id','url','sourceIds','entityIds','relationshipIds','responseIds','recordIds','from','to','canonicalId','localityIds','fromDate','toDate','statusAsOf','publishedAt','retrievedAt','route'} else readable(x)) for k,x in v.items()}
    if isinstance(v,str):
        v=re.sub(r'([a-zA-Z%])(?=\d)',r'\1 ',v)
        v=re.sub(r'(?<=\d)(?=[A-Z])',' ',v)
        v=re.sub(r',(?=[A-Za-z])',', ',v)
        v=re.sub(r'(?<=[a-z])(?=[A-Z])',' ',v)
        v=re.sub(r'(?<=\d),(?=(?:19|20)\d{2}\b)',', ',v)
        v=re.sub(r'\bL (\d{5}) (DL|GJ) (\d{4}) PLC (\d{6})',r'L\1\2\3PLC\4',v)
        v=re.sub(r'\bEFTA (\d+)',r'EFTA\1',v)
        for token in ['IPI','ICM','Puri','Epstein','Hoffman','CBI','SEBI','RRPR','INR','USD','MA1465','October','September','August','July','June','May','April','January','November','December','FY2025']:
            v=re.sub(r'(?<=[a-z])'+token,r' '+token,v)
        return v
    return v
S=readable(S)
OUT.write_text(json.dumps(S,indent=2,ensure_ascii=False)+'\n')
print({k:len(v) for k,v in S.items()})
