#!/usr/bin/env python3
"""Reproduce the manually reviewed international finance slice. No generated inference or inferred joins."""
import json,pathlib,re
R=pathlib.Path(__file__).resolve().parents[4]
OUT=R/'research/raw/atlas-expansion/international-finance.json'
D={'sources':[],'entities':[],'relationships':[],'records':[],'localities':[]}
def source(id,title,publisher,date,locator,summary,tier='documented',limitations=None,url=None):
 receipt=pathlib.Path(__file__).parent/(id+'.receipt.json')
 if url is None:url=json.load(open(receipt))['url']
 D['sources'].append(dict(id=id,title=title,url=url,publisher=publisher,publishedAt=date,retrievedAt='2026-10-07',locator=locator,summary=summary,tier=tier,limitations=(limitations or [])+[f'Archive: research/raw/atlas-expansion/international-finance-evidence/{id}.receipt.json; original bytes and extracted text are distinct artifacts.']))
def geo(src,state=None,local=None,note=None):
 return [{'scope':'city' if local else ('state' if state else 'national'),'stateCodes':[state] if state else [],'localityIds':[local] if local else [],'basis':'project-location' if state else 'national-context','note':note or ('Dated project location; no statewide spending inferred.' if state else 'National legal or institutional context; no allocation to every state inferred.'),'sourceIds':src}]
def dims(src,domain,route,layers=None,g=None,limitations=None):
 return dict(sourceIds=src,domains=domain,layers=layers or ['funding','legal'],route=route,geography=g or geo(src),limitations=limitations or [])
def entity(id,label,type,src,domain,route,summary,basis=None,canonical=None,g=None):
 x=dict(id=id,label=label,type=type,resolved=True,identityBasis=basis or 'Exact institution or instrument named in the cited primary document.',summary=summary,**dims(src,domain,route,['organisations','funding','legal'],g))
 if canonical:x['canonicalId']=canonical
 D['entities'].append(x)
def amount(value,unit,stage,period,currency='INR'):return dict(value=value,currency=currency,unit=unit,stage=stage,period=period)
def edge(id,a,b,label,kind,date,src,domain,route,summary,records=None,responses=None,amounts=None,tier='documented',status=None,g=None,limits=None,end=None):
 D['relationships'].append(dict(id=id,from_=a,to=b,kind=kind,label=label,tier=tier,status=status or 'documented dated relationship',statusAsOf=date,fromDate=date,toDate=end or date,dateBasis='Dated legal, contract or disclosure event; an instantaneous event is not an ongoing ownership assertion.',summary=summary,alternativeExplanations=['A lawful policy, contract or financing relationship does not by itself establish preferential treatment or wrongdoing.'],falsifier='A corrected original instrument identifying a different legal party, date, scope or financial stage would require amendment of this relationship.',responseIds=responses or [],recordIds=records or [],amounts=amounts or [],**dims(src,domain,route,['organisations','funding','legal'],g,limits)))
 D['relationships'][-1]['from']=D['relationships'][-1].pop('from_')
def record(id,title,summary,kind,date,src,entities,edges,domain,route,response,alternatives,falsifier,amounts=None,tier='documented',status='documented historical event',asof=None,end=None,g=None,limits=None,period=None):
 D['records'].append(dict(id=id,title=title,summary=summary,kind=kind,tier=tier,status=status,statusAsOf=asof or date,fromDate=date,toDate=end or date,dateBasis='Event/commencement date is distinct from publication, retrieval and later outcome dates; see period.',entityIds=entities,relationshipIds=edges,period=period or date,response=response,alternativeExplanations=alternatives,falsifier=falsifier,amounts=amounts or [],**dims(src,domain,route,['legal','funding','review'],g,limits)))

F=['international-finance','finance']
T=F+['public-finance','public-works','procurement','disaster-relief']
M=F+['capital','transport']
B=F+['energy','procurement','foreign']
def country(src,codes,note):
 return [dict(scope='country',countryCodes=codes,stateCodes=[],localityIds=[],basis='country-context',note=note,sourceIds=src)]
def cash(v,stage,date,c='USD',u='dollars'):return amount(v,u,stage,date,c)
source('tn-loan-original','Loan 8488-IN: signed India–IBRD loan agreement','World Bank','2015-06-03','PDF pp2–4,8–9; Article II, Article III and Schedule 2 section I.A','US$400m loan to India; Union makes proceeds available to Tamil Nadu, which makes proceeds available to TNUDF and eligible bodies.',['documented'][0],['Signed historical terms, not a current debt balance. Date corroborated by original 2020 amendment because scanned handwriting is poorly extracted.'])
source('tn-project-tnudf','8488-IN: TNUDF–TNUIFSL Project Agreement','World Bank / TNUDF / TNUIFSL','2015-06-03','PDF pp1–2,5–6; Article II and Schedule section I.A','Exact implementing entities and Part B duties; projected net revenue must cover debt service before additional debt.',['documented'][0],['TNUDF is a fund; TNUIFSL is a separate company. Neither is automatically the purchaser of every project contract.'])
source('tn-loan-amendment','8488-IN amendment: removal of credit enhancement facility','World Bank','2020-06-30','PDF pp1–3; amendment paragraphs1–7 and revised withdrawal table','Removes credit enhancement component and reallocates categories; US$400m aggregate unchanged in this amendment.',['documented'][0],['Amendment effective on last required countersignature and receipt, not automatically the covering-letter date. Later ICR records further changes.'])
source('tn-completion','TNSUDP P150395 implementation completion report','World Bank','2023-09-22','PDF pp6–7 financing/dates; pp25–26 safeguards/procurement; paragraphs51,64–70','IBRD actual disbursement US$352,729,993 and programme closure31March2023; satisfactory overall outcome coexists with procurement and safeguard concerns.',['documented'][0],['Programme totals and findings cannot be assigned to the selected flood-monitoring contract without contract-specific evidence.'])
source('tn-awards','World Bank procurement notices P150395: OP00218737 and OP00187128','World Bank procurement notices API',None,'JSON procnotices IDs OP00218737 (award notice15March2023) and OP00187128 (invitation18July2022); retained exact rows','WRD purchaser, loan84880-IN linkage, two named awarded bidders, one signed contract price and comparator bids.',['documented'][0],['13March2023 is award-notification date, not a verified signature date. The notice establishes no legal JV name, per-firm share or cash payment. The complete115-notice response contains unrelated packages.'])
source('mahindra-cash-2023','Mahindra exchange filing: MLMML cash allotment to IFC','Mahindra & Mahindra Limited','2023-10-09','PDF pp1–3; attached original22March2023 disclosure pp4–12','30,00,000 CCPS at₹1,000 each allotted for₹300cr cash; 5.9% voting-instruction rights until conversion, within an up-to₹600cr commitment.',['documented'][0],['Issuer filing and receipt statement, not an independently obtained bank ledger. Later tranches/conversion are not verified.'])
source('ifc-mahindra-project','IFC project42622: Mahindra LMM Co','International Finance Corporation','2023-05-15','Original HTML Summary of Investment Information; previous events, equity table, project description and E&S rationale','Names Mahindra Last Mile Mobility Limited; equity/compulsorily convertible instrument, not sovereign lending; investment event3October2023.',['documented'][0],['Last updated8October2023. IFC investment event differs from issuer allotment9October2023; these are different recorded milestones, not silently merged. Expected benefits are projections.'])
source('ifc-bajaj-project','IFC project50037: BFL Loan FY25','International Finance Corporation','2024-10-16','Original HTML previous events; project description; amount/nature and investment table','Senior secured loan up toUS$400m to Bajaj Finance; US$100m microfinance and up toUS$300m climate use; approved9August, signed30August, invested9September2024.',['documented'][0],['Invested status is not a published drawdown ledger; up-to ceilings and intended on-lending do not identify ultimate customers. Last updated17October2024.'])
source('ifc-bajaj-announcement','IFC participates in Bajaj Finance US$1bn fund raise','International Finance Corporation','2024-11-06','Original HTML announcement and Bajaj CFO statement','IFC identifies its ownUS$400m loan within largerUS$1bn fundraising and anticipated climate/microfinance objectives.',['documented'][0],['US$600m mobilisation from other lenders is not IFC own-account cash. Targets for2027 are not realised outcomes.'])
source('adb-loan-2019','Loan3853-BAN: Dhaka and Western Zone loan agreement','Asian Development Bank / Bangladesh','2019-12-11','PDF pp2,4–7; recitalsG–H, sections2.01–2.05 and3.01','Bangladesh is sovereign borrower of EUR271,838,000; it must relend proceeds to PGCB through a subsidiary financing agreement.',['documented'][0],['The US$300m figure on the project page is an equivalent, not the signed euro principal. Original2024 closing date was later extended.'])
source('adb-bangladesh-project-indexed','ADB51137-003 official project page: finance and contract table','Asian Development Bank',None,'Opened full indexed official-origin page; Contracts Awarded and Loan3853-BAN/8374-BAN utilisation tables','Exact L&T package3 award US$60,232,129.73; loan utilisation reported as of3August2026; AIIB cofinancing separately listed.','documented',['Live HTML returned403; original failure body retained. This source is the opened full indexed page, not original live bytes. Signed loan and borrower monitoring PDFs were obtained directly.','Contract table says10May2021; borrower monitoring report says signed9May2021. Keep one-day discrepancy explicit.','Different sections have different dates. Do not treat older narrative text as a2026 status update.'])
source('adb-monitoring-2025','Dhaka and Western Zone environmental monitoring January–June2025, Part A','Power Grid Bangladesh PLC; disclosed by ADB','2025-08-20','PDF pp12–15,21–22; Table1-2 and pp114–119 corrective actions','Borrower report records package3 L&T contract9May2021, approximately85% progress byJune2025, rejected monitoring submission and planned corrective action.','self-reported',['Borrower/consultant monitoring report, not a judicial finding or independent completion certificate. Front cover monthAugust2025; report version20August2025.','Package8 termination is a different contractor/package and is not attributed to L&T. No later completion certification verified.'])
source('imf-position-2026','India: Financial Position in the Fund,30September2026','International Monetary Fund',None,'Original HTML sectionsII–VI; observation date30September2026, publication date not established','Outstanding purchases and loans: None; quota, reserve tranche, SDR allocation/holdings and projected charges shown separately.',['documented'][0],['This is a dated financial position; it does not prove an absence of every IMF-related financial obligation. IMF notes table is informational and does not replace other official statements.'])
source('imf-transactions-2026','India: Transactions with the Fund through30September2026','International Monetary Fund',None,'Original HTML year table through30September2026; latest transaction-year row2000; publication date not established','No purchase/loan transaction rows in2011–2026; corroborates the dated no-outstanding-credit snapshot.',['documented'][0],['No transaction rows is not a universal no-influence claim. This table excludes quota/SDR transactions and does not imply zero SDR charges.'])
source('imf-articleiv-2025-original','India2025 Article IV report: informational annex','International Monetary Fund','2025-11-26','PDF p105, Fund Relations as of30September2025','Earlier official snapshot independently records no outstanding purchases or loans; ArticleIV consultation is surveillance, not a lending approval.',['documented'][0],['Data date30September2025 differs from report publication and2026 financial position.'])
source('rbi-sdr-release','General Allocation of Special Drawing Rights by the IMF','Reserve Bank of India','2021-09-01','Press release52158; both substantive paragraphs','India received SDR12.57bn allocation effective23August2021; total holdings became SDR13.66bn; RBI says holdings form part of foreign exchange reserves.',['documented'][0],['Allocation, total holdings and USD equivalents are different quantities. This is not a sovereign project loan or a fiscal grant.'])
source('ida-pmgky-pd','P174027: second COVID social-protection development-policy financing document','World Bank','2020-11-13','PDF cover and paragraph94, printedp42; paragraph103 fiscal risk','Proposed SDR77m concessional plusUS$291.4m non-concessional IDA credit; proceeds go to GoI RBI account and Consolidated Fund for general budget use.',['documented'][0],['This document is a proposal at publication; final approval/actual financing is established by the completion report. It explicitly says proceeds do not finance specifically agreed activities.'])
source('ida-pmgky-icr','PMGKY P173943/P174027 joint implementation completion report','World Bank','2024-04-22','PDF pp5–7, financing tables; paragraph1 and footnote1','P174027 approved15December2020; closed31December2022. IDA68130 actualUS$111,201,860 and68120 actualUS$291,400,000; totalUS$402,601,860.',['documented'][0],['Cover transposes first-operation IDA/IBRD instrument labels; use correctly identified financing table for P174027, corroborated by original programme document.','USD reporting equivalents of SDR credit vary with exchange rates; actualUSD402.60m vs approvedUSD400m is not evidence of unauthorised overspending.'])

# CASE 1: sovereign loan, state implementation and an exact procurement award.
tg=geo(['tn-loan-original','tn-awards'],'TN',note='Loan supports Tamil Nadu; selected WRD flood-monitoring procurement is in Chennai and named basin/collectorate locations. No equal allocation across the state is inferred.')
entity('ibrd','International Bank for Reconstruction and Development','multilateral-lender',['tn-loan-original'],F,'/finance','World Bank lending institution and party to loan8488-IN.',canonical='legacy:entity:fin:ibrd')
entity('india','India — sovereign borrower','sovereign',['tn-loan-original','ida-pmgky-icr'],F+['public-finance'],'/finance','Borrower is the Union, separate from state implementers and private borrowers.')
entity('tn-loan8488','IBRD loan8488-IN / P150395','loan-instrument',['tn-loan-original','tn-completion'],T,'/public-works','US$400m original commitment; programme-wide actual disbursementUS$352,729,993.',g=tg)
entity('tamil-nadu','Government of Tamil Nadu','state-government',['tn-loan-original'],T,'/public-works','State implementing entity receiving proceeds under Union–state arrangements.',g=tg)
entity('tnudf','Tamil Nadu Urban Development Fund','public-development-fund',['tn-project-tnudf'],T,'/public-works','Fund named separately from its corporate manager in the signed agreement.',g=tg)
entity('tnuifsl','Tamil Nadu Urban Infrastructure Financial Services Limited','company',['tn-project-tnudf'],T,'/public-works','Exact corporate implementing entity; no assumption that contract-reference prefix makes it purchaser.',g=tg)
entity('tn-wrd','Tamil Nadu Water Resources Department — Groundwater Circle','state-agency',['tn-awards'],T,'/public-works','Invitation names the Superintending Engineer, WRD Groundwater Circle, as purchaser on behalf of the Governor.',g=tg)
entity('tn-flood-contract','IN-TNUIFSL-298576-GO-RFB flood-monitoring award','procurement-instrument',['tn-awards'],T,'/public-works','One award jointly lists two firms; no separately incorporated JV or per-firm allocation is asserted.',g=tg)
entity('azista','Azista Industries Private Limited','company',['tn-awards'],T,'/public-works','Exact awarded company name and World Bank bidder431194; CIN and beneficial ownership not established.',g=tg)
entity('sstech','SSTECH Salem Commercials Pvt. Ltd.','company',['tn-awards'],T,'/public-works','Exact awarded company name and World Bank bidder722929; do not substitute another SSTech company.',g=tg)
tr=['tn-urban-sovereign-contract'];tp=['tn-urban-response']
edge('ibrd-india-8488','ibrd','india','Lent under8488-IN','sovereign-loan','2015-06-03',['tn-loan-original'],T,'/public-works','Signed agreement commitsUS$400m; this is a commitment, not a same-day transfer.',tr,tp,[cash(400000000,'original signed loan commitment','2015-06-03')],g=tg)
edge('india-8488-instrument','india','tn-loan8488','Is borrower of specified instrument','borrower','2015-06-03',['tn-loan-original'],T,'/public-works','Instrument remains separate from later contract awards.',tr,tp,g=tg)
edge('india-tn-proceeds','india','tamil-nadu','Must make loan proceeds available to state','contractual-fund-route','2015-06-03',['tn-loan-original'],T,'/public-works','Schedule2I.A.1 specifies developmental-assistance arrangements; not a quantified transfer ledger.',tr,tp,g=tg)
edge('tn-tnudf-route','tamil-nadu','tnudf','Must pass proceeds under subsidiary loan arrangement','contractual-fund-route','2015-06-03',['tn-loan-original'],T,'/public-works','Schedule2I.A.2 distinguishes TNUDF from other eligible bodies and recipients.',tr,tp,g=tg)
edge('8488-tnuifsl','tn-loan8488','tnuifsl','Names corporate Part B implementer','implementation','2015-06-03',['tn-loan-original','tn-project-tnudf'],T,'/public-works','TNUIFSL and TNUDF carry out their respective Part B activities; no payment between them is quantified.',tr,tp,g=tg)
edge('8488-wrd-procurement','tn-loan8488','tn-wrd','Identified loan linked to WRD purchaser','procurement-financing-context','2022-07-18',['tn-awards'],T,'/public-works','Invitation states loan84880-IN and intends proceeds for eligible contract payments; this is not proof of disbursement to winners.',tr,tp,g=tg)
edge('wrd-flood-award','tn-wrd','tn-flood-contract','Procurement award notification','contract-award','2023-03-13',['tn-awards'],T,'/public-works','Award notice specifies one signed contract priceINR763,891,408 for the flood data/control-room system. Date is notification, not signature.',tr,tp,[amount(763891408,'rupees','one signed contract price in award notice; no payment or split verified','award notified2023-03-13')],g=tg)
for id in ['azista','sstech']:
 edge('flood-awarded-'+id,'tn-flood-contract',id,'Named co-awarded bidder','awarded-party','2023-03-13',['tn-awards'],T,'/public-works','Both names appear under Awarded Bidder(s) in one notice. No duplicate amount and no invented JV identity.',tr,tp,g=tg)
record('tn-urban-response','Tamil Nadu: competition, closure and programme-level limits','The same award notice records Yokogawa’s evaluatedINR1,139,999,888 and Canarys/OrangeINR1,285,652,986.57 against the winningINR763,891,408. Programme completion rates outcome Satisfactory but procurement and financial management Moderately Satisfactory; red flags and an unresolved January2023 incident compensation proceeding are not assigned to this contract.','response','2023-09-22',['tn-awards','tn-completion'],['tn-wrd','tn-flood-contract','azista','sstech','tnuifsl'],[],T,'/public-works','No contract-specific adverse judicial finding or respondent denial was verified. Programme-level judicial compensation status is historical; later outcome remains unknown. No outreach occurred.',['Lower evaluated price offers an ordinary procurement explanation; bid evaluation is not proof of performance.','Programme red flags cannot identify this recipient as responsible.'],'Signed contract, payment certificates, bank statements, specific review findings and later court order would change these conclusions.',asof='2023-09-22',g=tg)
record('tn-urban-sovereign-contract','IBRD → India → Tamil Nadu → a flood-monitoring award','Loan8488-IN committedUS$400m to India with an explicit Union→Tamil Nadu→TNUDF route and separate TNUIFSL implementation. A2022WRD invitation links loan84880-IN to flood-monitoring procurement; the13March2023 notification jointly names Azista and SSTECH for oneINR763,891,408 contract. The programme closed31March2023 withUS$352,729,993 actually disbursed by IBRD; contractor cash remains unverified.','investigation-case','2015-06-03',['tn-loan-original','tn-project-tnudf','tn-loan-amendment','tn-awards','tn-completion'],['ibrd','india','tn-loan8488','tamil-nadu','tnudf','tnuifsl','tn-wrd','tn-flood-contract','azista','sstech'],['ibrd-india-8488','india-8488-instrument','india-tn-proceeds','tn-tnudf-route','8488-tnuifsl','8488-wrd-procurement','wrd-flood-award','flood-awarded-azista','flood-awarded-sstech'],T,'/public-works','Response retains comparator bids and mixed programme findings. The state/fund/company/purchaser roles are distinct; full programme disbursement is not attributed to the selected contract.',['Co-awarded companies may divide work, but no split is disclosed.','The2020removal of credit enhancement and later programme savings can lawfully explain differences between commitment and disbursement.'],'Reconcile signed award, amendments, invoices, payment certificates and treasury/bank credits; obtain any contract-specific review before alleging misallocation.',[cash(400000000,'original loan commitment','2015-06-03'),cash(352729993,'ICR programme-wide actual IBRD disbursement','ICR2023-09-22'),amount(763891408,'rupees','one contract price; not payment to each awarded company','award notification2023-03-13')],asof='2023-09-22',status='loan and award documented; programme closed; company receipts not verified',end='2023-03-31',g=tg,limits=['Curated programme and contract sample, not all World Bank loans or all state procurement.','No later contract-specific payment/completion or court disposition established by6October2026.'],period='Loan3June2015; amendment30June2020; invitation18July2022; award notification13March2023; programme closed31March2023; ICR22September2023')

# CASE 2: IFC private equity instrument with issuer evidence of cash.
entity('ifc','International Finance Corporation','multilateral-private-sector-investor',['ifc-mahindra-project','ifc-bajaj-project'],F,'/finance','World Bank Group member making its own private-company equity and debt investments; separate from IBRD/IDA sovereign credit.')
entity('mahindra-parent','Mahindra & Mahindra Limited','company',['mahindra-cash-2023'],M,'/finance','Issuer and parent party to22March2023 subscription/shareholder arrangements; not the recipient subsidiary.')
entity('mlmml','Mahindra Last Mile Mobility Limited','company',['mahindra-cash-2023','ifc-mahindra-project'],M,'/finance','Exact CCPS issuer and cash recipient; a subsidiary that ceased to be wholly owned on9October2023.')
entity('mlmml-ccps','MLMML–IFC2023 CCPS subscription','equity-instrument',['mahindra-cash-2023'],M,'/finance','Compulsorily convertible preference shares, distinct from senior debt or sovereign lending.')
mr=['ifc-mahindra-cash'];mp=['ifc-mahindra-response']
edge('ifc-mlmml-commitment','ifc','mlmml-ccps','Committed up to₹600cr across tranches','equity-commitment','2023-03-22',['mahindra-cash-2023','ifc-mahindra-project'],M,'/finance','Commitment at valuation up to₹6,020cr; neither figure is a single confirmed cash receipt.',mr,mp,[amount(600,'crore','maximum CCPS investment commitment','2023-03-22')])
edge('mlmml-issues-ccps','mlmml','mlmml-ccps','Issued30,00,000CCPS at₹1,000 each','instrument-issuance','2023-10-09',['mahindra-cash-2023'],M,'/finance','Issuer allotment dated9October2023; the separate IFC event field says invested3October.',mr,mp)
edge('ifc-mlmml-cash','ifc','mlmml','Issuer confirms₹300cr first tranche received','equity-cash-receipt','2023-10-09',['mahindra-cash-2023'],M,'/finance','Exchange filing says allotted for cash and subsidiary received₹300cr. This is not an ordinary loan.',mr,mp,[amount(300,'crore','issuer-confirmed first cash tranche against CCPS allotment','2023-10-09')])
edge('mahindra-mlmml-control','mahindra-parent','mlmml','Subsidiary continued after first IFC allotment','ownership-status','2023-10-09',['mahindra-cash-2023'],M,'/finance','MLMML ceased being wholly owned but remained subsidiary; no2026share percentage inferred.',mr,mp)
edge('ifc-mahindra-vote','ifc','mahindra-parent','Gained instruction rights over5.9% of MLMML equity votes','voting-instruction-right','2023-10-09',['mahindra-cash-2023'],M,'/finance','The right is to instruct parent voting until conversion, not a statement of5.9% ordinary-share ownership.',mr,mp)
record('ifc-mahindra-response','Mahindra and IFC: clean-mobility purpose and instrument limits','Both parties describe electric last-mile vehicles and microentrepreneur incomes as the investment purpose. IFC classifies the project CategoryB and identifies labour, safety, battery-waste and stakeholder risks. These are diligence requirements, not established violations.','response','2023-10-09',['mahindra-cash-2023','ifc-mahindra-project'],['ifc','mahindra-parent','mlmml','mlmml-ccps'],[],M,'/finance','No adverse court finding concerning this investment was verified. Later tranche payment, conversion and exact current ownership remain unverified; no outreach was attempted.',['Projected climate and livelihood gains are not independently measured outcomes.','The3OctoberIFCinvestment-event date and9Octoberissuer allotment can describe different administrative milestones.'],'Obtain later allotment/conversion filings and audited cash-flow notes; correct dates if signed transaction records resolve the milestone difference.')
record('ifc-mahindra-cash','IFC → Mahindra Last Mile Mobility: cash against convertible shares','IFC’s private-sector route is evidenced by a22March2023 up-to₹600cr CCPS commitment and the issuer’s9October2023 filing confirming₹300cr cash for30,00,000CCPS. The recipient is Mahindra Last Mile Mobility Limited, distinct from its parent. IFC gained voting-instruction rights over5.9% of subsidiary equity until conversion; that is not5.9% ordinary-share ownership.','investigation-case','2023-03-22',['mahindra-cash-2023','ifc-mahindra-project'],['ifc','mahindra-parent','mlmml','mlmml-ccps'],['ifc-mlmml-commitment','mlmml-issues-ccps','ifc-mlmml-cash','mahindra-mlmml-control','ifc-mahindra-vote'],M,'/finance','Issuer receipt/allotment is primary disclosure; no independent bank statement was obtained. Party rationale and environmental/social controls are retained in the response.',['A development institution can take lawful equity risk in an Indian company without lending to India’s government.','Unpaid commitment and projected valuation cannot be added to cash raised.'],'Later issuer filings, transaction statements and conversion terms must support any further cash or ownership claim.',[amount(600,'crore','up-to CCPS commitment','2023-03-22'),amount(300,'crore','issuer-confirmed first cash tranche','2023-10-09')],asof='2023-10-09',end='2023-10-09',status='first cash tranche documented; later tranches and conversion not verified',limits=['No assumption of sovereign guarantee or public procurement in this private transaction.','Invested status in IFC page is a dated2023snapshot, not a current2026ownership ledger.'])

# CASE 3: foreign sovereign, on-lending to agency, and India-linked procurement.
bg=country(['adb-loan-2019','adb-bangladesh-project-indexed'],['BD'],'Bangladesh sovereign borrower and Bangladesh electricity-transmission project; Indian contractor identity does not make the spending an Indian-state project.')
entity('adb','Asian Development Bank','multilateral-lender',['adb-loan-2019'],B,'/foreign','Lender to Bangladesh under3853-BAN; institution is separate from any one member country.',canonical='legacy:entity:fin:adb',g=bg)
entity('bangladesh','People’s Republic of Bangladesh','sovereign',['adb-loan-2019'],B,'/foreign','Exact sovereign borrower; proceeds must be relent to PGCB.',g=bg)
entity('ban-loan3853','ADB loan3853-BAN / project51137-003','loan-instrument',['adb-loan-2019'],B,'/foreign','Signed EUR271,838,000 principal; the project page also presents USD equivalents.',g=bg)
entity('pgcb','Power Grid Company of Bangladesh Limited','public-utility',['adb-loan-2019','adb-bangladesh-project-indexed'],B,'/foreign','Exact2019executing agency and2021contracting entity; later project report uses Power Grid Bangladesh PLC. No separate corporate-name-change finding is made.',g=bg)
entity('lt','Larsen & Toubro Limited','company',['adb-bangladesh-project-indexed','adb-monitoring-2025'],B,'/foreign','Exact package3 contractor name, Mumbai India, independently linked to L&T India by borrower monitoring.','Exact full legal name in ADB award row and same package’s borrower report; reviewed match to retained Larsen & Toubro Limited. No consortium or subsidiary substitution.',canonical='legacy:entity:co:larsen-toubro',g=country(['adb-bangladesh-project-indexed'],['IN','BD'],'Indian corporate contractor for Bangladesh project; no Indian-state project spending inferred.'))
entity('ban-package3','3853-BAN transmission package3','procurement-instrument',['adb-bangladesh-project-indexed','adb-monitoring-2025'],B,'/foreign','Specific230kV/132kV western-zone transmission package; separate from other project packages.',g=bg)
entity('aiib','Asian Infrastructure Investment Bank','multilateral-lender',['adb-loan-2019','adb-bangladesh-project-indexed'],B,'/foreign','Separate cofinancing institution, not a synonym for a bilateral Chinese loan.',g=bg)
br=['bangladesh-adb-lt'];bp=['bangladesh-adb-response']
edge('adb-bangladesh-loan','adb','bangladesh','Signed sovereign euro loan','sovereign-loan','2019-12-11',['adb-loan-2019'],B,'/foreign','EUR271,838,000 under3853-BAN; interest is Euribor plus contractual components, with0.15% commitment charge on unwithdrawn balance.',br,bp,[cash(271838000,'signed sovereign loan principal commitment','2019-12-11','EUR','euros')],g=bg)
edge('bangladesh-instrument','bangladesh','ban-loan3853','Is borrower of3853-BAN','borrower','2019-12-11',['adb-loan-2019'],B,'/foreign','Loan is owed by Bangladesh, not by L&T or India.',br,bp,g=bg)
edge('bangladesh-pgcb-relending','bangladesh','pgcb','Must relend loan proceeds to executing utility','contractual-on-lending','2019-12-11',['adb-loan-2019'],B,'/foreign','Section3.01 requires subsidiary financing agreement satisfactory to ADB; exact subsidiary-ledger transfers not obtained.',br,bp,g=bg)
edge('pgcb-package3-award','pgcb','ban-package3','Awarded specific transmission package','contract-award','2021-05-10',['adb-bangladesh-project-indexed','adb-monitoring-2025'],B,'/foreign','ADB contract table says10May2021 andUS$60,232,129.73 total/ADB-financed contract amount; borrower report says signed9May2021. Amount is award value, not cash received.',br,bp,[cash(60232129.73,'ADB-published USD contract amount/financed amount; not contractor cash','contract table2021-05-10')],g=bg,limits=['One-day signature/date discrepancy remains unresolved; both source dates retained.'])
edge('package3-lt','ban-package3','lt','Names Indian corporate contractor','contract-party','2021-05-10',['adb-bangladesh-project-indexed'],B,'/foreign','Exact named contractor M/S Larsen & Toubro Limited; not an IFC or World Bank loan to L&T.',br,bp,g=bg)
edge('aiib-bangladesh-cofinance','aiib','bangladesh','Separate cofinancing loan listed as8374-BAN','cofinancing-commitment','2020-06-30',['adb-bangladesh-project-indexed','adb-loan-2019'],B,'/foreign','Project page recordsUS$200m cofinancing signed30June2020. This is a different loan and is not added to3853-BAN cash or assigned to package3.',br,bp,[cash(200000000,'separate AIIB cofinancing commitment reported by ADB','2020-06-30')],g=bg)
record('bangladesh-adb-response','Bangladesh: ongoing work, comparator awards and corrective action','ADB’s contract table also lists India’s Transrail, Korean Hanbaek and Chinese contractors on different packages. Borrower monitoring records package3 at about85% inJune2025 and a rejected April2025 monitoring submission, followed by a new vendor and expected resubmission. No programme GRM grievances were reported as referred to court in that reporting period.','response','2025-06-30',['adb-bangladesh-project-indexed','adb-monitoring-2025'],['adb','bangladesh','pgcb','lt','ban-package3','aiib'],[],B,'/foreign','Development purpose, corrective action and incomplete work are retained. Zero reported GRM referrals is not a comprehensive no-litigation finding. No later package3 completion, final court outcome or contractor payment ledger was verified. No outreach occurred.',['Different contractors on different packages offer a control against inferring national exclusivity.','Environmental reporting deficiencies require correction but do not alone establish diverted finance.'],'Later independent completion, accepted monitoring, project audit and payment certificates would resolve status and cash attribution.',asof='2026-08-03',tier='self-reported',g=bg,limits=['Package8 termination belongs to a different contract and must not be assigned to L&T.'])
record('bangladesh-adb-lt','ADB → Bangladesh → PGCB → L&T transmission package','The11December2019agreement lends EUR271,838,000 to Bangladesh and requires relending to PGCB. ADB’s contract table identifies L&T’s package3 atUS$60,232,129.73; borrower monitoring records about85% work complete byJune2025. ADB reportsUS$136.54m cumulative3853-BAN disbursement at3August2026, across the loan, not as L&T’s receipts. AIIB’sUS$200m is separate cofinancing.','investigation-case','2019-12-11',['adb-loan-2019','adb-bangladesh-project-indexed','adb-monitoring-2025'],['adb','bangladesh','ban-loan3853','pgcb','ban-package3','lt','aiib'],['adb-bangladesh-loan','bangladesh-instrument','bangladesh-pgcb-relending','pgcb-package3-award','package3-lt','aiib-bangladesh-cofinance'],B,'/foreign','The response retains contractor-country comparators, borrower monitoring concerns and planned corrections. Signed date discrepancy9vs10May2021 is explicit; source status and dollar equivalents do not replace bank-ledger evidence.',['Foreign sovereign borrowing can lawfully finance a contract won by an Indian company.','Loan disbursement may cover multiple contracts and eligible costs; no automatic backward attribution to one winner.'],'Trace withdrawal applications, subsidiary-loan ledger, contractor invoices and payment certificates; use actual contract amendments to resolve dates, currency and closing balances.',[cash(271838000,'signed loan commitment','2019-12-11','EUR','euros'),cash(60232129.73,'published contract/ADB-financed award value, not cash paid','2021-05-10 table'),cash(136.54,'ADB loan3853 cumulative disbursement in USD reporting units; not contractor receipt','2026-08-03','USD','million')],asof='2026-08-03',status='loan active with revised2027closing; partial loan disbursement and dated package progress',end='2026-08-03',g=bg,limits=['Official project HTML was blocked; full opened official-origin indexed table retained. Original loan and monitoring PDFs were downloaded.','Country coverage is a bounded Bangladesh–India link, not an all-nations or all-contractors census.'],period='Loan11December2019; package3signed9May2021 per borrower /10May perADB; progressJune2025; loan utilisation3August2026; revised closing31December2027 is future, not a completed event')

# Supplemental private debt, IDA budget support and IMF non-loan financial position.
entity('bajaj-finance','Bajaj Finance Limited','company',['ifc-bajaj-project'],F+['capital'],'/finance','Exact borrower underIFC50037; not Bajaj Auto or Bajaj Finserv.')
edge('ifc-bajaj-loan','ifc','bajaj-finance','Senior secured private-company loan','private-corporate-loan','2024-08-30',['ifc-bajaj-project','ifc-bajaj-announcement'],F+['capital'],'/finance','Up toUS$400m own-account debt. IFC says invested9September2024 but publishes no tranche ledger here. IntendedUS$100m women-focused microfinance plus up toUS$300m climate lending.', ['ifc-bajaj-private-debt'],[],[cash(400000000,'approved own-account senior secured loan ceiling; exact drawdown not published','2024-08-30')])
record('ifc-bajaj-private-debt','IFC → Bajaj Finance: private debt with intended on-lending','IFC50037 approved9August2024, signed30August and records investment9September. The borrower is Bajaj Finance Limited; up toUS$400m senior secured debt comprisesUS$100m women-focused microfinance and up toUS$300m climate finance. A furtherUS$600m mobilisation target is other lenders’ funding, not IFC own-account cash.','financing-instrument','2024-08-30',['ifc-bajaj-project','ifc-bajaj-announcement'],['ifc','bajaj-finance'],['ifc-bajaj-loan'],F+['capital'],'/finance','Bajaj’s CFO describes diversification and anticipated climate-loan growth; IFC lists eligible uses and exclusions. Actual loan drawdown by tranche and named ultimate recipients are not established. No adverse court finding on this loan verified.',['Private financial-intermediary lending is a different instrument from Mahindra’s CCPS and India’s sovereign loan.'],'Obtain signed financing terms, audited lender balances and anonymised allocation reports before quantifying realised on-lending.',[cash(400000000,'senior secured loan ceiling','2024-08-30'),cash(100000000,'intended women-focused microfinance allocation within ceiling','2024 disclosure'),cash(300000000,'maximum intended climate allocation within ceiling','2024 disclosure')],asof='2024-11-06',status='IFC reports invested; precise drawdown and subloan recipients unverified')
entity('ida','International Development Association','multilateral-lender',['ida-pmgky-pd','ida-pmgky-icr'],F+['welfare'],'/finance','World Bank institution making specific concessional and non-concessional credits; distinct from IBRD.',canonical='legacy:entity:fin:ida')
entity('dea','Department of Economic Affairs, Ministry of Finance','union-agency',['ida-pmgky-icr','ida-pmgky-pd'],F+['public-finance','welfare'],'/finance','Implementing agency for P174027; programme cash enters Union general budget through RBI account.')
entity('ida-p174027','IDA68130 /68120 — P174027','development-policy-instrument',['ida-pmgky-pd','ida-pmgky-icr'],F+['public-finance','welfare'],'/finance','Second PMGKY development-policy financing; not a corporate procurement contract.')
edge('ida-india-p174027','ida','india','Financed2020 second social-protection DPF','sovereign-development-policy-finance','2020-12-15',['ida-pmgky-icr','ida-pmgky-pd'],F+['public-finance','welfare'],'/finance','ApprovedUS$400m equivalent; underlying concessionalSDR77m and non-concessionalUS$291.4m instruments. ICR reports actualUS$402,601,860 equivalent.', ['ida-budget-support'],[],[cash(400000000,'approval equivalent, not fixed single-currency principal','2020-12-15')])
edge('ida-p174027-dea','ida-p174027','dea','Names implementing agency and general-budget route','implementation','2020-12-15',['ida-pmgky-icr','ida-pmgky-pd'],F+['public-finance','welfare'],'/finance','GoI RBI account→Consolidated Fund route; funds not ringfenced to specific activities. No private downstream payee identified.', ['ida-budget-support'])
record('ida-budget-support','IDA → India’s budget: actual disbursement with no contractor trace','P174027’sSDR77m concessional credit68130 andUS$291.4m non-concessional credit68120 were approved15December2020. The2024ICR reportsUS$402,601,860 actual disbursement equivalent and closure31December2022. Proceeds enter the Union’s RBI account and Consolidated Fund; the programme document explicitly excludes tracing them to specifically agreed activities.','financing-instrument','2020-12-15',['ida-pmgky-pd','ida-pmgky-icr'],['ida','india','ida-p174027','dea'],['ida-india-p174027','ida-p174027-dea'],F+['public-finance','welfare'],'/finance','ICR footnote1 expressly attributes actual disbursement differing from approval to SDR/USD exchange-rate fluctuation, using WFACS data of8April2024. ICR rates the two-operation series Highly Satisfactory; these are programme assessments, not contractor-payment proof. The legacy raw finance fleet supplied discovery; original PD/ICR were newly retrieved and checked.',['TheUSD402.60m actual versusUSD400m approval reflects mixed currency reporting; the values cannot by themselves establish an overrun.'],'Reconcile credit-level withdrawals and FX translation to Treasury receipts; require separate appropriation/payment evidence for any corporate beneficiary claim.',[cash(77,'original concessional credit principal','2020 proposal/approved operation','XDR','million SDR'),cash(291400000,'non-concessional credit principal','2020 approved operation'),cash(402601860,'ICR actual disbursement in USD equivalent','ICR2024-04-22')],asof='2024-04-22',end='2022-12-31',status='closed; disbursement verified at programme level; no specific corporate pass-through',limits=['This is a reviewed supplement to retained P174027, not an additional loan to add again to corpus totals.','Cover-page first-operation instrument-label errors in ICR are avoided by using the credit-level financing tables.'])
entity('imf','International Monetary Fund','multilateral-monetary-institution',['imf-position-2026','imf-articleiv-2025-original'],F,'/finance','India’s2026financial position has no outstanding purchases/loans; quota, SDR and reserve-tranche accounts remain distinct.',canonical='legacy:entity:fin:imf')
entity('rbi','Reserve Bank of India','central-bank',['rbi-sdr-release'],F+['public-finance'],'/finance','Official reporter of India’s SDR holdings as a component of foreign exchange reserves.',canonical='finance-research:entity:rbi')
edge('imf-india-sdr','imf','india','Allocated SDRs in2021 general allocation','reserve-asset-allocation','2021-08-23',['rbi-sdr-release'],F+['public-finance'],'/finance','RBI reportsSDR12.57bn allocation; it is not a programme loan, corporate loan or unconditional fiscal grant.', ['imf-sdr-allocation'],['imf-india-no-programme-credit'],[cash(12.57,'general SDR allocation, distinct from holdings and programme lending','2021-08-23','XDR','billion SDR')])
record('imf-sdr-allocation','IMF → India: SDR allocation enters reserve accounting','RBI recordsSDR12.57bn allocated on23August2021 and totalSDR13.66bn holdings after the allocation. Holdings form part of foreign exchange reserves. Allocation is distinct from quota, reserve-tranche position and IMF programme borrowing; it is not a contractor payment or grant.','reserve-account','2021-08-23',['rbi-sdr-release','imf-position-2026'],['imf','india','rbi'],['imf-india-sdr'],F+['public-finance'],'/finance','The financial-position table shows both cumulative allocation and holdings and projected charges even with no purchases/loans. SDR arrangements must not be described as wholly obligation-free.',['Changes in holdings can reflect use or transactions after allocation; holdings need not equal cumulative allocations.'],'Use IMF SDR-department transaction data and RBI reserve accounts for any claim about conversion, use, charges or counterparties.',[cash(12.57,'2021 allocation','2021-08-23','XDR','billion SDR'),cash(13.66,'total holdings immediately after allocation, not a second allocation','2021-08-23','XDR','billion SDR')],asof='2021-09-01')
record('imf-india-no-programme-credit','India and IMF: no outstanding programme credit at30September2026','The IMF’s original financial-position table says Outstanding Purchases and Loans: None. It separately recordsSDR13,114.40m quota, SDR3,532.21m reserve-tranche position, SDR16,547.82m cumulative allocation andSDR13,720.50m holdings. Official transaction records contain no2011–2026purchase/loan rows; the2025ArticleIV annex corroborates an earlier no-credit snapshot.','institution-financial-position','2026-09-30',['imf-position-2026','imf-transactions-2026','imf-articleiv-2025-original'],['imf','india','rbi'],[],F+['public-finance'],'/finance','This corrects the retained corpus’s earlier official-source access gap. IMF surveillance and policy advice do not by themselves create a lending instrument. Projected SDR-related charges remain visible and no all-obligations-zero claim is made.',['A country can hold SDRs, pay associated charges and undergoArticleIVsurveillance while having no outstanding programme purchases/loans.'],'A later official financial-position table or signed arrangement recording new credit would supersede this dated snapshot.',[cash(13114.4,'quota subscription measure; not loan disbursement','2026-09-30','XDR','million SDR'),cash(3532.21,'reserve-tranche position','2026-09-30','XDR','million SDR'),cash(16547.82,'net cumulative SDR allocation','2026-09-30','XDR','million SDR'),cash(13720.5,'SDR holdings','2026-09-30','XDR','million SDR')],asof='2026-09-30',status='official dated no-outstanding-purchases/loans finding',limits=['Historical1981/1991arrangements are outside this15-year sample and are not rendered as new lending events.','This is a financial-status finding, not a claim that IMF has no policy influence.'])

# Human prose spacing only; identifiers, dates, currency codes and source URLs stay exact.
human={'title','label','summary','identityBasis','status','dateBasis','period','response','falsifier','note','stage','locator','unit'}
def textclean(s):
 identifiers=re.findall(r'\b(?:OP[0-9]+|P[0-9]{6}|GoI)\b',s)
 for i,v in enumerate(identifiers):s=s.replace(v,'protectedidentifier'+chr(97+i),1)
 s=re.sub(r'([a-z])([A-Z])',r'\1 \2',s)
 s=re.sub(r'([A-Za-z])([0-9])',r'\1 \2',s)
 s=re.sub(r'([0-9])([A-Za-z])',r'\1 \2',s)
 s=re.sub(r'(?<=[;])(?=[A-Za-z0-9₹])',' ',s)
 s=re.sub(r'(?<=[a-z])(?=₹)',' ',s)
 for a,b in {'IFCinvestment':'IFC investment','IFCevent':'IFC event','Article IVsurveillance':'Article IV surveillance','loan84880':'loan84880'}.items():s=s.replace(a,b)
 for i,v in enumerate(identifiers):s=s.replace('protectedidentifier'+chr(97+i),v)
 return s
def clean(x,key=''):
 if isinstance(x,dict):return {k:clean(v,k) for k,v in x.items()}
 if isinstance(x,list):return [textclean(v) if isinstance(v,str) and key in ['limitations','alternativeExplanations'] else clean(v) for v in x]
 return textclean(x) if isinstance(x,str) and key in human else x
D=clean(D)
OUT.write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
print({k:len(v) for k,v in D.items()})
