#!/usr/bin/env node
/** Curated water/food adapter. Does not infer local coverage from directory coverage. */
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
const read=file=>JSON.parse(readFileSync(`${root}${file}`,'utf8'));
const weather=read('research/raw/water/weather-research.json');
const publicWater=read('research/raw/water/public-research.json');
const food=read('research/raw/water/food-research.json');
const stateRows=[['AN','Andaman and Nicobar Islands'],['AP','Andhra Pradesh'],['AR','Arunachal Pradesh'],['AS','Assam'],['BR','Bihar'],['CH','Chandigarh'],['CG','Chhattisgarh'],['DN','Dadra and Nagar Haveli and Daman and Diu'],['DL','Delhi'],['GA','Goa'],['GJ','Gujarat'],['HR','Haryana'],['HP','Himachal Pradesh'],['JK','Jammu and Kashmir'],['JH','Jharkhand'],['KA','Karnataka'],['KL','Kerala'],['LA','Ladakh'],['LD','Lakshadweep'],['MP','Madhya Pradesh'],['MH','Maharashtra'],['MN','Manipur'],['ML','Meghalaya'],['MZ','Mizoram'],['NL','Nagaland'],['OD','Odisha'],['PY','Puducherry'],['PB','Punjab'],['RJ','Rajasthan'],['SK','Sikkim'],['TN','Tamil Nadu'],['TS','Telangana'],['TR','Tripura'],['UP','Uttar Pradesh'],['UK','Uttarakhand'],['WB','West Bengal']];
const states=stateRows.map(([code,name])=>({code,name}));
const slug=value=>value.toLowerCase().replaceAll('&','and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const stateCode=name=>states.find(state=>slug(state.name)===slug(name))?.code??({'D&NH and D&D':'DN','Dadra & Nagar Haveli and Daman & Diu':'DN','Tamilnadu':'TN','NCT of Delhi':'DL','Jammu & Kashmir':'JK'}[name]);
const window={start:'2021-10-06',end:'2026-10-06'};
const classify=publishedAt=>!publishedAt?'undated':publishedAt.length===7&&[window.start.slice(0,7),window.end.slice(0,7)].includes(publishedAt)?'undated':publishedAt<window.start?'background':publishedAt<=window.end?'in-window':'background';
const sources=[],observations=[],discovery=[],leads=[],localities=[];
const addPlace=(name,code,kind,extra={})=>{
 const id=`${kind}-${code}-${slug(name)}`;
 if(!localities.some(place=>place.id===id))localities.push({id,name,stateCode:code,kind,...extra});
 return id;
};
const dimensions=(override={})=>({scope:'national',stateCodes:[],localityIds:[],domains:['drinking-water'],stages:['distribution'],...override});
const dimensionsOf=source=>Object.fromEntries(['scope','stateCodes','localityIds','domains','stages'].map(key=>[key,source[key]]));
const domainsOf=raw=>[...new Set(raw.flatMap(domain=>({drought:['weather'],flood:['weather'],heat:['weather'],'water-supply':['drinking-water'],'water-quality':['drinking-water'],'food-safety':['food'],agriculture:['farming'],irrigation:['farming'],seed:['farming'],reservoirs:['drinking-water','farming'],groundwater:['groundwater'],weather:['weather']}[domain]??[])))];
for(const row of weather.records){
 const isNews=['news','news-interview','local-news'].includes(row.kind);
 const isPortal=row.kind==='official-data-portal';
 const scope=row.stateCodes.length===0?'national':row.geoscope==='city'||row.geoscope==='locality'?'city':row.geoscope==='district'?'district':row.geoscope==='block'?'block':row.stateCodes.length>1?'multi-state':'state';
 let placeIds=[];
 if(scope==='district')placeIds=row.localityNames.map(name=>addPlace(name==='Kancheepuram'?'Kanchipuram':name,row.stateCodes[0],'district'));
 if(scope==='city')placeIds=[addPlace(row.stateCodes[0]==='KA'?'Bengaluru':'Chennai',row.stateCodes[0],'city',row.stateCodes[0]==='KA'?{aliases:['Bangalore']}:{})];
 if(scope==='block')placeIds=row.localityNames.filter(name=>name!=='Cuttack').map(name=>addPlace(name,'OD','block',{districtName:'Cuttack'}));
 const domains=domainsOf(row.domains);
 if(row.id==='wx-ngt-ennore-2024')domains.push('groundwater');
 const stages=row.id==='wx-agromet-cuttack-2025-07'?['seed','irrigation','growing']:domains.includes('farming')?['irrigation','growing','harvest']:domains.includes('drinking-water')||domains.includes('groundwater')?['distribution']:['growing','harvest'];
 const source={id:row.id,title:row.title,url:row.url,publisher:row.publisher,publishedAt:row.publishedAt,period:row.period.label,retrievedAt:row.retrieval.retrievedAt,type:isNews?'news':isPortal?'portal':'document',tier:isNews?'reported':'primary',...dimensions({scope,stateCodes:row.stateCodes,localityIds:placeIds,domains,stages}),summary:[row.summary,...row.supportedFacts].join(' '),limitations:row.limitations,windowStatus:classify(row.publishedAt),geographicLabel:row.id==='wx-agromet-cuttack-2025-07'?'Athagad and Badamba blocks, Cuttack district, Odisha':row.localityNames.length?`${row.geoscope}: ${row.localityNames.join(', ')}`:row.geoscope,retrievalStatus:`${row.retrieval.method}; extracted sections reviewed, full-document audit not claimed.`,locator:row.locator,...(row.temporalType==='historical-forecast'?{isForecast:true,...(row.issuedAt?{issuedAt:row.issuedAt}:{}),...(row.validFrom?{validFrom:row.validFrom}:{}),...(row.validUntil?{validUntil:row.validUntil}:{})}: {})};
 sources.push(source);
 for(const [index,item]of(row.observations??[]).entries())observations.push({id:`${row.id}-observation-${index+1}`,title:row.title,label:item.indicator.replaceAll('_',' '),summary:`${item.attribution}. ${row.id==='wx-nrsc-tn-inundation-2023'?'Total across the 10 listed districts; not a value for any single district. ':''}${item.qualifier??row.summary}`,...dimensionsOf(source),value:item.value,unit:item.unit,measure:item.indicator==='annual_rainfall'?'rainfall':'other',period:item.period,sourceIds:[row.id],limitations:row.limitations});
}
const sourceById=()=>Object.fromEntries(sources.map(source=>[source.id,source]));
const addDiscovery=(id,title,sourceId,summary,steps,availableGrains,overrides={})=>{
 const source=sourceById()[sourceId];if(!source)throw Error(`Discovery references unavailable source ${sourceId}`);
 discovery.push({id,title,summary,url:source.url,sourceIds:[sourceId],steps,availableGrains,...dimensionsOf(source),...overrides,limitations:['This is a retrieval route; no unexamined local values or current alerts are implied.',...source.limitations]});
};
const addLead=(id,title,sourceIds,signal,summary,attribution,alternatives,falsifier,overrides={})=>{
 const source=sourceById()[sourceIds[0]];if(!source)throw Error(`Lead references unavailable source ${sourceIds[0]}`);
 leads.push({id,title,sourceIds,signal,summary,attribution,kind:'analytic-question',alternativeExplanations:alternatives,falsifier,status:'investigate',...dimensionsOf(source),...overrides});
};
addDiscovery('climate-state-archive','Find the state’s climate statement','wx-imd-state-climate-archive','Choose a state and report year, then inspect rainfall, SPI and documented extreme-weather impacts.',['Choose state and year in the official archive.','Record the original release date separately from the observation year.','Retrieve station/district evidence before making a city or village claim.'],['state']);
addDiscovery('reservoir-storage','Trace reservoir storage through dated bulletins','wx-cwc-reservoir-archive','Reservoir observations complement rainfall evidence; the retrieved archive is historical.',['Select the dated weekly bulletin.','Match reservoir name, live capacity, storage unit and observation date.','Do not treat monitored reservoirs as all village tanks or groundwater sources.'],['state','project']);
addDiscovery('river-flood-forecast','Check the official river forecast','wx-cwc-flood-portal','Open the official portal for station-specific issued forecasts; none were ingested as live alerts.',['Select a river station.','Record issue time, valid horizon, gauge datum and warning threshold.','Check updated official local instructions before acting.'],['station']);
addLead('bengaluru-delivery','Bengaluru: separate water in the basin from water reaching households',['wx-bengaluru-shortage-2024','wx-bengaluru-bwssb-response-2024','wx-bengaluru-community-2024'],'March 2024 reporting quotes a 500 MLD shortfall; the utility separately describes basin reserves and peripheral borewell dependence.','Compare service boundaries, dates, piped reach and tanker deliveries before calling these statements contradictory.','Chief Minister and BWSSB chairman as reported by The Hindu; residents and institutions interviewed by Citizen Matters.',['Basin storage and local distribution measure different parts of the system.','Dates and drinking/non-drinking demand definitions differ.','Peripheral service coverage may explain shortages despite upstream reserves.'],'Resolve the apparent contradiction if same-date supply/demand boundaries and delivery records reconcile the figures and show the identified access gap was addressed.');
addLead('inundation-crop-loss','Tamil Nadu: mapped standing water is not a crop-loss census',['wx-nrsc-tn-inundation-2023','wx-tn-disaster-2023'],'NRSC mapped 148,360 hectares of inundation or standing water on 7 December 2023 with no ground verification.','Join acquisition dates and crop calendars with field damage assessments before estimating damaged hectares or compensation.','NRSC rapid mapping and the Tamil Nadu Gazette declaration.',['Some mapped water may be normal paddy water or temporary rain accumulation.','Flood peaks and satellite acquisition times differ.'],'Reject a crop-loss interpretation where field checks show normal paddy water, no crop damage or land outside the claimed crop area.');
addLead('ennore-quality-followup','Ennore: distinguish documented contamination from present safety',['wx-ngt-ennore-2024'],'A March 2024 technical assessment filed at NGT describes December 2023 oil contamination and affected open wells.','Trace later remediation, dated water/fish testing and official clearances at the same locations.','IIT Madras assessment filed with TNPCB; not a final court finding.',['Contamination intensity and persistence vary by location and sampling date.','Oil, oily sludge and water concentrations are different measures.'],'Close a current-exposure concern only when representative later tests at the affected sources meet applicable standards and remediation records resolve the documented pathways.');
addLead('imd-table-reconciliation','Reconcile climate tables before mapping drought classifications',['wx-imd-drought-2023','wx-imd-hydroclimate-2026-06'],'Fetched text contains a mismatched year caption and non-reconciling district-category totals.','Inspect the original rendered pages, document versions and table structure before promoting district values.','Observed extraction inconsistencies in two IMD document extracts.',['PDF text reading order can merge columns.','A reused caption or a different aggregation convention may explain the mismatch.'],'Close the discrepancy if original-page checks or a corrected official edition reconcile each table and its total.',{status:'context'});

// Food supply-chain sources and observations retain the grain and estimate vintage of each row.
if(food){
 for(const place of food.localities)addPlace(place.name,place.stateCode,place.kind);
 for(const row of food.sources){
  const places=food.localities.filter(place=>place.sourceIds.includes(row.id));
  const stateCodes=[...new Set([...row.stateCodes,...places.map(place=>place.stateCode)])];
  sources.push({id:row.id,title:row.title,url:row.url,publisher:row.publisher,publishedAt:row.publishedAt,period:row.period,retrievedAt:row.retrievedAt,type:row.type,tier:row.tier,...dimensions({scope:row.scope,stateCodes,localityIds:places.map(place=>place.id),domains:row.domains.filter(domain=>domain!=='water'),stages:row.stages}),summary:row.claims.join(' '),limitations:row.limitations,windowStatus:classify(row.publishedAt),retrievalStatus:row.retrievalStatus,locator:row.locator,geographicLabel:places.map(place=>`${place.name} (${place.kind}): ${place.coverage}`).join(' ')});
 }
 for(const row of food.observations){
  const source=sourceById()[row.sourceIds[0]];
  const measure=row.metric==='production'?'crop-production':['installed_capacity','storage_capacity'].includes(row.metric)?'storage-capacity':'other';
  observations.push({id:row.id,title:row.indicator,label:row.indicator,summary:`${row.grain}. ${row.estimateVersion??source.title}. Locator: ${row.locator}.`,...dimensions({scope:row.scope,stateCodes:row.stateCodes,localityIds:row.localityIds,domains:[row.domain],stages:[row.stage]}),value:row.value,unit:row.unit,measure,period:row.period,sourceIds:row.sourceIds,limitations:row.limitations});
 }
 for(const row of food.findings)addLead(row.id,row.title,row.sourceIds,row.finding,`${row.period}. Department/management response: ${row.response}`,'Comptroller and Auditor General of India; source-attributed audit finding, with the audited entity response retained.',row.alternativeExplanations,row.falsifier,{kind:'source-finding',scope:row.scope,stateCodes:row.stateCodes,localityIds:row.localityIds,domains:['tenders','food'],stages:row.stages});
 for(const row of food.cases)addLead(row.id,row.title,row.sourceIds,row.summary,`${row.period}. ${row.limitations.join(' ')}`,'Programme activity reported in DA&FW Annual Report 2024–25.',['Training activity does not establish later yields, income, water access or village-wide coverage.'],'Do not infer an impact unless matched follow-up measures establish outcomes for the same participants and period.',{kind:'methodology',status:'context',scope:row.scope==='multi-locality'?'village':row.scope,stateCodes:row.stateCodes,localityIds:row.localityIds,domains:['farming'],stages:row.stages});
 addDiscovery('seed-traceability','Trace a seed batch through SATHI','wf-sathi','Follow batch, certification and licensing records before attributing field outcomes to seed quality.',['Identify the label, lot and seed generation.','Match producer, laboratory/certification record and sale entry.','Check variety-specific adaptation advice; a traceable batch does not guarantee a yield.'],['state','project']);
 addDiscovery('market-arrivals','Find market arrivals and prices','wf-enam','Query a dated commodity and market observation; crop output and market arrivals are different indicators.',['Choose state, district, APMC, commodity and observation date.','Record market unit, variety/grade, arrival quantity and modal price separately.','Treat missing market reports as missing, not zero.'],['state','district','market']);
 addDiscovery('agmarknet-daily','Cross-check a daily market report','wf-agmarknet','Inspect prices and arrivals using the official commodity-wise daily report.',['Select commodity and market.','Preserve report date, unit and price/arrival mode.','Cross-check the reporting period and compare like varieties and grades.'],['state','district','market']);
 addDiscovery('food-procurement-storage','Trace foodgrain procurement, stocks and offtake','wf-fci-dashboard','Use separately dated operational measures across procurement, storage and distribution.',['Select crop/marketing season and operational measure.','Preserve stocks, capacity, procurement, allocation and offtake as distinct fields.','Seek depot or fair-price-shop delivery records for local access questions.'],['state','project']);
 addLead('fertilizer-geography','Fertilizer subsidy: do not invent a state allocation from national payments',['wf-fertilizer'],'The 2026 parliamentary answer says company subsidy is based on authenticated retail sales and state/district disbursement figures are not maintained.','Trace local supply and retail transactions using their actual grain; do not allocate the national subsidy using a state production proxy.','Ministry of Chemicals & Fertilizers, Lok Sabha answer of 7 August 2026.',['Company payment location differs from farmer purchase location.','Physical supply, retail sale and subsidy settlement have different cutoffs.'],'Resolve a local subsidy claim only with a documented transaction-to-beneficiary allocation method and reconciled matching-period records.',{kind:'methodology',status:'context'});
 addLead('production-market-gap','Crop production and mandi arrivals describe different flows',['wf-crop-table','wf-enam','wf-agmarknet'],'Crop tables describe production; reporting markets separately measure arrivals and trade.','Before calling a production–arrival gap a loss, account for retained grain, non-reporting markets, inter-state trade, timing and units.','Analytical comparison rule based on the definitions in official crop and market records.',['Farm retention and direct sales do not pass through a reporting mandi.','Marketing years and harvest periods differ.','Storage and inter-state movements change the destination and timing of arrivals.'],'Reject a loss claim when matched crop-year material balances and all documented outlets reconcile the apparent gap.',{domains:['farming','food'],stages:['harvest','market','storage']});
}

// Public-water observations retain the source's administrative/survey/programme denominators.
if(publicWater){
 const placeMap={};
 for(const place of publicWater.localities){
  const existing=localities.find(item=>item.name===place.name&&item.stateCode===place.stateCode&&item.kind===place.kind);
  placeMap[place.id]=existing?.id??place.id;
  if(!existing)localities.push({id:place.id,name:place.name,stateCode:place.stateCode,kind:place.kind,...(place.district?{districtName:place.district}:{})});
 }
 for(const row of publicWater.sources){
  const places=publicWater.localities.filter(place=>place.sourceIds.includes(row.id));
  const codes=[...new Set([...row.stateCodes,...places.map(place=>place.stateCode)])];
  const groundwater=['wp-cgwb-2025','wp-cgwb-repository'].includes(row.id);
  const crossWater=['wp-india-wris','wp-nwic-data'].includes(row.id);
  const domains=groundwater?['groundwater']:crossWater?['drinking-water','groundwater','farming']:row.domain==='tenders'?['tenders','drinking-water']:row.id==='wp-cag-karnataka'?['drinking-water','tenders']:['drinking-water'];
  const stages=groundwater||crossWater?['irrigation','distribution']:['distribution'];
  sources.push({id:row.id,title:row.title,url:row.url,publisher:row.publisher,publishedAt:row.publishedAt,period:row.period,retrievedAt:row.retrievedAt,type:['portal','dataset','discussion','news'].includes(row.type)?row.type:'document',tier:row.tier,...dimensions({scope:row.scope,stateCodes:codes,localityIds:places.map(place=>placeMap[place.id]),domains,stages}),summary:row.claims.join(' '),limitations:row.limitations,windowStatus:classify(row.publishedAt),retrievalStatus:row.retrievalStatus,locator:row.locator,geographicLabel:row.geographicScope});
 }
 for(const row of publicWater.observations){
  const isGroundwater=row.measure==='groundwater';
  const measure=row.id.endsWith('-regularityPct')?'supply-regularity':row.id.endsWith('-quantityAtLeast55LpcdPct')?'supply-quantity':row.measure==='tap-connection'?'household-connections':isGroundwater?(/extraction/.test(row.id)&&row.unit!=='assessment units'?'groundwater-extraction':row.unit==='BCM'?'groundwater-resource':'other'):row.measure;
  observations.push({id:row.id,title:row.indicator,label:row.indicator,summary:`${row.grain}. ${row.denominator?`Denominator: ${row.denominator}. `:''}Locator: ${row.locator}.`,...dimensions({scope:row.scope,stateCodes:row.stateCodes,localityIds:row.localityIds.map(id=>placeMap[id]),domains:isGroundwater?['groundwater']:['drinking-water'],stages:isGroundwater?['irrigation','distribution']:['distribution']}),value:row.value,unit:row.unit,measure,period:row.period,sourceIds:row.sourceIds,limitations:row.limitations,...(row.denominator?{denominatorLabel:row.denominator}:{}),...(row.asOf?{asOf:row.asOf}:{})});
 }
 for(const row of publicWater.findings){
  const kind=row.tier==='documented audit finding'?'source-finding':'analytic-question';
  const domains=row.domain==='tenders'?['tenders','drinking-water']:row.id==='wp-groundwater-stress'?['groundwater','farming']:['drinking-water'];
  addLead(row.id,row.title,row.sourceIds,row.finding,`${row.period}. Source / government response: ${row.response} ${row.limitations.join(' ')}`,kind==='source-finding'?'Comptroller and Auditor General of India; historical audit finding with government response retained.':'Analytical review question based on the cited official definitions and records.',row.alternativeExplanations,row.falsifier,{kind,scope:row.scope,stateCodes:row.stateCodes,localityIds:row.localityIds.map(id=>placeMap[id]),domains,stages:row.id==='wp-groundwater-stress'?['irrigation','distribution']:['distribution']});
 }
 addDiscovery('village-water-profile','Find a village water profile','wp-jjm-village','Resolve the state, district and village before inspecting programme status or water-quality reports.',['Choose state, district/subdistrict and the correct village identity.','Record reported and certified Har Ghar Jal status separately.','Seek commissioned-work, service-frequency, quantity and dated quality-test records; a connection alone is insufficient.'],['state','district','village']);
 addDiscovery('rural-water-admin','Trace rural tap-connection reporting','wp-jjm-dashboard','Use dated administrative records while preserving rural and PWS-village denominators.',['Choose a geography and capture the report date.','Keep household count, PWS coverage, reported completion and certification separate.','Do not interpret an empty dynamic page as zero coverage.'],['state','district','village']);
 addDiscovery('groundwater-local','Find the local groundwater assessment','wp-cgwb-repository','Use the actual assessment unit and aquifer report to place national statistics in local context.',['Search state/district and choose the relevant assessment year.','Record block/tehsil/aquifer boundaries and the extraction-stage definition.','Inspect quality separately; an extraction category called safe is not a drinking-water clearance.'],['state','district','block']);
 addDiscovery('water-quality-tests','Trace water-quality tests and remediation','wp-wqmis','Find dated, parameter-specific samples and follow-up action instead of treating connection counts as quality evidence.',['Choose the geography, laboratory/report type and sample period.','Preserve water-point identity, contaminant, threshold and test method.','Retrieve remedial-action and retest records for the same point.'],['state','district','village']);
 addDiscovery('water-spatial-data','Find station, basin and water-resource data','wp-india-wris','Explore official spatial and time-series records with their station and basin metadata.',['Open India-WRIS through the official system link.','Select parameter, station/basin and time range.','Check datum, gaps and geographic compatibility before combining with local service records.'],['state','district','station'],{url:'https://indiawris.gov.in/wris/#/'});
 addDiscovery('water-tender-trace','Trace a water tender through procurement stages','wp-cppp-search','Search official notices, then independently establish award, payment and commissioned output.',['Search organisation, water-work description, dates and tender ID.','Retain corrigenda, cancelled/re-tendered notices and the eventual award record.','Link contract payments and completion/service records before interpreting delay or cost.'],['state','district','city','village','project']);
 addDiscovery('gem-water-bids','Check GeM bids for a dated procurement record','wp-gem-bids','Use the official bid route as discovery, without treating a search result as a contract or payment.',['Find the bid identifier and procuring organisation.','Check item specification, delivery location, amendments and dates.','Obtain the award and delivery/payment evidence separately.'],['state','district','project']);
}


const output={updatedAt:'2026-10-06',window,methodology:[
 'The requested evidence-release window is 6 October 2021 to 6 October 2026, inclusive. Original publication date, observation period and retrieval date are separate fields. Older methodology is background; an undated portal does not acquire the retrieval date as its publication date.',
 'This curated desk is a bounded research collection, not a census of every city, village, tender or food-chain event. Official discovery tools provide routes for local follow-up without claiming those records have been extracted.',
 'Rainfall is not an administrative drought declaration. Household tap connections do not establish regularity, quantity or drinking-water quality. Satellite standing water is not automatically crop damage.',
 'Tender estimated value, contract award, payment and completed delivery are distinct stages. Crop production is not market arrival, and storage capacity is not stock held.',
 'National context can remain visible under a state filter. Place searches require an explicit place reference. City, district, block and village grains are kept separate; values are not distributed to smaller areas.',
 'Forecast issue and validity times must be explicit. Historical or expired bulletins are not live warnings, and forecasts are not evidence that the predicted event occurred.',
 ],coverageNotes:[
 'All 36 states and union territories are selectable. A selectable geography is not proof of complete local evidence coverage.',
 `${sources.length} curated source records: ${sources.filter(source=>source.windowStatus==='in-window').length} dated inside the requested window, ${sources.filter(source=>source.windowStatus==='undated').length} with unconfirmed release dates, and ${sources.filter(source=>source.windowStatus==='background').length} background records.`,
 'Numeric water coverage includes 34 rural state/UT administrative snapshots, 34 states/UTs plus India in the 2024 sample-based service table, and 15 selected AMRUT urban local bodies. Delhi and Chandigarh have no imputed rural values.',
 'City programme counts, sampled service measures, national crop figures and selected state output are separate series; no complete city or village inventory is claimed.',
 'No live weather alert, automated drought verdict, village water-safety clearance or corruption risk score is produced.',
 ],states,localities,sources,observations,discovery,leads};
writeFileSync(`${root}src/data/water-research.json`,`${JSON.stringify(output,null,2)}\n`);
console.log(`Water desk: ${sources.length} sources, ${observations.length} observations, ${discovery.length} discovery routes, ${leads.length} leads. Public-water payload ${publicWater?'present':'pending'}; food payload ${food?'present':'pending'}.`);
