#!/usr/bin/env node
/** A real money-trail workflow: map → case → typed edge → source/response → portable packet. */
import assert from 'node:assert/strict';
import { existsSync, mkdirSync, readFileSync } from 'node:fs';
import { createServer } from 'node:http';
import { extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import { build } from 'esbuild';
const root = fileURLToPath(new URL('../../', import.meta.url));
const dist = resolve(root, process.env.INVESTIGATION_DIST ?? 'dist');
const out = resolve(process.env.DEEP_INVESTIGATION_ARTIFACTS ?? '/tmp/follow-the-money-review');
mkdirSync(out, { recursive: true });
const bundle = await build({ entryPoints: [resolve(root, 'src/data/deepInvestigation.ts')], bundle: true, platform: 'node', format: 'cjs', write: false, logLevel: 'silent' });
const module = { exports: {} }; new Function('module', 'exports', bundle.outputFiles[0].text)(module, module.exports);
const api = module.exports;
assert.ok(api.DEEP_INVESTIGATION_CASES.length > 0, 'Browser acceptance requires researched casefiles, not fixtures.');
const fixture = api.DEEP_INVESTIGATION_CASES.find(row => api.getDeepInvestigationCaseEvidence(row.id).relationships.some(edge => edge.sourceIds.length && edge.from !== edge.to));
assert.ok(fixture, 'At least one researched case must have a sourced typed edge.');
const evidence = api.getDeepInvestigationCaseEvidence(fixture.id);
const edge = evidence.relationships.find(row => row.sourceIds.length && row.from !== row.to);
const originalSource = evidence.sources.find(row => edge.sourceIds.includes(row.id));
const mime = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.svg': 'image/svg+xml', '.woff2': 'font/woff2' };
const server = createServer((req, res) => { const path = new URL(req.url, 'http://localhost').pathname; const file = resolve(dist, `.${path === '/' ? '/index.html' : path}`); if (!file.startsWith(`${dist}/`)) return res.writeHead(403).end(); try { res.writeHead(200, { 'content-type': mime[extname(file)] ?? 'application/octet-stream' }).end(readFileSync(file)); } catch { res.writeHead(404).end(); } });
let base = process.env.INVESTIGATION_BASE_URL; let listening = false;
if (!base) { await new Promise(done => server.listen(0, '127.0.0.1', done)); listening = true; base = `http://127.0.0.1:${server.address().port}`; }
const binary = process.env.PLAYWRIGHT_CHROMIUM_PATH ?? '/usr/bin/chromium';
const browser = await chromium.launch(existsSync(binary) ? { executablePath: binary } : {});
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
const errors = []; page.on('pageerror', error => errors.push(error.message));
let checks = 0; const ok = (value, message) => { assert.ok(value, message); checks++; console.log(`PASS ${message}`); };
const params = () => new URLSearchParams(new URL(page.url()).hash.split('?')[1]);
async function go(query = '') { await page.goto(`${base}/#/follow-the-money${query}`); await page.locator('[data-follow-the-money]').waitFor({ timeout: 60000 }); await page.waitForFunction(({caseId, query}) => document.querySelector('[data-follow-the-money]')?.getAttribute('data-case-id') === caseId && document.querySelector('#fm-query')?.value === query, { caseId: new URLSearchParams(query).has('ftm_case') ? (api.getDeepInvestigationCase(new URLSearchParams(query).get('ftm_case'))?.id ?? '') : api.DEEP_INVESTIGATION_CASES[0].id, query: new URLSearchParams(query).get('ftm_q') ?? '' }); await page.evaluate(() => document.fonts.ready); }
try {
 await go();
 ok(await page.locator('.fm-case-brief h2').textContent() === api.DEEP_INVESTIGATION_CASES[0].title, 'Fresh research case is open immediately on the dedicated route');
 ok(await page.locator('[data-investigation-workspace]').count() === 0, 'New route is a dedicated atlas without the generic workspace hiding it');
 await page.screenshot({ path: resolve(out, 'atlas-1440.png') });
 await go(`?ftm_case=${encodeURIComponent(fixture.id)}&legacy_parameter=retained&iw_state=KA`);
 await page.getByLabel('State or union territory', { exact: true }).selectOption('UP');
 ok(params().get('legacy_parameter') === 'retained' && params().get('iw_state') === 'KA' && params().get('ftm_state') === 'UP', 'Map interaction preserves existing route and workspace parameters');
 await page.goBack();
 await page.waitForFunction(() => !new URLSearchParams(location.hash.split('?')[1]).has('ftm_state') && document.querySelector('.iw-map-select select')?.value === 'KA');
 ok(await page.getByLabel('State or union territory', { exact: true }).inputValue() === 'KA', 'Browser Back restores carried geographic scope');
 const scoped = api.getDeepInvestigationDiscovery({ stateCode: 'KA', includeNational: true, geographyMode: 'all' });
 const scopedCount = scoped.entities.length + scoped.records.length + scoped.relationships.length;
 await page.waitForFunction(expected => document.querySelector('.fm-result-count')?.textContent?.startsWith(expected), scopedCount.toLocaleString('en-IN'));
 ok((await page.locator('.fm-coverage-note').innerText()).includes('Karnataka plus national context'), 'Evidence discovery respects selected geography and makes national context explicit');
 await go(`?ftm_case=${encodeURIComponent(fixture.id)}&ftm_edge=${encodeURIComponent(edge.id)}`);
 await page.locator(`[data-inspected-id="${edge.id}"]`).waitFor();
 ok((await page.locator('.fm-inspector').innerText()).includes(edge.kind.replace(/[-_]/gu, ' ')), 'Typed edge inspection retains relationship kind and direction');
 const sourceLink = page.locator('.fm-inspector .fm-sources').getByRole('link', { name: 'Open cited source', exact: false }).first();
 ok(await sourceLink.getAttribute('href') === originalSource.url, 'Source link opens the exact retained cited URL');
 await page.locator('.fm-inspector .fm-sources .fm-text-button').first().click();
 await page.locator(`[data-source-id="${originalSource.id}"]`).waitFor();
 ok((await page.locator('.fm-source-detail').innerText()).includes(originalSource.locator), 'Source inspection retains exact source locator');
 await page.getByRole('button', { name: 'Return to selected evidence', exact: true }).click();
 await page.locator('.fm-endpoints').waitFor();
 ok(await page.locator('.fm-endpoints').isVisible(), 'Source back returns to the selected typed relationship');
 const downloaded = page.waitForEvent('download'); await page.getByRole('button', { name: 'Evidence JSON', exact: true }).click();
 const packet = JSON.parse(readFileSync(await (await downloaded).path(), 'utf8'));
 const sourceIds = new Set(packet.sources.map(row => row.id));
 ok(packet.records.some(row => row.id === fixture.id) && packet.relationships.some(row => row.id === edge.id), 'Case export retains the selected case and exact typed edges');
 ok([...packet.entities, ...packet.relationships, ...packet.records].every(row => [...row.sourceIds, ...row.geography.flatMap(geo => geo.sourceIds)].every(id => sourceIds.has(id))), 'Evidence export closes entity, edge, record and independent geographic sources');
 const responseIds = packet.relationships.flatMap(row => row.responseIds);
 ok(responseIds.every(id => packet.records.some(row => row.id === id) || packet.relationships.some(row => row.id === id)), 'Case export retains every linked response outside display filters');
 await page.getByRole('button', { name: 'Save evidence', exact: true }).click();
 await page.getByRole('button', { name: /^Casebook/ }).click();
 await page.getByRole('textbox', { name: 'Question or hypothesis', exact: true }).fill('Which source closes this exact money stage?');
 await page.reload(); await page.locator('[data-follow-the-money]').waitFor({ timeout: 90000 }); await page.getByRole('textbox', { name: 'Question or hypothesis', exact: true }).waitFor();
 ok(await page.getByRole('textbox', { name: 'Question or hypothesis', exact: true }).inputValue() === 'Which source closes this exact money stage?', 'Shared casebook preserves analyst notes across reload');
 await go();
 await page.locator('#fm-query').fill('zzzz_no_matching_evidence');
 await page.locator('.fm-search').getByRole('button', { name: 'Search', exact: false }).click();
 await page.getByRole('heading', { name: 'No matching evidence', exact: true }).waitFor();
 ok(params().get('ftm_q') === 'zzzz_no_matching_evidence', 'Search has a source-honest zero state and URL state');
 await page.goBack(); await page.waitForFunction(() => document.querySelector('#fm-query')?.value === '');
 ok(!params().has('ftm_q'), 'Back restores both submitted query and search draft');
 const unmatched = api.DEEP_INVESTIGATION_UNIVERSE.securities.find(row => row.registryEntityIds.length === 0);
 await go(`?ftm_scope=securities&ftm_q=${encodeURIComponent(unmatched.isin)}`);
 await page.locator('.fm-security-list>li').filter({ hasText: unmatched.isin }).waitFor();
 ok(await page.locator('.fm-security-list>li').count() === 1 && (await page.locator('.fm-security-list').innerText()).includes('No verified registry join'), 'Exact ISIN search exposes unmatched listing without inventing connections');
 ok(await page.locator('.fm-security-list button').count() === 0, 'Unmatched security does not offer a falsely joined graph');
 const matched = api.DEEP_INVESTIGATION_UNIVERSE.securities.find(row => row.registryEntityIds.length > 0);
 await go(`?ftm_scope=securities&ftm_q=${encodeURIComponent(matched.isin)}`);
 await page.locator('.fm-security-list button').first().click();
 await page.locator(`[data-inspected-id="${matched.registryEntityIds[0]}"]`).waitFor();
 ok(params().get('ftm_node') === matched.registryEntityIds[0], 'Verified ISIN match selects the exact canonical entity');
 const outsideCase = api.DEEP_INVESTIGATION_CASES.find(row => row.id !== fixture.id && api.getDeepInvestigationCaseEvidence(row.id).relationships.length);
 const outsideEdge = api.getDeepInvestigationCaseEvidence(outsideCase.id).relationships.find(row => row.from !== row.to);
 await go(`?ftm_case=${encodeURIComponent(fixture.id)}&ftm_edge=${encodeURIComponent(outsideEdge.id)}`);
 await page.locator(`.iw-graph-edge[data-relationship-id="${outsideEdge.id}"]`).waitFor();
 ok(await page.locator(`.iw-graph-node[data-entity-id="${outsideEdge.from}"]`).count() > 0 && await page.locator(`.iw-graph-node[data-entity-id="${outsideEdge.to}"]`).count() > 0, 'Outside-case relationship inspection changes the graph to the exact artifact and its endpoints');
 ok((await page.locator('.fm-network-export-note').innerText()).includes('excludes linked response and record content'), 'CSV scope is explicitly distinguished from full evidence packets');
 await go(`?ftm_case=${encodeURIComponent(fixture.id)}&ftm_record=${encodeURIComponent(outsideCase.id)}`);
 await page.locator(`[data-inspected-id="${outsideCase.id}"]`).waitFor();
 await page.locator(`.iw-graph-edge[data-relationship-id="${outsideEdge.id}"]`).waitFor();
 ok(params().get('ftm_record') === outsideCase.id && params().get('ftm_case') === fixture.id, 'Outside-case record deep link restores its graph without rewriting the selected case URL');
 await go(`?ftm_case=${encodeURIComponent(fixture.id)}&ftm_node=${encodeURIComponent(edge.from)}&ftm_edge=${encodeURIComponent(outsideEdge.id)}`);
 await page.locator(`.iw-graph-edge[data-relationship-id="${outsideEdge.id}"]`).waitFor();
 ok(await page.locator('.iw-graph-node.is-selected').count() === 0 && params().get('ftm_node') === edge.from, 'Explicit artifact takes graph precedence over an old node parameter while preserving the shared URL');
 await go('?ftm_case=unavailable&ftm_source=unavailable');
 ok(await page.getByRole('heading', { name: 'This casefile is not in the current snapshot.', exact: true }).isVisible(), 'Unavailable shared case is explicit and recoverable');
 for (const width of [768, 390, 320]) {
  await page.setViewportSize({ width, height: 950 });
  await go(`?ftm_case=${encodeURIComponent(fixture.id)}`);
  ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${width}px atlas has no horizontal page overflow`);
  await page.getByLabel('State or union territory', { exact: true }).focus();
  ok(await page.getByLabel('State or union territory', { exact: true }).evaluate(node => node === document.activeElement), `${width}px map has a keyboard-accessible equivalent selector`);
  await page.locator('.iw-map-state[tabindex="0"]').focus(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter');
  await page.waitForFunction(() => !!new URLSearchParams(location.hash.split('?')[1]).get('ftm_state'));
  ok(!!params().get('ftm_state'), `${width}px map geometry supports keyboard state selection`);
  await page.screenshot({ path: resolve(out, `atlas-${width}.png`) });
  await go(`?ftm_case=${encodeURIComponent(fixture.id)}&ftm_edge=${encodeURIComponent(edge.id)}`);
  await page.locator('.fm-inspector').scrollIntoViewIfNeeded();
  ok(await page.locator('.fm-inspector').isVisible() && await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${width}px exact edge inspector remains readable without overflow`);
  await page.screenshot({ path: resolve(out, `inspection-${width}.png`) });
 }
 await page.emulateMedia({ reducedMotion: 'reduce' });
 await go(`?ftm_case=${encodeURIComponent(fixture.id)}`);
 ok(await page.locator('.fm-case-list button').first().evaluate(node => getComputedStyle(node).transitionDuration.split(',').every(value => Number.parseFloat(value) <= 0.000011)), 'Reduced-motion transitions obey the global 0.01 ms safeguard');
 ok(errors.length === 0, `No browser runtime exceptions: ${errors.join(' | ')}`);
 console.log(JSON.stringify({ passed: true, checks, artifacts: out }));
} catch (error) { await page.screenshot({ path: resolve(out, 'failure.png'), fullPage: true }); console.error(JSON.stringify({ passed: false, checks, url: page.url(), message: error.message, errors, casebooks: await page.locator('.fm-book').count(), textareas: await page.locator('textarea').count(), tail: (await page.locator('body').innerText()).slice(-1200) })); throw error; }
finally { await browser.close(); if (listening) await new Promise(done => server.close(done)); }
