import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {loadDeepInvestigation} from './load.mjs';
import {loadInvestigation} from '../investigation/load.mjs';
import {validateDeepInvestigation,validateDeepSlice,validateUniverse,DEEP_SLICES} from './validate.mjs';
const api=await loadDeepInvestigation(),{INVESTIGATION_REGISTRY:registry,isInvestigationConnectivityEdge}=await loadInvestigation();

test('all research slices integrate with archive and identity integrity',async()=>{assert.deepEqual(await validateDeepInvestigation(),[]);for(const name of DEEP_SLICES)assert.ok(api.DEEP_INVESTIGATION_CASES.some(row=>row.namespace===`deep-${name}`));});
test('NSE security universe is explicitly separate from investigated cases and exact company coverage',()=>{const u=api.DEEP_INVESTIGATION_UNIVERSE;assert.ok(u.totalSecurities>2500);assert.equal(u.totalSecurities,u.securities.length);assert.ok(u.matchedRegistryCompanies<u.totalSecurities);assert.ok(u.reviewedCases<u.matchedRegistryCompanies);assert.ok(u.heldCandidates.some(row=>row.reason==='symbol-match-isin-conflict'));assert.ok(u.heldCandidates.some(row=>row.reason==='symbol-only-missing-isin'));assert.equal(u.securities.filter(row=>row.registryEntityIds.length).length,u.matchedRegistryCompanies);assert.deepEqual(validateUniverse(u,registry),[]);});
test('a similar name or matching symbol cannot create a legal-identity merge',()=>{const u=structuredClone(api.DEEP_INVESTIGATION_UNIVERSE),unmatched=u.securities.find(row=>!row.registryEntityIds.length),matched=u.securities.find(row=>row.registryEntityIds.length);unmatched.registryEntityIds=[...matched.registryEntityIds];unmatched.matchBasis='exact-isin';assert.ok(validateUniverse(u,registry).some(error=>error.includes('unsupported company identity join')));});
test('case evidence retains every case reference, source and linked response without a graph display cap',()=>{for(const record of api.DEEP_INVESTIGATION_CASES){const closure=api.getDeepInvestigationCaseEvidence(record.id),entities=new Set(closure.entities.map(row=>row.id)),edges=new Set(closure.relationships.map(row=>row.id)),records=new Set(closure.records.map(row=>row.id)),sources=new Set(closure.sources.map(row=>row.id));assert.equal(closure.truncated,false);assert.equal(closure.record.id,record.id);for(const id of record.entityIds)assert.ok(entities.has(id));for(const id of record.relationshipIds)assert.ok(edges.has(id));for(const edge of closure.relationships){assert.ok(entities.has(edge.from));assert.ok(entities.has(edge.to));for(const id of edge.responseIds)assert.ok(records.has(id));}for(const row of [...closure.entities,...closure.relationships,...closure.records])for(const id of [...row.sourceIds,...row.geography.flatMap(geo=>geo.sourceIds)])assert.ok(sources.has(id));}});
test('missing case and entity identifiers return explicit empty closures',()=>{assert.equal(api.getDeepInvestigationCase('missing'),undefined);assert.equal(api.getDeepInvestigationCaseEvidence('missing').record,undefined);assert.equal(api.getDeepInvestigationConnections('missing').relationships.length,0);assert.equal(api.getDeepInvestigationComponent('missing').entities.length,0);});
test('complete direct connection ledger contains every retained incident edge and does not count contextual case edges as direct',()=>{const entity=registry.entities.find(row=>registry.relationships.filter(edge=>edge.from===row.id||edge.to===row.id).length>30);assert.ok(entity);const expected=registry.relationships.filter(edge=>edge.from===entity.id||edge.to===entity.id);const result=api.getDeepInvestigationConnections(entity.id),ids=new Set(result.relationships.map(row=>row.id));for(const edge of expected)assert.ok(ids.has(edge.id));assert.equal(result.totalRelationships,expected.length);assert.ok(result.relationships.every(edge=>edge.from===entity.id||edge.to===entity.id));assert.equal(result.truncated,false);assert.ok(result.evidenceClosure.relationships.length>=result.relationships.length);});
test('full component uses exact retained endpoints and preserves source-bearing contra edges as evidence only',()=>{const entity=registry.entities.find(row=>row.namespace==='deep-procurement');assert.ok(entity);const closure=api.getDeepInvestigationComponent(entity.id);assert.equal(closure.truncated,false);const ids=new Set(closure.entities.map(row=>row.id));for(const edge of closure.relationships){assert.ok(ids.has(edge.from));assert.ok(ids.has(edge.to));assert.ok(registry.relationships.some(row=>row.id===edge.id));}assert.equal(isInvestigationConnectivityEdge({...registry.relationships[0],kind:'contra'}),false);});
test('raw case contract rejects missing falsifiers, responses and money stages',()=>{const raw=JSON.parse(readFileSync('research/raw/deep-investigation/procurement.json','utf8')),record=raw.records.find(row=>row.kind==='investigation-case');delete record.falsifier;delete record.response;record.amounts=[{value:10,currency:'INR',unit:'crore',period:'2024'}];const errors=validateDeepSlice(raw,'procurement');assert.ok(errors.some(error=>error.includes('response, alternative and falsifier')));assert.ok(errors.some(error=>error.includes('amount requires')));});
test('retained corpus discovery retains its full denominator and never labels inherited edges newly verified',()=>{const result=api.getDeepInvestigationDiscovery({q:'loan'});assert.ok(result.records.length);assert.equal(result.denominator.records,registry.records.length);assert.match(result.interpretation,/not all been freshly verified/);assert.ok(api.DEEP_INVESTIGATION_COVERAGE.relationshipKinds.some(row=>row.kind==='loan'));assert.equal(api.DEEP_INVESTIGATION_COVERAGE.retainedRelationships,registry.relationships.length);});
test('withdrawn inherited award retains its saved record and correction without a drawable edge',()=>{const old='8bbbf271af4f5617|aurobindo|award|mnre',record=registry.records.find(row=>row.id===`legacy:record:${old}`);assert.ok(record);assert.equal(record.kind,'withdrawn-correction');assert.equal(record.status,'withdrawn-claim');assert.equal(record.relationshipIds.length,0);assert.ok(!registry.relationships.some(row=>row.id===`legacy:relationship:${old}`));assert.ok(record.sourceIds.some(id=>registry.sources.find(source=>source.id===id)?.url.includes('PRID=1691185')));});
