"""Build three bounded public defence-contract paths; no cash settlement inferred."""
import json,pathlib
B=pathlib.Path(__file__).resolve().parent
out={'sources':[],'entities':[],'relationships':[],'records':[],'localities':[]}
DOMAIN=['defence-trade','security','public-finance']
ROUTE='/defence-trade'
def geo(codes,src):
    return [{'scope':'country','countryCodes':codes,'stateCodes':[],'localityIds':[],'basis':'country-context','note':'Public contracting, supplier-country or intergovernmental context only; not beneficial ownership, cash destination or operational deployment.','sourceIds':src}]
def dim(src,codes,layers):
    return dict(domains=DOMAIN,layers=layers,geography=geo(codes,src),route=ROUTE,sourceIds=src,limitations=[])
def source(i,title,url,pub,date,locator,summary,tier='documented',limits=[]):
    out['sources'].append(dict(id=i,title=title,url=url,publisher=pub,publishedAt=date,retrievedAt='2026-10-07',locator=locator,summary=summary,tier=tier,limitations=limits))
def entity(i,label,typ,src,codes,summary,basis,canonical=None):
    row=dict(id=i,label=label,type=typ,resolved=True,identityBasis=basis,summary=summary,**dim(src,codes,['organisations']))
    if canonical:row['canonicalId']=canonical
    out['entities'].append(row)
def amount(v,c,u,s,p):return dict(value=v,currency=c,unit=u,stage=s,period=p)
def edge(i,a,b,kind,label,summary,src,codes,case,date=None,tier='documented',amounts=[],status='source-retained',limits=[],response=None):
    row=dict(id=i,**{'from':a,'to':b},kind=kind,label=label,summary=summary,tier=tier,status=status,statusAsOf=date,fromDate=None,toDate=None,dateBasis='Source/status date only unless an exact event date is separately stated; no one-day affiliation or continuing contract is inferred.',alternativeExplanations=['Ordinary public procurement, industrial participation or stated intergovernmental cooperation explains this link; no corruption or improper influence is asserted.'],falsifier='A corrected original contract, government release, manufacturer delivery ledger or legal-entity record contradicting the named parties or stage would require correction.',responseIds=[response] if response else [],recordIds=[case],amounts=amounts,**dim(src,codes,['procurement'] if kind not in ['jurisdiction','partner','member','agency'] else ['organisations']))
    row['limitations']=limits;out['relationships'].append(row);return row
def record(i,title,summary,src,codes,entities,edges,period,start,end,status,reply,limits,tier='documented',kind='investigation-case'):
    out['records'].append(dict(id=i,title=title,summary=summary,kind=kind,tier=tier,status=status,statusAsOf=end,fromDate=start,toDate=end,dateBasis='Exact dated events bound the investigation; undated corporate history and forecast dates are separately labelled. Publication date is not automatically an event date.',entityIds=entities,relationshipIds=edges,period=period,response=reply,alternativeExplanations=['These are disclosed procurement and industrial arrangements; a contract value is not evidence of a bribe, a supplier receipt or a public loss.'],falsifier='Original amendments, actual payment records or corrected delivery/acceptance documents could revise these stages; specific corruption requires separate decision/payment evidence.',amounts=[],**{**dim(src,codes,['procurement','funding','organisations']), 'limitations':limits}))

source('c295-contract-2021','MoD signs contract with Airbus for 56 C-295MW aircraft','https://www.pib.gov.in/PressReleasePage.aspx?PRID=1757634','Ministry of Defence / PIB','2021-09-24','Contract announcement and separate offset-contract paragraph','Airbus Defence and Space S.A., Spain, is the contracting vendor; 16 flyaway and 40 Indian-built aircraft; offset contract also signed.',limits=['The release does not state the contract price, Tata receipt split or offset settlement.'])
source('c295-project-2022-normal','C-295 Indian manufacture: project cost and named Tata consortium','https://www.pib.gov.in/PressReleasePage.aspx?PRID=1871267','Ministry of Defence / PIB','2022-10-27','Paragraphs beginning It may be recalled and Addressing a press conference','INR21,935crore total project cost; Indian Aircraft Contractor is TASL-led consortium of TASL and TCS; same September2021 contract.',limits=['Project cost is not a TASL award or receipt; consortium participation is not a new legal JV or ownership percentage.'])
source('c295-first-2023','Airbus delivers first C295 to India','https://www.airbus.com/en/newsroom/press-releases/2023-09-airbus-delivers-first-c295-to-india','Airbus','2023-09-13','Opening delivery announcement and 16/40 manufacturing split','Manufacturer announces first delivery to IAF on13September2023.',limits=['Manufacturer announcement; no acceptance certificate or payment receipt retained.'])
source('c295-fal-2024','TASL and Airbus inaugurate C295 final assembly line','https://www.airbus.com/en/newsroom/press-releases/2024-10-tata-advanced-systems-and-airbus-inaugurate-c295-final-assembly-line-vadodara-india','Airbus','2024-10-28','Opening and six-delivered / first-rollout schedule paragraphs','Public final assembly line inauguration, six aircraft already delivered; first local rollout planned September2026.',limits=['Inauguration and target dates do not establish that the first local delivery occurred.'])
source('c295-count-2026','Airbus military aircraft orders and deliveries to 30June2026','https://mediaassets.airbus.com/pm_38_916_916227-fbdjtmjdm1.pdf?fileName=military-aircraft-orders-and-deliveries-jun-2026.pdf','Airbus',None,'p1, snapshot to30June2026, Asia and Pacific India row, C295 Ord/Del columns','India has56 C295 orders and16 deliveries in the manufacturer cumulative table.',limits=['Monthly snapshot not proof of a post-June delivery. In-operation column is not mapped to unit readiness or deployment.'])
source('brahmos-jv','BrahMos: inception, partners and 2014 IGA extension','https://www.brahmos.com/about-jv','BrahMos Aerospace',None,'The Inception of BrahMos Joint Venture section','Company identifies DRDO India and JSC Military Industrial Corporation NPO Mashinostroyenia Russia as partners;1998 formation and2014 indefinite IGA extension.',tier='self-reported',limits=['Undated company history accessed7October2026; 50.5/49.5 authorised-capital ratio is inception history, not audited current beneficial ownership or paid-in capital.'])
source('brahmos-award-2022','Philippines accepts BrahMos USD374,962,800 price proposal','https://www.thehindu.com/news/national/in-the-first-brahmos-missile-export-order-philippines-approves-374-mn-contract/article38272238.ece','The Hindu','2022-01-14','Quoted DND notice of award dated31December2021','Reports exact accepted price proposal in DND notice of award before contract signature.',tier='reported',limits=['Original notice instrument not retained; USD amount is award-stage reporting, not a bank receipt.'])
source('brahmos-contract-2022','DND signs PHP18.9billion BrahMos acquisition contract','https://www.pna.gov.ph/articles/1166596','Philippine News Agency','2022-01-28','Opening, named signatories and three-battery acquisition paragraphs','Government news agency reports signed DND–BrahMos contract, PHP18.9billion and three batteries including training and logistics.',tier='reported',limits=['Indexed original article retained; direct URL retrieval redirected to unrelated Facebook content and is recorded as failed. Signed instrument and exact currency schedule not opened.'])
source('brahmos-delivery-2025','DND confirms another BrahMos batch en route','https://www.pna.gov.ph/articles/1248536','Philippine News Agency','2025-04-23','DND Secretary quote and first-delivery retrospective','First deliveries occurred in April2024; another batch was en route on23April2025. No complete three-battery acceptance asserted.',tier='reported',limits=['Indexed original article retained; direct URL response was unrelated Facebook content. En route is not delivered or accepted.'])
source('mq9-federal-notice-2025','DSCA Transmittal24-07: India MQ-9B proposed sale','https://www.govinfo.gov/content/pkg/FR-2025-01-06/pdf/2024-31699.pdf','US Defense Security Cooperation Agency / Federal Register','2025-01-06','Printed pp624–625; Transmittal24-07 items i/ii/viii and Policy Justification','Original government publication reproduces1February2024 Congressional notification: national funds,31 aircraft, estimated USD3.99billion, principal General Atomics Aeronautical Systems.',limits=['Proposal-stage estimate, not signed contract value or disbursement; publication in January2025 is not a new January2025 approval.'])
source('mq9-signed-2024','India and US sign31 MQ-9B contract and separate logistics agreement','https://newsonair.gov.in/india-us-deal-for-procurement-of-31-mq-9b-predator-drones/','Akashvani / NewsOnAIR','2024-10-15','First two report paragraphs','Reports15October signature: MoD–US Government acquisition contract and MoD–General Atomics Global India Private Limited logistics contract.',tier='reported',limits=['Public broadcaster report of signing; executed contract and price schedule not retained.'])
source('mq9-pib-2024','Defence Year End Review2024: MQ-9B contracts','https://www.pib.gov.in/PressReleasePage.aspx?PRID=2088180','Ministry of Defence / PIB','2024-12-26','MQ-9B paragraph beginning MoD inked a contract with the US Government','Ministry confirms October2024 acquisition of31 and a separate Indian logistics contract with General Atomics Global India Pvt Ltd.',limits=['No final contract price, advance payment, delivery acceptance or corporate parentage is supplied in this paragraph.'])
source('mq9-delivery-plan-2024','MQ-9B deliveries expected2029–2030','https://www.thehindu.com/news/national/mq-9b-armed-uavs-to-be-delivered-by-2030/article68761650.ece','The Hindu','2024-10-17','Source quote on51–72 months after contract signing and initial payment','Officials describe prospective delivery51–72months after signature and initial payment, expected2029–2030.',tier='reported',limits=['Conditional forecast, not proof of initial payment or actual delivery. Unnamed-source approximate price is not substituted for unpublished definitive contract price.'])
source('defence-identity-2022','Ministry of Defence Year End Review2022: DRDO and BrahMos export identity','https://www.pib.gov.in/PressReleasePage.aspx?PRID=1884353','Ministry of Defence / PIB','2022-12-17','DEFENCE RESEARCH & DEVELOPMENT ORGANISATION heading and BrahMos export-contract paragraph','Official ministry spells out DRDO and identifies BrahMos Aerospace Private Limited (BAPL) as its joint-venture company signing the Philippine Department of National Defence export contract.',limits=['Used to document exact institutional/vendor identity, not current shareholder percentages, exporter receipts or the Philippine contract price.'])

entity('india','India','country',['c295-contract-2021','mq9-pib-2024'],['IN'],'National buyer and industrial-partner context.','Named Republic/Government of India in official procurement records; ISO3166 IN.')
entity('spain','Spain','country',['c295-contract-2021'],['ES'],'Country named for the C295 prime contractor.','PIB identifies Airbus Defence and Space S.A., Spain; ISO3166 ES. Country association does not establish state ownership.')
entity('russia','Russia','country',['brahmos-jv'],['RU'],'Intergovernmental and BrahMos partner-country context.','Company explicitly identifies Russian Federation and Russian partner; ISO3166 RU.')
entity('philippines','Philippines','country',['brahmos-contract-2022'],['PH'],'National public buyer of the BrahMos export package.','PNA identifies Philippine DND; ISO3166 PH.')
entity('usa','United States','country',['mq9-federal-notice-2025','mq9-pib-2024'],['US'],'Foreign Military Sales seller-country context.','US federal notice and India ministry identify United States; ISO3166 US.')
entity('mod','Ministry of Defence, India','ministry',['c295-contract-2021','mq9-pib-2024'],['IN'],'Named public acquisition contracting authority.','Exact ministry and retained legacy procurement identifiers; official PIB contract releases.','legacy:entity:min:ministry-of-defence')
entity('iaf','Indian Air Force','organisation',['c295-contract-2021','c295-first-2023'],['IN'],'Named C295 procurement beneficiary; no unit or basing information mapped.','Official PIB named beneficiary and manufacturer delivery announcement, same retained force entity.','legacy:entity:force:indian-air-force')
entity('airbus','Airbus Defence and Space S.A.','company',['c295-contract-2021','c295-project-2022-normal'],['ES'],'Spanish contracting vendor for56 C295 aircraft.','Exact S.A. counterparty and Spain in PIB1757634/1871267; reviewed same vendor behind legacy force:airbus-defence-and-space, not Airbus SE corporate parent.','legacy:entity:force:airbus-defence-and-space')
entity('tata-consortium','TATA Consortium for C295 manufacture','consortium',['c295-project-2022-normal'],['IN'],'TASL-led Indian Aircraft Contractor grouping TASL and TCS.','PIB explicitly names consortium and its two members. This is a project consortium node, not an inferred incorporated company or JV.')
entity('tasl','Tata Advanced Systems Limited','company',['c295-project-2022-normal','c295-fal-2024'],['IN'],'Lead consortium member and named local assembly partner.','Exact full legal name and TASL abbreviation in PIB; exact legacy force entity. No group holding percentage inferred.','legacy:entity:force:tata-advanced-systems')
entity('tcs','Tata Consultancy Services','company',['c295-project-2022-normal'],['IN'],'Named second member of C295 consortium.','PIB spells out Tata Consultancy Services (TCS); reviewed retained co:tata-consultancy-services issuer identity, not any generic Tata group company.','legacy:entity:co:tata-consultancy-services')
entity('c295-project','C295:56-aircraft Indian acquisition','procurement',['c295-contract-2021','c295-project-2022-normal'],['IN','ES'],'Single acquisition:16 flyaway,40 Indian-built; project cost and delivery are distinct stages.','Same24September2021 contract expressly recalled by2022 PIB; not a fresh2022 award.')
entity('drdo','Defence Research and Development Organisation','organisation',['defence-identity-2022','brahmos-jv'],['IN'],'India-side BrahMos joint-venture partner.','Original Ministry of Defence PIB1884353 spells out DEFENCE RESEARCH & DEVELOPMENT ORGANISATION, calls it DRDO, and identifies BAPL as its JV company; this is the same Union defence R&D institution in legacy force:drdo, not a name-only corporate match.','legacy:entity:force:drdo')
entity('npom','JSC Military Industrial Corporation NPO Mashinostroyenia','company',['brahmos-jv'],['RU'],'Russia-side partner identified in BrahMos company history.','Full Russian partner name and NPOM abbreviation explicitly joined in the company source; no downstream owner/control inference.')
entity('brahmos','BrahMos Aerospace Private Limited','company',['defence-identity-2022','brahmos-jv','brahmos-contract-2022'],['IN','RU'],'Indo-Russian JV and named Philippine export supplier.','Original Ministry of Defence PIB1884353 explicitly names BrahMos Aerospace Private Limited (BAPL), its DRDO JV role and Philippine export counterparty. This exact source also anchors legacy force:brahmos-aerospace; independent named-party contract reporting corroborates the same vendor, not a separate brand owner.','legacy:entity:force:brahmos-aerospace')
entity('dnd','Department of National Defense, Philippines','ministry',['brahmos-contract-2022','brahmos-delivery-2025'],['PH'],'Named contracting buyer in2022 BrahMos export.','PNA names Philippine Department of National Defense and its Secretary as signatory; not an intermediary or Indian department.')
entity('us-government','United States Government','government',['mq9-pib-2024'],['US'],'Named government counterparty in India MQ9B acquisition.','Indian MoD expressly names the US Government as contracting counterparty; distinct from manufacturer.')
entity('dsca','Defense Security Cooperation Agency','agency',['mq9-federal-notice-2025'],['US'],'Agency transmitting proposed-sale notification to Congress.','Agency and Transmittal24-07 identified in original Federal Register publication.')
entity('gaasi','General Atomics Aeronautical Systems','company',['mq9-federal-notice-2025'],['US'],'US principal contractor named in proposed MQ9B sale.','Federal Register expressly names General Atomics Aeronautical Systems, Poway CA; no merge with similarly branded India logistics company.')
entity('gagi','General Atomics Global India Private Limited','company',['mq9-pib-2024','mq9-signed-2024'],['IN'],'Separately named performance-based logistics contracting company.','Exact India ministry name Pvt Ltd and broadcaster expanded Private Limited; no CIN, parent ownership or receipt percentage inferred.')
entity('mq9-project','MQ-9B:31-aircraft Indian FMS acquisition','procurement',['mq9-federal-notice-2025','mq9-pib-2024'],['IN','US'],'Proposed-sale notification followed by signed acquisition and separate logistics agreement.','31-aircraft quantity and named India buyer cross-checked across original US notice and official Indian confirmation; stage matching, not price equivalence.')

C='c295-spain-india';BCASE='brahmos-philippines-export';M='mq9b-us-india';CR='c295-delivery-boundary';BR='brahmos-stage-boundary';MR='mq9-contract-boundary'
edge('india-mod','india','mod','agency','National public buyer','Official Indian ministry publishes and signs the aircraft acquisition.',['c295-contract-2021'],['IN'],C,response=CR)
edge('spain-airbus','spain','airbus','jurisdiction','Spanish contracting vendor','PIB identifies the prime as Airbus Defence and Space S.A., Spain. This is supplier-country context, not Spanish government ownership.',['c295-contract-2021'],['ES'],C,response=CR)
e=edge('mod-airbus-contract','mod','airbus','contracted','56-aircraft contract signed','MoD signed with Airbus on24September2021 for56 C295 aircraft,16 flyaway and40 Indian-built. Separate offsets also announced, with no amount or settlement retained.',['c295-contract-2021'],['IN','ES'],C,'2021-09-24',response=CR);e.update(fromDate='2021-09-24',toDate='2021-09-24',dateBasis='Exact contract signing date stated by ministry.')
edge('mod-c295-projectcost','mod','c295-project','project-cost','INR21,935crore total project cost','Defence Secretary states cost of the same2021 acquisition project in October2022; this is not Tata award value or bank disbursement.',['c295-project-2022-normal'],['IN','ES'],C,'2022-10-27',amounts=[amount(21935,'INR','crore','total project cost announced; not vendor receipt','2022-10-27 statement about2021 acquisition')],response=CR)
edge('airbus-tata-assembly','airbus','tata-consortium','industrial-participation','40 of56 to be made in India','Official project structure names TASL-led Tata consortium as Indian Aircraft Contractor for40. Financial subcontract terms and receipts remain unpublished in retained sources.',['c295-project-2022-normal'],['IN','ES'],C,'2022-10-27',response=CR)
edge('tasl-consortium','tasl','tata-consortium','member','Lead consortium member','PIB names TASL as consortium leader. No incorporated JV or ownership percentage is asserted.',['c295-project-2022-normal'],['IN'],C,'2022-10-27',response=CR)
edge('tcs-consortium','tcs','tata-consortium','member','Named consortium member','PIB names Tata Consultancy Services alongside TASL in the Indian Aircraft Contractor consortium. No amount allocated to TCS is reported.',['c295-project-2022-normal'],['IN'],C,'2022-10-27',response=CR)
e=edge('airbus-iaf-first','airbus','iaf','delivery','First delivery announced13September2023','Manufacturer announces handing over the first C295 to IAF. This one is included in the later cumulative16, not added to it.',['c295-first-2023'],['IN','ES'],C,'2023-09-13',response=CR);e.update(fromDate='2023-09-13',toDate='2023-09-13',dateBasis='Exact manufacturer delivery announcement date; no acceptance/payment date inferred.')
edge('c295-iaf-cumulative','c295-project','iaf','delivery','16 cumulative deliveries at30June2026','Airbus India row records56orders and16deliveries. October2024 final assembly inauguration and June2026 reported testflight are not extra deliveries.',['c295-count-2026'],['IN'],C,'2026-06-30',response=CR)
edge('india-drdo','india','drdo','agency','Indian JV partner agency','BrahMos identifies DRDO as India-side partner.',['brahmos-jv'],['IN'],BCASE,tier='self-reported',response=BR)
edge('russia-npom','russia','npom','jurisdiction','Russian JV partner company','BrahMos identifies NPOM as the Russian partner; this country link does not establish ultimate ownership.',['brahmos-jv'],['RU'],BCASE,tier='self-reported',response=BR)
edge('drdo-brahmos','drdo','brahmos','partner','India-side joint-venture partner','Company history identifies DRDO as partner from1998; the India–Russia IGA was extended indefinitely7February2014. Inception authorised-capital ratio50.5% Indian is historical, not current audited shareholding or cash injected.',['brahmos-jv'],['IN','RU'],BCASE,tier='self-reported',response=BR)
edge('npom-brahmos','npom','brahmos','partner','Russia-side joint-venture partner','Company history identifies NPOM as partner from1998; the India–Russia IGA was extended indefinitely7February2014. Inception authorised-capital ratio49.5% Russian is historical, not current audited shareholding.',['brahmos-jv'],['RU','IN'],BCASE,tier='self-reported',response=BR)
edge('philippines-dnd','philippines','dnd','agency','National public buyer','PNA identifies DND as Philippine public procurement authority.',['brahmos-contract-2022'],['PH'],BCASE,'2022-01-28',tier='reported',response=BR)
e=edge('dnd-brahmos-award','dnd','brahmos','award','USD374,962,800 accepted price proposal','The Hindu quotes DND notice of award dated31December2021 accepting the price proposal. Signature followed28January2022. No award-stage payment is established.',['brahmos-award-2022'],['PH','IN'],BCASE,'2022-01-14',tier='reported',amounts=[amount(374962800,'USD','dollar','notice-of-award accepted price proposal; not disbursement','2021-12-31 notice reported2022-01-14')],response=BR);e.update(fromDate='2021-12-31',toDate='2021-12-31',dateBasis='Notice date quoted by The Hindu; original notice not retained.')
e=edge('dnd-brahmos-contract','dnd','brahmos','contracted','PHP18.9billion export contract signed','PNA reports DND–BrahMos signed contract28January2022 for three batteries plus training and logistics. PHP amount and USD award describe the same acquisition; do not add or infer an exchange rate.',['brahmos-contract-2022'],['PH','IN'],BCASE,'2022-01-28',tier='reported',amounts=[amount(18.9,'PHP','billion','signed contract value reported by government news agency; not cash received','2022-01-28')],response=BR);e.update(fromDate='2022-01-28',toDate='2022-01-28',dateBasis='Exact signature date reported by PNA; signed instrument not retained.')
edge('brahmos-dnd-deliveries','brahmos','dnd','delivery','First delivery reported; another batch en route','PNA23April2025 says first deliveries were April2024 and quotes DND Secretary that another batch is on the way. This is not proof of delivery or acceptance of all three batteries.',['brahmos-delivery-2025'],['IN','PH'],BCASE,'2025-04-23',tier='reported',response=BR)
edge('usa-government','usa','us-government','agency','Federal contracting counterparty','Official Indian ministry identifies US Government as acquisition counterparty.',['mq9-pib-2024'],['US'],M,'2024-12-26',response=MR)
edge('usa-dsca','usa','dsca','agency','US notification agency','Original Federal Register publication identifies the Defense Security Cooperation Agency as notifying agency.',['mq9-federal-notice-2025'],['US'],M,'2025-01-06',response=MR)
edge('usa-gaasi','usa','gaasi','jurisdiction','US principal contractor','The original proposed-sale notice names General Atomics Aeronautical Systems, Poway CA. Country location is not US government ownership.',['mq9-federal-notice-2025'],['US'],M,'2024-02-01',response=MR)
e=edge('dsca-mq9-notification','dsca','mq9-project','notification','USD3.99billion proposed-sale estimate','Transmittal24-07 notified Congress on1February2024 for31 MQ9B aircraft and related package, funding source national funds. USD1.70billion MDE plus USD2.29billion other equals the USD3.99billion estimate; no cash transfer or loan is stated.',['mq9-federal-notice-2025'],['US','IN'],M,'2024-02-01',amounts=[amount(3.99,'USD','billion','Congressional notification estimated possible sale; not signed contract price','2024-02-01')],response=MR);e.update(fromDate='2024-02-01',toDate='2024-02-01',dateBasis='Congressional notification event1February2024; reproduced in6January2025 Federal Register, not a second approval.')
edge('gaasi-mq9-principal','gaasi','mq9-project','supplier','Principal contractor in proposed sale','Federal Register identifies GAASI as principal contractor; this is the notification-stage supplier role, not proof of a US Government payment or a legal parent of the India logistics entity.',['mq9-federal-notice-2025'],['US','IN'],M,'2024-02-01',response=MR)
e=edge('mod-us-mq9-contract','mod','us-government','contracted','31-aircraft acquisition signed15October2024','MoD year-end review confirms October2024 contract with US Government. Broadcaster reports signature15October. Final agreed price, initial payment and acceptance documents are not in these original official releases.',['mq9-pib-2024','mq9-signed-2024'],['IN','US'],M,'2024-10-15',response=MR);e.update(fromDate='2024-10-15',toDate='2024-10-15',dateBasis='Exact signature date from public broadcaster; October2024 independently confirmed by MoD.')
e=edge('mod-gagi-logistics','mod','gagi','contracted','Separate Indian logistics contract','MoD confirms separate contract with General Atomics Global India Pvt Ltd for performance-based depot-level maintenance, repair and overhaul. No public value, payment or corporate ownership split retained.',['mq9-pib-2024','mq9-signed-2024'],['IN'],M,'2024-10-15',response=MR);e.update(fromDate='2024-10-15',toDate='2024-10-15',dateBasis='Exact signing report15October2024; official year-end confirmation says October2024.')
edge('mod-mq9-buyer','mod','mq9-project','procurement','Indian acquisition programme','Named31-aircraft package links original US notification to Indian confirmation; it does not equate proposal estimate with final contract or with separate Indian logistics price.',['mq9-federal-notice-2025','mq9-pib-2024'],['IN','US'],M,'2024-12-26',response=MR)

ce=[e['id'] for e in out['relationships'] if C in e['recordIds']];be=[e['id'] for e in out['relationships'] if BCASE in e['recordIds']];me=[e['id'] for e in out['relationships'] if M in e['recordIds']]
cs=['c295-contract-2021','c295-project-2022-normal','c295-first-2023','c295-fal-2024','c295-count-2026'];bs=['brahmos-jv','brahmos-award-2022','brahmos-contract-2022','brahmos-delivery-2025'];ms=['mq9-federal-notice-2025','mq9-signed-2024','mq9-pib-2024','mq9-delivery-plan-2024']
record(C,'C295: Spanish prime → Tata consortium → Indian public buyer','The24September2021 MoD–Airbus contract covers56 aircraft:16 flyaway and40 Indian-built by a TASL-led consortium also naming TCS. PIB later states INR21,935crore total project cost, without allocating Tata receipts. Airbus records16 cumulative deliveries at30June2026. The2024 assembly-line inauguration is a production milestone, not delivery of all40.',cs,['IN','ES'],['india','spain','mod','airbus','tata-consortium','tasl','tcs','iaf','c295-project'],ce,'2021-09-24 to2026-06-30','2021-09-24','2026-06-30','contract-signed-deliveries-partial','MoD describes domestic manufacturing and offset objectives; manufacturer reports delivery milestones. No irregularity allegation is asserted. Latest retained delivery ledger is30June2026, not a full October2026 completion certificate.',['Same contract as existing force corpus c002/c055/c060; curated path adds exact consortium and updated deliveries, not a second procurement total.','No Airbus→Tata payment amount, TASL/TCS ownership split, offset discharge or supplier profit is established.','No first India-built handover is inferred from the September2026 target or test flight.'])
record(CR,'C295 delivery and money-stage boundary','One first delivery in2023 and16 cumulative deliveries inJune2026 overlap. INR21,935crore is total project cost announced in2022; the public releases do not establish Tata receipts or complete offset discharge. Manufacturer plans for local delivery remain forecasts until separately evidenced.',cs,['IN','ES'],['mod','airbus','tasl','tcs','iaf','c295-project'],ce,'2021–2026 source status',None,'2026-06-30','response-and-gap','Airbus announced its first delivery and later cumulative16; MoD explained the consortium role. These are ordinary disclosed procurement stages.',['No negative inference from missing private subcontract price or post-June delivery certificate.'],kind='response')
record(BCASE,'BrahMos: Indo-Russian JV → Philippine export award → deliveries','BrahMos identifies DRDO and Russia’s NPOM as its JV partners. A31December2021 award accepting USD374,962,800 preceded the28January2022 contract, reported by PNA as PHP18.9billion for three batteries with training and logistics. First delivery is reported inApril2024; DND said another batch was en route23April2025. No complete acceptance or supplier cash receipt is established.',bs,['IN','RU','PH'],['india','russia','philippines','drdo','npom','brahmos','dnd'],be,'2021-12-31 to2025-04-23;1998 formation is historical context','2021-12-31','2025-04-23','export-signed-deliveries-partial','DND described the contract as government-to-government cooperation enabled by a March2021 implementing agreement. Its Secretary confirmed the next batch en route inApril2025. No irregularity finding or criminal allegation is asserted.',['AwardUSD and contractPHP figures describe same acquisition; no cross-currency total or implied exact FX rate.','1998authorisedcapital ratios50.5/49.5 are inception history; no current shareholder ledger, paid-in capital or split of export proceeds verified.','This is the Philippine export, distinct from retained Indian domestic BrahMos contracts.','No all-three-battery completion, new2025/2026 order or advance remittance is established.'],tier='reported')
record(BR,'BrahMos export: signed value and delivery are distinct','The government news agency confirms signature and reports first delivery; the next shipment was still described as en route. Public partner names connect India and Russia to the supplier, without allocating export receipts between them.',bs,['IN','RU','PH'],['brahmos','dnd','drdo','npom'],be,'Contract2022; delivery statement2025',None,'2025-04-23','response-and-gap','DND said the forthcoming shipment was part of the previous order. Corporate JV history describes indefinite IGA extension in2014.',['Indexed PNA article evidence is distinguished from failed direct captures. No deployment locations or private bank account details are mapped.'],tier='reported',kind='response')
record(M,'MQ-9B: US possible-sale estimate → signed Indian acquisition','The US notified Congress on1February2024 of a possible31-aircraft sale estimated at USD3.99billion; its original notice was published in the Federal Register inJanuary2025. India signed a government-to-government acquisition15October2024 and a separate logistics contract with General Atomics Global India Private Limited. GAASI is named as US principal contractor at notification stage. The notification estimate is not the final signed price or a payment.',ms,['IN','US'],['india','usa','mod','us-government','dsca','gaasi','gagi','mq9-project'],me,'2024-02-01 to2025-01-06 publication; delivery forecast outside current window','2024-02-01','2025-01-06','contract-signed-price-and-settlement-gap','MoD confirms both October2024 contracts. Officials quoted by The Hindu forecast deliveries51–72months after signing and initial payment, expected2029–2030; this does not confirm initial payment. No irregularity allegation is asserted.',['No final signed price or actual expenditure is inferred from USD3.99billion notification estimate or approximate press reports.','National funds is the notice funding source; no US loan or grant is asserted.','No ownership link between GAASI and the separately named India logistics counterparty is inferred from brand similarity.','Earlier leased aircraft are separate from the31-aircraft purchase; no deliveries under the new purchase or operational basing are claimed.'])
record(MR,'MQ-9B value, identity and delivery boundary','US notification, Indian acquisition contract and Indian logistics contract are three distinct instruments/stages. Federal publication reproduces the earlier notification, not a new2025 deal. Original ministry confirmation supplies no price or payment. Conditional2029–2030 delivery reporting supplies no actual delivery.',ms,['IN','US'],['mod','us-government','dsca','gaasi','gagi','mq9-project'],me,'Notification2024; publication2025; future delivery forecast',None,'2025-01-06','response-and-gap','Official Indian year-end review confirms signature. The Hindu attributes a future delivery schedule to unnamed officials; this remains reported and conditional.',['No complete contract schedule or supplier cash ledger is retained. Absence in this curated corpus is not proof no payment occurred.'],kind='response')

# Make prose readable without altering IDs, URLs or exact numeric values.
import re
def space(text):
    text=re.sub(r'\b(INR|USD|PHP)(?=\d)',r'\1 ',text)
    text=re.sub(r'(?<=[a-z])(?=(?:January|February|March|April|May|June|July|August|September|October|November|December))',' ',text)
    text=re.sub(r'(?<=[a-z])(?=\d)',' ',text)
    text=re.sub(r'(?<=[A-Za-z])(?=\d{2,4}\b)|(?<=\d)(?=[A-Za-z])',' ',text)
    text=re.sub(r'(?<=[A-Za-z])(?=\d{2,4}(?:\s|[,.;]))',' ',text)
    text=re.sub(r':(?=\d)',': ',text)
    text=text.replace('C 295','C295').replace('C-295 MW','C-295MW').replace('MQ-9 B','MQ-9B').replace('ISO 3166','ISO3166')
    return text
for group in ['sources','entities','relationships','records']:
    for row in out[group]:
        if row.get('id')=='c295-spain-india':row['title']='C295: Indian public buyer → Spanish prime → Tata consortium'
        for key in ['title','label','summary','locator','identityBasis','dateBasis','period','response','falsifier']:
            if isinstance(row.get(key),str):row[key]=space(row[key])
        for key in ['limitations','alternativeExplanations']:
            if key in row:row[key]=[space(x) for x in row[key]]
        for a in row.get('amounts',[]):a['period']=space(a['period']);a['stage']=space(a['stage'])
(B.parent/'defence-trade.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
print({k:len(v) for k,v in out.items()})
