#!/usr/bin/env python3
"""Curate bounded corporate money trails from retained public evidence."""
import json,pathlib,hashlib,re,html
P=pathlib.Path(__file__).resolve().parent;ROOT=P.parents[3]; NS='money-trails-corporate'; DATE='2026-10-07'
def fid(kind,id):return f'{NS}:{kind}:{id}'
def dump(n,o):(P/n).write_text(json.dumps(o,indent=2,ensure_ascii=False)+'\n')
sources=[];entities=[];edges=[];records=[];hops=[];trails=[];hypotheses=[];bindings=[]
def source(id,title,url,publisher,date,locator,summary,files,tier='documented',limitations=[]):
 sources.append(dict(id=id,title=title,url=url,publisher=publisher,publishedAt=date,retrievedAt=DATE,locator=locator,summary=summary,tier=tier,limitations=limitations));bindings.append(dict(sourceId=fid('source',id),paths=[str((P/f).relative_to(ROOT)) for f in files]))
source('gvpr-icra-2025','GVPR: rated limits, audited indicators and exact subsidiary perimeter','https://www.icra.in/Rating/GetRationalReportFilePdf?Id=139218','ICRA Limited','2025-11-26','PDF pp.1–4; Annexure II at PDF p.6','Original dated rating rationale: 94% Honnavar Port and 100% Vijaya WB Smart Meters. ₹6,000 crore rated facilities are not drawn debt; financial statements are consolidated for ICRA analysis.',['gvpr-icra-2025.pdf','gvpr-icra-2025.txt','gvpr-icra-2025.receipt.json'],limitations=['Issuer-supplied financial data and ICRA analysis; ICRA states it has not audited the issuer. Ownership is dated to this report, not an assertion of current ultimate beneficial ownership.'])
source('gvpr-icra-2023','GVPR: disclosed promoter, management and public-sector client concentration','https://www.icra.in/Rating/GetRationalReportFilePdf?id=122377','ICRA Limited','2023-09-22','PDF pp.1–4, especially client profile and About the company','Names G.S.P. Veera Reddy as promoter, G. Shiva Shankar Reddy as chairman and G. Veera Sekhar Reddy as managing director. Publicly funded project exposure is not the origin of a particular donation.',['gvpr-icra-2023.pdf','gvpr-icra-2023.txt','gvpr-icra-2023.receipt.json'])
source('honnavar-care-2026','Honnavar Port: PFC sanction, undrawn debt and promoter support','https://www.careratings.com/upload/CompanyFiles/PR/202603130337_Honnavar_Port_Private_Limited.pdf','CARE Ratings Limited','2026-03-31','PDF pp.1–4; Annexure 1','Financial closure 24 September 2025, PFC sanction ₹540.64 crore, debt drawal pending at 31 December 2025; aggregate promoters’ equity and unsecured loans ₹79.48 crore.',['honnavar-care-2026.pdf','honnavar-care-2026.txt','honnavar-care-2026.receipt.json'],limitations=['Report date printed March 31, 2026, despite a potentially misleading URL filename. ₹500 crore rating scope differs from ₹540.64 crore sanction. Project cost is printed as both ₹789.58/₹789.59 crore; completion as September/October 2027. These differences are preserved and not treated as misconduct.'])
source('honnavar-care-2025','Honnavar Port: earlier sponsor infusion and delayed financial closure','https://www.careratings.com/upload/CompanyFiles/PR/202501120151_Honnavar_Port_Private_Limited.pdf','CARE Ratings Limited','2025-01-22','PDF pp.1–3: parent linkages, project execution risk and About the company','Earlier cumulative promoters’ equity/unsecured loans ₹61.86 crore at 31 October 2024; ₹702 crore project estimate and debt tie-up still under discussion.',['honnavar-care-2025.pdf','honnavar-care-2025.txt','honnavar-care-2025.receipt.json'],limitations=['Date must be read from PDF header rather than inferred from filename. Cumulative sponsor amounts at different dates must not be added.'])
source('vijaya-icra-2025','Vijaya WB Smart Meters: contract, direct-debit waterfall and bank finance','https://www.icra.in/Rating/ShowRationalReportFilePdf/133473','ICRA Limited','2025-03-05','PDF pp.1–3 and Annexure I','₹857.05 crore estimated AMISP contract; consumer-payment DDF priorities; ₹151 crore term loan and ₹110 crore sanctioned bridge loan, while rated bridge amount is ₹101.87 crore.',['vijaya-icra-2025.pdf','vijaya-icra-2025.txt','vijaya-icra-2025.receipt.json'],limitations=['A rating narrative of the signed agreement, not the retained signed agreement or actual collection ledger. The facility limit is not disbursed cash.'])
source('gvpr-lenders-2025','GVPR lender-wise rated facilities, 26 November 2025','https://www.icra.in/Rating/BankFacilities?CompanyId=22976&CompanyName=GVPR%20Engineers%20Limited&ArchiveDate=November262025','ICRA Limited','2025-11-26','Lender-wise facilities table; facility names retained separately','Public lender table distinguishes cash credit, bank guarantees and letters of credit. No drawn-debt total is computed.',['gvpr-lenders-2025.html','gvpr-lenders-2025.receipt.json'])
for kind in ['purchase','redemption']:
 source('eci-'+kind+'-mirror','SBI/ECI electoral bonds: selected GVPR donor-label '+kind+' rows (pinned mirror)','https://raw.githubusercontent.com/anagri/electoral-bond-analysis/9ff9171f5f14dc3796bd0fbc9b950b8f7e035559/new-'+('purchaser' if kind=='purchase' else 'receiver')+'.pdf','SBI / ECI; original-form PDF retained by anagri public archive','2024-03-21','Exact page and row IDs in eci-'+kind+'-selected.json; OC prefix plus bond number joined','Ten selected bonds: ₹5 crore redeemed by BJP on 16 October 2023 and ₹5 crore by President, AICC on 16 January 2024. Public extract omits bank-account suffixes and tellers.',['eci-'+kind+'-selected.json','bond-join.json','reproduce-bonds.py','eci-disclosure-probe.receipt.json'],'reported',['Original ECI index returned HTTP 406. These are pinned mirror PDF rows, not authenticated original-host bytes. Purchaser CIN/KYC is absent; a same-name join to the legal CCTV contractor is held.'])
source('adr-gvpr','ADR independent secondary rendering of GVPR bond serials','https://myneta.info/electoral_bonds/donor_bonds.php?action=full_details&donor=GVPR+ENGINEERS+LTD','Association for Democratic Reforms / MyNeta',None,'Retrieved donor detail renders eight of the ten selected serials; OC15934 and OC16990 absent from the retained HTML','The eight rendered secondary serial rows agree with the corresponding mirror rows. The remaining two are established only by the mirror PDF join. It does not solve the missing purchaser KYC/CIN.',['adr-gvpr-serials.html','adr-gvpr-serials.receipt.json'],'reported',['ADR warns similar company-name entries can be clubbed; this slice instead scans the exact donor label only. Retrieved HTML omits OC15934 and OC16990, so ADR does not independently corroborate all ten serials.'])

def geo(src,state='MH',city=True):return [dict(scope='city' if city else 'state',stateCodes=[state],localityIds=['mumbai'] if city else [],basis='project-location' if city else 'programme-coverage',note='Mumbai procurement is the starting point; counterparties and cross-state projects retain their separate locations and accounting perimeters.',sourceIds=src)]
def ent(id,label,type,summary,src,state='MH',city=True,canonical=None,resolved=True):
 o=dict(id=id,label=label,type=type,resolved=resolved,identityBasis='Exact legal/institutional name and expressly disclosed role in cited documents; no surname, proximity or generic group-name matching.',summary=summary,domains=['public-funds','governance','energy','transport'],layers=['organisations'],geography=geo(src,state,city),route='/money-trails',sourceIds=src,limitations=[])
 if canonical:o['canonicalId']=canonical
 entities.append(o)
def amount(v,stage,period,unit='crore'):return dict(value=v,currency='INR',unit=unit,stage=stage,period=period)
def edge(id,a,b,label,summary,src,date,kind='documented-context',amounts=[],tier='documented',state='MH',city=True,limits=[]):
 edges.append(dict(id=id,from_=a,to=b,kind=kind,label=label,summary=summary,tier=tier,status='source-disclosed-context-no-wrongdoing-finding',statusAsOf=date,fromDate=date,toDate=date,dateBasis='Source date unless the summary states a distinct event/snapshot date.',alternativeExplanations=[],falsifier='A corrected source, signed agreement or reconciled bank/ledger record could revise the stated perimeter.',responseIds=[],recordIds=[],amounts=amounts,domains=['public-funds','governance','energy','transport'],layers=['organisations' if kind in ['ownership','role'] else 'funding'],geography=geo(src,state,city),route='/money-trails',sourceIds=src,limitations=limits));edges[-1]['from']=edges[-1].pop('from_')
def record(id,title,summary,src,ents=[],rels=[],amounts=[],date='2026-03-31',kind='financial-context',tier='documented',limits=[]):
 records.append(dict(id=id,title=title,summary=summary,kind=kind,tier=tier,status='bounded-disclosure-no-corruption-finding',statusAsOf=date,fromDate=date,toDate=date,dateBasis='Dated report or explicitly stated reporting period; not necessarily transaction date.',entityIds=ents,relationshipIds=rels,period='Read each amount’s exact date and accounting stage',response='Published issuer/rating explanations and counterevidence are retained. No bespoke comment was solicited; silence is not treated as agreement.',alternativeExplanations=['Ordinary procurement, project finance, disclosed ownership and lawful political donations can coexist without a corrupt exchange.'],falsifier='Match the signed agreement, exact legal-entity identifiers, audited ledgers, invoices and bank advice before attributing an underlying source of funds.',amounts=amounts,domains=['public-funds','governance','energy','transport'],layers=['funding','organisations'],geography=geo(src),route='/money-trails',sourceIds=src,limitations=limits))
ent('gvpr','GVPR Engineers Limited','company','Mumbai CCTV contractor and exact named parent in ICRA/CARE disclosures.','gvpr-icra-2025'.split(),canonical='metro-mumbai-security:entity:gvpr')
ent('hppl','Honnavar Port Private Limited','company','94%-held subsidiary in the dated ICRA and CARE sources; separate legal borrower.',['gvpr-icra-2025','honnavar-care-2026'],'KA',False)
ent('vijaya','Vijaya WB Smart Meters Private Limited','company','100%-held special-purpose company in dated ICRA disclosure; separate legal borrower.',['gvpr-icra-2025','vijaya-icra-2025'],'WB',False)
ent('pfc','Power Finance Corporation Limited','financial-institution','Named sanctioning lender to Honnavar Port.',['honnavar-care-2026'],'KA',False)
ent('hppl-promoters','Honnavar promoters — disclosed aggregate','disclosed-funding-cohort','An accounting cohort, not a separate legal person: CARE does not allocate the aggregate contribution among promoters.',['honnavar-care-2026'],'KA',False)
ent('wbsedcl','West Bengal State Electricity Distribution Company Limited','government-company','AMISP counterparty and obligated creator of direct-debit payment arrangement.',['vijaya-icra-2025'],'WB',False)
ent('ddf','Vijaya/WBSEDCL direct-debit facility','payment-mechanism','Contractual payment-security mechanism; no account number, balance or actual debit is identified.',['vijaya-icra-2025'],'WB',False)
ent('consumers','Assigned WBSEDCL consumers — contract cohort','programme-cohort','Aggregate consumer cohort described by the contract narrative, not named people or household locations.',['vijaya-icra-2025'],'WB',False)
ent('veera-reddy','G. S. P. Veera Reddy — disclosed GVPR promoter','person','Historical promoter identified in ICRA 22 September 2023; not an ultimate-ownership percentage or source-of-funds conclusion.',['gvpr-icra-2023'])
ent('donor-label','GVPR ENGINEERS LTD (donor label; legal entity unverified)','source-mention','Disclosed label in ten selected bond purchases; CIN/KYC unavailable, contractor identity bridge held.',['eci-purchase-mirror'],resolved=True)
ent('bjp','Bharatiya Janata Party','political-party','Exact political party name in selected redemption records.',['eci-redemption-mirror'])
ent('aicc','President, All India Congress Committee','political-party','Exact recipient label in selected redemption records.',['eci-redemption-mirror'])
edge('gvpr-hppl','gvpr','hppl','94% ownership, dated disclosure','ICRA Annexure II and CARE identify 94% shareholding, not a transfer of 94% of any procurement receipt.',['gvpr-icra-2025','honnavar-care-2026'],'2025-11-26','ownership',state='KA',city=False)
edge('gvpr-vijaya','gvpr','vijaya','100% ownership, dated disclosure','ICRA Annexure II specifies full ownership. Subsidiary liabilities and receipts remain distinct.',['gvpr-icra-2025'],'2025-11-26','ownership',state='WB',city=False)
edge('gvpr-promoter','veera-reddy','gvpr','Disclosed promoter, September 2023','ICRA identifies the founder/promoter; no personal cash flow or ultimate ownership fraction is established.',['gvpr-icra-2023'],'2023-09-22','role')
edge('pfc-sanction','pfc','hppl','₹540.64 cr sanctioned; drawal pending at snapshot','CARE reports financial closure 24 September 2025 and PFC sanction; debt drawal was pending on 31 December 2025.',['honnavar-care-2026'],'2025-09-24','loan-sanction',[amount(540.64,'PFC debt sanctioned; not drawn as of 31 December 2025','Financial closure 24 September 2025; draw-status snapshot 31 December 2025')],state='KA',city=False,limits=['₹500 crore rated facility is a distinct scope, not another cash transfer. No later drawdown advice was retained.'])
edge('promoter-infusion','hppl-promoters','hppl','₹79.48 cr cumulative promoter funding disclosed','CARE reports aggregate equity infusion plus unsecured loans at 31 December 2025. Not apportioned to GVPR or individual shareholders.',['honnavar-care-2026'],'2025-12-31','disclosed-capital-contribution',[amount(79.48,'cumulative aggregate promoter equity plus unsecured loans; no split by contributor/instrument','As of 31 December 2025')],state='KA',city=False,limits=['Issuer/rating disclosure, not bank statements. ₹61.86 crore earlier snapshot is not additive.'])
edge('meter-contract','wbsedcl','vijaya','₹857.05 cr estimated AMISP contract','ICRA says letter of award 10 January 2024; contract signed between GVPR and WBSEDCL 20 February 2024. SPV implements smart-meter service.',['vijaya-icra-2025'],'2024-02-20','contract-commitment',[amount(857.05,'estimated lifetime AMISP contract value; not paid cash or installation cost','Award 10 January 2024; agreement 20 February 2024')],state='WB',city=False,limits=['Signed agreement/assignment document not retained. ICRA text distinguishes parent signatory from SPV implementation.'])
edge('consumer-ddf','consumers','ddf','Contract routes online receipts into DDF','ICRA describes future/contractual routing of assigned consumer online payments; no actual bank receipts are in the evidence.',['vijaya-icra-2025'],'2025-03-05','payment-waterfall',state='WB',city=False)
edge('ddf-priority','ddf','vijaya','Service-provider priority under DDF','DDF is to clear VWBSMPL payments first. Average monthly inflow should be at least five times estimated monthly AMISP payment. These are contractual controls, not observed diversion.',['vijaya-icra-2025'],'2025-03-05','payment-waterfall',state='WB',city=False)
edge('gvpr-guarantee','gvpr','vijaya','Unconditional, irrevocable corporate guarantee disclosed','ICRA analytical approach states an unconditional and irrevocable parent guarantee for subsidiary bank facilities; not evidence of guarantee invocation.',['vijaya-icra-2025'],'2025-03-05','guarantee-context',state='WB',city=False)
for id,party,date in [('bjp','bjp','2023-10-16'),('aicc','aicc','2024-01-16')]:
 edge('bond-'+id,'donor-label',party,'₹5 cr serial-matched bond redemptions','Five ₹1 crore instruments joined one-to-one on prefix OC and bond number, with denomination agreement. Original-form mirror sources; no contractor identity bridge.',['eci-purchase-mirror','eci-redemption-mirror'],'2023-10-16' if id=='bjp' else '2024-01-16','bond-redemption',[amount(5,'five serial-matched electoral-bond redemptions; disclosed donor label only','Purchased 7 October 2023, redeemed 16 October 2023' if id=='bjp' else 'Purchased 10 January 2024, redeemed 16 January 2024')],tier='reported')
record('port-case','From Mumbai CCTV contractor to port equity and PFC finance','The new join is exact disclosed parent/subsidiary ownership and the named PFC sanction. Sponsor funding is disclosed only as an aggregate; the trace stops before bank drawdown and upstream source-of-cash proof.',['gvpr-icra-2025','honnavar-care-2026'],['gvpr','hppl','pfc','hppl-promoters'],['gvpr-hppl','pfc-sanction','promoter-infusion'],kind='investigation-case')
record('meter-case','From Mumbai CCTV contractor to smart-meter payment priorities','Same parent, separate SPV: published rating documents describe contract finance and a direct-debit priority mechanism. No evidence identifies actual customer collections, disbursements or diversion.',['gvpr-icra-2025','vijaya-icra-2025'],['gvpr','vijaya','wbsedcl','ddf','consumers'],['gvpr-vijaya','meter-contract','consumer-ddf','ddf-priority','gvpr-guarantee'],kind='investigation-case',date='2025-03-05')
record('donor-case','Ten bond serials; the contractor identity and cash origin remain unproved','Pinned original-form mirrors reproduce ₹5 crore each to BJP and President, AICC. The purchaser label lacks CIN/KYC; no verified graph bridge connects it to the CCTV contractor.',['eci-purchase-mirror','eci-redemption-mirror','adr-gvpr'],['donor-label','bjp','aicc'],['bond-bjp','bond-aicc'],kind='investigation-case',date='2024-03-21',tier='reported')
record('port-counter','Port funding: debt undrawn, mixed promoter instruments and inconsistent estimate','At 31 December 2025, CARE says debt drawal pending and about ₹80 crore project cost incurred from promoter contributions. The ₹79.48 crore cumulative contribution mixes equity/unsecured loans. The report prints ₹789.58/₹789.59 crore project cost and September/October 2027 completion; no false precision is imposed.',['honnavar-care-2026','honnavar-care-2025'],['hppl','pfc','hppl-promoters'],kind='response',limits=['No primary bank advice, contributor-level ledger or later completion certificate retained.'])
record('meter-finance','Meter funding plan: loans, rated scope and project cost are distinct','ICRA gives ₹412.78 crore estimated project cost, about ₹65 crore planned equity, ₹151 crore tied-up term loan, ₹110 crore sanctioned bridge loan; rated bridge amount ₹101.87 crore. The ₹151 crore interchangeable LC is a sublimit, not another loan.',['vijaya-icra-2025'],['vijaya'],amounts=[amount(412.78,'estimated installation project cost','ICRA 5 March 2025'),amount(65,'approximate planned equity; not verified infusion','ICRA 5 March 2025'),amount(151,'tied-up term-loan facility; no drawdown statement','ICRA 5 March 2025'),amount(110,'sanctioned bridge loan; not the separately rated ₹101.87 crore scope','ICRA 5 March 2025'),amount(101.87,'rated bridge facility amount; not drawn cash and not additive to sanction','ICRA 5 March 2025')],date='2025-03-05')
record('meter-counter','Meter response: authority-related delay and controls','ICRA attributes execution delay to the authority; vendor back-to-back arrangements mitigate risk. Service-level penalties, installation milestones, one-time grants and monthly charges are contract features. No published ledger was inspected to show actual deductions or customer debits.',['vijaya-icra-2025'],['vijaya','wbsedcl'],kind='response',date='2025-03-05')
record('donor-counter','Donation comparison: two rival recipients and a long pre-award gap','The selected donor label bought bonds for BJP on 7 October 2023 and President, AICC on 10 January 2024. Mumbai CCTV approval is 15 April 2026, over two years later. A two-party split and mere sequence do not prove an exchange for the award.',['eci-purchase-mirror','eci-redemption-mirror'],['donor-label','bjp','aicc'],kind='response',date='2024-03-21',tier='reported')
record('gvpr-company-context','GVPR public-project footprint, promoter and rated facilities','ICRA records water/JJM, BMC and Maharashtra Jeevan Pradhikaran clients, a historical promoter and ₹6,000 crore rated limits. Order book, recognized income, cash balances and contingent guarantees are separate accounting populations; no source-of-donation allocation follows.',['gvpr-icra-2023','gvpr-icra-2025','gvpr-lenders-2025'],['gvpr','veera-reddy'],['gvpr-promoter'],date='2025-11-26',limits=['No audited related-party ledger, current beneficial-owner return or purchaser KYC retained.'])

def hop(id,title,summary,basis,state,ents,rels,recs,src,date,financialStage,amountRefs=[],responseIds=[],counterIds=[],missing='None required for this bounded fact',holder='Public issuer / rating agency',alternatives=[],limits=[],dateBasis='Dated disclosure; exact event or snapshot is stated in the summary.'):
 def ids(k,values):return [v if ':' in v else fid(k,v) for v in values]
 hs=ids('source',src)
 hops.append(dict(id=fid('hop',id),title=title,summary=summary,basis=basis,flowState=state,fromEntityId=ids('entity',ents)[0] if len(ents)>1 else None,toEntityId=ids('entity',ents)[1] if len(ents)>1 else None,entityIds=ids('entity',ents),relationshipIds=ids('relationship',rels),recordIds=ids('record',recs),sourceIds=hs,sourceLocators=[dict(sourceId=s,locator=(next((z['locator'] for z in sources if fid('source',z['id'])==s),'GR CCT-3125; PDF pp.2–4')),role='supports') for s in hs],date=date,dateBasis=dateBasis,financialStage=financialStage,amountRefs=[dict(kind=k,id=(i if ':' in i else fid(k,i)),amountIndex=n) for k,i,n in amountRefs],responseRecordIds=ids('record',responseIds),counterEvidenceRecordIds=ids('record',counterIds),response='Published explanations and limits are retained in the linked counterevidence; no bespoke response was solicited.',alternatives=alternatives or ['The disclosed arrangement can be lawful; a document gap does not establish misconduct.'],missingNextDocument=missing,documentHolder=holder,limitations=limits))
hop('mumbai-approval','Mumbai: approval of a negotiated bid','Home Department approved GVPR appointment at ₹2,098.92 crore including GST on 15 April 2026; GR directs subsequent work-order action. It is not payment.','contract-commitment','commitment',['metro-mumbai-security:entity:city-cctv','metro-mumbai-security:entity:gvpr'],['metro-mumbai-security:relationship:city-cctv-gvpr'],['metro-mumbai-security:record:city-cctv-award'],['metro-mumbai-security:source:cctv-gr'],'2026-04-15','Accepted bid/appointment approval, not expenditure',[('relationship','metro-mumbai-security:relationship:city-cctv-gvpr',0)],missing='Executed work order, stage invoices, acceptance certificates and treasury/bank payment advice',holder='Maharashtra Home Department / Mumbai Police procurement office',limits=['Four bids and two qualified bidders; QCBS H1 is not generic price L1.'])
hop('port-ownership','Same contractor, separate port borrower','ICRA dated Annexure II and CARE identify GVPR’s 94% holding in Honnavar Port. Ownership is context, not a route taken by CCTV money.','ownership-role-context','context',['gvpr','hppl'],['gvpr-hppl'],['port-case'],['gvpr-icra-2025','honnavar-care-2026'],'2025-11-26','Dated shareholding; not a transfer',missing='Current register of members and audited related-party funding schedule',holder='GVPR / Honnavar Port / Registrar of Companies',limits=['No ultimate beneficial-owner percentages asserted.'])
hop('pfc-sanction','Public lender: sanctioned, still undrawn at snapshot','PFC sanctioned ₹540.64 crore at financial closure on 24 September 2025. CARE says debt drawal was pending on 31 December 2025.','contract-commitment','commitment',['pfc','hppl'],['pfc-sanction'],['port-counter'],['honnavar-care-2026'],'2025-09-24','Sanctioned loan; not cash drawn',[('relationship','pfc-sanction',0)],counterIds=['port-counter'],missing='Executed PFC agreement, drawdown requests, disbursement advice and end-use certificates after 31 December 2025',holder='PFC / Honnavar Port',limits=['Rated facility ₹500 crore is a different scope and is not added to sanction.'])
hop('promoter-infusion','Sponsor side: an aggregate contribution is disclosed','CARE discloses ₹79.48 crore cumulative equity and unsecured loans from promoters at 31 December 2025. Contributor and instrument splits are unavailable.','documented-financial-disclosure','documented-transfer',['hppl-promoters','hppl'],['promoter-infusion'],['port-counter'],['honnavar-care-2026'],'2025-12-31','Cumulative issuer-disclosed promoter infusion, mixed equity/loan',[('relationship','promoter-infusion',0)],counterIds=['port-counter'],missing='Contributor-wise share allotment returns, unsecured-loan ledger, bank advice and source-of-funds reconciliation',holder='Honnavar Port / its contributing promoters',limits=['Not allocated entirely to GVPR or any individual. Not summed with earlier ₹61.86 crore snapshot.'])
hop('port-cash-stop','Stop: no procurement-to-port cash path','No retained document traces Mumbai CCTV receipts into Honnavar equity, unsecured loans or PFC debt service. The ownership connection alone does not do that.','unresolved-cash-path-stop','gap',['gvpr','hppl'],[],['port-case','port-counter'],['gvpr-icra-2025','honnavar-care-2026'],None,'Unresolved source of cash',counterIds=['port-counter'],missing='Parent and SPV bank-ledger reconciliation, project receipts and contributor-wise financing entries',holder='GVPR / Honnavar Port / funding banks',limits=['No criminal allegation is created by this missing link.'])
hop('meter-ownership','Same contractor, separate meter SPV','ICRA lists 100% GVPR ownership of Vijaya WB Smart Meters. The SPV was incorporated 30 October 2023.','ownership-role-context','context',['gvpr','vijaya'],['gvpr-vijaya'],['meter-case'],['gvpr-icra-2025','vijaya-icra-2025'],'2025-11-26','Dated shareholding and incorporation context',missing='Current shareholder and related-party disclosure',holder='GVPR / Vijaya WB Smart Meters')
hop('meter-contract','WBSEDCL contract: value is a commitment','ICRA reports a ₹857.05 crore estimated AMISP contract and 20 February 2024 agreement signed by GVPR and WBSEDCL; SPV implements 7.78 lakh meters.','contract-commitment','commitment',['wbsedcl','vijaya'],['meter-contract'],['meter-case','meter-counter'],['vijaya-icra-2025'],'2024-02-20','Estimated contract value, not project capex or actual receipts',[('relationship','meter-contract',0)],counterIds=['meter-counter'],missing='Signed AMISP contract, assignment/novation to SPV, installation milestones and invoicing schedules',holder='WBSEDCL / GVPR / Vijaya WB Smart Meters',limits=['Source identifies the parent as agreement signatory and SPV as implementer; their legal roles are not merged.'])
hop('meter-waterfall','Consumer payments: a priority mechanism','The DDF is designed to receive assigned consumer online payments and pay the service-provider first; prescribed average inflow is five times its estimated monthly payment.','contract-commitment','commitment',['consumers','ddf','vijaya'],['consumer-ddf','ddf-priority'],['meter-counter'],['vijaya-icra-2025'],'2025-03-05','Contractual payment waterfall; no observed collection',counterIds=['meter-counter'],missing='DDF/escrow agreement, aggregate monthly collections, service-level bills and certified payment waterfall reconciliations',holder='WBSEDCL / escrow bank / Vijaya WB Smart Meters',limits=['No consumer identities or account numbers requested or published. Priority mechanism is not diversion.'])
hop('meter-finance','Bank support: term and bridge limits','₹151 crore tied-up term loan and ₹110 crore sanctioned bridge loan are separate facilities. The rating covers ₹101.87 crore bridge scope, not an additional loan.','contract-commitment','commitment',['gvpr','vijaya'],['gvpr-guarantee'],['meter-finance'],['vijaya-icra-2025'],'2025-03-05','Facilities and guarantee, not drawdowns',[('record','meter-finance',2),('record','meter-finance',3),('record','meter-finance',4)],counterIds=['meter-counter'],missing='Facility sanction letters, lender identities, drawdown register, guarantee deed and utilisation certificates',holder='Vijaya WB Smart Meters / lenders / GVPR',limits=['Interchangeable ₹151 crore LC is a sublimit, not extra funding.'])
hop('meter-cash-stop','Stop: actual collections and onward payments unavailable','The records establish a contract structure and parent guarantee, not observed consumer debits, public grants, bank drawings or related-party extraction.','unresolved-cash-path-stop','gap',['ddf','vijaya'],[],['meter-case','meter-counter'],['vijaya-icra-2025'],None,'Unresolved receipts and payment execution',counterIds=['meter-counter'],missing='Aggregated DDF receipts and service bills, grants received, supplier invoices and related-party ledger matched to bank advice',holder='WBSEDCL / Vijaya WB Smart Meters / escrow bank')
for id,party,date in [('bjp','bjp','2023-10-16'),('aicc','aicc','2024-01-16')]:
 hop('bond-'+id,'Donor-label redemption: '+('BJP' if id=='bjp' else 'President, AICC'),'Five ₹1 crore bonds matched by OC prefix plus bond number and equal denomination; original-form pinned mirrors; ADR corroborates eight of ten selected serials, not the two omitted rows.','documented-financial-disclosure','reported-transfer',['donor-label',party],['bond-'+id],['donor-case','donor-counter'],['eci-purchase-mirror','eci-redemption-mirror','adr-gvpr'],date,'Serial-matched bond redemption from mirror records',[('relationship','bond-'+id,0)],counterIds=['donor-counter'],missing='Original ECI PDF byte validation and company-specific audited political-contribution disclosure',holder='ECI / SBI / disclosed purchaser',limits=['Source tier remains reported because primary-host files were not retrieved. Source label is not a verified legal-contractor identity.'])
hop('donor-identity-stop','Stop: donor label is not a verified company identity','GVPR ENGINEERS LTD appears in SBI purchase rows. The retained public rows contain no CIN or purchaser KYC; similarity to the CCTV contractor’s name is insufficient for a verified bridge.','unresolved-cash-path-stop','gap',['donor-label','gvpr'],[],['donor-case'],['eci-purchase-mirror','gvpr-icra-2025'],None,'Identity gap; no financial edge',missing='Company audited donation note and exact registered-identity confirmation; no private KYC publication',holder='GVPR corporate records / SBI via lawful disclosure',limits=['No canonical identity bridge, ownership assumption or cash-flow inference is made.'])
hop('donor-cash-stop','Stop: procurement revenue is not traced into bonds','Donations occurred in 2023/24 and the Mumbai CCTV approval is April 2026. No ledger ties either bond batch to any government project receipt or ministerial benefit.','unresolved-cash-path-stop','gap',['gvpr','donor-label'],[],['donor-case','donor-counter'],['eci-purchase-mirror','eci-redemption-mirror','metro-mumbai-security:source:cctv-gr'],None,'Unresolved upstream source; no quid-pro-quo finding',counterIds=['donor-counter'],missing='Audited contribution schedule, lawful company bank-ledger tracing and dated procurement decision records for a specified contract',holder='Identified purchaser / relevant procurement authority',limits=['Two rival recipients and more than a two-year gap are visible counterevidence against a simple recent award-for-donation story.'])

def hyp(id,question,obs,support,refute,test,needed,holder,status='open'):
 hypotheses.append(dict(id=fid('hypothesis',id),question=question,observation=obs,expectedDocumentaryFootprints=needed,supportingEvidence=[dict(kind=k,id=fid(k,i)) for k,i in support],refutingEvidence=[dict(kind=k,id=fid(k,i)) for k,i in refute],disconfirmationTest=test,documentHolder=holder,neededRecords=needed,status=status,limitations=['This is a testable review question; missing documents and network proximity do not establish wrongdoing.']))
hyp('port-source','Which disclosed cash sources funded the port contribution, and did PFC subsequently disburse?','A ₹79.48 crore aggregate contribution is disclosed while PFC debt remained undrawn at the snapshot.', [('relationship','promoter-infusion'),('relationship','pfc-sanction')],[('record','port-counter')],'A contributor-resolved funding ledger reconciled to lawful cash balances and bank advice can establish ordinary financing; absence of any CCTV receipts would defeat that proposed upstream route.',['Contributor-level equity/loan split','PFC sanction and disbursement ledger','Parent/SPV cash-source reconciliation'],'Honnavar Port / GVPR / PFC')
hyp('meter-controls','Did actual DDF payments respect the contracted service-level and milestone conditions?','The rating describes a consumer-payment priority mechanism and authority-related execution delays.', [('relationship','ddf-priority')],[('record','meter-counter')],'Reconcile aggregated DDF inflows to approved bills, SLA performance, penalties and funds released; compliant receipts and deductions would refute leakage.', ['DDF agreement and monthly reconciliation','Certified milestone and service-level reports','Approved invoices, deductions and grant-release statements'],'WBSEDCL / SPV / escrow bank')
hyp('donor-contract','Can either bond batch be connected to a specific legal contractor and a particular procurement cash receipt?','Serial matches identify two party recipients, but purchaser legal identity and upstream account transactions are missing.', [('relationship','bond-bjp'),('relationship','bond-aicc')],[('record','donor-counter')],'Reject the bridge if registered identity or audited donor disclosure differs. Even a valid identity match does not prove exchange: reconcile original cash sources and decision records; date proximity alone is insufficient.',['Audited company contribution disclosure','Exact registered identity confirmation','Specified procurement payment and decision record'],'Disclosed purchaser / procurement authority','weakened')
def trail(id,title,case,q,conclusion,hs,hypid,city='mumbai'):
 trails.append(dict(id=fid('trail',id),title=title,city=city,caseRecordId=fid('record',case),question=q,conclusion=conclusion,sourceStatus='Original rating disclosures and retained government GR; bond trail separately marked pinned-mirror/reported. No corruption finding is inferred.',cutoff=DATE,hopIds=[fid('hop',h) for h in hs],hypothesisIds=[fid('hypothesis',hypid)],limitations=['Branches show different entities, financial stages and dates. No total is computed across hops.','Public ratings are not the underlying bank ledger, signed contract or ultimate-beneficial-owner return.']))
trail('gvpr-port','Mumbai CCTV → corporate ownership → port and PFC finance','port-case','Where does the contractor’s disclosed corporate and project-finance network lead?','Verified corporate ownership reaches Honnavar Port and a named PFC sanction. Sponsor infusion is reported as a mixed aggregate; procurement-to-port cash origin and later debt drawdown remain untraced.',['mumbai-approval','port-ownership','pfc-sanction','promoter-infusion','port-cash-stop'],'port-source')
trail('gvpr-meters','Mumbai CCTV → smart-meter SPV → consumer-payment controls','meter-case','How is the same contractor’s meter subsidiary contracted, financed and paid?','Published disclosure establishes a separate SPV, estimated contract, parent guarantee and payment priority. Actual collections, drawings and onward supplier payments remain unverified.',['mumbai-approval','meter-ownership','meter-contract','meter-waterfall','meter-finance','meter-cash-stop'],'meter-controls')
trail('gvpr-bonds','GVPR donor label → ten bond serials → two political recipients','donor-case','What do original-form bond rows establish, and where does identity and cash-origin tracing stop?','Ten mirror-reproduced bond redemptions identify ₹5 crore each to BJP and President, AICC. The legal-contractor identity bridge and any procurement-funded cash path remain held.',['bond-bjp','bond-aicc','donor-identity-stop','donor-cash-stop'],'donor-contract')
source('pfc-shareholding-2025','PFC investor presentation: government majority holding at 30 June 2025','https://cms.pfcindia.co.in/media/documents/Investor%20presentation%20June%2025.pdf','Power Finance Corporation Limited',None,'PDF p.4: majority owned by Government of India; p.26: shareholder outlook as of 30 June 2025','Issuer publication identifies President of India holding 55.99% as of 30 June 2025. This is the institutional shareholder, not a personal interest of the office-holder.',['pfc-investor-june2025.pdf','pfc-investor-june2025.txt','pfc-investor-june2025.receipt.json'],limitations=['30 June 2025 is the shareholding snapshot, not an independently established publication date. No instruction to approve the Honnavar facility or sovereign guarantee is inferred.'])
ent('goi-holder','President of India — institutional PFC shareholder','government','Institutional government shareholding, not the personal assets or instructions of an individual office-holder.',['pfc-shareholding-2025'])
edge('goi-pfc','goi-holder','pfc','55.99% government holding at 30 June 2025','PFC issuer presentation identifies the President of India institutional holding and describes PFC as majority government owned.',['pfc-shareholding-2025'],'2025-06-30','ownership',limits=['Ownership does not establish ministerial direction, a sovereign guarantee, or responsibility for an individual loan.'])
hop('pfc-public-ownership','Why PFC is a public-sector connection','PFC’s own presentation identifies 55.99% held by the President of India institutionally at 30 June 2025. This adds a public ownership layer; it does not show ministerial direction of the loan.','ownership-role-context','context',['goi-holder','pfc'],['goi-pfc'],[],['pfc-shareholding-2025'],'2025-06-30','Institutional shareholding; no cash transfer',missing='None required for this dated ownership fact; a loan decision would need its own approval record',holder='PFC',limits=['Not the personal shareholding of the President; no sovereign guarantee or political instruction inferred.'])
for t in trails:
 if t['id'].endswith(':gvpr-port'):t['hopIds'].insert(t['hopIds'].index(fid('hop','pfc-sanction')),fid('hop','pfc-public-ownership'))
for e in entities:
 if e['id']=='pfc':e['sourceIds'].append('pfc-shareholding-2025')
source('pfc-board-2023','PFC Board report: infrastructure lending approval and entry into ports','https://cms.pfcindia.co.in/media/filer_public/2d/16/2d16e71b-3229-4d7e-bc79-c7d7c23e4f11/report_of_the_board_of_directors.pdf','Power Finance Corporation Limited',None,'PDF p.1, printed annual-report p.42, section 1(i)','Board report says Government of India approved expansion into logistics and infrastructure in August 2022 and describes actual FY 2022–23 entry into ports, desalination and metro rail.',['pfc-board-2023.pdf','pfc-board-2023.txt','pfc-board-2023.receipt.json'],limitations=['The underlying approval instrument/current MoA and any later sector cap are not retained. This issuer Board report establishes the stated policy change, not compliance of an individual loan.'])
ent('goi-policy','Government of India — lending-scope authorization','government','Government approval actor expressly identified in PFC Board report; no individual minister or loan instruction inferred.',['pfc-board-2023'])
edge('pfc-infra-scope','goi-policy','pfc','August 2022 approval to finance infrastructure','PFC Board reports Government of India assent to logistics/infrastructure lending and subsequent entry into ports, desalination and metro rail.',['pfc-board-2023'],'2023-03-31','policy-context',limits=['31 March 2023 is fiscal-report endpoint; approval is only dated August 2022 in this retained document, not the edge snapshot date. No individual loan compliance finding.'])
record('pfc-policy-counter','Port lending fits a disclosed expansion of PFC scope','PFC Board report says Government of India approved logistics/infrastructure lending in August 2022 and describes FY 2022–23 entry into ports. A loan to a port is not, by sector alone, evidence of diversion of power funds.',['pfc-board-2023'],['goi-policy','pfc'],['pfc-infra-scope'],kind='response',date='2023-03-31',limits=['Underlying authorization, current MoA, loan-specific eligibility and conditions require their own records.'])
hop('pfc-policy-scope','Policy change: port lending is within the disclosed expansion','PFC’s FY 2022–23 Board report says Government of India approved logistics/infrastructure lending in August 2022 and describes entry into ports. This challenges a sector-name-only diversion theory.','ownership-role-context','context',['goi-policy','pfc'],['pfc-infra-scope'],['pfc-policy-counter'],['pfc-board-2023'],None,'Dated policy-scope context; no loan payment',counterIds=['pfc-policy-counter'],missing='Underlying government approval, operative MoA and loan-specific eligibility review',holder='PFC / Government of India',limits=['A general lending-scope expansion does not establish that an individual loan complied with all conditions.'],dateBasis='Approval month August 2022, reported in FY 2022–23 Board report; no exact event day asserted.')
for t in trails:
 if t['id'].endswith(':gvpr-port'):t['hopIds'].insert(t['hopIds'].index(fid('hop','pfc-sanction')),fid('hop','pfc-policy-scope'))
for h in hops:
 if h['id'].endswith(':pfc-sanction'):
  h['counterEvidenceRecordIds'].append(fid('record','pfc-policy-counter'))
  h['sourceIds'].append(fid('source','pfc-board-2023'));h['sourceLocators'].append(dict(sourceId=fid('source','pfc-board-2023'),locator='PDF p.1, printed p.42: logistics/infrastructure approval and ports',role='counterevidence'))
 if h['id'].endswith(':meter-waterfall'):
  h['title']='Consumer payments: contracted routing to DDF';h['summary']='The DDF is designed to receive assigned consumer online payments. The retained rating describes this obligation, not actual account receipts.';h['relationshipIds']=[fid('relationship','consumer-ddf')];h['entityIds']=[fid('entity','consumers'),fid('entity','ddf')]
hop('meter-priority','DDF: contracted priority to the service provider','ICRA states the DDF will first clear payments to the SPV and should receive average monthly inflows of at least five times the estimated monthly AMISP payment. This is a control term, not observed transfers.','contract-commitment','commitment',['ddf','vijaya'],['ddf-priority'],['meter-counter'],['vijaya-icra-2025'],'2025-03-05','Contractual priority, not actual receipts',counterIds=['meter-counter'],missing='Aggregate DDF waterfall reconciliations matched to approved bills and service-level certificates',holder='WBSEDCL / escrow bank / Vijaya WB Smart Meters',limits=['Actual compliance, debits and deductions are not established.'])
for t in trails:
 if t['id'].endswith(':gvpr-meters'):t['hopIds'].insert(t['hopIds'].index(fid('hop','meter-waterfall'))+1,fid('hop','meter-priority'))
# Geometry retains the evidence's own scope; a trail's Mumbai starting point does
# not move the port, meter scheme or donor records to Mumbai.
metro=json.loads((ROOT/'research/raw/metro-spending/mumbai-security.json').read_text())
mumbai_source=next(x for x in metro['sources'] if x['id']=='cctv-gr').copy();mumbai_source['id']='mumbai-cctv';sources.append(mumbai_source)
bindings.append(dict(sourceId=fid('source','mumbai-cctv'),paths=['research/raw/metro-spending/mumbai-security-evidence/cctv-phase3-gr-2026.pdf','research/raw/metro-spending/mumbai-security-evidence/cctv-phase3-gr-2026.txt','research/raw/metro-spending/mumbai-security-evidence/cctv-phase3-gr-2026-receipt.json']))
def national(src):return [dict(scope='national',stateCodes=[],localityIds=[],basis='national-context',note='National legal/financial context; no project location, recipient residence or state allocation inferred.',sourceIds=src)]
for e in entities:
 if e['id']=='gvpr':
  e['sourceIds'].append('mumbai-cctv');e['geography']=geo(['mumbai-cctv']);e['identityBasis']='Exact legal name GVPR Engineers Limited in original Mumbai CCTV GR and ICRA/CARE issuer and parent disclosures. The SBI donor label is expressly not merged.'
 if e['id'] in ['donor-label','bjp','aicc','veera-reddy','goi-holder','goi-policy']:e['geography']=national(e['sourceIds'])
 if e['id']=='donor-label':
  e['identityBasis']='Resolved identity of the exact SBI disclosure-label object and its ten serial rows only; not resolution of a legal company. No CIN/KYC or canonical company link is asserted.';e['limitations']=['Source-mention data object; legal-entity identity remains unresolved.']
for e in edges:
 if e['id'] in ['gvpr-promoter','bond-bjp','bond-aicc','goi-pfc','pfc-infra-scope']:e['geography']=national(e['sourceIds'])
for r in records:
 if r['id'].startswith('port'):r['geography']=geo(r['sourceIds'],'KA',False)
 elif r['id'].startswith('meter'):r['geography']=geo(r['sourceIds'],'WB',False)
 else:r['geography']=national(r['sourceIds'])
# Financial event, reporting cutoff and later source date remain separate.
for e in edges:
 if e['id']=='pfc-sanction':
  e['statusAsOf']='2026-03-31'
  e['dateBasis']='Sanction/financial-closure event: 24 September 2025. Undrawn-debt snapshot: 31 December 2025. CARE report/status assertion date: 31 March 2026; no later drawdown inferred.'
 if e['id']=='promoter-infusion':
  e['statusAsOf']='2026-03-31'
  e['dateBasis']='31 December 2025 is the reporting cutoff for a cumulative contribution balance, not the date of a single transfer. Individual infusion dates are not supplied. CARE report/status assertion date: 31 March 2026.'
for h in hops:
 if h['id'].endswith(':pfc-sanction'):
  h['dateBasis']='Exact sanction/financial-closure event: 24 September 2025; undrawn-debt snapshot: 31 December 2025; reported by CARE on 31 March 2026.'
  h['eventPeriod']='Sanction 24 September 2025; draw-status snapshot 31 December 2025; report 31 March 2026'
 if h['id'].endswith(':promoter-infusion'):
  h['dateBasis']='31 December 2025 is a cumulative reporting snapshot, not a single-day payment. CARE published the amount on 31 March 2026; individual infusion dates are not supplied.'
  h['eventPeriod']='Cumulative promoter contribution through 31 December 2025; exact transfer dates unavailable'
dump('slice.json',dict(sources=sources,entities=entities,relationships=edges,records=records,localities=[dict(id='mumbai',name='Mumbai',stateCode='MH',kind='city',aliases=['Greater Mumbai','Brihanmumbai'])]))
hop_responses={
 'mumbai-approval':'The GR describes four bids, two technically qualified bidders and a negotiated QCBS H1 approval. It directs subsequent work-order action; no payment or duplicate billing is established.',
 'port-ownership':'Both rating sources identify 94% ownership at their dated disclosures. Neither identifies a specific procurement receipt as the source of subsidiary funding.',
 'pfc-public-ownership':'PFC reports 55.99% institutional government ownership at 30 June 2025. This is not a personal asset of the President or evidence of political direction of this loan.',
 'pfc-policy-scope':'PFC’s Board explicitly says government approved infrastructure lending in August 2022 and describes lending to ports. Sector diversification alone therefore does not show misuse of power-sector funds.',
 'pfc-sanction':'CARE explicitly says debt drawal was pending on 31 December 2025. The separate ₹500 crore rated scope is not another disbursement; PFC’s Board reports authority to enter port financing.',
 'promoter-infusion':'CARE attributes ₹79.48 crore to promoters collectively and combines equity with unsecured loans. It cannot be assigned entirely to GVPR, an individual, or a named public contract.',
 'port-cash-stop':'The records establish ownership and disclosed financing stages. None reconciles a CCTV receipt to port funding, and PFC debt was still undrawn at the stated snapshot.',
 'meter-ownership':'The 100% holding is dated ICRA disclosure. The parent’s ownership does not merge the SPV’s contracts, debts or cash with the parent.',
 'meter-contract':'ICRA identifies the parent as contract signatory and SPV as implementer. It attributes execution delay to the authority and mentions contractual penalties and vendor risk-sharing.',
 'meter-waterfall':'ICRA describes intended receipt routing only. No retained DDF statement establishes a consumer debit, balance or executed payment.',
 'meter-priority':'The source describes payment priority and a five-times inflow control; no retained bank or service-level records demonstrate whether this control operated compliantly.',
 'meter-finance':'₹110 crore bridge sanction and ₹101.87 crore rated bridge scope are not additive. Interchangeable LC is a sublimit; no drawdown or invoked parent guarantee is shown.',
 'meter-cash-stop':'Installation conditions, authority-related delays and penalties remain visible. No actual consumer collections, grants, lender drawings or onward supplier payments have been reconciled.',
 'bond-bjp':'Five selected mirror instruments total ₹5 crore. The donor label also funded President, AICC; its legal-company identity and source of funds remain unverified.',
 'bond-aicc':'Five selected mirror instruments total ₹5 crore. The donor label also funded BJP; its legal-company identity and source of funds remain unverified.',
 'donor-identity-stop':'The disclosure contains a purchaser label but no CIN/KYC. The site keeps a separate source-mention node and draws no donor-to-contractor identity edge.',
 'donor-cash-stop':'The 2023/24 purchases precede the April 2026 CCTV approval by over two years and name two rival recipients. Neither timing nor a shared-looking name proves procurement-funded donations.'}
for h in hops:
 h['response']=hop_responses[h['id'].split(':')[-1]]
 if h['id'].endswith(('bond-bjp','bond-aicc','donor-identity-stop','donor-cash-stop')):h['identityStatus']='Exact documentary donor-label object; legal-company identity unresolved'
 if h['id'].endswith(('bond-bjp','bond-aicc')):h['sourceFamily']='SBI disclosure through pinned public mirror; ADR secondary comparison'
 if h['flowState']=='gap':h['stopReason']=h['missingNextDocument']
dump('trails.json',dict(schemaVersion=1,namespace=NS,cutoff=DATE,trails=trails,hops=hops,hypotheses=hypotheses))
# Existing government source reused without mutating or copying its evidence.
bindings.append(dict(sourceId='metro-mumbai-security:source:cctv-gr',paths=['research/raw/metro-spending/mumbai-security-evidence/cctv-phase3-gr-2026.pdf','research/raw/metro-spending/mumbai-security-evidence/cctv-phase3-gr-2026.txt','research/raw/metro-spending/mumbai-security-evidence/cctv-phase3-gr-2026-receipt.json']))
paths=sorted({p for b in bindings for p in b['paths']} | {str((P/n).relative_to(ROOT)) for n in ['build.py','slice.json','trails.json']})
dump('sha256-manifest.json',dict(artifacts=[dict(path=p,bytes=len((ROOT/p).read_bytes()),sha256=hashlib.sha256((ROOT/p).read_bytes()).hexdigest()) for p in paths],sourceArtifacts=bindings))
print(json.dumps(dict(sources=len(sources),entities=len(entities),relationships=len(edges),records=len(records),trails=len(trails),hops=len(hops),hypotheses=len(hypotheses))))
